### ISSUE TITLE
SVG rendering?

### ISSUE THREAD

**Issue by nhoizey** [liabru/matter-js#1]
I'm developing a game using SVG ( http://play.esviji.com/ ) and I feel a physics engine could help me on some topics.

All physics engines I've seen use only Canvas rendering, none of them uses SVG.

Is there a way Matter could provide both?

**Comment by FabricioLayedra** [comment]
Definitely, d3 is not the option if you want interactive physics in your app. DON'T USE FOR IT. It's a wonderful library but not for that.
