### ISSUE TITLE
Hide rubber band when dragging

### ISSUE THREAD

**Issue by run-time** [liabru/matter-js#10]
I love all the options for turning various mechanics on/off but couldn't find one for the little green rubber band that shows up when dragging a shape.  can i change the color or hide this easily?

**Comment by stephenDyksen** [comment]
I tried adding the render.visible = false line to my code, but could not seem to get it working.  I am not sure there is a render function for the mouseConstraint.

**Comment by liabru** [comment]
@stephenDyksen see #72

**Comment by stephenDyksen** [comment]
It worked...Excellent! Thanks for the help, and the fast reply!
