### ISSUE TITLE
RenderPixi suggestions to enable use of spritesheets and Sprites/Containers as externally-held sprites

### ISSUE THREAD

**Issue by Neofish22** [liabru/matter-js#100]
PIXI can load spritesheets described JSON, but the RenderPixi._getTexture function only tries getting the texture from a file. I believe that one could check PIXI.Sprite.fromFrame before trying from file (Sprite.fromImage), to see if the resource has already been loaded from such a sheet.

Potential problem is that the sheets I've seen have IDs built without file suffix, thus filenames/IDs wouldn't be interchangeable without alteration. I solved this cheaply in my own project. I have yet to produce a sheet to see if this was stylistic or intentional. If documented, users could easily cope with the difference anyway.

Secondly, and not separated as related:
I wanted my non-physical background scene to be rendered neatly, so modified setBackground to allow the use of Containers (basically replaced the sprite load, and didn't parse it like a filename). This worked (my scene displays), so I believe it would be possible to add some type check (i.e. not a string) to allow the use a user-supplied Container (or Sprite).

I also think that RenderPixi should allow similar attaching of Container and Sprite to Body. For example, I would use this to attached bone-animated figures to an appropriately sized Body (don't want limb collision). From what I can tell RenderPixi.world invokes the creation of sprites in RenderPixi.body. I think this again could be easily achieved. Currently seems like one check (against bodyRender.sprite.texture) would prevent the user from entering a Container or Sprite under the 'sprite' creation option (sets bodyRender.sprite.texture?), so could modify RenderPixi._createBodySprite to expect this and act accordingly.

Proposed changes to RenderPixi.js:
- _getTexture check PIXI.Sprite.fromFrame before trying file.
- _createBodySprite check bodyRender.sprite.texture for Object (not string), then use that as sprite. (Presuming that the 'sprite' creation option does correspond to the texture member).
- setBackground should do the same as _createBodySprite (as it stands, it seems that setBackground cannot use this directly): check background (param) for Object (not string), then use that as sprite.

I believe none of these changes would be affected by RenderPixi.clear, and can't think of any other major interferences.

I think I could make these changes, but want to see want you think / if my observations are correct. Sorry if this isn't a well-formed issue, and thanks for you time.

**Comment by liabru** [comment]
So essentially are you saying it should support Pixi objects passed as part of `body.render.sprite.texture`, in addition to file path strings? 

If so sounds like a good addition, a pull request would be appreciated if you have time!

**Comment by Neofish22** [comment]
Yes precisely. I did have a crack at it but couldn't get all options behaving consistently together. I can submit a pull request later and make a more formal attempt in the next week.

**Comment by easwee** [comment]
I'm currently trying to solve this same exact issue - PIXIs (v3) spritesheets are a very powerful way of animating things on canvas, and as far as physics go I'm very pleased with matter, it would be worth to make them work together.

**Comment by easwee** [comment]
I managed to make it run by modifying the _getTexture method of RenderPixi in Matterjs:

    var _getTexture = function(render, imagePath) {
        var texture = render.textures[imagePath];

        if (!texture) {
            if(texture != imagePath) {
                texture = render.textures[imagePath] = PIXI.Texture.fromFrame(imagePath);
            }
            else {
                texture = render.textures[imagePath] = PIXI.Texture.fromImage(imagePath);
            }
        }
        return texture;
    };

The most simple check that came to mind, is to check if the required texture path is different from previous - if  it is, it means I am looping a sprite sequence. 
I do all the sprite logic looping on the game side in game.update() method, I increment the current frame id, and I store the amount of frames per animation sequence and work with that. You will also have to handle animation speed separately, but that shouldn't be a problem.

So far haven't seen any performance drop. Hope this helps if someone using PIXIjs stumbles upon it.

Haven't tried to implement PIXI MovieClip - that one I suppose is a bit more tricky to add.
