### ISSUE TITLE
1.7.0 "stats & performance" demo on my local have much bigger stats value than office demo site

### ISSUE THREAD

**Issue by lancety** [liabru/matter-js#1001]
I saw 1.7 release on top of this issues list, so I tried checkout my local branch to 1.7.0, but the 2nd "ut" time after "fps" is 6 - 7 times longer than the same demo on 1.7.0 official site (https://brm.io/matter-js/demo/#stats),  I can see the lagging issue when my local demo page just refreshed (when the balls start falling down).

I tried reopen browser (chrome 90.0.4430.72),  re-installed whole node_modules folder, could reproduce the issue. 
Below screenshot is taken from same PC side by side, left is official demo site, right side is my local demo running "dev" npm task.

Is there anything from my local webpack dev server will affect it?
Thanks for help.

![image](https://user-images.githubusercontent.com/5547558/116186029-2a1d5400-a766-11eb-95a2-32729625e88e.png)

**Comment by liabru** [comment]
Thanks for reporting, I actually noticed this too while I've been working on some performance improvements.

__It turns out that the default `devtool` config in Webpack _severely_ impacts performance in development builds.__

Adding the line __`devtool: 'source-map'`__ (or similar, but not an eval mode) to the Webpack config and restarting the dev server drastically improves this.

For example `stress3` example goes from `30ms` per update to `6.5ms` per update on my machine.

I'd recommend anybody using Webpack with Matter.js to make this change in their own config to get the correct performance in development builds, but also check this in production builds too. I've pushed a change that makes it default for maintainers of this project (releases are already production builds though).

Let me know if this resolves for you, I'll likely have to make note of this in the readme I think.

**Comment by lancety** [comment]
hi @liabru ,  adding dev-tool to the webpack.demo.config.ts fixed the issue.  Thanks  :)

Now just wondering if prod  will be affected by this. I can see the demo webpack config is resolve"matter-js" from src folder.  It will be helpful to let demo to use "build" min file so we know the build file doesnt have this issue.

**Comment by Durss** [comment]
Hello :)

I have terrible performances running matter-js on a Vue-JS 2 project.
If I profile the page without running matter-js everything's fine, the project actually does nothing, which suggest it's not source of these performances issues.

I added the `devtool:'source-map'` option and I went from 5-6fps to 11-12fps on the `"Stress 3 demo"` which is better but still quite bad :/
Is there anything else I could try ?

Have a good day :)

**Comment by Durss** [comment]
Ok nevermind i found out the issue !

It seems to be due to Vue adding watchers !
I was storing a renderer's reference as a public prop of my class *(using Typescript)* which tells Vue that it should make the value reactive.

If I set it as private to remove the reactivity things run fine !

That may help others knowing this :)

**Comment by liabru** [comment]
@Durss thanks for the update, that will probably help some Vue users I'm sure.

**Comment by KaliaJS** [comment]
If you use the Vue 3 you need to use the shallowRef() for the engine, runner, bodies, etc (everything that has heavy and deep modifications). It avoid deep reactivity.

**Comment by denzhe22** [comment]
> Ok nevermind i found out the issue !
> 
> It seems to be due to Vue adding watchers ! I was storing a renderer's reference as a public prop of my class _(using Typescript)_ which tells Vue that it should make the value reactive.
> 
> If I set it as private to remove the reactivity things run fine !
> 
> That may help others knowing this :)

Hi, Please, How do I set it as private to remove the reactivity things run fine ? I'm not quite sure what you mean

**Comment by Durss** [comment]
> > Ok nevermind i found out the issue !
> > 
> > It seems to be due to Vue adding watchers ! I was storing a renderer's reference as a public prop of my class _(using Typescript)_ which tells Vue that it should make the value reactive.
> > 
> > If I set it as private to remove the reactivity things run fine !
> > 
> > That may help others knowing this :)
> 
> Hi, Please, How do I set it as private to remove the reactivity things run fine ? I'm not quite sure what you mean

If you're on vue 3 with class decorators you'll need to declare every matterjs vars outside of the class as simple vars.
```typescript
let engine = blabla;
class YourVueComponent {
 public mounted() {
...
}
}
```
With vue2 and class decorators just use private keyword `private engine = blaba`

**Comment by denzhe22** [comment]
> > > Ok nevermind i found out the issue !
> > > It seems to be due to Vue adding watchers ! I was storing a renderer's reference as a public prop of my class _(using Typescript)_ which tells Vue that it should make the value reactive.
> > > If I set it as private to remove the reactivity things run fine !
> > > That may help others knowing this :)
> > 
> > 
> > Hi, Please, How do I set it as private to remove the reactivity things run fine ? I'm not quite sure what you mean
> 
> If you're on vue 3 with class decorators you'll need to declare every matterjs vars outside of the class as simple vars.
> 
> ```ts
> let engine = blabla;
> class YourVueComponent {
>  public mounted() {
> ...
> }
> }
> ```
> 
> With vue2 and class decorators just use private keyword `private engine = blaba`

Thank you very much for your reply.
But I'm sorry, I still don't understand, please forgive my ignorance.
Here's my code:

svelte1.svelte

`<script lang="ts">
  let engine
  let render
  let runner
  const initMatter: Action<HTMLCanvasElement> = (node) => {
    $matterEngine = new MatterEngine (node);
    engine = $plinkoEngine.engin
    render = $plinkoEngine.render
    runner = $plinkoEngine.runner
  };
</script>
<div>
     <canvas
        use:initMatter
        width=100
        height=100
        class="absolute inset-0 h-full w-full"
      />
</div>
`


MatterEngine.ts
`class PlinkoEngine {
  public engine: Matter.Engine;
  public render: Matter.Render;
  public runner: Matter.Runner;

  constructor(canvas: HTMLCanvasElement) {
        this.runner = Runner.create();
        this.engine = Engine.create()
        this.render = Render.create();

  }
}`

That's what I understand, but it doesn't seem to solve my problem.
I'm using the svelte kit
Then I found that when I clicked my button, or played the sound, or played node.animation, the game would be very slow, but when I didn't do anything, Matter.js would be very normal.

**Comment by TheHackerClown** [comment]
hi @liabru, I was trying to use Vite with Matter-JS, but i am having an issue, in the development build the performance is pretty good, but in production build, the render lags heavily. I have tried setting the build.sourcemap to false, and rollupOptions.sourcemap to false. My main suspicion is towards the Matter.Composite.translate function, as the code given below

`    let OffsetX = window.innerWidth / 2 - playerbody.current.position.x;
    if (Math.abs(OffsetX) > 0.01) {
      Matter.Composite.translate(engineref.current.world, {
        x: OffsetX,
        y: 0,
      });
    }
`
else everything works fine.
