### ISSUE TITLE
Renderer.create options

### ISSUE THREAD

**Issue by jaykyburz** [liabru/matter-js#1002]
I just started playing with matter today and something seems off om Render.create. I don't think the supplied options are being copied over onto the render object correctly. 

I assume the line  var render = Common.extend(defaults, options); is supposed to do it, but it does not. 

I'm on 0.17.1

**Comment by jaykyburz** [comment]
quick update.. I'm not sure how you would do it in matter.js, but Ive added the following so that my supplied options are used. 

```
        for (const key in options){
            render.options[key] = options[key]
        }
```

**Comment by jaykyburz** [comment]
I see my bug, options is property of defaults.

**Comment by liabru** [comment]
Yeah this was an unfortunate naming choice at the start of the project I think, I'll consider if there's a way to make this clearer or refactor somehow, thanks for raising.
