### ISSUE TITLE
why texture opacity changed, when body setStatic true

### ISSUE THREAD

**Issue by cuixi** [liabru/matter-js#1003]
i want setStatic(bodyA, true) after the body collisionEnd, but the body opacity been changed, what should i do to keep the body opacity and style after setStatic, thank you!

like this

![b](https://user-images.githubusercontent.com/8605867/117397960-e1b52180-af2f-11eb-9597-0d553b22af2d.jpg)

![a](https://user-images.githubusercontent.com/8605867/117397918-c9450700-af2f-11eb-8e78-42126cad2d83.jpg)

**Comment by cuixi** [comment]
> Im not too sure but maybe try `Sleeping.set(body, false);`

yes, spleeping changed the opacity, i got it in render.js, thank you

> if (options.showSleeping && body.isSleeping) {
>     c.globalAlpha = 0.5 * part.render.opacity;
> } else if (part.render.opacity !== 1) {
>     c.globalAlpha = part.render.opacity;
> }

**Comment by cuixi** [comment]
> Yeah you should be able to set `render.options.showSleeping = false` to disable that, let me know if that's not working though.

it works, but it would lost performance, it that? is there any way to set sleep status but would not change opacity?

**Comment by liabru** [comment]
The bodies will still sleep as before so it won't change that, that option is only to disable the rendering opacity effect (which is just a debug tool). So should be exactly what you need here.
