### ISSUE TITLE
did Body.scale change the speed?

### ISSUE THREAD

**Issue by cuixi** [liabru/matter-js#1004]
I scale the body to fit the different phone size, but i found the speed has been changed, it become fast at small screen. is that Body.scale change speed?

_this's body.scale code_

>     const rect = Bodies.rectangle(x, y, width, height, {
>        elementType: type,
>        friction: 0.3,
>        render: {
>            sprite: {
>                key,
>                texture: src,
>                xScale: scaleFixed,
>                yScale: scaleFixed
>            }
>        },
>        collisionFilter: {
>            group: 1
>        },
>        chamfer: {
>            radius: 10
>        }
>    });
>    Body.scale(rect, scaleFixed, scaleFixed);

**Comment by liabru** [comment]
I'd assume yes as `Body.scale` physically changes the size of the body including its mass, so this will change its dynamics. 

It sounds like you should scale your drawing instead in this case?
