### ISSUE TITLE
Interconnected constraints: bodies get stuck oscillating between other bodies

### ISSUE THREAD

**Issue by klaraseitz** [liabru/matter-js#1005]
Nice library! 
I am just getting started with trying it out for my use case. I am trying to build a visualisation of a graph structure where nodes always have a predecessor and (almost) always connect to another node. The links to connect the nodes need to be drawn at a given distance (can vary from node to node) which is why I tried using Matter.Constraint to simulate links between nodes by specifying the length property.
My goal is to show this as interactive graph with no (link- or node-) overlaps / folds. 

Here I have an [example codepen](https://codepen.io/Clarina/pen/MWpaBve) which shows my issue. Click on the canvas to add nodes. The first 3 still work nicely and spread well but after that they get stuck between the previous nodes and are oscillating because the bodies are colliding but the length of the constraint is still not satisfied. (Which it could - just not in between the nodes)
![image](https://user-images.githubusercontent.com/11996418/117840868-d0944980-b27c-11eb-8539-e44cdbf90ec5.png)

This is what I want to see in the case where multiple nodes connect to a center node (it can spread it out nicely after dragging the bodies around):
![image](https://user-images.githubusercontent.com/11996418/117839873-e9502f80-b27b-11eb-8032-39919ed627fe.png)

The graph in my application can and will grow larger than just a few nodes into a center node. So I was hoping defining the constraints would be enough for an autolayout. But since I always have to specify a position for a new node (in my example (0,0) ) mostly it gets drawn directly in between nodes. 

I tried already various settings for stiffness and even tried adding bodies between nodes to act like a barrier so that nodes cannot get stuck. But then they still managed to get into that triangular space inbetween sometimes. 

Previously I have worked with force graphs. The 'charge force' which makes all nodes repel each other helped with this issue. But there the length of the links where not close enough to the given values.

I'd be very grateful for any hints and suggestions for solving this. 
Thanks!

**Comment by liabru** [comment]
Some suggestions to try:

- increase `engine.constraintIterations`
- use a low `constraint.stiffness`
- use more constraints to form a mesh
- use a smaller engine timestep and multiple engine updates

and your idea of a repelling force is worth a try I think?
