### ISSUE TITLE
how can i disable drag event?

### ISSUE THREAD

**Issue by cuixi** [liabru/matter-js#1006]
i don't want to drag the shapes, so can i disable it

**Comment by michael-garofalo** [comment]
I'm not sure what's going on here, but it sounds related to MouseConstraint...

https://brm.io/matter-js/docs/classes/MouseConstraint.html

...if you simply don't want the items to be draggable, perhaps removing the related MouseConstraint code is what you're looking for.

**Comment by liabru** [comment]
Yeah sounds like you should remove the `MouseConstraint`, thanks @michael-garofalo.
