### ISSUE TITLE
linewidth and strokeSTyle do nothing when using sprite

### ISSUE THREAD

**Issue by koraysels** [liabru/matter-js#1008]
consider following function:

```
 const addImage = async imagePath => {
        let {width, height} = await dimensions(imagePath);
        let imageblock = Bodies.rectangle(500, 50, width, height, {
            render: {
                sprite: {
                    texture: '/image-test.jpg'
                },
                strokeStyle: '#0000ff',
                fillStyle: '#0000ff',
                strokeColor: "#000000",
                strokeWidth: 3,
                lineWidth: 40
            }
        });
        World.add(engine.current.world, [imageblock])
    }
```

It renders the sprite perfectly, but there are no strokes present. how can we get the linewidht and stroke width to do what they are supposed to do ? are they perhaps underneath the sprite ?

**Comment by liabru** [comment]
Ah this is probably not documented, but the built in renderer doesn't render any vector shapes if a sprite is set, so I'd suggest making your own fork of `Matter.Render` if you need something like this.
