### ISSUE TITLE
Slingshot game with keys, as cannon?

### ISSUE THREAD

**Issue by lisaspiering** [liabru/matter-js#1009]
Hi all,

I'm trying to adapt the slingshot game so that instead of using the mouse to pull and shoot the rock, users can use the keyboard buttons to do the same. Is this is any way possible? 
To simplify this, I wondered whether it would be easier to first pre-set the rock so that it already starts in a 'pulled' position and the users would only use the e.g. arrow keys to adjust the angle of the rock.
The slingshot would function a bit like a cannon

Any help would be much appreciated!
Best, Lisa

**Comment by michael-garofalo** [comment]
Well, these days, I'd probably not rely on keyboard controls. Lots of people are using mobile devices and they might not have a keyboard attached.

Also, Tumult already built something with Hype. On this page... https://tumult.com/hype/tutorials/ ...there's the "Mastering Physics" template at the bottom. That has all sorts of information about Physics. In particular, the "Castle Cannon" scene might be what you're looking for. Hype is a Mac exclusive app, but it uses Matter.js as the Physics engine.

But OK, let's say you want to do this without Hype... and you really REALLY want to use the keyboard... I'd probably not use Physics movement on the rock right away. Instead, I'd use something like the left/right keys to increase/decrease the radius from the center-point. This is where it gets complicated.

The rock can be positioned on a circular path using SIN/COS...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sin
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/cos

Looks like you'd need to convert the angle to radians. Using the cos and sin math functions, as shown in the examples on those pages, you can get the X&Y values for the rock. You'd also want to add some limits on the slingshot — not a full 360° of range.

Another tricky part is managing the controls. The values would have to change steadily as the player holds down the arrow keys. That becomes a matter of managing keydown / keyup events. Then, something like the spacebar could be used to launch the rock. That's when the velocity (X&Y) could be set, based on the distance from the center point.

This is theoretical, as I haven't actually built a rock chucking game with Matter.js or Hype, but it sounds like it could be fun. 😃

**Comment by lisaspiering** [comment]
Thanks so much for all these infos and resources :) ! Sorry about my late reply, it took me a bit to find the time to implement this right away.
Thanks for the links to Hype, I didn't know about this. Unfortunately, I couldn't use this for my study and instead implemented this myself. I coded a version in which at the beginning of the game round, the rock is at a pulled position and one can use the left and right arrow keys to move the rock on a circular path around the anchor. Finally one can press the middle button to shoot the ball.
This is the overall workflow for this:

**1. first pull back the rock to a pre-defined position:**
 - preset rock to a position different from the anchor
 - apply force to rock and set rock static so that it its position can be changed using the left and right arrow key
```
// set initial position to 45 degree angle, 80 pixels horizontally and vertically from anchor
new_x_rock_position = rock.position.x - 80
new_y_rock_position = rock.position.y + 80
Body.setPosition(rock, {x: new_x_rock_position, y: new_y_rock_position}); // put rock into default 45 degree position
Body.applyForce(rock, {x: rock.position.x, y: rock.position.y}, {x: 0.15, y: 0.15}); // apply force to rock so that it flies when middle button is pressed the next time
Body.setStatic(rock,true) // set static so that the position of the ball can be adjusted and the ball doesn't immediately go back to initial position
```

**2. Add event listener to key presses and then call SlingshotButtonDown function**
 - In  `settings.btnbox.XXX_button_id` I predefined the key code IDs of the left, middle and right button
 - If one press the left or right button, a separate function to change the rock's position is called (slingshotAim(): this function moves the rock position on a circular path around the anchor (left button press moves the rock upwards, right button press moves the rock downwards)
 - If the player presses the middle button, release the rock
```
window.addEventListener('keydown',SlingshotButtonDown)
[...]
var SlingshotButtonDown = function(e) { 
  if (temp.btnbox.sling_is_pulled & (e.keyCode === settings.btnbox.left_button_id | e.keyCode === settings.btnbox.right_button_id)) { // if the rock is pulled and they press the left button, move rock UP on circular path
    if (e.keyCode === settings.btnbox.left_button_id) { // if the rock is pulled and they press the left button, move rock UP on circular path
      temp.btnbox.pressed_up = true; // these variables will be used in slingshotAim()
    } else if (e.keyCode === settings.btnbox.right_button_id) {
      temp.btnbox.pressed_down = true;
    }
    slingshotAim()
  } else if (temp.btnbox.sling_is_pulled & !temp.btnbox.pressed_shoot & e.keyCode === settings.btnbox.middle_button_id) {
    temp.btnbox.pressed_shoot = true;
    Body.setStatic(rock,false) // release rock
  }
}

function slingshotAim() {
  // Before moving the rock, we need to compute the angle between the anchor and the rock which is the center of the circle on which the rock can be moved on
  // 1) compute distance from anchor to rock position
  distance_rock_anchor = Math.sqrt(Math.pow(anchor.x - rock.position.x, 2) + Math.pow(anchor.y - rock.position.y, 2)) // hypotenuse
  distance_x_rock_anchor = Math.abs(anchor.x - rock.position.x) // adjacent
  // 2) compute angle in radians
  angle_rock_anchor = Math.acos(distance_x_rock_anchor / distance_rock_anchor)
  // 3) compute new angle depending on the pressed button
  if (temp.btnbox.pressed_up == true) { // if the rock is pulled and they press the left button, move rock UP on circular path
    angle_rock_anchor_new = angle_rock_anchor - 0.01 // decrease this value to move rock upwards
    temp.btnbox.pressed_up = false
  } else if (temp.btnbox.pressed_down == true) {
    angle_rock_anchor_new = angle_rock_anchor + 0.01 // increase this value to move rock downwards
    temp.btnbox.pressed_down = false
  }
  // set new positions
  distance_x_rock_anchor_new = Math.cos(angle_rock_anchor_new) * distance_rock_anchor
  distance_y_rock_anchor_new = Math.sin(angle_rock_anchor_new) * distance_rock_anchor
  new_x_rock_position = anchor.x - distance_x_rock_anchor_new
  new_y_rock_position = anchor.y + distance_y_rock_anchor_new
  Body.setPosition(rock, {x: new_x_rock_position, y: new_y_rock_position}); 
  return new_x_rock_position // make these values available to functions above to compute the performance of participants
  return new_y_rock_position
}
```

**3. On every update of the engine, instead of checking whether `mouseConstraint.mouse.button === -1`, I now check whether the middle button has been pressed yet**
for example:
```
Events.on(engine, 'afterUpdate', function () { //fires off this function every time the engine updates
        if (temp.btnbox.pressed_shoot == true && (rock.position.x > 175)) {
           window.removeEventListener('keydown', SlingshotButtonDown) // stop listening for key presses
           [...]
```

On my keyboard, I can hold down the arrow keys to repeatedly change the rock position. But in the study for which I am coding this, participants will use a button box which doesn't behave like this. So like you suggested, I will need to change the code and handle keydown / keyup events differently. I'll try to implement this as well and then put it here :)
