### ISSUE TITLE
TypeError: root is undefined

### ISSUE THREAD

**Issue by cp7781** [liabru/matter-js#1010]
The **goal**: Start learning. How to use the library?
Current **situation**: Imported the library in a JavaScript module file. While debugging with Firefox, an error is shown.

![image](https://user-images.githubusercontent.com/73904480/118307434-f888e480-b4ea-11eb-94bf-ba9ef3f6b3fa.png)

So, any comments, hints, tips or tricks?

https://github.com/cp7781/cp7781.github.io/tree/physics

**Comment by cp7781** [comment]
Fixed with change in the import statement.

`import matterJs from 'https://cdn.skypack.dev/matter-js'
`

**Comment by liabru** [comment]
Do these CDNs use the official release build? If they do and the problem lies there do let me know, otherwise contact the CDN I think.
