### ISSUE TITLE
I like enabling sleep. and keep isSensor body always awake - what is the easiest way to implement this?

### ISSUE THREAD

**Issue by lancety** [liabru/matter-js#1012]
my game map is formated by several polygons, I made these polygons and set them isSensor = true;  
Then I want to make these polygon sensors to detect player body move in/out with the collision start/end, the issue is when enabling "sleep" the player body will go to sleep quickly after stop moving. 

I want to make the polygon keep awake, so even player went to sleep sensor still able to detect player is there. 
The most obviouse way is to get all these sensors and set isSleep to false when "beforeUpdate", but wondering if there is a more similer way to force a body not to sleep, such as body.forceAway = true or bodyDefinition.forceAwake = true;

Thanks for help.

**Comment by lancety** [comment]
seems below code is the only place set sleep to true, so if I set body.sleepThreshold = 0 should block sleeping right?

`
if (body.sleepThreshold > 0 && body.motion < Sleeping._motionSleepThreshold * timeFactor) {
                body.sleepCounter += 1;
                
                if (body.sleepCounter >= body.sleepThreshold)
                    Sleeping.set(body, true);
            } else if (body.sleepCounter > 0) {
                body.sleepCounter -= 1;
            }
`

**Comment by lancety** [comment]
seems the sensor body now stopped sleeping, but when player body inside the polygon and stop moving, it will still trigger collissionEnd when the player body went to sleep;  ;(

**Comment by AurangAsif** [comment]
```js
Events.on(body, 'sleepStart', e => {
  Sleeping.set(body, false);
  // or...
  // Sleeping.set(e.source, false)l
});
```
https://brm.io/matter-js/docs/classes/Body.html#event_sleepStart
https://brm.io/matter-js/docs/classes/Sleeping.html#method_set

**Comment by lancety** [comment]
thank you @AurangAsif ,  I should review the Events supported names again.
