### ISSUE TITLE
Explosions in matter.js

### ISSUE THREAD

**Issue by beetrandahiya** [liabru/matter-js#1013]
I was working on making 3 body gravitational interaction system, and when the bodies collide, is there a way to add something like an explosion there, maybe a gif of explosion at the point of collision maybe. 
If someone can help, please stop by.

**Comment by AurangAsif** [comment]
Do you want graphic some effect or do you want to simulate an explosion?

**Comment by beetrandahiya** [comment]
just the graphic effect, simulating an explosion would be hard job, so just an effect

**Comment by liabru** [comment]
There's nothing built in as the renderer is mostly for debugging or other simple uses, but you could probably draw it in the [afterRender event](https://brm.io/matter-js/docs/classes/Render.html#event_afterRender) or fork `Matter.Render` and implement it in there somewhere.
