### ISSUE TITLE
what does the "Pair" means in the status bar when enabling "showDebug" on demo page?

### ISSUE THREAD

**Issue by lancety** [liabru/matter-js#1015]
hi there,  I modified the "sensor" example, made 1500 random static polygons, each with 30 sides. then added a circle sensor, keep setPosition of it and keep it NOT sleep. 

When everything not sleep, the "Pair" value is always around 90-95 (collided polygons normally is about 50, plus extra polygons on the way to fall sleep equals about 90-95 in total)
When enable sleeping in "engine" menu, all polygons went to sleep except those ones collided with the moving circle, the "Pair" then becomes the total number of circles HAS collided with circle on the moving path from left to right, and finally stay at 349.

Is this number bigger means optimised better or should be smaller.  If smaller is better then making things sleep should not make it becomes larger number, right? I am little confused about the value.

![image](https://user-images.githubusercontent.com/5547558/119233053-878ca100-bb6a-11eb-97f1-575169a88354.png)

**Comment by liabru** [comment]
The `Pair` number refers to the number of collision pairs currently in the engine's internal collision pair manager, which is _roughly_ the number of colliding pairs of bodies in the last few seconds (it should drop when collisions end). 

The number just relates to how many collisions are happening, so I wouldn't worry about this number unless you're familiar with the internal collision system and know there is a problem?

**Comment by lancety** [comment]
thanks for feedback~ :)
