### ISSUE TITLE
Object's Speed can not be zero

### ISSUE THREAD

**Issue by mengxun1437** [liabru/matter-js#1018]
hello,i am very confused that when i use the Body.speed , i see the Body has been stoped, however in fact, its speed is not zero, hero is the screen shot:
![image](https://user-images.githubusercontent.com/54832685/120186076-9b5c9500-c245-11eb-909c-61b831c0b3a1.png)
 
and i do this just because i want to judge if a Body has been stoped or not?
could you please help me with it?Or could you please give me some other way to deal with my demand？
thanks!

**Comment by liabru** [comment]
Unfortunately bodies often don't truly come exactly to rest for various reasons, so what you need to do is use a threshold and check the motion over a few updates. This is how the built in sleeping feature works which is worth looking at here [Matter.Sleeping](https://github.com/liabru/matter-js/blob/master/src/core/Sleeping.js#L45-L52).

**Comment by mengxun1437** [comment]
> Unfortunately bodies often don't truly come exactly to rest for various reasons, so what you need to do is use a threshold and check the motion over a few updates. This is how the built in sleeping feature works which is worth looking at here [Matter.Sleeping](https://github.com/liabru/matter-js/blob/master/src/core/Sleeping.js#L45-L52).

**Comment by mengxun1437** [comment]
thank you for your reply, your project help me great, and wish you become better!
