### ISSUE TITLE
Bodies created on canvas "lag" when dropping down

### ISSUE THREAD

**Issue by danielshamsudin** [liabru/matter-js#1019]
I'm currently creating a game where a player has to catch dropping items. The dropping items are created with Bodies.circle and paddle is created with Bodies.rectangle . As for now I'm having problems with the item dropping at a weird behavior. The item will drop slowly at around 10-20% of screen height, and continue to drop normally onwards. Is there any particular reason why this happens?

**Comment by liabru** [comment]
Could you share an example or a gif and what your expectation is more specifically?

Are they just dropping under gravity? Bodies will take a little time to accelerate when a force is applied, this combined with friction means speed will not be constant or linear. Would that explain what you're seeing or is it something else?

**Comment by danielshamsudin** [comment]
![github](https://user-images.githubusercontent.com/63139460/121429637-b77cd680-c9a9-11eb-9879-9ccc2652863b.gif)
This is the current situation. Based on your explanation, I think that was whats happening. Let's say i wanted to make the item drop on a constant speed from the top to the bottom, what is the best way to achieve that?

**Comment by liabru** [comment]
What I'd suggest to do that in this case is disable gravity, then set `body.frictionAir = 0` and set an initial velocity e.g. `Body.setVelocity` which then should remain constant until there is a collision.

**Comment by danielshamsudin** [comment]
Alright, that solves the problem, thank you very much! Great library btw!
