### ISSUE TITLE
Resolver: uncaught error

### ISSUE THREAD

**Issue by demipel8** [liabru/matter-js#102]
> Uncaught error:  positionImpulse is not defined

Hi I'm creating a wrapper for craftyjs framework and I've comed across this little problem.

The fix is as easy as adding the `positionImpulse` variable declaration at the start of Resolve.solvePosition function. 

Is it a bug or perhaps I'm doing a bad use of the framework?

thanks

**Comment by liabru** [comment]
Should now be solved, thanks for raising this!
