### ISSUE TITLE
Github API for matterjs releases returns empty

### ISSUE THREAD

**Issue by msawired** [liabru/matter-js#1020]
Hello,

I am trying to feature matterjs on OpenProcessing libraries section, however we need to access the releases via Github API to automatically update any releases. For some reason, it shows empty on the REST API below. Any ideas?
https://api.github.com/repos/liabru/matter-js/releases

**Comment by liabru** [comment]
Ah that might be because the project is only using tags as releases? 

They do seem to show up on the API under here instead:
https://api.github.com/repos/liabru/matter-js/tags

Hopefully that can that work?

**Comment by msawired** [comment]
I see. It is formatted quite differently from the releases JSON format, so that wouldn't work unfortunately. Let me know if  you have any plans to add releases to your workflow, so I can add the automation to our backend. Cheers, and thank you for providing us this library!

**Comment by liabru** [comment]
I think it will likely stay as tags only since it makes releases much more straightforward. Great to see it's going up on OpenProcessing though, I'll close this but let me know if there's anything else to help.
