### ISSUE TITLE
How to draw bodies (shapes) with a responsive-fluid dimensions?

### ISSUE THREAD

**Issue by mattiaband** [liabru/matter-js#1028]
I was able to finalize a logo animation, the logo is built with different shapes.

here you can see the final result > [codepen link](https://codepen.io/mp1985/pen/zYwrrQq)

but I don't know how to draw bodies (shapes) with responsive (fluid) dimensions? not the canvas itself (i can do this with viewport's width/height and css), but the actual logo and the bodies (shapes) that compose it.

basically, I would like that the logo will be always aligned in the center and it will take always 90% of the width of the viewport.
the problem is that the logo is not just one element, but it is composed by 17 different shapes (matterjs Bodies), for this reason, I am not sure the best way to deal with this.

I know that in matter.js you need to write x,y numbers in pixel from the top-left corner for the bodies, but I am wondering how to deal with alignment in the center on the viewport and how to make it responsive (so the shapes will take always a % of the viewport).

I hope that my question/doubt is clear, maybe an image will explain better.

![Screenshot-2021-07-05-at-12 44 31](https://user-images.githubusercontent.com/15800085/124485576-02251f00-ddad-11eb-8b44-f92d70ae35dc.jpg)

Could somebody point me to the right direction?

I am approaching the canvas world while I am studying matterjs, so any recommendation would be great!

is there an extra app that you recommend that helps to understand how to write x,y values based on your layout? (I tried with photoshop and illustrator to get the x,y of the singular shape, but I am wondering if there is a better app)

**Comment by liabru** [comment]
Yeah exactly, hopefully you managed to get this working but if I understand what you mean, you'd probably need to rescale and update the position of the bodies when the window resizes? 

Check out both [Composite.scale](https://brm.io/matter-js/docs/classes/Composite.html#method_scale) and [Body.scale](https://brm.io/matter-js/docs/classes/Body.html#method_scale) and the [body manipulation example](https://brm.io/matter-js/demo/#manipulation) which can probably get you started.
