### ISSUE TITLE
How to prevent body lifting by a platform upon collision?

### ISSUE THREAD

**Issue by kornerr** [liabru/matter-js#1029]
Hi.

I've implemented one-sided collision to have a normal platform game behavior where you can jump from below a platform. The implementation is based on the suggestion in #284: changing collisionFilter.mask based on the player's velocity.

Jumping from below a platform works almost right, however, platforms now lift the player when the player is half way through the platform, here's the video: https://youtu.be/oPdY7LFG4dU

How to prevent that lifting and let the player fall through the platform if collision is not happening under the players' feet?

**Comment by liabru** [comment]
The lifting is probably the collision solver pushing the player body out out of the platform? 

I think what you probably need to do is make sure the player makes it all the way through to a clear spot above the platform, rather than landing half way inside it and getting pushed out.

**Comment by dariosn85** [comment]
@kornerr did you solve your issue (and how)?

@liabru could you please tell more about how to determine if player is above the platform?

> I think what you probably need to do is make sure the player makes it all the way through to a clear spot above the platform, rather than landing half way inside it and getting pushed out.
