### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by phillips1012** [liabru/matter-js#103]
Matter.js does not currently support node.js

![](http://i.imgur.com/4XyecTm.png)

Since matter.js supports multiple rendering backends, it would make sense for it to work in node.js

**Comment by corsa1r** [comment]
At the beginning of your node project you can set window as empty object.

var window = {};

**Comment by ronami** [comment]
I would really like to be able to run matter.js headless (without any rendering) on node.js too. Without having to hack stuff like the above post mentioned.

**Comment by liabru** [comment]
This has now been resolved in #101, please refer to my latest comment in that thread, thanks.
