### ISSUE TITLE
Cannot read property 'push' of undefined. 

### ISSUE THREAD

**Issue by radshan** [liabru/matter-js#1030]
Hello, I have the following script injected in my index.html file:

<script>
      let engine = Matter.Engine.create();
      let render = Matter.Render.create({
        element: document.body,
        engine: engine,
      });

      let ground = Matter.Bodies.rectangle(400, 600, 810, 60, {
        isStatic: true,
      });

      let boxA = Matter.Bodies.rectangle(400, 200, 80, 80);
      let boxB = Matter.Bodies.rectangle(400, 200, 80, 80);
      Matter.Composite.add(engine, ground);
      Matter.Engine.run(engine);
      Matter.Render.run(render);
 </script>

 Upon opening the site, I get the following error: 
 
`Uncaught TypeError: Cannot read property 'push' of undefined
    at Object.Composite.addBody (matter.js:1904)
    at Object.Composite.add (matter.js:1780)
    at index.html:19
`

Any idea how I can fix this?

**Comment by japraj** [comment]
In your call to `Matter.Composite.add`, you should pass `engine.world` instead of `engine`

**Comment by radshan** [comment]
> In your call to `Matter.Composite.add`, you should pass `engine.world` instead of `engine`

It worked! Thank you.
