### ISSUE TITLE
Is this call to setModified necessary

### ISSUE THREAD

**Issue by japraj** [liabru/matter-js#1031]
Hello is the call to `Composite.setModified` necessary here

https://github.com/liabru/matter-js/blob/e909b0466cea2051267bab92a38ccaa9bf7f154e/src/body/Composite.js#L238

since `Composite.removeAt` calls `setModified` anyway? I noticed that `removeComposite` has an extra call too while `removeConstraint` does not

**Comment by liabru** [comment]
Good catch, possibly not though I'd have to investigate so marked have this, thanks!

**Comment by liabru** [comment]
It think this one was resolved [here](https://github.com/liabru/matter-js/blob/master/src/body/Composite.js#L245-L258) so closing, thanks again.
