### ISSUE TITLE
Add a way of making bodies unmovable by collisions but movable by setting velocity

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [liabru/matter-js#1035]
## What I'm trying to do
Here is my understanding of the `isStatic` property:

|                       | isStatic = false | isStatic = true |
|-----------------------|------------------|-----------------|
| Movable by Collisions | Yes              | No              |
| Movable by Setting Velocity   | Yes              | No              |

I want to make my rectangle movable by velocity, but not movable by collisions:

|                       | What I'm trying to do  |
|-----------------------|------------------------|
| Movable by Collisions | No                     |
| Movable by Setting Velocity   | Yes                    |

So the `isStatic` option does not work for my use case.

## What I tried
- I tried setting `density` to `Infinity`, because I thought that it would make nothing be able to move it, but then it still got moved, so it didn't work.
- I tried resetting the position of the body on every tick, but that messed up its interaction with other objects that collide with it.
- `Body.setVelocity()` on the static body.

**Comment by liabru** [comment]
I'd say check out the [body manipulation example](https://brm.io/matter-js/demo/#manipulation) as hopefully that covers what you need. 

Static bodies don't move themselves or respond to collisions in a physically simulated way (so no velocity or force), but you can still move them around manually like in the example by setting their position which from the engine point of view effectively just 'teleports' them even though it appears like motion.

**Comment by ChocolateLoverRaj** [comment]
@liabru I am currently setting their position, but I am making a pong game, and I want the ball to spin depending on if the paddle is moving up, down, or not moving. Currently the paddles are static, and the ball isn't. I might be wrong, but I think that if the paddle had a velocity, it would internally affect the way the ball moves.

**Comment by japraj** [comment]
@ChocolateLoverRaj I resolved this issue in a custom build of the engine by adding an `ignoresCollisions` property to `Body` and editing the Resolver module

Specifically, I changed all conditionals that reference the `isStatic` property to also check for `ignoresCollisions`. For example, in Resolver.js, you would change `if (bodyA.isStatic || bodyB.isStatic) {...}` to `if (bodyA.isStatic || bodyB.isStatic || bodyA.ignoresCollisions || bodyB.ignoresCollisions) {...}` and `if (!(bodyA.isStatic || bodyA.isSleeping)) {...}` to `if (!(bodyA.isStatic || bodyA.isSleeping || bodyA.ignoresCollisions)) {...}` (and do that for every single line that uses `isStatic`, in the entire file)

**Comment by ChocolateLoverRaj** [comment]
@japraj can you share the code/fork please?

**Comment by japraj** [comment]
@ChocolateLoverRaj Sorry I did not post the code because I made a lot of breaking changes to the file (rewrote in typescript with ES6 classes and a new API, and made modifications to support changes in several other modules) so it is not really recognizable or easily usable outside of my codebase

**Comment by ChocolateLoverRaj** [comment]
@japraj Oh ok so I should do what you said in https://github.com/liabru/matter-js/issues/1035#issuecomment-908027042 with the latest version for my own use.
