### ISSUE TITLE
How to get click coordinates in world position?

### ISSUE THREAD

**Issue by py82py** [liabru/matter-js#1037]
because of player move, camera move, camera padding(this is problem) ..., i can't get mouse coordinate in world

how can i get this?

**Comment by py82py** [comment]
i found it mouseConstraint.mouse.position.x, mouseConstraint.mouse.position.y,

**Comment by py82py** [comment]
mouseConstraint.mouse.position.x,  mouseConstraint.mouse.position.y, sry i found it

**Comment by PiotrSzlagura** [comment]
@py82py @liabru I tried to use `mouseConstraint.mouse.position` but it still returns position on mouse relative to canvas, not position in the world. Are there some settings which are required for this behaviour?

**Comment by liabru** [comment]
@PiotrSzlagura if you're using `Matter.Render` with render bounds you also need to keep the mouse in sync. So for that I think you might be missing `render.mouse = mouse` e.g. here:

https://github.com/liabru/matter-js/blob/master/examples/airFriction.js#L61-L62

**Comment by PiotrSzlagura** [comment]
@liabru Thak you!!! This change fixed my issue and it all works perfect now :)

**Comment by qtanran** [comment]
Thak you!!!
