### ISSUE TITLE
Prevent rotation

### ISSUE THREAD

**Issue by ar7hur** [liabru/matter-js#104]
Thanks for the great library.

I'm trying to prevent my bodies to rotate. It would be a "unary" constraint. I've looked at the code and issues but it looks like it's not possible currently. If not, I'd be happy to submit a PR if you can put me on the right track!

**Comment by liabru** [comment]
Try set `inertia` to `Infinity` when you create your body.

**Comment by ar7hur** [comment]
Awesome! Thanks a lot.

**Comment by roschler** [comment]
Does that still work?  I tried setting my player object's `inertia` property to `Infinity` and it still tips over.  I tried both:
```
player.body.inertia = 'Infinity';
```
And
```
player.inertia = 'Infinity';
```
The object still tips over.  Note this is with a Phaser JS app using the Matter JS physics engine.

**Comment by liabru** [comment]
@roschler it needs to be the word `Infinity` without any quotes as it's a value in JS, then it should work.

**Comment by jackyrusly** [comment]
@roschler you can use `setFixedRotation `func
`player.setFixedRotation();`

**Comment by myrriad** [comment]
@roschler Also be sure to set `player.inverseInertia=0`.
