### ISSUE TITLE
how to draw uncosed line

### ISSUE THREAD

**Issue by cuixi** [liabru/matter-js#1041]
Hey, I'm creating a game with the library, it's great.
and i want to draw a line on canvas and add to the word

> const line = Bodies.fromVertices(150, 200, vertexSets, {
            render: {
                fillStyle: 'transparent',
                lineWidth: 6
            }
        });
        World.add(myEngine.world, [line]);

First i draw a line on canvas, it works great, like this.

![drawline](https://user-images.githubusercontent.com/8605867/132098489-95b0ccd0-7a06-43a5-8c9c-b40279dbaec4.png)

I get the vertexSets when touchmove, and then i add the line to word, it closed, like this

![closedLine](https://user-images.githubusercontent.com/8605867/132098643-6bcf49ed-ca58-4721-84f2-6cc384fb538a.png)

what can i do, if i want get a unclosed line, thanks!

**Comment by liabru** [comment]
Think of it more as a tube than a line, so you'll need to figure out all of the vertices that trace around the edges and connect them first.

**Comment by cuixi** [comment]
> Think of it more as a tube than a line, so you'll need to figure out all of the vertices that trace around the edges and connect them first.

oh, thanks, that was great, you inspired me
