### ISSUE TITLE
 How to make a body phase through anything in Matter-JS?

### ISSUE THREAD

**Issue by noobie-boobie** [liabru/matter-js#1042]
I need to implement a Body using Matter.js which can move through any body like a ghost. Is it possible to do using Matter? Is there any function which can break this law of Physics in Matter-js?

I am looking for something like this:
```
let body = Matter.Bodies.rectangle(x, y, w, h);
body.ghost_mode = true;
```

**Comment by japraj** [comment]
Try using `body.collisionFilter.mask = 0` to allow a body to go ignore collisions with all other bodies, and reset it to `body.collisionFilter.mask = -1` if you want to revert it to normal

**Comment by liabru** [comment]
Exactly you can use collision filters for this, take a look at the [collision filtering example](https://brm.io/matter-js/demo/#collisionFiltering).

**Comment by noobie-boobie** [comment]
@liabru @japraj It worked. Thanks :)
