### ISSUE TITLE
trying to bind interaction sensor circle body to player circle body, what is the right setting for using constraint?

### ISSUE THREAD

**Issue by lancety** [liabru/matter-js#1046]
I had a look some discussion about binding a sensor to a body by using constratint, so when player body moving, the sensor will move together with player body, and detect any interactable body close to player when collision happens to the sensor. 

My problem now is when using Body.translate BodyA (player body) position, the body wont move and I can see the constraintImpluse is much larger than translate movement speed. , the player body remain staying at same location without moving.

here are my bodyA (player) and bodyB (sensor).  Wondering why body wont move when updating translate value of bodyA.  Thanks for any advice :)

here is how I made the constraint
` const sensorConstraint = Constraint.create({
      bodyA: body,
      bodyB: sensorBody,
      stiffness: 1,
  })`

body A - player body
`angle: 0
anglePrev: 0
angularSpeed: 0
angularVelocity: 0
area: 0.253154
axes: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
bInfo: {r: 1133, z: 694, floor: 0, space: 0}
bStatus: Set(1) {0}
bounds: {min: {…}, max: {…}}
chamfer: null
circleRadius: 0
collisionFilter: {category: 2, mask: 32709, group: -6001}
constraintImpulse: {x: 0, y: 0, angle: 0}
density: 2.1861463726730848
events: null
force: {x: 0, y: 0}
friction: 0
frictionAir: 0
frictionStatic: 0.5
gi: 1
gp: 6001
id: 6
inertia: 0.00004080451552266666
inverseInertia: 24507.091609616247
inverseMass: 3950.164721868902
isSensor: false
isSleeping: false
isStatic: false
label: "Polygon Body"
mass: 0.5534316988276821
motion: 0
parent: {id: 6, type: 'body', label: 'Polygon Body', parts: Array(1), plugin: {…}, …}
parts: [{…}]
plugin: {}
position: {x: 1208.7119420655845, y: 1816.7867247994895}
positionImpulse: {x: 0, y: 0}
positionPrev: {x: 1208.7119420655845, y: 1816.7867247994895}
region: {id: '25,25,37,37', startCol: 25, endCol: 25, startRow: 37, endRow: 37}
render: {visible: false, opacity: 1, strokeStyle: '#ccc', fillStyle: '#f5d259', lineWidth: 0, …}
restitution: 0
sensorConstraints: (4) [{…}, {…}, {…}, {…}]
sensorParts: (4) [{…}, {…}, {…}, {…}]
sleepCounter: 0
sleepThreshold: 60
slop: 0.05
speed: 0
timeScale: 1
torque: 0
totalContacts: 0
type: "body"
velocity: {x: 0, y: 0}
vertices: (16) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]`

bodyB of the constraint (sensor)
`angle: 0
anglePrev: 0
angularSpeed: 0
angularVelocity: 0
area: 70.69577199999999
axes: (4) [{…}, {…}, {…}, {…}]
bInfo: {r: 1133, z: undefined, floor: 0, space: 0}
bStatus: Set(1) {0}
bounds: {min: {…}, max: {…}}
chamfer: null
circleRadius: 0
collisionFilter: {category: 64, mask: 58, group: -7001}
constraintImpulse: {x: 0, y: 0, angle: 0}
density: 0.0000014145117476049347
events: null
force: {x: 0, y: 0}
friction: 0.1
frictionAir: 0.01
frictionStatic: 0.5
gi: 1
gp: 7001
id: 7
ignoreSync: true
inertia: 3.1890110002368743
inverseInertia: 0.313576842452322
inverseMass: 14.145117476049348
isSensor: true
isSleeping: false
isStatic: false
label: "Polygon Body"
mass: 0.0001
motion: 0
parent: {id: 7, type: 'body', label: 'Polygon Body', parts: Array(1), plugin: {…}, …}
parts: [{…}]
plugin: {}
position: {x: 1208.7119420655845, y: 1816.7867247994895}
positionImpulse: {x: 0, y: 0}
positionPrev: {x: 1208.7119420655845, y: 1816.7867247994895}
region: {id: '25,25,37,37', startCol: 25, endCol: 25, startRow: 37, endRow: 37}
render: {visible: false, opacity: 1, strokeStyle: '#ccc', fillStyle: '#063e7b', lineWidth: 0, …}
restitution: 0
sleepCounter: 0
sleepThreshold: 60
slop: 0.05
speed: 0
timeScale: 1
torque: 0
totalContacts: 0
type: "body"
velocity: {x: 0, y: 0}
vertices: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]`

**Comment by lancety** [comment]
finally I decided to add a afterUpdate listener to check each body, if it has sensor child, set its position to child.

**Comment by liabru** [comment]
I'd probably avoid using a constraint for that purpose and just move the sensor around directly each step using `Body.setPosition(sensorBody, otherBody.position)`? Would that help?

**Comment by lancety** [comment]
thanks @liabru , seems this requires the min steps of calculation, I will implement it this way.
