### ISSUE TITLE
Air friction doesn't consider mass

### ISSUE THREAD

**Issue by IsraEB** [liabru/matter-js#1047]
Making a pendulum simulator, I realized that air friction don't consider mass of the object, when it should be taked into consideration in a non-vacuum space.

Example:
2 circles with frictionAir: 0.01, one with mass 0.1 and the other with mass 5000, fall at the same time, but the 5000kg sphere should fall faster

**Comment by dominictarr** [comment]
hmm, i think you are incorrect, air friction does not depend on mass of the object, it depends on the mass of the air that gets pushed out of the way (and dragged along)

gravity is proportional to mass, so a light object is attracted with less force than the heavy object, so this means they both accelerate the same rate.

**Comment by liabru** [comment]
This was discussed in #833 so take a look there, but in short realistic air resistance doesn't depend on object mass, it's actually proportional to surface area and velocity. 

That said Matter.js uses a constant value as a simplified model as it's easier to work with in games. If you need something else then just set the built in to `0` and manually apply your own resistance forces each update.
