### ISSUE TITLE
Hide internal edges

### ISSUE THREAD

**Issue by ar7hur** [liabru/matter-js#105]
I work with concave polygons. I'm not able to hide internal edges (that are created when the concave polygon is decomposed into convex polygons). I tried to use `renderOptions.showInternalEdges = false` to no avail. Am I doing something wrong?

**Comment by liabru** [comment]
Would you be able to provide a jsfiddle? It depends how you create the bodies and also internal edge detection may not be perfect for some cases.

**Comment by ar7hur** [comment]
Sorry for the delay, here it is: https://jsfiddle.net/choqey7c/3/

**Comment by liabru** [comment]
Two issues here. You need to set the `flagInternal` argument of `Bodies.fromVertices` to `true`. The second is that the built in renderer can't yet handle body stroke correctly for solid rendering modes.

The best you can do for now is set the stroke and fill to the same colour or just use wireframe rendering or create a custom renderer.

Check out my updated version of your [fiddle](https://jsfiddle.net/choqey7c/6/).
