### ISSUE TITLE
New API documentation generator?

### ISSUE THREAD

**Issue by onetrickwolf** [liabru/matter-js#1051]
Hey I was having a hard time navigating the Matter.js docs and played around with running it through webdoc with the [PixiJS ](https://pixijs.download/dev/docs/index.html) config. It actually worked with pretty little effort and it's so much easier for me to navigate I've actually been using it in my day to day.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/13836477/135686844-a31e1586-646c-438f-98e2-6db074de3712.png)

Would Matter.js be interested at all in a contribution to migrate to webdoc? I think I could do it pretty easily and adjust the colors and style to match Matter.js branding more.

I noticed YUIDoc isn't really being maintained anymore as well so might be an added benefit switching in case that ever causes a problem.

**Comment by liabru** [comment]
I've updated the [docs](https://brm.io/matter-js/docs/classes/Engine.html) for the latest release and included a new members navigation panel, hopefully that makes things a bit easier.

**Comment by onetrickwolf** [comment]
@liabru that's amazing thank you so much! Honestly was just coming here to see if I could help out a bit with your awesome project but thank you for taking the time to actually address this.
