### ISSUE TITLE
how to specify image instead of path to image for background option in the renderer?

### ISSUE THREAD

**Issue by rayanisran** [liabru/matter-js#1053]
Is there a way to specify an image element instead of the path to an image for the background parameter of the options in the renderer?

```js
    var render = Render.create({
      engine: engine,
      canvas: canvas,
      options: {
          width: worldWidth,
          height: worldHeight,
          background: 'image/example.jpg' // <--- change this parameter to an actual image element
          wireframes: false,
          showAngleIndicator: false
        }
});
```
Specifically what I am trying to do is load an image (with p5.js), resize it, and use the resized image instead. If anyone here has used p5.js, all I'm trying to do is make a background image fit the same size of the p5 canvas. Perhaps there is an easier way?

**Comment by liabru** [comment]
So the background here is actually applied just as CSS [as you can see here](https://github.com/liabru/matter-js/blob/master/src/render/Render.js#L1522-L1530).

What you could probably do here is use `background: 'transparent'` and then overlay the canvas element on top of your image element using some CSS?
