### ISSUE TITLE
please tell me what is the problem.

### ISSUE THREAD

**Issue by ranveer2000** [liabru/matter-js#1057]
i am getting.
Uncaught TypeError: Cannot read properties of undefined (reading 'x') when i use x in setPosition
![sketch js - Pro34-Project-Boilerplate-main - Visual Studio Code 28-10-2021 11_36_19](https://user-images.githubusercontent.com/90261646/139196773-68b3e99f-8e78-40d9-a4e4-1cde815ba5ed.png)

(Pink is a class)

**Comment by PiotrSzlagura** [comment]
@ranveer2000 If you still have this issue, here's my proposal for solution - based on documentation this parameter should be Vector, which is not a plain JS object but matter-js object (see https://brm.io/matter-js/docs/classes/Vector.html)

**Comment by PiotrSzlagura** [comment]
I had the same issue when trying to use plain JS objects as vector (in my case it was in `applyForce` but I assume your case is similar)

**Comment by liabru** [comment]
[Body.setPosition](https://brm.io/matter-js/docs/classes/Body.html#method_setPosition) takes a body object as its first argument, so you should create a body and keep it on a `.body` property instead.
