### ISSUE TITLE
Matter.js tutorial not working

### ISSUE THREAD

**Issue by BigbrainNgl** [liabru/matter-js#1061]
I have exactly this
```
// module aliases
var Engine = Matter.Engine,
    Render = Matter.Render,
    Runner = Matter.Runner,
    Bodies = Matter.Bodies,
    Composite = Matter.Composite;

// create an engine
var engine = Engine.create();

// create a renderer
var render = Render.create({
    element: document.body,
    engine: engine
});

// create two boxes and a ground
var boxA = Bodies.rectangle(400, 200, 80, 80);
var boxB = Bodies.rectangle(450, 50, 80, 80);
var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

// add all of the bodies to the world
Composite.add(engine.world, [boxA, boxB, ground]);

// run the renderer
Render.run(render);

// create runner
var runner = Runner.create();

// run the engine
Runner.run(runner, engine);
```

I am getting an error 

```
matter-js: Render.create: options element was undefined, render.canvas was created but not appended warn
```
How can I fix it?

Also here is the HTML code

'''
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="package.js"></script>
	<script src="matter.js"></script>

</head>
<body>
</body>
<style>
	body {
		margin: 0;
		padding: 0;
	}
</style>
</html>
'''

**Comment by CarterCodesRSA** [comment]
Hey, Hopefully this can help out:

Try moving your script tag for your script.js into the body itself:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Matter.js</title>
  </head>
  <script  type="text/javascript" src="/matter.js"></script>
  
  <body>
    <script  type="text/javascript" src="/script.js"></script>
  </body>
</html>
```

If you're `script.js` is not being loaded within the body itself, it doesn't have any context as to what the "body" is that the Render.create() method is trying to use.
Give it a test by (before making a change) try console.log(document) and see what props it has.

**Comment by liabru** [comment]
As @CarterCodesRSA says, I think you need to make sure your HTML page is complete and make sure the script is loaded last so that the body element is available when it runs.
