### ISSUE TITLE
Sensor body as part of compound body

### ISSUE THREAD

**Issue by tawjaw** [liabru/matter-js#1067]
Hello, 
I have a sensor body as part of a compound body. 

The problem is that the sensor body is affecting the movement when forces are applied to the compound body. Although it should not have an effect (as far as I understand). I am also setting the mass and area to 0 for the sensor body and that didn't solve the problem. 

```js
        //create the robot body object
        this.robotBody = Bodies.rectangle(100, 100, 50, 30, {render: {fillStyle : 'DarkRed'}} );
        this.leftWheelBody = Bodies.rectangle(88, 82, 20, 6, {render: {fillStyle : 'black'}});
        this.rightWheelBody = Bodies.rectangle(88, 118, 20, 6, {render: {fillStyle : 'black'}});
        //create the ultrasonic sensor body
        this.ultrasonicSensor = createPartCircle(110,-30, 50,200, -3*Math.PI/7,{label: 'ultrasonic'});
        this.ultrasonicSensor.isSensor = true;
        this.ultrasonicSensor.render.opacity = 0.2;
        this.ultrasonicSensor.mass = 0;
        this.ultrasonicSensor.area =  0;
        //create the robot from parts
        this.robot = Body.create({parts: [this.robotBody,this.ultrasonicSensor ,this.leftWheelBody, this.rightWheelBody]});
        this.robot.frictionAir = 0.1;
        Body.setMass(this.robot, 100000);
```

the full code can be found here: https://github.com/p4labs/p4-robotsim/blob/main/src/robots/TwoWheelRobot.ts

If I create the body without the sensor

```
        this.robot = Body.create({parts: [this.robotBody,this.leftWheelBody, this.rightWheelBody]});

```

Then the movement of the robot when forces are applied from the position of the wheels make sense. With the sensor it does not rotate properly. 

What am I missing? 

Thanks

**Comment by PiotrSzlagura** [comment]
Maybe try setting `isSensor` in `createPartCircle` options instead of setting it afterwards? If this doesn't help, I would try setting `density = 0` for this object, maybe this will have desired effect. (It's all just a guess, I just started exploring matter-js yesterday) :)

**Comment by tawjaw** [comment]
> Maybe try setting `isSensor` in `createPartCircle` options instead of setting it afterwards? If this doesn't help, I would try setting `density = 0` for this object (the sensor object), maybe this will have desired effect. (It's all just a guess, I just started exploring matter-js yesterday) :) 

@PiotrSzlagura That worked! Thanks.
I had to use the setter 
`Body.setDensity(this.ultrasonicSensor, 0)` for it to work.

**Comment by billgothacked** [comment]
Yeah I THINK I have one too: )
