### ISSUE TITLE
Objects overlapping after collision

### ISSUE THREAD

**Issue by PiotrSzlagura** [liabru/matter-js#1068]
Hi, I have a problem where one body overlaps with another after collision:
<img width="77" alt="Zrzut ekranu 2021-12-8 o 20 40 33" src="https://user-images.githubusercontent.com/15186961/145274393-bbb4e6e2-95c3-48fa-b8f7-865d5381ad24.png">

The wheel falls on the ground (flat line below) due to gravity, below are lines of code which are used to create both bodies:

```js
let wheel = Matter.Bodies.circle(400, 200, 50);
let floor = Matter.Bodies.rectangle(1680 / 2, 670 - 1, 1680, 1, { isStatic: true, name: "floor" });
```

Could anyone tell me what am I doing wrong?

EDIT:
An idea came to my head while I was writing this description, and the solution turned out to be increasing height of the floor body (before it had 1 height as you can see above). For anyone having the same problem in future, try this solution :) 

But still, is there any way to prevent such behaviour when we deal with very thin objects?

**Comment by liabru** [comment]
Unfortunately very thin objects like this will cause problems so you should increase the thickness until it becomes stable (see #5). If you'd like them to appear thinner though, then try doing that during rendering instead.

**Comment by PiotrSzlagura** [comment]
Yeah, it seems to be this case exactly :) when I was starting this thread I didn't even realise that I'm in a wireframe mode, in regular rendering mode it seems that I can do whatever I want :)
