### ISSUE TITLE
Rubber band ejection a ball

### ISSUE THREAD

**Issue by herono2010** [liabru/matter-js#1070]
There is a rubber band that is fixed at both ends, and the ball is placed on it and pulled it down with the mouse. Release the mouse and it will pop up. After reading all the example code, i don't know how to add this body to the world. Can someone help me，looking forward to your reply. At the same time,  look forward to the official can provide such an example.

**Comment by liabru** [comment]
Are you talking about the [bridge](https://brm.io/matter-js/demo/#bridge) example? You can check out the [code here](https://github.com/liabru/matter-js/blob/master/examples/bridge.js).

**Comment by herono2010** [comment]
> Are you talking about the [bridge](https://brm.io/matter-js/demo/#bridge) example? You can check out the [code here](https://github.com/liabru/matter-js/blob/master/examples/bridge.js).

First of all, thank you very much for your reply. I can cross the bridge by dragging the small square with the mouse. How about not crossing and setting the elasticity of the bridge.

**Comment by liabru** [comment]
You can set the stiffness of the chain constraints like seen [here](https://github.com/liabru/matter-js/blob/master/examples/bridge.js#L53) then you'll probably want to increase iterations or substep to avoid passing through as shown here https://github.com/liabru/matter-js/issues/5#issuecomment-1050738814
