### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by griffi-gh** [liabru/matter-js#1083]
```
Uncaught TypeError: root is undefined
    webpackUniversalModuleDefinition http://localhost:8080/game/lib/matter.js:36
    <anonymous>
```

**Comment by griffi-gh** [comment]
i use `import './lib/matter.js';`

**Comment by liabru** [comment]
I'm not sure what `root` is so this might be an issue with your setup?

**Comment by griffi-gh** [comment]
@liabru It's a variable produced by Webpack. (version from esm.run works just fine btw)
