### ISSUE TITLE
Make hinge joint stickman stand

### ISSUE THREAD

**Issue by EditedCocktail** [liabru/matter-js#1085]
I made stickman ragdoll, but how to make it stand?
My opinion is to use this code, but hinge joints doesnt have this function:
Is anyone know, how to port this unity function to javascript:
```js
Bone.MoveRotation(Mathf.LerpAngle(bone.rotation, force * time.deltaTime))
```
![Screenshot_20220214-193114](https://user-images.githubusercontent.com/72161012/153883249-9530841d-2ca3-49ff-9b55-3721d158fdcf.png)

**Comment by liabru** [comment]
Closing as the scope and complexity of this is much too broad - rigging and control like this is something you'd need a game engine for rather than just the physics engine.
