### ISSUE TITLE
Weird movement with Body.applyForce()

### ISSUE THREAD

**Issue by 8BitSoda** [liabru/matter-js#1097]
So, I'm working on a platformer game but I'm stuck trying to correct the player's movement using `Body.applyForce()` due to multiple problems:

1. If the player is colliding on top of a body, it moves really slowly. However, once it jumps off, it quickly accelerates:

https://user-images.githubusercontent.com/97743889/158050437-8216d994-b63f-469c-9b69-1db122105598.mp4

2. Sometimes, if the player collides with a wall while falling, it just slides along it until it collides with another body below it:

https://user-images.githubusercontent.com/97743889/158050505-b41f2849-89b6-4d07-8dea-ad636502be88.mp4

And if I use `setVelocity()`, I'd end up with less smooth movement as the player just suddenly changes directions and velocity.

Here is my code:

Creating the player body
```js
const playerHead = Bodies.rectangle(
    275 + (head.xOffset + head.width / 2) * scale,
    175 + (head.yOffset + head.height / 2) * scale,
    head.width * scale,
    head.height * scale,
);

const playerTorso = Bodies.rectangle(
    275 + (torso.xOffset + torso.width / 2) * scale,
    175 + (torso.yOffset + torso.height / 2) * scale,
    torso.width * scale,
    torso.height * scale,
);

const playerBody = Body.create({
    parts: [playerHead, playerTorso],
    inertia: Infinity,
});
```

Moving the player body
```js
// Each player body is assigned their own player class
// this.isFacing is changed whenever keys `a` or `d` is pressed

if (this.isFacing === 'left')
{
    Body.applyForce(this.body, this.body.position, {
        x: -0.001,
        y: 0
    });
}

if (this.isFacing === 'right')
{
    Body.applyForce(this.body, this.body.position, {
        x: 0.001,
        y: 0
    });
}

// this.isJumping is set to `true` when space key is pressed
if (this.isJumping)
{
    this.isMidAir = true;
    Body.setVelocity(this.body, {
        x: this.body.velocity.x,
        y: -8,
    });
}
```

**Comment by liabru** [comment]
Check out the [manipulation](https://brm.io/matter-js/demo/#manipulation) example which shows how to precisely control movement of a body, especially needed for platform type games you'll want to use velocity / position based control (which act instantly and precisely) rather than forces (which act relatively slowly). 

As @CuzICanM8 mentioned you might also want to disable the built in friction and implement your own specially for the player body, or enable / disable it based on what the player is doing.
