### ISSUE TITLE
Body gaining velocity after its constrained part changes angle rapidly

### ISSUE THREAD

**Issue by PiotrSzlagura** [liabru/matter-js#1098]
Hi, I have a problem where I have a box with a "hand" attached to it, and when I move this hand rapidly (change its angle) then the box moves as well. It's hard to explain so I'm posting a video showing a problem:

https://user-images.githubusercontent.com/15186961/158852042-4e1bcbb8-6960-436a-a1b8-532fd93fd6d4.mov

Light-green box (which I call torso) is created using following code:
```js
this.torso = Matter.Bodies.rectangle(400, 200, 70, 120, {
  restitution: this.defaultRestitution, // 0.3
  friction: 0.3,
  render: {
    fillStyle: this.getBodyColor(), // probably irrelevant
  },
});
```

The hand is created using:
```js
this.rightHand = Matter.Bodies.rectangle(440, 200, 100, 20, {
  render: {
    fillStyle: "green",
  },
  isSensor: true,
  mass: 0,
  friction: 0,
  frictionStatic: 0,
  frictionAir: 0,
});
```

The constraint is as follows:
```js
this.rightHandJoint = Matter.Constraint.create({
  bodyA: this.torso,
  bodyB: this.rightHand,
  pointA: Matter.Vector.create(20, -40),
  pointB: Matter.Vector.create(-40, 0),
  length: 0,
  stiffness: 1,
  damping: 1,
  mass: 0,
});
```

I then set `inertia` of both the hand and the torso to `Infinity`.

What can I do to prevent this behavior? My goal is for hand to be placed relative to mouse position so I can't really make its movement slower.

Btw - there is also a `sword` attached to a hand (the thin gray rectangle) but it doesn't really affect this behavior so I left it visible for this "presentation"

**Comment by liabru** [comment]
A little tricky to tell with out a live example but maybe the arm is creating a very large force on the torso when it rotates, so it maybe the arm needs a low inertia / mass value and the torso needs a high mass value?
