### ISSUE TITLE
Background color and sprite

### ISSUE THREAD

**Issue by matthijn** [liabru/matter-js#1101]
I'm trying to create a number of bodies with sprites, and was wondering if I could set both a sprite (with transparency) and a background color. It seems I can only do one or the other at this moment.

**Comment by liabru** [comment]
Only one or the other is supported as the built in renderer is mostly for debugging, but you can always directly copy the [Matter.Render code](https://github.com/liabru/matter-js/blob/master/src/render/Render.js) and customise as you need!
