### ISSUE TITLE
How to remove object on click

### ISSUE THREAD

**Issue by elixirbuild** [liabru/matter-js#1107]
Is there a way I can remove an object when clicking it?

**Comment by ggorlen** [comment]
More information about your use case would be helpful. Are you using the built-in renderer or running headlessly?

Detection of the body (or bodies) being clicked can be done with [`Matter.Query.Point`](https://brm.io/matter-js/docs/classes/Query.html#method_point), using the mouse x/y position as arguments, or [mouseconstraint.body](https://brm.io/matter-js/docs/classes/MouseConstraint.html#property_body).

Here's an example of `mouseconstraint.body` with the internal renderer:

```html
<!DOCTYPE html>
<html>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/matter-js/0.18.0/matter.js"></script>
<script>
const engine = Matter.Engine.create();
const render = Matter.Render.create({
  element: document.body,
  engine: engine,
});
const bodies = [
  Matter.Bodies.rectangle(
    400, 310, 810, 60, {isStatic: true, angle: 0.0}
  ),
  ...[...Array(100)].map(() =>
    Matter.Bodies.rectangle(
      Math.random() * 400,     // x
      Math.random() * 100,     // y
      Math.random() * 50 + 10, // w
      Math.random() * 50 + 10, // h
      {angle: Math.random() * (Math.PI * 2)},
    )
  ),
];
const mouseConstraint = Matter.MouseConstraint.create(
  engine, {element: document.body}
);
Matter.Events.on(mouseConstraint, "mousedown", () => {
  if (mouseConstraint.body) {
    Matter.Composite.remove(engine.world, mouseConstraint.body);
  }
});
Matter.Composite.add(engine.world, [...bodies, mouseConstraint]);
Matter.Runner.run(engine);
Matter.Render.run(render);
</script>
</body>
</html>
```

**Comment by elixirbuild** [comment]
I already tried using that, but for some reason, `mouseConstraint.body` doesn't remove Composite bodies.

**Comment by elixirbuild** [comment]
And yes, I'm using the built-in renderer.

**Comment by ggorlen** [comment]
Can you share a minimal example of the composite body you want to remove on click?

**Comment by elixirbuild** [comment]
`deep=true` seems to work. Thanks for the help!
