### ISSUE TITLE
matterjs  Bodies.fromVertices Concave deformation is not supported

### ISSUE THREAD

**Issue by a6965921** [liabru/matter-js#1109]
matterjs  Bodies.fromVertices Concave deformation is not supported

` [
        { "x": 23, "y": 25 }, { "x": 53, "y": 39 }, { "x": 88, "y": 23 }, { "x": 53, "y": 94 },
    ]`

**Comment by liabru** [comment]
You need to set up [poly-decomp](https://github.com/schteppe/poly-decomp.js) to decompose concave vertices see the docs for [Bodies.fromVertices](https://brm.io/matter-js/docs/classes/Bodies.html#method_fromVertices).
