### ISSUE TITLE
Remove pairs if bodies removed from world

### ISSUE THREAD

**Issue by liabru** [liabru/matter-js#111]
If `world.isModified` then remove collision pairs that contain bodies which are no longer in `world.bodies`.

**Comment by marekventur** [comment]
Is there a way I can help with this one? I think I stumbled across this issue just now, using ```World.remove(word, box)``` makes other boxes stacked on top just float in the air.

**Comment by liabru** [comment]
I've investigated this more and it seems that `Pairs.removeOld` already covers this, along with the use of `broadphase.controller.clear` when `world.isModified`.
