### ISSUE TITLE
why example fps is 60 in mobile   

### ISSUE THREAD

**Issue by a6965921** [liabru/matter-js#1110]
why example fps is 60 in mobile   but I write it  is slowly fps is 30 in mobile
`
    // create engine
    var engine = Engine.create(),
      world = engine.world;

    // create renderer
    var render = Render.create({
      element: $('.p2')[0],
      engine: engine,
      options: {
        width: 800,
        height: 600,
        showAngleIndicator: true
      }
    });

    Render.run(render);

    // create runner
    var runner = Runner.create();
    Runner.run(runner, engine);

    // add bodies
    var stack = Composites.stack(20, 20, 20, 5, 0, 0, function (x, y) {
      return Bodies.circle(x, y, Common.random(10, 20), { friction: 0.00001, restitution: 0.5, density: 0.001 });
    });

    World.add(world, stack);

    World.add(world, [
      Bodies.rectangle(200, 150, 700, 20, { isStatic: true, angle: Math.PI * 0.06 }),
      Bodies.rectangle(500, 350, 700, 20, { isStatic: true, angle: -Math.PI * 0.06 }),
      Bodies.rectangle(340, 580, 700, 20, { isStatic: true, angle: Math.PI * 0.04 })
    ]);

    // add mouse control
    var mouse = Mouse.create(render.canvas),
      mouseConstraint = MouseConstraint.create(engine, {
        mouse: mouse,
        constraint: {
          stiffness: 0.2,
          render: {
            visible: false
          }
        }
      });

    World.add(world, mouseConstraint);`
    
    https://brm.io/matter-js/demo/#avalanche

**Comment by liabru** [comment]
I'm not sure what you mean here, can you explain and give details?

**Comment by a6965921** [comment]
Polygon fps is very slow
`for (let i = 0; i <= 100; i++) {
    setTimeout(() => {
        var boxA = Bodies.fromVertices(500, 70, [
            { "x": 175, "y": 16.5 }, { "x": 141, "y": 11 }, { "x": 130, "y": 11.5 }, { "x": 175.5, "y": 91 }, { "x": 177.5, "y": 74 },
            { "x": 32, "y": 0.5 }, { "x": 15.5, "y": 39 }, { "x": 13.5, "y": 50 }, { "x": 9.5, "y": 101 }, { "x": 173.5, "y": 97 }, { "x": 175.5, "y": 91 }, { "x": 93, "y": 7.5 }, { "x": 86, "y": 5.5 },
            { "x": 0, "y": 211.5 }, { "x": 11, "y": 221.5 }, { "x": 27, "y": 228.5 }, { "x": 1.5, "y": 202 },
            { "x": 145, "y": 234.5 }, { "x": 159.5, "y": 214 }, { "x": 163.5, "y": 194 }, { "x": 167.5, "y": 148 }, { "x": 5.5, "y": 139 }, { "x": 0.5, "y": 176 }, { "x": 69, "y": 238.5 }, { "x": 107, "y": 240.5 },
            { "x": 1.5, "y": 202 }, { "x": 27, "y": 228.5 }, { "x": 69, "y": 238.5 }, { "x": 0.5, "y": 176 },
            { "x": 167.5, "y": 148 }, { "x": 173.5, "y": 107 }, { "x": 173.5, "y": 97 }, { "x": 9.5, "y": 101 }, { "x": 7.5, "y": 109 }, { "x": 5.5, "y": 139 },
            { "x": 123, "y": 9.5 }, { "x": 112, "y": 9.5 }, { "x": 175.5, "y": 91 }, { "x": 130, "y": 11.5 },
            { "x": 105, "y": 7.5 }, { "x": 93, "y": 7.5 }, { "x": 175.5, "y": 91 }, { "x": 112, "y": 9.5 }
        ], { friction: 0.00001, restitution: 0.5, density: 0.001 });
        Body.scale(boxA, 0.2, 0.2);
        World.add(world, boxA);
    }, 200);

}

World.add(world, [
    Bodies.rectangle(200, 150, 700, 20, { isStatic: true, angle: Math.PI * 0.06 }),
    Bodies.rectangle(500, 350, 700, 20, { isStatic: true, angle: -Math.PI * 0.06 }),
    Bodies.rectangle(340, 580, 700, 20, { isStatic: true, angle: Math.PI * 0.04 })
]);

`
