### ISSUE TITLE
two bodies repel each other

### ISSUE THREAD

**Issue by thaibao071196** [liabru/matter-js#1111]
can anyone tell me how to make two bodies repel each other like a magnet,thanks

**Comment by Baraa-Baba** [comment]
try this 
https://github.com/liabru/matter-js/blob/master/examples/timescale.js#L37-L58

**Comment by liabru** [comment]
Use `Body.applyForce` based on the distance between them, you could also try out the [matter-attractors](https://github.com/liabru/matter-attractors) plugin but instead flip the force direction.
