### ISSUE TITLE
Random velocity of object 

### ISSUE THREAD

**Issue by hoanghai9650** [liabru/matter-js#1113]
Hi,
Is there any way that I can  set random velocity after period time ?
I tried setInterval but it's seem fail.
Thank you

**Comment by Baraa-Baba** [comment]
I think you should `Matter.Engine.update(engine)` so the changes appear

**Comment by liabru** [comment]
You should use engine events rather than `setInterval` so things stay in sync, you can see that here as well as setting velocity in the [manipulation example](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L65-L105).
