### ISSUE TITLE
How to improve performance when FPS is lower than 30

### ISSUE THREAD

**Issue by a6965921** [liabru/matter-js#1115]
How to improve performance when FPS is lower than 30

**Comment by Baraa-Baba** [comment]
you can use the matter sleep  ` engine.enableSleeping =true 
Matter.Sleeping` this will improve stability and performance, but often at the expense of accuracy.

**Comment by liabru** [comment]
@a6965921 since you didn't give any info, generally lower the amount of bodies and avoid collisions as much as possible.
