### ISSUE TITLE
Chain bouncing

### ISSUE THREAD

**Issue by rahul925kumar** [liabru/matter-js#1116]
Hi,

I am having a chain in my application. In that chain, there are multiple bodies connected and I have created two constraints to hang up the chain from both sides. The issue is when an application gets reloading chain bouncing continuously and when I stretched the chain it get stretched from both constraints ends. So, I want to control the bouncing of the chain and stretching. This makes the chain bounce continuously. Is there any way to stop that bouncing?? Thanks in advance.
You can check the issue here ... https://www.loom.com/share/a294fc3ddce9462695b8bb887f26de18
![image](https://user-images.githubusercontent.com/38293842/164370676-774b95e8-00a7-4eaa-84f5-aa18650b9f0b.png)

**Comment by liabru** [comment]
Could it be to do with low gravity? Try increasing it, you could also increase air friction (at least for a short time after interaction).
