### ISSUE TITLE
Multiple parts shape won't update strokeStyle value

### ISSUE THREAD

**Issue by ilmandone** [liabru/matter-js#1118]
On a concave shape generate with the Bodie.fromVertices a render strokeStyle update will affect only the first part item.
I guess that this issue is related to all the others render values.

My code as reference:

```
const basicOptions = {
  restitution: 0.8,
  isStatic: true,
  render: {
    fillStyle: 'transparent',
    lineWidth: 2,
    strokeStyle: '#9a9a9a',
  }
}

const vertices = VERTICES.fromPath('104 0 146 0 146 104 250 104 250 146 146 146 146 250 104 250 104 146 0 146 0 104 104 104')

_statics.about.shape = BODIES.fromVertices(500, 200, vertices, {
    ...basicOptions,
    collisionFilter: {category: CATEGORY_SPINNER},
    isStatic: false,
})

```
Other shapes are register in _statics and are all simple primitives.

... later on an user interaction ( I leave the two logic splitted to be more clear )

```
Object.values(_statics).forEach(sb => {

  const strokeColor = theme === 'light' ? COLOR_MAP.static_light : COLOR_MAP.static_dark // Get a different color
  
  if(sb.shape.parts.length > 1 ) {
    sb.shape.parts.forEach(part => {
      part.render.strokeStyle = strokeColor
    })
  } else {
    sb.shape.render.strokeStyle = strokeColor  <-- this doesn't work for _statics.about.shape
  }

})
```

And BTW ... thanks a lot for the library 😄

**Comment by liabru** [comment]
The built in renderer only supports render properties from the parent body to keep things simple, so I'd say go with your own renderer or fork the built in one to add this (or alternatively use a renderer event and draw on top).
