### ISSUE TITLE
b669ea0 breaks old code

### ISSUE THREAD

**Issue by upisfree** [liabru/matter-js#112]
b669ea0da1e3db314aad13c47f2dbe812a0f21a9 breaks old code, I need to use constructions like `render.element: document.body` when I create engine.
Is it bug or not?

**Comment by liabru** [comment]
This was indeed a bug, should be fixed in c46e915 and master build, can you confirm?

**Comment by upisfree** [comment]
Yep, I confirm.

**Comment by upisfree** [comment]
Maybe should create new branch for node version?

https://github.com/upisfree/matter-server-js
Check it, I remove everything associated with rendering (like render object in Body), demo also there.

**Comment by liabru** [comment]
Thanks for the confirm. Actually I'm already working on decoupling the renderers and the runner in the main branch, but hopefully at least for now you shouldn't be getting errors from them in node.
