### ISSUE TITLE
Disable fisical collision and detect intersection

### ISSUE THREAD

**Issue by markvaaz** [liabru/matter-js#1126]
I know that I can disable fisical collision by filtering, but how do I detect if they are intersecting?

I have a body that can pass through other bodies, but I need to detect if this specific body are intersecting with any other body that it is being filtered

The documentation is not detailed enough, I've tried using `isSensor = true`, but it disables all collisions, I've tried `Matter.Bounds.overlaps(boundsA, boundsB)`, but the problem with that is, that every body have to check every single other body to teste the intersection, and that will cause performance issues.

**Comment by liabru** [comment]
It sounds like `isSensor` is what you're looking for if you don't want the collision response? See the [sensors](https://brm.io/matter-js/demo/#sensors) example.

**Comment by markvaaz** [comment]
So, imagine this, I have a main character and that can collide physically with everything except with an enemy, and the same goes for the enemy's collision.

If the character collides with an enemy he will receive damage, but using `isSensor` the character can go through everything, can I filter it to go through another body as described and still call the collision event? I did it by modifying the `Resolver.solvePosition` and it works just fine, but just because I couldn't find a solution or details anywhere

**Comment by liabru** [comment]
I think what you can do for that is to have a separate but duplicate sensor body, that you then set the position and angle to always match the controlled body, in an update event?
