### ISSUE TITLE
No pairs in collision events

### ISSUE THREAD

**Issue by emaillenin** [liabru/matter-js#113]
I am trying to find the pair that are involved in a collision but event.pairs is empty in all 3 collision events.

Test repo - https://github.com/emaillenin/learn-matterjs

**Comment by liabru** [comment]
I tried out your test repo but I can't reproduce the problem. I used the following code:

    Events.on(engine, 'collisionStart collisionActive collisionEnd', function (event) {
        console.log(event.pairs);
    });

And each time I got back an array with at least one pairs object in. 
Can you provide more information?
