### ISSUE TITLE
Breakable constraint

### ISSUE THREAD

**Issue by Qrokqt** [liabru/matter-js#1133]
I want to make a constraint that breaks if the force/torque exceeds a threshold. Is there a way to get the force being applied to a constraint so that I could then delete the constraint?

**Comment by liabru** [comment]
What I'd suggest here is instead to try to roughly [estimate stress / strain](https://www.linearmotiontips.com/mechanical-properties-of-materials-stress-and-strain/) on the constraint, by comparing its current length to its rest length and average that over a few frames, if it crosses a threshold for a long enough time then consider it broken.
