### ISSUE TITLE
Can sprite.texture be drawed adjust to the bodies shape or size? 

### ISSUE THREAD

**Issue by yhlgithbu** [liabru/matter-js#1135]

**Comment by yhlgithbu** [comment]
var stack_circle=Composites.stack(500,200,10,5,2,3,function (x,y) {
    return Bodies.circle(x,y,60,{

        render: {
            sprite: {
                xScale: 0.6,
                yScale: 0.6,
                texture: 'gj.png' // picture is square     I want to change the image to rounded corners
            }
        }

    });
});

**Comment by yhlgithbu** [comment]
var options = {render: {
        sprite: {
              texture: '/img/rect_800*600.png'
        }
}}

 Bodies.circle(100, 100, 50, options)
Can the texture be drawed in a circular shape and resized to the body's size?

**Comment by liabru** [comment]
You can use [body.render.xScale](https://brm.io/matter-js/docs/classes/Body.html#property_render.sprite.xScale) and [body.render.yScale](https://brm.io/matter-js/docs/classes/Body.html#property_render.sprite.yScale), for a circular texture you would have to do that inside the `png` directly.

**Comment by goodwin74** [comment]
I have a similar problem
`Bodies.circle(50, 50, 6, {
    collisionFilter:{
        category:2,
        mask:4
    },
    label:'mainSph',
    render: {
        sprite: {
            texture: './css/sphere/img/sph.png',
            xScale: 1,
            yScale: 1
        }
    }
});`

After launch, just a circle without texture is displayed. There are no download errors in the console, and there are no attempts to download this resource in the Network tab either.

**matter-js 0.20.0**
