### ISSUE TITLE
`Composite.get` is slow

### ISSUE THREAD

**Issue by Anatoly03** [liabru/matter-js#1143]
I'm trying to create my own renderer, and did the following, which turned out to be slow, any tips? I'm using bitECS and a canvas. To link an entity to the matter.js body I created a component `Physics` with the attribute `id` that is given the id of the `Body` of matter.js

```js
(world: IWorld) => {
   const blocks = blocksQuery(world)

   for (let i = 0; i < blocks.length; i++) {
      const eid = blocks[i]
      const body = (<Matter.Body>Composite.get(engine.world, Physics.id[eid], 'body')).position

      ctx.strokeStyle = '#FFFF00'
      ctx.strokeRect(Math.floor(body.x / 5 - 10), Math.floor(body.y / 5 - 10), 20, 20)
   }

   return world
},
```

Any ideas how to achieve a link between a library that focuses on ECS and matter.js?

**Comment by ggorlen** [comment]
Why not reference the body directly? You should have a reference to it when you create it, right? `Composite.get` will search the whole tree starting with `engine.world` for every call.

I see also you're using `.position`, but maybe better to store the actual body, which can easily access the `.position` when needed, depending on your needs.

**Comment by liabru** [comment]
Yeah exactly as @ggorlen mentioned, you should just keep hold of a direct reference rather than searching.

**Comment by Anatoly03** [comment]
I see. Well, yeah, the problem is that ECS doesn't quite like objects, that's sad.

**Comment by Anatoly03** [comment]
I have created a table that connects entity id's with the references that binds the ecs package with matter.js While not the cleanest solution, definitely a possible one.
