### ISSUE TITLE
[HELP] How to limitate Mouse?

### ISSUE THREAD

**Issue by djtech-dev** [liabru/matter-js#1144]
The mouse in Matter.js by default can move any Body that isn't static.

Is there a way to "limitate" the mouse to just a list of bodies that it can move (so not all the objects in the scene?).

Thanks for your time

**Comment by ggorlen** [comment]
Does https://github.com/liabru/matter-js/issues/48 answer this?

**Comment by djtech-dev** [comment]
> Does https://github.com/liabru/matter-js/issues/48 answer this?

Yes, thanks for the help.
