### ISSUE TITLE
Rotate/setAngle broken?

### ISSUE THREAD

**Issue by EskelCz** [liabru/matter-js#115]
Hi, first of all, thanks for this incredible library, it's an absolute treasure.

I've found a problem with the most basic thing though, rotating a body a certain degree.
Here is a simple example: http://jsfiddle.net/zakvgL0m/2/
Visually, the box isn't rotated anywhere near 90 degrees (about 30 would be my guess), even though the box.angle says it is.

Am I doing something wrong? Thanks a lot for looking into this.

**Comment by liabru** [comment]
The angle should be in radians not degrees (I'll update the docs to make this clearer).

**Comment by EskelCz** [comment]
Ah, right, I'm feel stupid for not trying. :) Anyway, the doc update would be good, it says degrees. Thanks a lot for quick answer!
