### ISSUE TITLE
Is there a way to make render.options.showVelocity visibly bigger?

### ISSUE THREAD

**Issue by Kafiling** [liabru/matter-js#1150]
Hi! I'm making a projectile motion simulation for an E-learning website using matter.js. I'm using **render.options.showVelocity**  to display object's velocity. But it's so small and hard to see. 

![Screenshot 2022-08-06 183700](https://user-images.githubusercontent.com/92731304/183247255-94cf2a8a-1075-4b1f-b607-69cb55565e81.png)

So my question is :
(1) Is there a way to make render.options.showVelocity visibly bigger?
(2) Is it possible to show Velocity in X,Y Axis separately?

Thanks in advance and sry for my English.

**Comment by liabru** [comment]
My suggestion for that would be to make a copy of [Matter.Render](https://github.com/liabru/matter-js/blob/master/src/render/Render.js) and customise [Matter.Render.bodyVelocity](https://github.com/liabru/matter-js/blob/8ca9cb4fa4902b0c12f4ee350f18ec106775823c/src/render/Render.js#L1098) (or just patch that function if it's the only change you'll need).

**Comment by Kafiling** [comment]
Thanks for the help! It works as I want now
![Screenshot 2022-08-10 091518](https://user-images.githubusercontent.com/92731304/183795530-07d3386b-9ff1-4277-aacb-fe3a99b558cc.png)

If anyone wants here the code https://github.com/Kafiling/matter-js-for-e-learning
