### ISSUE TITLE
Physics run way to fast on a really good gaming PC

### ISSUE THREAD

**Issue by lafkpages** [liabru/matter-js#1152]
I showed my cousin a game I made with Matter.js but his computer is so good the game runs like 3 to 4 times faster than it should and is impossible to play.

Is there a way to set an FPS limit?

**Comment by ggorlen** [comment]
Are you using your own runner or the built-in MJS runner? A minimal example would be useful.

**Comment by lafkpages** [comment]
Built-in runner.

This is how the runner is made.

``` javascript
// create runner
let runner = Runner.create({
  isFixed: false // I tried both true and false, same result
});

// run the engine
Runner.run(runner, engine);
```

The full script is [here](https://perfectly-balanced.luisafk.repl.co/script.js) (didn't post all because it's 2.3k lines of code)
The game is [here](https://perfectly-balanced.luisafk.repl.co)

**Comment by LexSerest** [comment]
## Fix fps / fix fast simulation
```js 
Events.on(runner, 'tick',() => {
  runner.deltaMin = runner.fps > 60 ? 1000 / runner.fps : 1000 / 60;
})
```

I spent a long time solving the problem.

@liabru please add a fix to the runner code

**Comment by MinhChanh6** [comment]
Hi everyone, I try with the code of @LexSerest above but it doesn't work?!. 

Has anyone found a way yet?

Here my example code:
![code](https://github.com/liabru/matter-js/assets/56917306/16abe6ed-2ac1-4710-955c-23e2aa9161ae)

**Comment by catinrage** [comment]
@MinhChanh6 you missed the `this` before first `runner` at line 7, maybe that will fix.

**Comment by liabru** [comment]
Closing this thread to refer to updates in #702 on this topic, thanks again for the reports here.

**Comment by liabru** [comment]
As of [0.20.0](https://github.com/liabru/matter-js/pull/1300) there is now built in `Matter.Runner` support by default for fixed timestep with high refresh displays see https://github.com/liabru/matter-js/pull/1300.
