### ISSUE TITLE
Best way to make edges of world to act like walls?

### ISSUE THREAD

**Issue by MichaelPriebe** [liabru/matter-js#1162]
I have a matter world that takes up the size of the page. As the size of the page can change, I reposition the four walls at the edges of the page. There's not a true way to set the size of a body, so I do some math to scale the four walls to the size of the page.

This seems pretty convoluted for something that probably could be calculated while updating other bodies.

I tried clamping the other bodies positions to the edges of the page, this works, except bodies seem to continue gaining velocity / inertia as they are technically free-falling. I am not familiar with physics to know what to do with the bodies velocity and inertia to mimic hitting a figurative wall.

**Comment by ggorlen** [comment]
Could you share your code? I don't really follow the problem here.

**Comment by liabru** [comment]
It sounds like the way you're doing it is what I'd suggest, but you can make it a bit easier by making the rectangles extremely large (so effectively a pseudo-plane) then you don't need to resize them, just move them offset by half their bounding box.

**Comment by MichaelPriebe** [comment]
> It sounds like the way you're doing it is what I'd suggest, but you can make it a bit easier by making the rectangles extremely large (so effectively a pseudo-plane) then you don't need to resize them, just move them offset by half their bounding box.

I don't know why I didn't think about that, its much simpler now, requires no scaling.

Setup:
```javascript
const thickness = Number.MAX_SAFE_INTEGER
const floor = Matter.Bodies.rectangle(0, 0, thickness, thickness, { isStatic: true })
const left = Matter.Bodies.rectangle(0, 0, thickness, thickness, { isStatic: true })
const right = Matter.Bodies.rectangle(0, 0, thickness, thickness, { isStatic: true })
const ceil = Matter.Bodies.rectangle(0, 0, thickness, thickness, { isStatic: true })
```
Position: (I do this before updating the engine, you could use the window resize event, but I've found it does not always update the values before calling the event.)
```javascript
const width = window.innerWidth
const height = window.innerHeight
Matter.Body.setPosition(floor, { x: width / 2, y: height + thickness / 2 })
Matter.Body.setPosition(left, { x: -thickness / 2, y: height / 2 })
Matter.Body.setPosition(right, { x: width + thickness / 2, y: height / 2 })
Matter.Body.setPosition(ceil, { x: width / 2, y: -thickness / 2 })
```

I still think there should be a setting for this effect though.

**Comment by liabru** [comment]
I think as a physics engine that feature would be a little too specific to a certain use case which I'd rather avoid, but it might make for a good example in future so will keep in mind!
