### ISSUE TITLE
How to 'move' bodies as if they're being pushed by mouse cursor?

### ISSUE THREAD

**Issue by l7ana** [liabru/matter-js#1165]
Hi,

What would be the best way to have multiple bodies move AWAY from the mouse (without dragging a body)? I've seen examples where bodies will follow/be attracted to the mouse, but not the other way around.

Sorry if this question was already answered or if the answer lives somewhere already. I'm new to javascript overall and not familiar with reading docs yet. I'm doing my best.

**Comment by forwhat461** [comment]
I don't quite understand 'move away bodies from th mouse "without drag" '
you can just simply Body.applyForce to the bodies or Body.setPostion to move these bodies to somewhere. 
maybe you want to applyForce to the reversed direction from mouse?

**Comment by l7ana** [comment]
Hi, yes I think that's what I'm trying to do. 
I want the bodies to move away from my mouse position. I'm not sure where to look to find out how to do that.

**Comment by issuefiler** [comment]
Get the mouse cursor position. Get the body position. Calculate the force vector from the cursor to the body. Apply.

**Comment by liabru** [comment]
Looks like you got it! Thanks for helping @issuefiler @forwhat461
