### ISSUE TITLE
Grid friendly position and rotation

### ISSUE THREAD

**Issue by EskelCz** [liabru/matter-js#117]
I've ran into a problem with how pivot/origin of the transformation are handled. I'm trying to position various custom collision shapes (bodies) onto a grid and rotate them in place around the center. They all have same bounding box size (100×100), but different inner shapes, for rounded corners etc.

I understand that for the purposes of physics interaction it is natural to move around the center of mass (centroid), but for exact placement of various shapes on a grid, I need to devise a way to use center of the whole bounding box for these operations.

Here is a simple demo to illustrate this with two triangles: http://jsfiddle.net/Eskel/hxdzo0ud/6/

For my use case (and I hope I'm not alone in this), the bounding boxes of those triangles should still occupy the exact same space even while rotated 90/180/270 degrees. It also hinders exact positioning, since the shape itself displaces the origin of the position attribute.

Any idea how could I solve this? Advice on what to modify, or any temporary work-around would be most appreciated.

**Comment by EskelCz** [comment]
here is an example of the positioning issue http://jsfiddle.net/Eskel/cce3pxo6/1/

**Comment by EskelCz** [comment]
I've added a method Vertices.boundsCentre that solves it by finding the boundry box center for the Body.setVertices method. It seems to work fine for my needs. Should I make a pull request?

It's not pretty, but it's working well. Maybe someone can help me refine it.
```
    /**
     * Returns the centre of the set of vertices based on bounds.
     * @method boundsCentre
     * @param {vertices} vertices
     * @return {vector} The centre point
     */
    Vertices.boundsCentre = function(vertices) {
        var average = { x: 0, y: 0 };
        var minX = 0;
        var minY = 0;
        var maxX = 0;
        var maxY = 0;

        for (var i = 0; i < vertices.length; i++) {
            if (vertices[i].x < minX) {
                minX = vertices[i].x;
            }
            if (vertices[i].x > maxX) {
                maxX = vertices[i].x;
            }
            if (vertices[i].y < minY) {
                minY = vertices[i].y;
            }
            if (vertices[i].y > maxY) {
                maxY = vertices[i].y;
            }

            average.x = (maxX + minX) / 2;
            average.y = (maxY + minY) / 2;
        }
        return average;
    };
```

**Comment by EskelCz** [comment]
Just found out it doesn't work for concave shapes that are made of many smaller shapes.

**Comment by EskelCz** [comment]
After some hours of delving into the library, I managed to make it work with parts and simlified the function to this:
```
    Vertices.boundsCentre = function(vertices) {
        bounds = Bounds.create(vertices);
        var centre = Vector.add(bounds.min, bounds.max);
        centre = Vector.div(centre, 2);
        return centre;
    };
```
it has to be used in Body.setVertices, Bodies.fromVertices instead of Vertices.centre.

I'm gonna polish it some more and open a pull request.

**Comment by acasaccia** [comment]
I had the same problem. I think exact positioning of objects should be a very basic feature if you are building a game or a simulation of some kind. I used this approach https://github.com/acasaccia/matter-js/commit/6ff103103ddc0b4a7bda0499c783512971418598

**Comment by vncnz** [comment]
Hi @acasaccia , I'm facing the same problem and I can't see the commit you've mentioned. How did you solve it?
The function proposed by EskelCz doesn't seem useful with concave objects and as far as i can see they are positioned using a point that is not the mean nor the center.

Thanks in advance!
