### ISSUE TITLE
Torque vs Angular Velocity

### ISSUE THREAD

**Issue by siyasiyasiya** [liabru/matter-js#1171]
So I was confused on what the difference between `body.torque `and `Body.setAngularVelocity()` is. In my code, I am implementing a turning motion for a gear that stays in one place but is turning. So what would be the difference between angular velocity and torque for me?

**Comment by liabru** [comment]
Torque is rotational force which applied over time (rotational acceleration) results in angular velocity on the body (its rotational speed / direction).

So the relation here is similar to `body.force` effect on `body.velocity`, but relating to rotation instead.

When you apply torque you should usually do so over multiple updates as it takes time to accelerate.
