### ISSUE TITLE
Releases feature

### ISSUE THREAD

**Issue by msawired** [liabru/matter-js#1172]
Hello from OpenProcessing!

We are happy to feature this library on our default libraries list! However, to automatically keep up with the new versions, we require the libraries to use the Github Releases feature so that we can pull any new version information. Do you think you can enable it?

**Comment by liabru** [comment]
I'd recommend to use the releases published [at npm](https://www.npmjs.com/package/matter-js?activeTab=versions) for this, but they are also tracked via [github tags](https://api.github.com/repos/liabru/matter-js/tags). I don't plan to use Github Releases though, as I'd prefer to stick to a single source.
