### ISSUE TITLE
Feature Request: Fire a mid-update event, after all body positions set, but but just before collision detection begins.

### ISSUE THREAD

**Issue by OdinvonDoom** [liabru/matter-js#1173]
I'm just really looking for the chance to have the engine do it's basic velocity-position updating (Engine.js: Engine._bodiesUpdate), but then get to run a bit of my own code before any of the collision detection begins. Then I could make whatever minor tweaks I feel I need, like if a body slightly overshot a target destination in that frame, I could repositions them to be precise, and then there would be no chance of an incorrect detection being made.

Example: player clicks to move 25px away, and velocity has then going 10px per frame. Each frame I'd check if target pos is between prev and curr pos (20 and 30), and if so, hard-set to desired pos, and negate velocity, THEN collisions are checked, no chance of hitting some thing that was originally 28px along the path.

**Comment by liabru** [comment]
I've logged this as a feature request, but in the meantime you could try something like:

```js
Matter.after('Engine._bodiesUpdate', () => {
 // do something here
})
```

It's not ideal but might do the trick for some cases.
