### ISSUE TITLE
body objects not following physics rule with resized canvas

### ISSUE THREAD

**Issue by vtheviking** [liabru/matter-js#118]
Hello, thanks for creating Matter.js btw. I've been working on an issue that seems to be persistent and hard to identify. I currently resized the matter.js canvas element using the rendering options. So I went from 800 => 1350 and 600 => 665. The screen resizes, but what i am noticing is that my objects/sprites are freezing when getting past the original 800 width mark. So all of my physics such as gravity and friction are turning off or non responsive. Im not sure where i am going wrong here and if you could point me in the right direction i would be greatly happy.

**Comment by liabru** [comment]
See #67 this should be solved if you use the latest master build.

**Comment by vtheviking** [comment]
my codepen btw http://codepen.io/Vili_illy/pen/Xbqgrp

**Comment by vtheviking** [comment]
okay, i will give it a look, I saw that they had a solution.
engine.world.bounds.max.x = 1600;
engine.world.bounds.max.y = 600;

is this solution still valid, or is it better to go with the master build.
thanks

**Comment by vtheviking** [comment]
thanks for the help, 67 helped out a ton, thanks!
