### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by strarsis** [liabru/matter-js#1181]
So this library can render on its own and it can use webGL?

Can I also use it to simulate the model and then update the vertices of e.g. ThreeJS vertices?

**Comment by liabru** [comment]
Sure you can render how ever you need, see the [rendering](https://github.com/liabru/matter-js/wiki/Rendering) wiki page for a minimal rendering example (the built in `Matter.Render` is 2D canvas but is entirely optional).

**Comment by strarsis** [comment]
Yes, after some diving into the matter (pun intended) I noticed that one uses the simulation models to update rendering models (which can be rendered by anything, including webgl).
