### ISSUE TITLE
Complex SVGs

### ISSUE THREAD

**Issue by Eugene-Mokrushin** [liabru/matter-js#1183]
Do I understand correctly that it's unreal to create bodies with such svgs: https://www.svgrepo.com/svg/96084/armchair?
![image](https://user-images.githubusercontent.com/82924768/204067938-6d542d76-b63f-4a73-8c84-9ab99b8efb6f.png)

Does SVGs have to be just one simple loop? 

If that so, do you have any recomendations on how to reacreate bodies like these?

Thanks ahead!

**Comment by liabru** [comment]
You'll need to break it up somehow into convex pieces (decomposition / triangulation) and set them as [body parts](https://brm.io/matter-js/docs/classes/Body.html#method_setParts). 

If you're looking to use the utility [Matter.Svg](https://brm.io/matter-js/docs/classes/Svg.html) make sure all the paths are simple polygons (no holes or self intersections) and ensure paths don't overlap each other.

**Comment by Eugene-Mokrushin** [comment]
Than you! Got it.
