### ISSUE TITLE
Any event that atribute to constraint length? 

### ISSUE THREAD

**Issue by Eugene-Mokrushin** [liabru/matter-js#1184]
Hello!

I couldn't find any info on the internet, except your old reply that implies that this is possible:
![image](https://user-images.githubusercontent.com/82924768/204171042-bc393d2d-c498-4242-b590-82ecc4af5534.png)

How may I check the length of the constraint to then "cut" it?  I have a bunch of bodies with two constraints attached to each. I want to check every tick if constraint is more than the N limit of length and then 'cut' it.

Here's what I've already done:
```
Matter.Events.on(engine, "afterUpdate", () => {
                
                Matter.Composite.allConstraints(world).forEach(constraint => {
                    // constraint.length += 1
                    console.log(constraint)
                    // if (constraint.length > 50) {
                    //     Matter.Composite.remove(world, constraint)
                    // }
                })
            })
```

Any ideas or maybe **events** that will get me straight to the point? 

Thanks ahead!

**Comment by issuefiler** [comment]
By calculating the _Euclidean distance_ between the two glued points?

**Comment by liabru** [comment]
The property `constraint.length` is the rest length, what you also need is the current length:

`const currentLength = Vector.magnitude(Vector.sub(Constraint.pointAWorld(constraint), Constraint.pointBWorld(constraint)));` (thinking I might add a function for that!)

Then you can check `currentLength / constraint.length > threshold` and decide if to remove the constraint.
