### ISSUE TITLE
How to complete ignore collision between objects without even checking for collision?

### ISSUE THREAD

**Issue by guilhermesilveira** [liabru/matter-js#1187]
I have many thousand particles type A that can't collide with each other. I have applied the same negative group for them, so they don't collide. So far so good:

```
        this.body.collisionFilter.group = -5;
```

Since there are thousands of particles, there is still an O(N^2) check of collisions between them, as matter checks for the same collisionFilter group in O(N^2) I imagine, and that takes some time.

How can I completely skip collision between those particles?

Note that I have another type of body, let's call it type B, and bodies from type A still have to collide with type B.
Is there a way to group all those particles A in a composite that does not check amongst themselves, but check against other top-level composites?
Does it make sense?
So how can I completely skip collision between those particles avoiding the O(N^2) comparisons and still colliding with other type of bodies?

**Comment by ggorlen** [comment]
Are you sure collision is O(nn)? Without looking into it, my understanding was that it waits until two bodies overlap before looking at their respective filter properties to determine whether the collision resolution should be triggered. O(1).

**Comment by guilhermesilveira** [comment]
I solved the problem by patching the code.


The current algorithm sorts in x before performing the comparisons and then
filtering. But yes, still looks quadratic in the worst case, which is my
case.

If I have some hundred thousand particles that loop becomes impossible to
run. I must first filter which bodies are collidable, loop them.

So if we have n collidable and m non collidable it becomes O(nm). In my
scenario n is 10^2 and m 10^4 and the algorithm runs fine.

What I mean by non collidable is a body which can not collide with non
collidable bodies.

So a collidable body collides with any body. Non collidable bodies collide
only with collidable bodies.

It seems like my problem is not a typical optimizarion problem as my non
collidable particles do not seem to be common bodies in simulations.

If anyone is interested in the solution I can post it here.

**Comment by liabru** [comment]
Indeed you'd need to add something yourself for that. This project is designed specifically around polygon rigid bodies rather than optimised for large amounts of particles, though the idea is on my list somewhere it's not currently a focus for now.
