### ISSUE TITLE
Some bugs in the Demo of the latest DOWNLOAD SCRIPT.

### ISSUE THREAD

**Issue by vrbvillor** [liabru/matter-js#119]
When the demo select changs to "Chains" or "Bridge" or "Cloth", the console.log shows error "Body.nextGroup" is not a function on Demo.js 677(chains) or line 714(bridge) or line 1203(cloth)...
The "Time scale" demo is not the same as the one on your website. The shapes disappear....
The "Ray casting" demo shows error Bodies.fromVertices is not a function on line 1480

More , please release the instructions of the options of shapes. Such as champfer:{radius:r}, it's not in the API, but can be found in demo.js...

And the function name in demo.js is not the same as the select options in the page...

But , matter.js is so awesome, especially the "cloth" and "softbodies"

**Comment by vrbvillor** [comment]
BTW,  I'm Chinese. And I got to know Matter.js from the demos of Stage.js..  I keep in touch with Ali via emails.  And the Chinese translation I wrote has been post onto Wiki of Stage.js.  I've done the same work on Matter.js API.  I'm not very good at English, poor in physics too,  but I'll do my best to write accurate translations.  I hope I can get teamwork with you as I with Ali.  I want to help Chinese programmers to study Matter.js more convenient.  If you agree ,  please concact with me. I'm Villerio, email vrbvillor@126.com..   Wish to cooperate   ^3^

**Comment by liabru** [comment]
Can you try cloning the repo and then following the [building and contributing](https://github.com/liabru/matter-js#building-and-contributing) instructions to run the demo?

> More , please release the instructions of the options of shapes. Such as champfer:{radius:r}, it's not in the API, but can be found in demo.js...

Options support any of the properties of bodies. You can find docs on most of these properties here in the [body properties docs](http://brm.io/matter-js-docs-master/classes/Body.html#properties). Though chamfer is different, it's an option that is specific to the `Matter.Bodies` factory methods, you're right it still needs to be documented, but the demo hopefully is enough to show you how to use it.

**Comment by vrbvillor** [comment]
Sorry, I'm new to Github.  I get the script by download the ZIP.  Is the file newest?  Or would you please tell me how to get the newest zip file? Thanks.

**Comment by liabru** [comment]
The best way is to clone this repository using git, but if you'd just like a zip file then you can click the 'download zip' button on the bottom right of the [matter-js github page](https://github.com/liabru/matter-js) or just use this direct link to [download zip](https://github.com/liabru/matter-js/archive/master.zip).
