### ISSUE TITLE
Real circle implementation

### ISSUE THREAD

**Issue by reececomo** [liabru/matter-js#1191]
/Just curious if there is an implementation of real circles available in another branch - it's been referenced a few times [#511](https://github.com/liabru/matter-js/issues/511#issuecomment-344117335) [#934](https://github.com/liabru/matter-js/issues/934) [#1190](https://github.com/liabru/matter-js/issues/1190#issuecomment-1383265156)

A plain ball bouncing on a flat surface is shooting off in all sorts of weird directions --> bouncing is wildly inconsistent, and no value of `maxSides`.

**Comment by liabru** [comment]
Closing as a duplicate of #301.

I'll keep this in mind but please use that thread and see the suggestions there, thanks.

**Comment by reececomo** [comment]
Thanks for the response @liabru - we did see #301 at the time (and tried your suggestions, but with no luck).

**Comment by reececomo** [comment]
For future readers - our game simulation leans heavily on ball physics, so we ended up using a different engine.

**Comment by KaliaJS** [comment]
@reececomo What engine are you using instead?
