### ISSUE TITLE
How to make my own drawer of colliders using pure WebGL

### ISSUE THREAD

**Issue by 8Observer8** [liabru/matter-js#1197]
Hello. I know that Matter.js has its own drawer of colliders. Is it possible to get coordinates of colliders?

**Comment by liabru** [comment]
You can get collisions from pairs via engine collision events or iterating over `engine.pairs.list`. You can see how they are rendered here in [Matter.Render.collisions](https://github.com/liabru/matter-js/blob/master/src/render/Render.js#L11560) and see docs for [collision objects](https://brm.io/matter-js/docs/classes/Collision.html).

**Comment by 8Observer8** [comment]
I'll try to post an example or my question with an example if I run into problems. Thank you!
