### ISSUE TITLE
Having en elastic behavior when mouse grabs body since 0.19.0

### ISSUE THREAD

**Issue by oguilleux** [liabru/matter-js#1200]
Is there any body parameters I should set to 0 to disable this new behavior ?

Test it here in my [codepen](https://codepen.io/olig/full/eYLGPwW). Grab an image and move your mouse while holding the image. The image will have an elasticky behavior. This did not happen in 0.18.0.

Thanks for your help.

**Comment by liabru** [comment]
See migration in the [release notes](https://github.com/liabru/matter-js/blob/master/RELEASE.md) and the linked PR there.

There are multiple ways to handle this but I think in this case the easiest might be to increase your mouse constraint stiffness to e.g. `0.8`.

**Comment by oguilleux** [comment]
mouse constraint stiffness set to 2 solved my problem thanks a lot
