### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by ergflip** [liabru/matter-js#1207]
I was wondering how secure was to make a game e.g slingshot angry birds style while making sure a bad actor couldn't change the code to make the bullet used to tear down a building way bigger, so that the game is easier.

I am kinda new to frontend development so I was wondering how possible it is for someone to cheat at a game created with matter.js, I know that if the result was provided by the backend the user can't just inject some code, but if everything is being dealt with frontend it is easier to cheat. Am I wrong? Thanks in advance

**Comment by photonstorm** [comment]
This is nothing really to do with Matter. You're going to need a 3rd party service like https://jscrambler.com/ if you're serious about protecting your code.

**Comment by ergflip** [comment]
I see thank you @photonstorm just learnt something!

**Comment by ergflip** [comment]
Also after researching about jscrambler, determined attackers can still find ways to bypass these measures, such as by reverse engineering the obfuscated code etc, how do certain websites e.g gambling websites make sure someone doesn't cheat on games like Plinko (search for YT videos of it if you dont know what kind of casino game this is)

**Comment by photonstorm** [comment]
Good luck with reverse engineering JScrambler code! Have you ever looked at it? It's not simple obfuscation.

Casino games would _never_ do _any_ logic on the client side. They would do it all on the server and validate all user input on the server, making it fully authoritative. The client would be entirely dumb, used for nothing but rendering and collecting input.

This is a massive and deep topic (I hope your server-side security skills are top-notch!) and unsuitable for the Matter JS GitHub repo IMHO. This issue should be closed, and the discussion should be moved somewhere more sensible for it.

**Comment by ergflip** [comment]
@photonstorm im just trying to code it for fun and to learn some more MatterJS, I am currently testing stuff with this codepen: https://codesandbox.io/s/okol4x?file=/src/index.tsx I was trying to make it so that the ball falling would go to the left or right constantly based on an results array, e.g [0,1,1,1,0,0] being 0 left and 1 right.

Make it fall one by one and basically go one to the left/right based on that array, any ideas?

**Comment by liabru** [comment]
This question is not related to an issue with Matter.js - there is also no server side or multiplayer component in this project, so this is out of scope here.

Please keep in mind this is not a game development forum, so closing this one, thanks!
