### ISSUE TITLE
Directional Friction for racing game

### ISSUE THREAD

**Issue by TheThirdOne** [liabru/matter-js#121]
I want to make a top-down racing game with accurate driving physics, but I can't think of how I could make a a body that would act appropriately. 

Is there a way I can make wheels that have directional friction (higher coefficient of friction in one direction over another)?

**Comment by liabru** [comment]
There's no built in support for that but you can set friction at any time using `Body.setFriction`. You could then use the engine update event to modify the friction of your body how ever you like.

**Comment by TheThirdOne** [comment]
How would Body.setFriction help? This isn't friction varying over time.

Is there a way to apply impulse or set velocity to a body? Without that I don't think I could modify friction.

**Comment by liabru** [comment]
Sure you can set velocity and such, take a look at the [Matter.Body docs](http://brm.io/matter-js-docs-master/classes/Body.html). But if I understand correctly, you mean that the wheels should be able to slide ('roll') along one body relative axis but stick (until they slip) along the other axis?

If so you'll need to implement that yourself and do it inside an engine `beforeUpdate` event and you'll want to set the built in friction and gravity values to `0` on your body.

Here's a nice [2d car physics tutorial](http://www.asawicki.info/Mirror/Car%20Physics%20for%20Games/Car%20Physics%20for%20Games.html) and some [example code](https://www.gamedev.net/topic/470497-2d-car-physics-tutorial/) that may be helpful.
