### ISSUE TITLE
Objects sticking to boundries

### ISSUE THREAD

**Issue by vtheviking** [liabru/matter-js#122]
Hello, im building a website for a client, and the objects that i had developed happen to stick to the walls or borders around the window screen. When my objects start bouncing around they end up getting stuck on the wall and don't repel back. Any idea how to fix it. The website can be viewed at http://berberianmysterytheatre.com/
Thanks again for the help.

**Comment by GurpreetSran** [comment]
Please have a look here.

 https://github.com/liabru/matter-js/issues/67

**Comment by liabru** [comment]
Thanks @GurpreetSran, also note that upgrading to the latest master build has this set by default.
