### ISSUE TITLE
There is a strange problem

### ISSUE THREAD

**Issue by MaxMinimus** [liabru/matter-js#1236]
There is a strange problem. The application works fine offline, but online it slows down a lot. At the same time, the application does not depend on the server, and is designed to work offline.

But even online sometimes there is no this problem, in a different operating system and browser.

Here is a demo - https://dvadeshki.ru/d1g1
press enter to run
to exit - escape

**Comment by photonstorm** [comment]
This issue doesn't really make much sense (lost in translation perhaps?) because there is absolutely no difference in how Matter runs if it's on a local web server or a hosted one. There's no such thing as running it "offline". Perhaps try and explain in a different way?

**Comment by MaxMinimus** [comment]
Yes, it's very strange. Everything works fine on the local server. But in the same browser it does not work well if the page is open on the Internet.

The overall speed is reduced by about a factor of three and the animation is not smooth.

**Comment by MaxMinimus** [comment]
I'm sorry, I found my mistake.
Thank you.

**Comment by mreinstein** [comment]
@MaxMinimus  can you close this issue please? That will help de-clutter the issue list.
