### ISSUE TITLE
How can set predefine path ?

### ISSUE THREAD

**Issue by yashk2023** [liabru/matter-js#1241]
I'm creating a game. 
where functionality is user select a top arrow and drop the ball, and I make an API call to decide the bottom slot. 

I need guidance on creating dynamic paths from the selected arrow to the determined slot. How can I achieve this functionality efficiently within Matter.js, considering possible obstacles? Any code examples or tips would be greatly appreciated.

**Comment by ggorlen** [comment]
Related:
- [MatterJS precompute final position](https://stackoverflow.com/questions/70847252/matterjs-precompute-final-position)
- [In the plinko game written with the matter.js engine library, how to make the ball always fall into the pre-planned position](https://stackoverflow.com/questions/75642529/in-the-plinko-game-written-with-the-matter-js-engine-library-how-to-make-the-ba)
- #820 
- #1190 
- #1199
