### ISSUE TITLE
Mass/density has no effect on fall speed

### ISSUE THREAD

**Issue by JorensM** [liabru/matter-js#1245]
I'm trying to make 'heavy' bodies by altering their mass, but it seems that no matter how big or small I set the mass/density to be, the bodies fall at the same speed.

This can be reproduced by going to one of the [demos](https://brm.io/matter-js/demo/#wreckingBall), creating a body with low mass, then creating a body with high mass, and seeing that they fall with the same speed.

Thanks!

**Comment by ninjadev64** [comment]
I believe mass only affects terminal velocity and not gravity (in real life), but I might be wrong.

**Comment by JorensM** [comment]
@ninjadev64 I did some research and this turns out to be true! I never knew that haha! I guess I will close this.
