### ISSUE TITLE
Render canvas object

### ISSUE THREAD

**Issue by hlxdev** [liabru/matter-js#1249]
I'm trying to render text with canvas, but it doesn't appear on the screen

```
useEffect(() => {
    const cw = 500
    const ch = 500

    const render = Render.create({
      element: boxRef.current!,
      canvas: canvasRef.current!,
      engine: engine.current,
      options: { width: cw, height: ch, wireframes: false },
    });

    renderRef.current = render

    Runner.run(engine.current)
    Render.run(render)

    const ctx = renderRef.current!.context

    ctx.font = '48px Arial'
    ctx.fillStyle = '#fff'
    ctx.fillText('OBS', 50, 50)

    return () => {
      Render.stop(render)
      World.clear(engine.current.world, false)
      Engine.clear(engine.current)
    };
  }, [])
```
I used a console.log to see the value of `ctx` and it returns the context normally

**Comment by ggorlen** [comment]
See [Matter.js: placing text or images on the canvas behind objects](https://stackoverflow.com/questions/26043360/matter-js-placing-text-or-images-on-the-canvas-behind-objects) for an example of drawing text on top of the canvas after Matter's renderer has drawn on it using the `afterRender` event.

if you want to do complex drawing, probably don't use the prototyping renderer built into MJS and [run MJS headlessly](https://stackoverflow.com/a/72849141/6243352) with your own canvas front-end (or maybe even non-canvas DOM elements, if you're working with text). Knowing more about your use case would make it easier to make a recommendation.

**Comment by hlxdev** [comment]
> See [Matter.js: placing text or images on the canvas behind objects](https://stackoverflow.com/questions/26043360/matter-js-placing-text-or-images-on-the-canvas-behind-objects) for an example of drawing text on top of the canvas using the `afterRender` event, after Matter's renderer has drawn on it.
> 
> if you want to do complex drawing, probably don't use the prototyping renderer built into MJS and [run MJS headlessly](https://stackoverflow.com/a/72849141/6243352) with your own canvas front-end (or maybe even non-canvas DOM elements, if you're working with text). Knowing more about your use case would make it easier to make a recommendation.

actually, i would need to draw a trajectory line from a circle (a projectile that is fired using applyForce when a button is clicked) to the point it can reach
i thought the best way to do this would be with the canvas, as i didn't find a native way in MJS to create curved lines

**Comment by ggorlen** [comment]
Thanks for the context. If you don't mind the trajectory line being on top of the drawing MJS has already done on the frame, then you may be able to get away with `afterRender` (first link above). Otherwise, your use case is probably stretching MJS's prototyping renderer beyond its capabilities, and it'd be better to use your own rendering front-end (second link above). Does one of these approaches meet your needs?

**Comment by hlxdev** [comment]
i tried the first approach, but the `afterRender` event is not being emitted, I also tried with `collisionStart` and that one is working fine

**Comment by hlxdev** [comment]
i think the first way should work, i was able to render canvas using the 'afterRender' event
Thankss

**Comment by ggorlen** [comment]
Canvases are re-drawn from scratch per frame, so you can draw the curved line with changes from frame to frame. Your `afterRender` event callback should run on every frame, so if you're drawing the curve at a particular X/Y position and you increment the X position by some small amount every frame, it'll appear to move rightward across the screen.

Feel free to close the issue if/once you feel it's resolved satisfactorily.
