### ISSUE TITLE
"z" axis gravity?

### ISSUE THREAD

**Issue by GAZ082** [liabru/matter-js#125]
Hi there. I plan to toy around with a top-down game. Did not see a Z axis gravity option nor a way to simulate it.

How can i do it?

Thanks.

**Comment by liabru** [comment]
The engine is obviously 2d only, but I assume you just want z-axis for things like jumping?
It's possible to do a basic simulation of it _without collisions_ (or possibly simplified collisions), if you implement it yourself.

You could add your own `body.position.z` and `body.positionPrev.z` variables at body creation, then you could add some code in an engine `beforeUpdate` event (or create your own fork of Matter.js) to do verlet integration for every body like it's done here in [Body.update](https://github.com/liabru/matter-js/blob/master/src/body/Body.js#L513-L525) but on the `z` positions instead.

Then you will need to apply gravity for `z` like it's [done here](https://github.com/liabru/matter-js/blob/2ab20b0656eec30eeba9c9ed3b65103bd5138023/src/core/Engine.js#L290-L301). You'll want to clamp `z >= 0` to simulate the ground. Then to render it I guess you'll want to scale your body drawing by `z` (or just use a 3d renderer).

This will be obviously quite limited, but might suffice for a simple top down game where z is limited to jumping or throwing objects over walls.

If you end up needing full blown 3d physics, then [Cannon.js](http://www.cannonjs.org/) is worth a look.

**Comment by GAZ082** [comment]
Mmm, just want to simulate the gravity for a football, for example. Players would go in the x-y axis, but the ball can be kicked up to the sky (now that i'm writing this, players as well can jump and fall).
