### ISSUE TITLE
Slow performance when drawing path on canvas

### ISSUE THREAD

**Issue by JayChetty** [liabru/matter-js#126]
Hi,  awesome library.   Making an animation of moving balls.  Trying to draw some static lines that don't effect the the balls,  so just rendering them directly from the canvas context, using the afterTick event ( see below ).   Find that this greatly slows down the animation.  Wondering if there is another more efficient way to do this?  Thanks, Jay

```javascript  
var ctx = engine.render.context;
var path=  new Path2D();
Events.on(engine, 'afterTick',  function(ev){
   path.moveTo(boxLeftX, bottomY - (channelHeight*1));
   path.lineTo(boxRightX, bottomY - boxHeightAdjust - (channelHeight*1));
   ctx.stroke(path);
 }

**Comment by liabru** [comment]
Why are you using `Path2D` here? That might be the source of the performance issue.
If you just need lines, then why not just use `context` to draw them?

**Comment by JayChetty** [comment]
Thanks, that was the cause of the performance problem.
