### ISSUE TITLE
Slow on mobile

### ISSUE THREAD

**Issue by juanmarianacci** [liabru/matter-js#127]
Hi!,
I m working on a game, this work fine in desktop, but very slow in some devices (Samsung Galaxy Tab 4, for example) :(
I try the demos, on my device and work slow too... Do you have any idea?
Thanks!!!

**Comment by juanmarianacci** [comment]
Probé quitando todos los elementos móviles de la pantalla y dejando sólo uno, pero también funciona lento. También intenté habilitando la opción "enableSleeping"

**Comment by liabru** [comment]
How are you rendering your game? Try disabling your rendering to see if that is the bottleneck.

**Comment by Aralun** [comment]
I would expand on what @liabru said and suggest profiling your game. Try to identify bottlenecks, and if one happens to be MatterJS come back with more data.

**Comment by juanmarianacci** [comment]
Hi, thanks for your replys!
Here is a part of my code:
// create a Matter.js engine
            var engine = Engine.create($('#canvas-container')[0], {
                render: {
                    options: {
                        wireframes: false,
                        background: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/28963/ball-bk2.jpg',
                        //enableSleeping: true,
                        //positionIterations: 1,
                        //velocityIterations: 1,
                        width: 1200,
                        height: 800
                    }
                }
            });

I tried with enableSleeping: true, positionIterations: 1, velocityIterations: 1 and wireframes: true, but there was no change.

Actually, my game has 4 static blocks with the format:
var shelfA = Bodies.rectangle(40, 200, 100, 20, { isStatic: true, mass: 1000, friction: 0.99 });

And a mobile block as:
var book = Bodies.rectangle(350, 560, 180, 40, { chamfer: { radius: 4 }, mass: 1000, friction: 0.8 });

How can I disabling my rendering?

**Comment by liabru** [comment]
As @Aralun mentioned, it's best if you use a profiler to first identify the bottleneck (check out [remote debugging](https://developer.chrome.com/devtools/docs/remote-debugging)).

If you only have a few bodies colliding, then I will bet that the bottleneck is rendering.
What browser are you using? Could you try using `engine.render.options.pixelRatio = 0.5` or a lower value to see if that helps?

**Comment by juanmarianacci** [comment]
Hi liabru,
I'm using Chrome, and in Safari in a Iphone 4 (more slow). Mobile demo also works me slow on both.
I'll try with everything else that you mention and I will comment on the results.

**Comment by juanmarianacci** [comment]
I tried changing the pixelRatio like you said, and I noticed a big change! thank you!
I also found that I was using the 'matter-0.8.0.js' version, and making use of pixelRatio is 'matter.min.js'.
With this version change it thinks I work well on devices, but I began to notice a strange comprtamiento on objects (begin to vibrate, for example). In this you will have to do the mass or other factor?
This version (matter.min.js) is stable?
Thanks again for your answers!
I will comment when I have more news.

**Comment by liabru** [comment]
> I began to notice a strange comprtamiento on objects (begin to vibrate, for example). In this you will have to do the mass or other factor?

This could be a bug, could you please give a jsfiddle with sample code?

> This version (matter.min.js) is stable?

Generally it should be stable, but please report any issues you find.

**Comment by juanmarianacci** [comment]
Sorry, I can not associate the file 'xx' (which is the one I use) in codepen or jsFiddle. I tried 'http://brm.io/js/libs/matter-js/matter.min.js' but is not the same file. You have another file path?

**Comment by juanmarianacci** [comment]
Hi liabru, here is my example:
http://codepen.io/anon/pen/WvgEOQ

Sometimes the objects on the larger rectangle vibrate. You can move this rectangle with the arrow keys (left and right). When objects fall to the ground, these are vibrating infinitely. You have any idea what can be?

**Comment by liabru** [comment]
A number of reasons:

- values for mass are far too large (better to use e.g. between 0.5 - 2)
- too much mass difference (keep them similar)
- the `book` body spawns inside another body, so it gets pushed up (ensure no collision at create)
- the `domino` bodies are thin and chamfered so will wobble (remove chamfer)

**Comment by StinkyVoid** [comment]
Hi liabru, I am using Coolpad Android Lollipop, which runs all mobile (and non-mobile) examples like butter. I was inspired and started doing this with p5.js, with help of Daniel "Awesome" Shiffman's tutorials.
But it works probably with 4-5 fps. Help! This code can turn into my future dollar bills!

**Comment by liabru** [comment]
Is the issue with p5.js? I'm not a user of that myself so I can't really suggest what the issue is.
Maybe just trying working directly from the examples instead of using p5.js?
