### ISSUE TITLE
Why might there be such an error?

### ISSUE THREAD

**Issue by MaxMinimus** [liabru/matter-js#1275]
![Снимок экрана 2024-01-26 в 20 23 36](https://github.com/liabru/matter-js/assets/25684443/2049d7a3-4940-47ff-bc12-2b87ac376915)

when this error occurs, bodies fly apart at high speed and the game crashes

**Comment by greg-gorlen-andela** [comment]
I suggest sharing your code as text so someone can execute it easily to reproduce the problem.

**Comment by MaxMinimus** [comment]
the problem was that some bodies had Null density
