### ISSUE TITLE
Engine.create should size the canvas to fill the supplied element id

### ISSUE THREAD

**Issue by gamecubate** [liabru/matter-js#128]
It looks like Engine.create does not size the canvas to fill its containing element, but rather hard-codes its dimensions.

```
var engine = Engine.create(document.body);
// document.body was 320 by 480 yet canvas is fixed at 800 by 600
```

Meanwhile, is there an undocumented option for Engine.create that would allow one to specify canvas size? If not, I'll have to hack it.

Thanks!

**Comment by gamecubate** [comment]
Solution:
```
var w = document.body.offsetWidth;
var h = document.body.offsetHeight;
var engine = Engine.create(document.body, {
	render: {
        	options: {
			width: w,
			height: h
		}
	}
});
```

**Comment by liabru** [comment]
Yep that's how to do it!

> Had it been in the API documentation, I would have found it much sooner... (a nudge & a wink)
Well it kind of is [here](http://brm.io/matter-js-docs-master/classes/Render.html#property_options.height) but I agree it's not the most obvious thing, I'll work on making this clearer when I'm next updating the docs :)
