### ISSUE TITLE
How do set world gravity at Engine.create invocation time?

### ISSUE THREAD

**Issue by gamecubate** [liabru/matter-js#129]
I couldn't figure out how to set world gravity until I saw an example in CodePen. The solution -- modifying engine.world.gravity.x and/or .y after having called Engine.create -- is not elegant.

Looking at (edge version) matter.js, I couldn't figure out if there was an option to Engine.create that would let me do this.

I see that World.create would support an option for setting gravity, but that function is invoked by Engine.create thus: ```engine.world = World.create(engine.world);```. And that just doesn't make sense (to me). How would I invoke Engine.create such that World.create was invoked with the right option?

Thanks.

**Comment by gamecubate** [comment]
Solved:
```
engine = Engine.create(document.body, {
  world: {
    gravity: { x:0, y:0.01 }
  },
  render: {
    options: {
      width: w,
      height: h
    }
  }
});
```

**Comment by liabru** [comment]
This is correct, in general Matter.js constructors can take partially completed objects and the missing properties are filled with defaults.

Also, you can modify `world.gravity.x` at any time. Looks like the docs are missing the gravity and bounds property, I need to fix this!

**Comment by gamecubate** [comment]
Thanks. It would certainly be nice if the docs were fleshed out a bit. Barring that, more CodePen examples, or a cookbook. (Or, joint angle limits... ;)
