### ISSUE TITLE
Is there a 1:1 correspondance between world units and screen pixels?

### ISSUE THREAD

**Issue by gamecubate** [liabru/matter-js#130]
Is there a 1:1 correspondance between world units and screen pixels as opposed to, say, Box2D?

**Comment by liabru** [comment]
All units are simply relative but consistent, so you should be able to define them how ever you like so long as you scale consistently in the appropriate places (e.g. applying forces, position, rendering).

`Matter.Render` for example uses 1:1px for position values, but you can scale your rendering how ever you like.

**Comment by gamecubate** [comment]
Thanks for the info. A 1:1 seems okay for now although, my simulation of small screen objects (30px x 30px crates), the forces I can apply on them are of the order of 0.0001; anything stronger than that and they move much too fast.
