### ISSUE TITLE
concave body fixed texture

### ISSUE THREAD

**Issue by ezshine** [liabru/matter-js#133]
Hello , I'm create a concave body like Tetris "L"

var tetris=Vertices.fromPath('0 60 40 60 40 40 20 40 20 0 0 0');
var compoundBodyB = Matter.Bodies.fromVertices(0, 0, tetris,{render:{sprite:{texture:"images/test.png"}}});

the texture has some problem.

and the position it's not at (0,0) , how can i fixed these issue?

thanks so much~

**Comment by ezshine** [comment]
the texture size is width:40px height:60px

**Comment by liabru** [comment]
I think the problem here might be the same as in #153, so please now refer to that thread, thanks.

**Comment by arindammojumder** [comment]
I am facing texture repetition issue while using fromVertices. Any solution? Check the attached screenshot.
![repeat](https://user-images.githubusercontent.com/282325/42570408-6ad4bb5a-8531-11e8-9ad9-ec52d44aefa3.jpg)

`var customTrey = Vertices.fromPath('0 0 0 20 152 20 152 0 150 0 150 18 2 18 2 0 0 0');
 var trey = Bodies.fromVertices(1080, 385, customTrey, getOptions('images/trey.png', true, false), true, 0.01, 30);

function getOptions(sprite = '', static = false, sensor = false) {
    var options = {
        isSensor: sensor,
        isStatic: static,
        density: 0.1,
        frictionAir: 0.001,
        restitution: 0,
        friction: 0,
        // id: 420,
        render: {
            fillStyle: 'none',
            sprite: {
                texture: sprite,
                xScale: 1,
                yScale: 1
            }
        }
    }
    return options;
};`
