### ISSUE TITLE
applyForce on collisionStart event

### ISSUE THREAD

**Issue by juanmarianacci** [liabru/matter-js#134]
Hi liabru,
I have a question.
How can I use "Matter.Body.applyForce" within "collisionStart" event ??

From this I can use "Matter.Body.translate", but not "applyForce".

I tried this but it does not work for me:

Events.on(engine, 'collisionStart', function (event) {
   for (var i = 0; i < event.pairs.length; i++) {
       var pair = event.pairs[i];

      if (pair.bodyB.label == 'regla' && pair.bodyA.label == 'dominoTableB18' ) {
         Matter.Body.applyForce(lemmon, { x: 0, y: 0 }, { x: 0.1, y: 0 });
      }
   }
});

Thanks!

**Comment by liabru** [comment]
As it stands, forces get cleared in `Engine.update` right after the event is emitted, so they won't ever get applied.

This probably should be changed, but for now you should cache the forces you need to apply in some place outside of the event, then apply them in the next engine `beforeUpdate` event.

**Comment by juanmarianacci** [comment]
With this works very well.
Thanks liabru!

**Comment by liabru** [comment]
Great, no problem!

**Comment by ChubbRck** [comment]
I'm still having trouble getting this to work using the method you describe. Am I misunderstanding the logic?
```
Events.on(engine, 'beforeUpdate', function(event) {
	for (i = 0; i<bodiesToBeMovedNextFrame.length; i++){
		var theBody = bodiesToBeMovedNextFrame[i];
		Body.applyForce(theBody, { x: 0, y: 0 }, {x: 100, y: 100});
	}
});
Events.on(engine, 'collisionStart', function(event) {
	var pairs = event.pairs;
	for (var i = 0; i < pairs.length; i++) {
	    var pair = pairs[i];
	   	if (pair.bodyA.label == 'outerHex' && pair.bodyB.label = 'outerHex'){
				bodiesToBeMovedNextFrame.push(pair.bodyA);
				bodiesToBeMovedNextFrame.push(pair.bodyB);
	   	}
	}
});
```

**Comment by liabru** [comment]
Yeah that looks about the right approach, see the [events example](https://github.com/liabru/matter-js/blob/master/examples/events.js).
