### ISSUE TITLE
Small Circle body constantly slipping if enableSleeping is false

### ISSUE THREAD

**Issue by kbkrisa3** [liabru/matter-js#135]
I was just experimenting with matter, because by sight it seemed to be a better physics option for me than box2dweb, but as I started having some fun with it, I came across a really strange issue. 

I created a box, and a circle. The box seems to work correctly but when the circle falls down, it starts slipping weirdly. The most interesting thing is that this only happens if the circle has a small radius (like 35). 

Here is my experiment:
https://www.dropbox.com/s/1aclnnbk02byjse/matter.js.issue.zip?dl=0

**Comment by kbkrisa3** [comment]
Ok! So I experimented a little more with this, and discovered, that when I had a higher friction on the circle body than 0.05, the body goes crazy, and starts moving no matter what. Under 0.05 it's still moving, but the movement is not visible (only from the console). Unfortunately I still don't really know what the problem is. Is that supposed to work like that and only stop when sleeping is enabled?

Thanks

**Comment by liabru** [comment]
Try the latest [master build](https://github.com/liabru/matter-js/blob/master/build/matter.js) which I think should solve this.

**Comment by kbkrisa3** [comment]
And so it did. Thank you, and sorry for not using the latest release!
