### ISSUE TITLE
Scrollbars added to page

### ISSUE THREAD

**Issue by notflip** [liabru/matter-js#136]
Hi,

I'm calculating the full width and height of the #container div but i'm getting a small scrollbar horizontal en a small on on the vertical axis. Any idea what might be causing this? 
It doesn't happen if i turn the plugin off. Thanks!

**Comment by liabru** [comment]
Did you manage to solve this? I couldn't reproduce it, so an example would be helpful.

**Comment by liabru** [comment]
Closing this as I don't think it's a problem related to matter.js
