### ISSUE TITLE
Revolute constraint

### ISSUE THREAD

**Issue by jszanto** [liabru/matter-js#139]
It would be nice to have a way to anchor bodies at a certain point. Basically allowing objects to only rotate around a certain point and not move in any other way. I know this can partially be achieved through constraints, but those still allow the body to move in all directions.

For an example, look at the triangle in the Box2D demo on this page: http://box2d-js.sourceforge.net/index2.html

**Comment by KrisKlip** [comment]
+1

**Comment by greenSnot** [comment]
+1

**Comment by staff0rd** [comment]
Is there any workaround for this currently?  For example, is it possible to rotate a given rectangle body around a specific, non-central point of that rectangle or otherwise?

**Comment by kroko** [comment]
+1 pivot constraint

**Comment by liabru** [comment]
I've spent some time refactoring the constraint system, these should be coming pretty soon!

**Comment by liabru** [comment]
An alpha build that supports revolute constraints is now in the `constrain-fixes` branch:

https://github.com/liabru/matter-js/tree/constraint-fixes/build

To create a revolute (or pin constraint) just create a `Matter.Constraint` with `length: 0` (and `stiffness: 1` which is default). See the [catapult example](https://github.com/liabru/matter-js/blob/constraint-fixes/examples/catapult.js#L55-L60). As a bonus, this branch also completely upgrades the constraint resolve so it's far more accurate and stable than before.

Anyone who is interested please try it out on your use case!

**Comment by Bugin10** [comment]
Possible bug when using poly-decomp.js with the new constraint. When i try to join an object to a body made from poly-decomp, the constraint doesnt appear to attach at the correct location and both objects will be pulled randomly around each other.

An example of the behaviour i want with poly-decomp disabled: https://codepen.io/Bugin10/pen/YVLXrB
An example with poly-decomp: https://codepen.io/Bugin10/pen/wdjBZb

**Comment by liabru** [comment]
Thanks for the test case, looks like maybe there's a problem with the new constraints on compound bodies. I'll look into it.

**Comment by liabru** [comment]
@Bugin10 it seems that the solution is to set the axel stiffness to `0.7`. You should also remove the `density: 0.1` as this creates a huge mass difference which also breaks stability. Not quite sure why a value of `1` is breaking this case though. Need to decide if this is a release blocker.

**Comment by muniatu** [comment]
Is there a way to achieve this behaviour with a mouse constraint? Make an object pivot where you are clicking? So you can drag an object and it's affected by gravity?

**Comment by liabru** [comment]
Yeah it does work with the mouse constraint too, I'll show an example of that!

**Comment by Bugin10** [comment]
@liabru I'm using randomly generated geometry in my application with poly-decomp where I've found i need to use a lower value of 0.3 to significantly reduce the problem. With a value of 0.7 i usually get 2-3 of my 20 generated objects with issues. The new system is a massive improvement though. Even with a value of 0.3 my cars no longer act like they have suspension made from jelly :)

**Comment by liabru** [comment]
Pin constraints are implemented of `0.13.0`, you can see how they're used in the [constraints example](https://github.com/liabru/matter-js/blob/master/examples/constraints.js). You can see how to apply it to the mouse constraint on [these lines](https://github.com/liabru/matter-js/blob/master/examples/constraints.js#L146-L156).

**Comment by gabbah** [comment]
Is it just me, or is there still some give in the pin constraint, making it act like a very stiff spring? :/

**Comment by liabru** [comment]
Do you mean when interacting with the constrained body using a `MouseConstraint`? Or when other bodies are colliding with the constrained body?

**Comment by gabbah** [comment]
@liabru Yes, when using the mouse constraint on a body.
In you chain example, the rightmost chain has the following constraints:
  `Composites.chain(ropeC, 0.3, 0, -0.3, 0, { stiffness: 1, length: 0 });
    Composite.add(ropeC, Constraint.create({ 
        bodyB: ropeC.bodies[0],
        pointB: { x: -20, y: 0 },
        pointA: { x: ropeC.bodies[0].position.x, y: ropeC.bodies[0].position.y },
        stiffness: 0.5
    }));`
So the 'Composites.chain' should connect all the bodies with stiff constraints with length zero, meaning a pin constraint with no give at all, right? But still, if I pull at the chain using the mouse constraint, the chain seems to be connected by springs that have less than 1 in stiffness.

Another example. In my own code, I copied the example code, and instead of using stiffness 0.5 for the first body in the chain (than "hangs it up"), I used stiffness 1. What happens then?
Well, if I pull on the *first* body with the mouse, it works as it should, and there's no give. It actually works as a pin constraint then. BUT, if I instead pull on the middle of the chain say, then the FIRST bodies constraint suddenly is not stiff anymore! That seems like a bug to me?

**Comment by liabru** [comment]
There's generally room for improvement with the pin constraints, but there's a bigger issue that by using the mouse constraint like this you're creating an unsolvable system - somewhere, something has to give. So I think there likely needs to be some sort of priority system where the mouse constraint has some extra 'give' such that it will be the one to fail before pin constraints do. Does that make sense?

**Comment by gabbah** [comment]
It makes total sense and I thought about this as well - if all constraints are have stiffness 1, then that's unsolvable. However, as soon as one of them is not 1, then that's the one that should give in, right? Currently that's not the case. Even though my mouse constraint is lower than 1, a constraint that is 1 (between the links in the chain) give in instead. That is just a bug for the user.

The docs should just state that if you set all constraint to 1 in a system, then either the outcome is undefined, or there will be some priority given according to some rule. In general, the user should avoid doing that I think.

But in my case, of course the mouse constraint is the one that should give in.

It was also quite strange that the stiff constraint started acting like a soft spring if I pull from the middle of the chain instead. :P

**Comment by liabru** [comment]
I've opened an issue regarding this #623 please +1, thanks.

**Comment by gabbah** [comment]
Great!
Does this issue solve the last point I made?
Pulling the middle of the chain, turns the first constraint (where the chain is hanging from) into a soft spring (even though stiffness is 1)?

**Comment by ethanmay** [comment]
I had these issues of springy pin joints when building a rope out of a chain of rectangles with a large object on the end.

For future reference, it is worth noting that when building chains, the bodies in your chain must have proper density set in order for the constraints holding those chains together to behave as expected. In my case, I increased the density of each rope segment (rectangle body) from the default to `0.01`. It takes a very high-density mass at the end of the rope to pull the constraints apart.

Hope this helps someone else! [Here's a demo.](https://codepen.io/emay/pen/vbzqoW)

**Comment by liabru** [comment]
Thanks, yes they can take some tweaking when they are under a lot of strain, see [this post](https://github.com/liabru/matter-js/issues/682#issuecomment-499077009) for some things to try if you're having these types of problem.
