### ISSUE TITLE
How to find force of body?

### ISSUE THREAD

**Issue by YChebotaev** [liabru/matter-js#140]
Hello.

I need to sum speed of two bodies one of which is emitter (a moving missle launcher for example). Because only way to set speed of body is by applying force to it, i need to find force of first body and add it to second body.

I was found a formula: http://formulas.tutorvista.com/physics/force-formula.html that says i need to know acceleration which is defined as velocity per time. I have velocity but does not have time and i'm actually don't want to have reference to `engine.timing` inside my entity instance because it's ruins separation of concerns and lead to spaghetti code.

Is there any way to find acceleration or force of body or maybe you can add a `Body.applyBodyForce(bodyA, bodyB)` helper for this?

**Comment by liabru** [comment]
> Because only way to set speed of body is by applying force to it

Actually in the latest master build there is [Body.setVelocity](http://brm.io/matter-js-docs-master/classes/Body.html#method_setVelocity), does that help?

**Comment by YChebotaev** [comment]
Yes. It's exactly what i'm looking for. Thanks.
