### ISSUE TITLE
MouseConstraint does not apply to bodies with chamfer 30

### ISSUE THREAD

**Issue by kirtangajjar** [liabru/matter-js#145]
To reproduce this bug, go to http://brm.io/matter-js-demo/ and add a body with champher 30. 

1. You won't be able to drag the body
2. The created body will not be perfectly round

**Comment by liabru** [comment]
This only happens when the chamfer radius is too big for the body and causes the vertices to self intersect. If you also increase the size option enough on the demo then chamfer 30 works fine.
