### ISSUE TITLE
how to manually render between updates?

### ISSUE THREAD

**Issue by evanthebouncy** [liabru/matter-js#147]
I'm refactoring my code to replace Engine.run with calling Engine.update a pre-set number of times instead. However, I could not get the rendering to work.

I've created the engine as follows:

    engine = Engine.create(document.getElementById('canvas-container'));

and I'm attempting to simulate 1 second of a box falling as follows:

    var boxA = Bodies.rectangle(400, 200, 80, 80);
    World.add(engine.world, [boxA])
    console.log(boxA.position)
    var n = 0
    while(n < 100) {
      Engine.update(engine, 10.0)
      n = n + 1
    } 
    console.log(boxA.position)
 
From the log I observe the box has correctly been falling through the updates, but it'll be nice to actually see it as well. How might I render it? I tried calling engine.render.controller.world(engine) after every update, but the result seems buggy. Thanks!!

**Comment by liabru** [comment]
Try using [Runner.create](http://brm.io/matter-js-docs-master/classes/Runner.html#method_create] and Runner.tick which will update and render etc. but don't use Runner.run.

**Comment by evanthebouncy** [comment]
thanks it did the trick for me. here's what I'm using now.

    // animate n key frames with 100 ms delay
    function animateN(n) {
      var cur_frame = 0
      function animate() { 
        if (cur_frame < n) { 
          Runner.tick(runner, engine, 100)
          cur_frame += 1
          setTimeout(animate, 100)
        } else {
        }
      }
      animate()
    }
