### ISSUE TITLE
How to create a joint for a rectangle?

### ISSUE THREAD

**Issue by bimgonzaga** [liabru/matter-js#149]
I am trying to create a joint for a rectangle so I can simulate a flipper for a pinball prototype, but I had no luck.

I am creating a constraint like this:

        var axelA = Constraint.create({
            pointA: { x: xx, y: yy },
            bodyB: body,
            pointB: { x: -50, y: 0 },
            stiffness: 0.9999
        });

But the -50 pointB (100 rectangle width) creates an 100px elastic band even though it is connected to the correct position in the rectangle.

Anyways, any sample code of a pinball flipper is much appreciated!

**Comment by liabru** [comment]
Until pivot constraints are implemented (see #71 and #139) it would be better to implement this by changing the centre of mass of the flipper to be at the pivot point, and then manually set the body's angle (see the [body manipulation example](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js)) when you press the key.
