### ISSUE TITLE
Reposition bodies without force velocity

### ISSUE THREAD

**Issue by hellopath** [liabru/matter-js#151]
Hi there!

I have a hard time to reposition some bodies depends of the window size without messed up the velocities.
Let's take as an example your Newton's Cradle http://codepen.io/liabru/pen/abFml
How can I reposition the circles so to be always in the middle of window's height?

Thanks,
Panagiotis

**Comment by liabru** [comment]
Are you using [Body.setPosition](http://brm.io/matter-js-docs-master/classes/Body.html#method_setPosition)?

**Comment by hellopath** [comment]
It works perfectly!
Thanks for the quick answer ;)
