### ISSUE TITLE
Custom loop not working

### ISSUE THREAD

**Issue by mroglic** [liabru/matter-js#152]
I would like to use Matter.js with my custom game loop, I followed instructions from here and added Engine.update(engine, 1000/60, 1); in draw loop, but nothing happens, just blank screen. Do I need to add tick method somewhere?

Here is my code:

window.onload = function () {

    // Matter.js module aliases
    var Engine = Matter.Engine,
        World = Matter.World,
        Bodies = Matter.Bodies;

    // create a Matter.js engine
    var engine = Engine.create(document.body);

    // create two boxes and a ground
    var boxA = Bodies.rectangle(400, 200, 80, 80);
    var boxB = Bodies.rectangle(450, 50, 80, 80);
    var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

    // add all of the bodies to the world
    World.add(engine.world, [boxA, boxB, ground]);

    // run the engine
    //Engine.run(engine);

    draw();

    function draw(){ 
        Engine.update(engine, 1000/60, 1);        

        requestAnimationFrame(draw);
    }
};

**Comment by liabru** [comment]
Can you look at #147 and tell me if it answers your issue?

**Comment by mroglic** [comment]
Thanks, It's working fine with Runner.tick. But now when I switched to RenderPixi I got an error in console: 
matter.js:8603 Uncaught ReferenceError: Common is not defined

Here is changed code with RenderPixi (I also included pixi.js):
window.onload = function () {

    // Matter.js module aliases
    var Engine = Matter.Engine,
        World = Matter.World,
        Bodies = Matter.Bodies,
        Runner = Matter.Runner;

    // create a canvas renderer
    //var engine = Engine.create(document.body);

    // create a pixi renderer
    var engine = Engine.create({
        render: {
            element: document.body,
            controller: Matter.RenderPixi
        }
    });

    // create two boxes and a ground
    var boxA = Bodies.rectangle(400, 200, 80, 80);
    var boxB = Bodies.rectangle(450, 50, 80, 80);
    var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

    // add all of the bodies to the world
    World.add(engine.world, [boxA, boxB, ground]);

    // run the engine
    //Engine.run(engine);

    var runner = Runner.create();

    draw();

    function draw(){ 
        //Engine.update(engine, 1000/60, 1);     
        Runner.tick(runner, engine, 1000/60);
        
        requestAnimationFrame(draw);
    }
};

**Comment by liabru** [comment]
I've just updated the master build with a fix for this, can you try it?
