### ISSUE TITLE
Single sprite covering a composite body?

### ISSUE THREAD

**Issue by erzahurak** [liabru/matter-js#153]
I'm experimenting with importing shapes from SVG, and that's working pretty well, but I'd like to apply a single sprite over top of the composite body that's created.  (See the svg demo stuff; Bodies.fromVerticies).

Is there an easy way to do this?  Currently, it applies the same sprite to all composite shapes.

Thanks!

**Comment by liabru** [comment]
Currently the function copies all of the options to all of the body parts, looks like I need to add an exception so that sprites don't get copied.

In the meantime, can you try loop through `body.parts` from index 1 and then set each `part.sprite = null`?

**Comment by erzahurak** [comment]
Been working on this here, too.  Looping through body.parts isn't enough,
because the sprite is still tied to a component, rather than the body, and
that makes for some alignment issues.  And there's some fun, fun issues
with aligning the sprite and the body because the bounds and position
aren't equivalent in the sprite and the body. Slowing working through the
trigonometry to make that work, too.  I'll be happy to share my ugly
solution with you when it's done, but you may want to pretty it up. :)

**Comment by liabru** [comment]
Please do share an example that demonstrates the issues. Compound bodies are a relatively new feature and support for rendering is pretty limited right now.

> looping through body.parts isn't enough, because the sprite is still tied to a component, rather than the body

This is correct, I assumed earlier that you only wanted one sprite for the whole body.

If you actually do want different sprites for each part, then things will be trickier.
But this is to be expected?

**Comment by erzahurak** [comment]
No, no, I want to do one sprite per the entire object.  I guess my
terminology isn't correct.

Using the SVG demo as a base, I'm able to pull in non-convex polygon shapes
from SVG.  Matter does this by breaking the SVG path down into a bunch of
convex polygons, which are treated as a body made up of a whole lot of
parts.

I'm looking to do just one sprite for the entire body and I'm having some
decent success in doing so, except that I can't get the two to align
correctly at the moment, mostly because the body "origin" is its center of
mass (as near as I can tell) and the sprites origin is the top left.
Translating one to the other is proving frustrating.  The centering stuff
you used for the circles and squares of the sprites demo would be easy, but
they just don't work here. An irregular shape, like, say, a kitten?  It's a
little trying. There's probably a simple way to do it that I'm completely
ignorant of; I'm just not a big math and vectors guy.  I expect to
recollect enough of my high school trigonometry classes within the next
couple of days to solve my problem.

Different sprites per body part would be cool, but I'm not looking for that
any time soon. :)

**Comment by liabru** [comment]
Actually, looks like this is due to an oversight in [Render.js line 431](https://github.com/liabru/matter-js/blob/master/src/render/Render.js#L431-L432).

The offset is assumed to be half the sprite dimension, but this only works when the centroid is the same as the centre of the sprite. Doh. Looks like a fix is needed here!

**Comment by erzahurak** [comment]
I've sort of got one, but at the moment it requires me to pass in the
min/max bounds of the body at 0 radians rotation to use to later calculate
an offset.  I'm thinking of moving those values into the Body itself, and
having them created/stored with a new body.

My codes in no shape to just push it to the project.  If you want to email
me your contact info, I'll email you what I have so far.

It's pretty fast, but I've noticed an odd behavior in the process.  If I
render all shapes, my frame rate stays right about 60fps.  If I render just
sprites, it stays around 60fps.  If I render sprites AND shapes, my fps
drops dramatically to about 20fps.  Some I'm trying to figure that out
first.

**Comment by lanewinfield** [comment]
I would love to see an example of this code. Currently attempting to do the same thing—applying a texture to a concave composite body.

**Comment by erzahurak** [comment]
Hi Brian, I have it, but it's ugly.  I'm quite hesitant to put it in the
project officially.  If you want to email me directly (erzahurak@gmail.com)
I'll zip up what I've got and send it to you.

Ed

**Comment by scottglz** [comment]
I took a stab at a pretty simple solution to this, where I modified the renderer to render the main body and not the parts when it has a sprite. See my <a href="https://github.com/liabru/matter-js/pull/207">pull request</a>.

**Comment by majman** [comment]
You might be able to use fillstyle = canvas pattern to achieve something similar: 
http://codepen.io/majman/pen/reqzBW?editors=0010

**Comment by liabru** [comment]
@majman Awesome! Love it.

**Comment by willmcl** [comment]
Anyone coming across this. I had some success with this: 

```
let body = Bodies.fromVertices(x, y, vertexSets, {
            render: {
              fillStyle: 'none',
              strokeStyle: 'none',
              lineWidth: 1,
              slop: 0,
            },
          }, true)
          let spriteHolder = Bodies.rectangle(
            body.bounds.min.x,
            body.bounds.min.y,
            (body.bounds.max.x - body.bounds.min.x),
            (body.bounds.max.y - body.bounds.min.y),
            {
              collisionFilter: {
                mask: 0,
              },
              render: {
                fillStyle: 'none',
                strokeStyle: '#ffffff',
                sprite: {
                  texture: './texture.png',
                  xOffset: 0,
                  yOffset: 0,
                }
              }
            }
          )
          let constraint = Constraint.create({
            bodyA: body,
            pointA: {x: 0, y: 10},
            bodyB: spriteHolder,
            pointB: {x: 0 y: 10},
            length: 0
          });
          let constraint2 = Constraint.create({
            bodyA: body,
            pointA: {x: 0, y: -10},
            bodyB: spriteHolder,
            pointB: {x: 0, y: -10},
            length: 0
          });

          let group = Composite.create({label: `group`});
          Composite.add(group, [body, spriteHolder, constraint, constraint2])
          Composite.add(world, group)
```

**Comment by Samgeven** [comment]
@willmcl Awesome solution! Works even better, if constraints have slightly increased stiffness. I tried 1.1
