### ISSUE TITLE
Rendering with PIXI does not seem to work 

### ISSUE THREAD

**Issue by LucasBertrand** [liabru/matter-js#154]
Hi !
When i set the controller to RenderPixi, an error occur that say 'Common is not defined' (line 8601).
I forgotten something ?
I guess my problem is isolated, but if you can help me, thanks !

**Comment by liabru** [comment]
I've just updated the master build with this fix, can you try it?

**Comment by LucasBertrand** [comment]
It works ! Thanks dude
