### ISSUE TITLE
Calculate force of collision

### ISSUE THREAD

**Issue by marekventur** [liabru/matter-js#155]
Hi!

Is there any way to detect the force(?) of a collision? When I listen to ```collisionActive``` I get a list of current collision with some information like overlap and contact points, but I can't quite figure out whether I can use any of that to calculate how hard the impact was.

My use case is to detect whether an object should be destroyed after a collision has been detected. E.g. I want object to be stackable but if you throw a heavy stone at it they should disappear.

Thanks!

**Comment by liabru** [comment]
For a quick hack, you could probably get away with using `collision.depth > threshold` as it should roughly scale with impact velocity (but not guaranteed). You could also factor in the masses of each body.

But a better way I think is by finding the relative momentum at impact.
Unfortunately, the velocity at impact time isn't currently recorded in the collision result.

What you should do is keep track of the velocities of your objects at the start of each step, which should be a reasonable approximation for this.

Then when you get a `collisionStart` event that includes these bodies, look up their velocities that you recorded and find the relative momentum from there.

I think something like this might be a good start:

	var bodyAMomentum = Vector.mult(bodyAVelocity, bodyA.mass);
	var bodyBMomentum = Vector.mult(bodyBVelocity, bodyB.mass);
	var relativeMomentum = Vector.sub(bodyAMomentum, bodyBMomentum);

	if (Vector.magnitude(relativeMomentum) > threshold) {
		// do something
	}

Where `threshold` is some constant that is the limit of relative momentum at which you want to take some action, probably just find this by trial and error.

(I've not yet tried this, so I don't know how well it will work in practice!)

**Comment by marekventur** [comment]
Thank you, that sounds like what I was looking for. Will give it a try!

**Comment by LiorArbel** [comment]
Hey,

Your solution is a bit problematic for me, as collision.depth doesn't care about the bodies' masses, and saving the last velocity of every single body in the game sounds a bit crazy, and will break the design of my code :S

I tried a simple workaround - multiplying the collision.depth by the absolute mass difference of the two objects (I have not a bit of experience in physics, sorry in advance).

Now I get better collision force feeling, however with a very big flaw - the current workaround doesn't consider the penetration direction, and throwing a very light object into a very heavy object outputs the same force as throwing the heavy object into the light one.

So - isn't there a way to calculate the force using the penetration vector direction?
