### ISSUE TITLE
Stick A Body To Another Body

### ISSUE THREAD

**Issue by glopratchet** [liabru/matter-js#156]
You did such a great job answering the question of marekventur perhaps you would be so kind as to answer mine.

So in my game there are circular bodies bouncing around the screen. There is one type of rectangular body different than all others. If a circular body collides with the rectangular body it should stick to the rectangular body and not move or respond to gravity. After a certain amount of time the circular body should become unstuck and respond to gravity again. Do you have any idea how you can make a body 'sticky' on demand?

**Comment by liabru** [comment]
Depends on how sticky you want it, you could try:

- apply a constant force towards the rectangular body every step with `Body.applyForce` on the engine `beforeUpdate` event
- create a constraint with `Constraint.create`
- remove the body from the world and add the body to the rectangular body's composite parts with `Body.setParts`
