### ISSUE TITLE
[RenderPixi] setting the body position directly break the collision detection

### ISSUE THREAD

**Issue by karlito40** [liabru/matter-js#162]
Hello,

I'm trying to make a Body jump after an impact with the same rebound no matter what. The documentation specified that:

``If you need to modify a body's velocity directly, you should either apply a force or simply change the body's position (as the engine uses position-Verlet integration).``

Unfortunately, if you hard code a position the collision does not work correctly for pixi.

```
var width = window.innerWidth;
var height = window.innerHeight;
var engine = Engine.create({
  render: {
    element: document.body,
    controller: Matter.RenderPixi,
    options: { width: width, height: height }
  }
});

var boxA = Bodies.rectangle(400, 200, 80, 80);
var groundHeight = 20;
var ground = Bodies.rectangle(width/2, height - groundHeight, width, groundHeight, { isStatic: true });

World.add(engine.world, [boxA, ground]);

Events.on(engine, 'collisionActive', function(e) {
  var y = boxA.position.y;
  boxA.position.y = boxA.position.y - 10;  // It works well without pixi
})

Engine.run(engine);
```

In this test case, the box will go higher and higher.

Does someone have an idea to resolve this ? Should i use another technique ?

--  I use the matter edge build and pixi v3.0.7.

**Comment by karlito40** [comment]
Nevermind, setting the velocity fix my issue.

```
Body.setVelocity(boxA, {x:boxA.velocity.x, y: -10}) 
```

But the bug describe above still exist. Hard coding a position as shown in the documentation is not working correctly for the pixi renderer.

**Comment by jstoeffler** [comment]
I don't know if it fixes it, but it's recommended to use the setter, ie: Body.setPosition

The method does a lot more than 

    body.position.x = // whatever
    body.position.y = // whatever

**Comment by liabru** [comment]
Exactly as @jstoeffler says, you should use the setter for position and velocity. I think this was the problem. Many other properties use setters too so always check!
