### ISSUE TITLE
Implementing Wraparound in matter js

### ISSUE THREAD

**Issue by nikhil-bhandari** [liabru/matter-js#164]
I am trying to implement a game where there are no boundary walls for the scene. ie. if the player/object reaches/crosses the edge of the screen it spawns back on the opposite edge, with the same velocity and trajectory.

Wraparound: https://en.wikipedia.org/wiki/Wraparound_(video_games)

I was trying to implement this in the beforeRender event but the circle object translates to the position but doesn't appear back on the screen.

```
//bubble = Matter.Body.circle
//height = canvas height
// ....
            Events.on(engine, "beforeRender", function () {
                        if(bubble.position.y <= 500){
                            Matter.Body.translate(bubble,{ x:0, y: height});
                        }
            });
```

Any thoughts or ideas on implementing this? I have started using matter today so I don't even know the whole API. any suggestions are welcomed.

**Comment by nikhil-bhandari** [comment]
Changed method logic to this and it works, but I am not sure if this is the best way
```            Events.on(engine, "tick", function () {
                    if (ball.position.y <= 0) {
                        Matter.Body.translate(ball, {x: 0, y: height});
                    }
                    if (ball.position.y >= height) {
                        Matter.Body.translate(ball, {x: 0, y: -height});
                    }

                    if (ball.position.x <= 0) {
                        Matter.Body.translate(ball, {x: width, y: 0});
                    }
                    if (ball.position.x >= width) {
                        Matter.Body.translate(ball, {x: -width, y: 0});
                    }
            });```

**Comment by nikhil-bhandari** [comment]
Fiddle for anyone who wants to try it out.

http://jsfiddle.net/fxhwLj7s/

**Comment by nikhil-bhandari** [comment]
How can I bind event listeners for touch and mouse?  Double tap and Double Click?

**Comment by liabru** [comment]
Sorry for the delay, looks like you got it!

Bonus: if you use `ball.bounds` instead you can make the wrapping smoother:

    Events.on(engine, "beforeRender", function () {
        if(ball.bounds.max.y <= 1){
            Matter.Body.translate(ball,{ x:0, y: height + (ball.bounds.max.y - ball.bounds.min.y) });
        }

        if(ball.bounds.min.y >= height){
            Matter.Body.translate(ball,{ x:0, y: -height - (ball.bounds.max.y - ball.bounds.min.y) });
        }

        if(ball.bounds.max.x <= 1){
            Matter.Body.translate(ball,{ x:width + (ball.bounds.max.x - ball.bounds.min.x), y: 0 });
        }

        if(ball.bounds.min.x >= width){
            Matter.Body.translate(ball,{ x:-width - (ball.bounds.max.x - ball.bounds.min.x), y: 0 });
        }
    });

**Comment by nikhil-bhandari** [comment]
Oh git it thanks. Any thoughts on adding double tap to the ball? I haven't figured that out yet.
