### ISSUE TITLE
Collision with ghost object

### ISSUE THREAD

**Issue by Misiur** [liabru/matter-js#165]
What I want to achieve: area which will trigger collisionStart, even though it won't affect motion of colliding object. I've tried slop, changing mass and inertia, but can't seem to get it to work. collisionFilter is not an option, as it doesn't trigger collisionStart at all. Anybody tried something similar?

**Comment by glopratchet** [comment]
Oh yes! I've been curious about how to achieve this as well with no success.

**Comment by Misiur** [comment]
https://github.com/liabru/matter-js/pull/166

I guess there is a 1000% better way to achieve this, but for me it works. If the repo is still mantained it'd be awesome if somebody told me about better way to do this.

**Comment by liabru** [comment]
I think what you need here are sensors? If so this is covered by #66, they're not currently implemented but please +1 if that's what you mean.

**Comment by liabru** [comment]
Closing this as [sensors are implemented](https://github.com/liabru/matter-js/issues/66) which should have resolved this.
