### ISSUE TITLE
Engine.create does not resize the provided canvas

### ISSUE THREAD

**Issue by schahriar** [liabru/matter-js#168]
This issue originates from [a fellow programmer's question on StackOverflow.](http://stackoverflow.com/questions/33569688/change-default-canvas-size-in-matterjs/33605320)

## Brief
`Engine.create` takes a canvas element or creates a new canvas using the given options. While the properties width and height in options do apply to the created canvas, they do not apply to the passed canvas. These set options are under `render.canvas`, `render.options.width` and `render.options.height`.

## Reproducing the issue
The issue in form of passed canvas where width and height of 1000px are expected:
https://jsfiddle.net/ns0s7oco/1/

The behavior of Matter.js with created canvas (as you can see 1000px is correctly set):
https://jsfiddle.net/ns0s7oco/2/

## Solution
Setting passed canvas's width and height like so would achieve consistency and could be easily done using (|| guarantees a correct width and height if options are not set):
```javascript
if(render.canvas) {
    render.canvas.width = render.options.width || render.canvas.width;
    render.canvas.height = render.options.height || render.canvas.height;
}
```
I've made a pull request for `./src/render/Render.js` found at #167 . There were no tests for PixiRenderer (at least I couldn't find them) so I decided to leave it alone, but the same code could apply to any renderer.

## Why?
Although this issue may seem as an enhancement, I firmly believe that new comers can be confused with this behavior of Matter.js. The documentation only hints to the fact that the options are applied to a created canvas and provides no alternative to achieving a consistent behavior whether a canvas is passed or not.

All files modified are lint free. All tests are passing. Done without errors.

**Comment by liabru** [comment]
I think this was intentional originally, as if you are passing a canvas then it is assumed you have already configured it. But you're right that it might be confusing, so I've merged this. Thanks.
