### ISSUE TITLE
[Question] Only one object affected by collision

### ISSUE THREAD

**Issue by NiciusB** [liabru/matter-js#17]
I'm creating a basketball game, and I need that only the ropes from the basket get affected by the ball's collision.
There's any way to do this?
Thanks

**Comment by bouraqadi** [comment]
Can a body belong to multiple groups?

**Comment by liabru** [comment]
Not at the moment, but you should be able to replace the function:
`Matter.Detector.canCollide = (filterA, filterB) => { ... }` with your own function that does anything you need.

Collision filters are definitely something I'd like to improve though, check out #341.
