### ISSUE TITLE
Update npm package please

### ISSUE THREAD

**Issue by LestaD** [liabru/matter-js#170]

**Comment by feross** [comment]
:+1: please -- can't use the `sleepStart` event because the npm package is super old

**Comment by liabru** [comment]
Sorry for the delay guys, I can't use my machine at the moment due to a hardware issue, but I'll prioritise this when I get it sorted.

**Comment by pauly815** [comment]
any luck with this?

**Comment by piranha771** [comment]
waiting for npm update too!

**Comment by liabru** [comment]
Sorry for the delay, just pushed release 0.9.0, along with a [new homepage](http://brm.io/matter-js/) and [new docs](http://brm.io/matter-js/docs/).

Tell me how you get on!

**Comment by piranha771** [comment]
Thank you sooooo much! I have already pushed a 0.9.0 defintion file for typescript to /definetlytyped.

**Comment by pauly815** [comment]
Awesome.  Installed with bower.  Thanks for the updates!
