### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fps' of undefined

### ISSUE THREAD

**Issue by chumo** [liabru/matter-js#171]
With the last version of the library (https://github.com/liabru/matter-js/blob/master/build/matter.min.js), when I run the engine, I always get the following error in the console:

Uncaught TypeError: Cannot read property 'fps' of undefined

every single frame of the animation. The message is only visible when I render the engine with the flag showDebug: true, so it is not fatal, but still annoying. Anybody knows the reason?

Thanks,
Jesús

**Comment by anthropomorphic** [comment]
Well, I don't know exactly how to fix it, but I see that in commit dcdc43d475879f73681a139f03edaa2968f39823 the `fps` attribute was moved from the `Engine` class to the `Runner` class.

As of df5f16ca5f16ab2aabf71641341823f88dd15490 the error is on line `269` of `src/render/Render.js`:

```javascript
text += "fps: " + Math.round(metrics.timing.fps) + space;
```
where `metrics` is defined as `var metrics = engine.metrics`
Apparently `Render.debug` needs to be updated to use `Runner.fps` instead.

**Comment by anthropomorphic** [comment]
What's confusing is that when you run the demo it works just fine. But after a bit of spelunking I found this on line `81` of `demo/js/Demo.js`:
```javascript
// pass through runner as timing for debug rendering
demo.engine.metrics.timing = demo.runner;
```
So the demo code hacks its way around the problem by passing in a reference to the runner.

**Comment by anthropomorphic** [comment]
Really it seems that the only problem here is that `Render.debug` is trying to display information it has no business knowing about. Since the game loop is decoupled from the engine, it should be the programmer's job to display an FPS counter if they want one, since they're in charge of driving the game loop themselves.

I propose that the fps counter simply be removed from `Render.debug` in the release version.

**Comment by anthropomorphic** [comment]
fa86527302e43a082ee3a1305c7d8b24fe9c0045

**Comment by liabru** [comment]
Looks like I didn't properly maintain backwards compatibility when I refactored this.
I've added a check that should prevent this error.

@anthropomorphic you're right about this and it's something I hope to address when I get around to working on decoupling the renderers, but this should at least prevent the errors for the time being
