### ISSUE TITLE
Render a label on top of body

### ISSUE THREAD

**Issue by Sheepzez** [liabru/matter-js#174]
I have a world similar to the [ball pool example](http://brm.io/matter-js-demo-master/#ballPool), I would like to have a label on each of the balls visible to the user.

Is there anyway to do this currently with Matter.js? 

Sorry if this is a really obvious solution.

**Comment by liabru** [comment]
You should use a custom renderer, you can copy `Matter.Render` and then add some code for drawing the labels. See the wiki page on [Rendering](https://github.com/liabru/matter-js/wiki/Rendering).
