### ISSUE TITLE
Ignoring Mousewheel event

### ISSUE THREAD

**Issue by northernlite69** [liabru/matter-js#175]
Is there a way of ignoring the mousewheel so that when an absolutely positioned Matter DIV is on top of content, we can still use Mousewheel to scroll the page normally?

Currently, if I create a DIV with Matter content, ALL mouse events for anything under the content get swallowed.  This *could* be fine for most mouse events, but it appears as though the page is not responding when the MouseWheel (or a touch and scroll) are fired.

Generally, are there any good examples of MouseEvent?

**Comment by liabru** [comment]
Please see my comments in #84 about removing the event.

**Comment by northernlite69** [comment]
Excellent! Thank you for your swift reply and a HUGE thank you for all your work- GREAT lib!

**Comment by northernlite69** [comment]
Sorry!  I tried but get error:
mouse.element is undefined
Where EXACTLY should I be targetting!?

**Comment by northernlite69** [comment]
Works via:

var mouse = mouseConstraint.mouse;
mouse.element.removeEventListener("mousewheel", mouse.mousewheel);
mouse.element.removeEventListener("DOMMouseScroll", mouse.mousewheel);
