### ISSUE TITLE
Making a "phantom" object that other objects don't collide with

### ISSUE THREAD

**Issue by DZGoldman** [liabru/matter-js#178]
Is it possible to have a static object that other objects pass through i.e, no collision event is triggered when they overlap?

**Comment by liabru** [comment]
Check out the [Collision Filtering](http://brm.io/matter-js-demo-master/#collisionFiltering) demo and the [source](https://github.com/liabru/matter-js/blob/master/examples/collisionFiltering.js) and this article for [collision filtering](http://www.iforce2d.net/b2dtut/collision-filtering) (it's for box2d but it's implemented similarly in matter.js)

**Comment by DZGoldman** [comment]
Wow, I thought I looked through the demos, but I must've missed the Collision filtering one. Thanks!

**Comment by liabru** [comment]
No problem, actually these are the demos for the master version (reminds me I need to update links in the readme soon).

**Comment by DZGoldman** [comment]
Update: the groupId attribute for bodies gave me what I needed; a bit easier than using the collision filtering object.
