### ISSUE TITLE
Resurrect-js Usage Example

### ISSUE THREAD

**Issue by glopratchet** [liabru/matter-js#183]
I'd like to save the world. 
I've been attempting all morning to get this to work.
Alas, Sigh and Spin my luck is a jerk.
Currently this powerful project is suddenly stuck 
Can't seem to serialize functions in all this muck

Read you can use resurrect-js to accomplish this.
I'm imagining this to be a pretty powerful behavior.
Do anyone now where I could gaze upon some working examples.
Thank YOU!!

**Comment by liabru** [comment]
Check out the source for [matter-tools Gui.js](https://github.com/liabru/matter-tools/blob/master/src/tools/Gui.js#L100-L154) which has this built in.
