### ISSUE TITLE
Body placement (position/rotation) by center of vertex bounds

### ISSUE THREAD

**Issue by EskelCz** [liabru/matter-js#186]
I think I've found a bug in compound body collisions.

Please take a look at this demo, how the moving body reacts to concave compounded shape collision:
http://eskel.cz/js/matter

I'm moving the body with force impulse but it's the same with pure position updates.

I hope the js file (http://eskel.cz/js/matter/js/debug.js) is readable, but here you can see the original coffee code just in case: http://eskel.cz/js/matter/js/debug.coffee.

So far I've found just one workaround, overwriting the force in each update, but it still makes pretty ugly bump even in one update. I'd rather solve the cause of this so I can use position based movement.

**Comment by liabru** [comment]
Looks like you're using a pretty old build, can you try the latest [master](https://github.com/liabru/matter-js/blob/master/build/matter.js)?

**Comment by EskelCz** [comment]
Oh, that was it. Sorry, not sure how that happened. Is this npm package up to date?
https://www.npmjs.com/package/matter-js

Maybe I just haven't updated my local packages in a long time. Thanks a lot for quick answer, case closed. :)

**Comment by EskelCz** [comment]
On a side note, it wasn't exactly easy to set up rendering in a custom loop to my own canvas (or offscreen three.js texture). For me anyway.

Only thing that works for me is running 'engine.render.controller.world engine' in the loop, which doesn't seem optimal.
Couldn't the render event be public? Or did I miss some interface?

**Comment by liabru** [comment]
The npm package isn't up to date yet, I'd advise just using a local copy for now.

As for rendering, I'm not sure exactly what you want. Why do you need to call `engine.render.controller.world(engine)` if you're doing your own rendering? Just do what ever you need in your own loop?

**Comment by EskelCz** [comment]
I'm using your renderer as a debug preview of 2d collisions in a 3d game, rendered with three.js. I like it more then using another module, like pixi.
Thankfully it's possible, just the method doesn't seem very intuitive that's all. I'd prefer the Render object to have a render method, or a public way of emitting the render event. But I guess you have your reasons.
Anyway, thank you very much for a great physics engine. I tried p2.js as well and concluded matter.js is better. :+1:

**Comment by liabru** [comment]
Ah well by default `engine.render.controller.world(engine)` is the same as `Render.world(engine)` if that helps.

You're right that the way the renderers works is not very intuitive, which is why I'm planning to fully decouple them in the near future. They were never originally intended to be more than my own simple debugging tools, so they were never really designed to be used by others. But since people like them, I'll work on making them easier to use :)

**Comment by EskelCz** [comment]
Oh my, I just figured out what was the problem. I could use some guidence.

The reason for the old build is that I made a fork to change how you place bodies. I completely forgot.
I have my game on a square grid and I needed my geometry to match those tiles. When you add bodies you make axis in the center of gravity, but I need them centered by vertex bounds.
Such as this: http://eskel.cz/js/matter2
Here I have all current geometry types on one tile space, with rotations around the bounds axis.

Somehow when I made this change I forgot to test the compound shapes for collisions. The center 'offset' seems to be doing the bouncing effect. I merged my changes into your latest master and it does the same thing.

Do you by chance have some idea how to make this work?
I tried the most straight forward way, making a new 'centre' method and applying it to the body parts before placing them into the scene.
https://github.com/BlackDice/matter-js/blob/c5eaa63a721610e4a8a62ad3b8b05279f659ab5c/src/geometry/Vertices.js#L99
https://github.com/BlackDice/matter-js/blob/c5eaa63a721610e4a8a62ad3b8b05279f659ab5c/src/factory/Bodies.js#L257

**Comment by EskelCz** [comment]
@liabru I guess this is a feature request of such a method of positioning. I may be able to implement it on my own if you can guide me a little.

**Comment by liabru** [comment]
What you need to do is translate the body by the vector like `Body.translate(body, Vector.sub(body.bounds.min, body.position))`.

Might be a useful feature to have in the engine, not sure how best to implement it though.

**Comment by EskelCz** [comment]
@liabru I wish it was that easy. If I just translate the body, the transform center (axis) is offset as well and 90 degree rotations will break the grid.
What I need is a method of repositioning the axis or placement of the body in a way that the axis gets created in the geometric middle of the body (average of bounds, instead of vertices).

I implemented the latter and for some reason it broke collisions on compound bodies. Regular bodies are working well. The implementation is above.

For the first aproach I'd need to know what exactly controls the origin of transforms. Can it be moved?

Thank you very much. I think this might be helpful in general for anyone developing games based on tile assets.

**Comment by EskelCz** [comment]
As an example, you can have tiles assets like these: http://i.imgur.com/u6w6L.png
Vou then create vector outline for each, that fits into the tile. Then you need to be able to import the vector shape into the engine and have the positions match the grid map.

The centered rotation axis allows you to use rotation and flip feature of the tiled map editor, so you can have fewer tiles and faster map creation.

**Comment by liabru** [comment]
> For the first aproach I'd need to know what exactly controls the origin of transforms. Can it be moved?

The origin is the center of mass. If you move the origin then the physics simulation will no longer be correct. Can't you just translate and rotate the bodies to the correct position after they are created?

**Comment by EskelCz** [comment]
Not really. I'm using the engine for collision detection, not physics in general. I'm calculating my own movement vectors and they are based on the imported grid data. So I need the bodies to have positions and transform origins in the middle of the tile. I guess I'll have to create some kind of a wrapper, or special class of "offset" objects to be positioned differently than circles and boxes.

I'd be ok with breaking physics if collision forces worked well. And they are, except the compound shapes. Maybe I can figure out some workaround in the creation code for those.

**Comment by liabru** [comment]
Ok well I don't think that this is particularly appropriate to implement directly in a physics engine unfortunately. It would make more sense to do this as part of a game engine built on top. So my suggestion still remains the same but I guess you could just fork.

**Comment by EskelCz** [comment]
Ok. I guess I need a "collision engine" not a physics engine then. Not sure if there is one.

**Comment by EskelCz** [comment]
I tried implementing your proposal, even solved the rotation with Vector.rotateAbout.
But the problem is deeper still. I can position the bodies into correct places, but I also have 3D models that need to be positioned on top of them. To fit they would have to be created with origins in the exact center of mass as well. Not practical at all.
Not sure how to do a 3D game (with concave polygon bodies) on top of matter-js then.

**Comment by liabru** [comment]
Have you tried just changing `body.position` and `body.positionPrev` after creation? This should move the centre of mass, so long as you don't also translate vertices.

**Comment by EskelCz** [comment]
Oh my god, that's it! *dances happily*
Thank you so much. I went through a lot of testing this whole week, trying to replicate the same thing in p2js and such. The problem was that I wasn't changing positionPrev, only position. That was the entire problem. :)
You're my hero.

**Comment by liabru** [comment]
Great, no problem!
