### ISSUE TITLE
Matter.Body.setStatic() - setting to false after already true removes body

### ISSUE THREAD

**Issue by dvulanov** [liabru/matter-js#187]
I would like to be able to toggle a body between static and non-static, but it looks like once a body is set to static un-setting it messes something up and the body disappears from the render view.

Should it be possible to use setStatic in this manner? I'm using latest build (2015-12-23).

Thanks!

Dan

**Comment by dvulanov** [comment]
Ok, looks like resetting the body's mass to something non-static (i.e. non-infinity) does the trick.  This allows me to use Matter.Body.setStatic() in a way where I can toggle a body's static property.

thanks,
Dan

**Comment by liabru** [comment]
It's a known limitation that you can't unset static once it's been set. The reason is that it requires certain properties to be set to Infinity (e.g. mass) which means the old value is lost.

A possible fix is to add some sort of property cache to bodies so they can be restored, but this is currently a low priority.

If you need this, you should be able to look at [Body.setStatic](https://github.com/liabru/matter-js/blob/master/src/body/Body.js#L229-L249) and do something similar for your own project though.

**Comment by dvulanov** [comment]
Perfect, will do.

**Comment by EzraLopez** [comment]
Was this ever solved?

**Comment by liabru** [comment]
Not implemented yet but in the meantime you can implement your own based on my previous comment, I'll look at this again soon.

**Comment by alecdwm** [comment]
@EzraLopez || anyone who comes across this in the future, here's a hint:
```javascript
function setStatic(body, static) {
    if (static) {
        Matter.Body.set(body, 'staticMassCache', body.mass)
        Matter.Body.set(body, 'staticInertiaCache', body.inertia)
        Matter.Body.setStatic(body, true)
    } else {
        Matter.Body.setStatic(body, false)
        Matter.Body.setMass(body, body.staticMassCache || 0)
        Matter.Body.setInertia(body, body.staticInertiaCache || 0)
    }
}
```

**Comment by gamingRocksters** [comment]
can someone help me to change isStatic:true; to isStatic: false on click of down arrow.
please help..

**Comment by zgrcnltnk** [comment]
> can someone help me to change isStatic:true; to isStatic: false on click of down arrow.
> please help..

you can use eventListener to change static status with Body.setStatic(obj.body, false/true);

**Comment by gamingRocksters** [comment]
thnks

**Comment by parthsharma365628** [comment]
> can someone help me to change isStatic:true; to isStatic: false on click of down arrow.
> please help..

me too

**Comment by liabru** [comment]
@parthsharma365628 did you try [Body.setStatic](https://brm.io/matter-js/docs/classes/Body.html#method_setStatic)?

**Comment by gamingRocksters** [comment]
Thanks...

**Comment by jivishghai1109** [comment]
how to collide two bodies one static one non static
