### ISSUE TITLE
stacking bricks

### ISSUE THREAD

**Issue by ajthinking** [liabru/matter-js#188]
I am stacking "bricks" in a matter.js model. The bricks are overlapping like a classic wall for stability. However I can't get the wall stable enough to remain standing.

![alt text](http://i.stack.imgur.com/Fljq1.gif "Logo Title Text 1")

I found the below properties of Body in the documentation (I have only added what I found relevant.)
```
// Brick properties (Body defaults)
options = { 
    isStatic: false,
    density: 0.001,
    slop: 0.05,
    restitution: 0,
    sleepThreshold: 60,
    friction: 0.1,
    frictionAir: 0.01      
};
```
I have no success in altering any of these parameters. I expected especially friction to prevent the wall from sliding apart, but no, not even when setting it to 1.

Here is a jsfiddle. Any ideas what im missing?
http://jsfiddle.net/1L0dek1t/1/

**Comment by liabru** [comment]
First use the master build:
https://github.com/liabru/matter-js/blob/master/build/matter.js

Which already improves it a lot. Then I'd suggest increasing iterations:

var engine = Engine.create(document.body, {
  positionIterations: 10,
  velocityIterations: 10
});

I think you should also add small bricks on the ends to ensure there's no overhang.
Even then I still think it may eventually collapse. You should also make the blocks larger (2x would be good) which will help reduce the error, you can then simply render them smaller.

If you enable sleeping this should prevent it collapsing, but sleeping has a few drawbacks in the current implementation, but it's worth a shot.
