### ISSUE TITLE
bounds issue

### ISSUE THREAD

**Issue by Ionito** [liabru/matter-js#189]
Hi liabru

Hope you are doing fine

I'am making my first steeps using matter.js
Could you please explain me why after a few clicks on the red button the cube goes out of the walls?
http://codepen.io/anon/pen/VepGQg
There is no logic at all....

Thanks in advance for your help
Regards
ioni

**Comment by liabru** [comment]
This is due to the force causing the blocks to move so fast that they miss collisions, this problem is covered in issue #5.

You should reduce the force and make the walls larger and this should stop the problem.
