### ISSUE TITLE
Any reason to invoke Common.isElement() twice?

### ISSUE THREAD

**Issue by seckwei** [liabru/matter-js#190]
Hi,

Just curious, in [Engine.js](https://github.com/liabru/matter-js/blob/master/src/core/Engine.js#L41-L43) instead of doing 
```javascript
Engine.create = function(element, options) {

        // options may be passed as the first (and only) argument
        options = Common.isElement(element) ? options : element;
        element = Common.isElement(element) ? element : null;
```
why not
```javascript
Engine.create = function(element, options) {

        // options may be passed as the first (and only) argument
       if(!Common.isElement(element)){
              options = element;
              element = null;
       }
```
I know `Common.isElement()` is not an expensive function to run and `Engine.create` is most likely to be called once, but is there a reason for writing it in such way? or am I missing something? :fearful:

**Comment by liabru** [comment]
No reason other than following the same conventions used in the rest of the codebase :) this will be deprecated soon anyway so closing, thanks.
