### ISSUE TITLE
attraction / repulsion force?

### ISSUE THREAD

**Issue by dvulanov** [liabru/matter-js#191]
Is it possible to have bodies attract and/or repulse each other?  Or have static bodies that exert forces? Something akin to simple planetary dynamics?

I googled around, looked through the api, couldn't find any mention of this type of feature for matter.js

**Comment by liabru** [comment]
You can just apply forces how ever you like inside the update event, for example:

http://brm.io/matter-js-demo-master/#timescale
https://github.com/liabru/matter-js/blob/master/examples/timescale.js#L37-L58
