### ISSUE TITLE
Demos don't work on local machine

### ISSUE THREAD

**Issue by WhiteHotLoveTiger** [liabru/matter-js#192]
After cloning the repository I tried running the demos locally. Neither the regular nor the mobile demo would run for me. I did notice on the "demo/mobile.html" page that it references "./js/lib/matter-dev.js" rather than "./js/lib/matter-0.8.0.js" which is actually in the directory. I tried updating this reference, but I still couldn't get the mobile demo to run. I'm serving it on my local machine via Apache.
I notice that the page does run fine at http://brm.io/matter-js/demo/mobile.html
What am I missing to get it to run locally?

**Comment by liabru** [comment]
To run the demos from source you'll need to build first, see CONTRIBUTING.md for instructions.

**Comment by WhiteHotLoveTiger** [comment]
haha, whoops, my mistake. Everything's working great now. Thanks.
