### ISSUE TITLE
[RenderPixi] Can't pass options for PIXI.WebGLRenderer

### ISSUE THREAD

**Issue by hideyukisaito** [liabru/matter-js#193]
In case of working with high density displays like retina, we have to pass the "resolution" (and optionally "autoResize") option to PIXI.WebGLRenderer. But it seems we don't have ways to pass it, or any other option values described in [PIXI's document](https://pixijs.github.io/docs/PIXI.WebGLRenderer.html). 

https://github.com/liabru/matter-js/blob/master/src/render/RenderPixi.js#L53-L58 

I think there should be all option parameters filled with default values and we should be able to overwrite them by passing a "options" argument for RenderPixi.create().

Thanks!

**Comment by liabru** [comment]
You can now pass `pixiOptions` in your `RenderPixi.create` options (you could also pass a `PIXI.WebGLRenderer` instance as the option as `renderer` instead).

**Comment by hideyukisaito** [comment]
@liabru Cool!! Thanks for the fix!
