### ISSUE TITLE
isFixed and delta not giving expected results

### ISSUE THREAD

**Issue by WhiteHotLoveTiger** [liabru/matter-js#197]
I'm playing around with the examples, trying to learn Matter.js better.

I added `engine.timing.isFixed = true;` and `engine.timing.delta = 1000 / 2;` to the slingshot example. I expected this to produce a deterministic simulation with a very slow frame rate (2 fps), but it just seems to run as normal. Have I done something wrong, or have I misunderstood these options?

https://gist.github.com/WhiteHotLoveTiger/397436fbc1ae0bf97e83

Sorry if this isn't the right place to ask this sort of thing.

**Comment by liabru** [comment]
These properties were moved to `Matter.Runner`, see the [docs](http://brm.io/matter-js/docs/classes/Runner.html#properties). Note that `Matter.Engine.run = Matter.Runner.run` which returns a `Matter.Runner` instance that you can use.

**Comment by WhiteHotLoveTiger** [comment]
Thanks! I'll give this a try soon.
