### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Elumina-Group-LW** [liabru/matter-js#198]
Your demo folder has it's index referencing non existent (missing from the repo) -- ( Examples.js and matter-dev.js )

**Comment by WhiteHotLoveTiger** [comment]
I had a similar problem the other day: #192 

The answer is to check out the [CONTRIBUTING file](https://github.com/liabru/matter-js/blob/master/CONTRIBUTING.md).

**Comment by liabru** [comment]
Yeah you need to build the project to run the demo from source. I guess should make this clearer though, or maybe remove the build step for examples somehow.
