### ISSUE TITLE
Getting NaN when following instructions for Node.js implementation

### ISSUE THREAD

**Issue by mrmckeb** [liabru/matter-js#200]
We've been trying to get this working server-side in Node.js, and for some reason movements are resulting in NaN for x/y positions. We used the code example provided here: https://github.com/liabru/matter-js/issues/101#issuecomment-116822596

CodePen example: http://codepen.io/anon/pen/dGKeJq

Sorry if this is just something silly we missed, but after a lot of fiddling, I can't work it out.

**Comment by CAOakleyII** [comment]
I am also receiving this same issue, it seems to only happen after the initial engine tick.

**Comment by liabru** [comment]
This is because `engine.timing.delta` is no longer defined, it was moved to `Matter.Runner`.
The solution here is to pass a defined value for delta e.g.:

     Matter.Engine.update(engine, 16);

See the docs for [Matter.Engine.update](http://brm.io/matter-js/docs/classes/Engine.html#method_update).

**Comment by mrmckeb** [comment]
Thanks @liabru, I'll get moving with this project again ;)

**Comment by Shadowstep33** [comment]
I am experiencing a similar issue. angle and some other angle related properties, as well as axes, all are plagued by NaN. I have at least narrowed down the problem to one of these lines of code:

```
						Body.setVelocity(buckets['walking'][b].body, {
							x: x_move,
							y: y_move
						});
						Body.setAngle(buckets['walking'][b].body, 0);
						Body.setAngularVelocity(buckets['walking'][b].body, 0);
						Body.setInertia(buckets['walking'][b].body, 0);
```

When I comment out setAngle, setAngularVelocity, and setInertia, i no longer get the NaN problem but the bodies do not move as I want them to. buckets.walking[b].body isStatic = false (when I set it to true, but leave all code intact no problem arises).

**Comment by liabru** [comment]
@Shadowstep33 is this on node or in the browser? Do all of those setters cause NaN or can you narrow it to one? Can you try debugging and stepping through?
