### ISSUE TITLE
How to make smoke particles?

### ISSUE THREAD

**Issue by vanuatu** [liabru/matter-js#201]
I'm creating a side-scrolling game using Matter.JS, in this game one of heros is made of fire, so he needs to get some smoke, but I dont know how to make particles floating in the air, how I can make a float body in Matter.JS?

I want something like this: https://www.youtube.com/watch?v=b-QhKcae-6E

Please see my codepen here: http://codepen.io/vanuatu/pen/VeQMpp

**Comment by liabru** [comment]
What you're looking for is a [particle system](https://en.wikipedia.org/wiki/Particle_system). There's nothing currently built in to the engine for this, it's more of something you'd find in a game engine so it's a bit out of scope.

You could build your own by to defining a particle object (position, velocity, lifetime etc) and then use the engine update event to update the particle positions, then render them to the same canvas as the physics objects.

**Comment by vanuatu** [comment]
thanks for the clear explanation, @liabru

**Comment by liabru** [comment]
No problem!

**Comment by ZachSaucier** [comment]
I created a fake smoke effect by using spheres and [a PNG](https://imgur.com/yWvwLrh) of something that resembles (black) smoke.
