### ISSUE TITLE
Installing from NPM breaks

### ISSUE THREAD

**Issue by msfeldstein** [liabru/matter-js#205]
if i install with `npm install --save matter-js` then try to `require('matter-js')` I get this error

```Cannot find module '../geometry/Vertices' from '/Users/michael/Source/MatterTest/node_modules/matter-js/build'```

Am I doing something wrong here?  Seems pretty straightforward

**Comment by scottglz** [comment]
I had the same issue. Matter-js's package.json declares build/matter.js as its main entry point, but that's a pre-built (browserified, I think) package, not a require-able module, so this happens. 

Work-around:

var matter = require('../matter-js/src/module/main.js');

**Comment by liabru** [comment]
Strange. I can't reproduce this issue using the instructions from @msfeldstein. Are you using 0.9.0 as the previous release had problems.

@scottglz The main file is indeed built by browserify but using the standalone mode which creates a UMD module, so it should work fine...

Either way, do you think I should change the package.json to reference `matter-js/src/module/main.js` instead?

**Comment by scottglz** [comment]
My error (and I'm guessing @msfeldstein's) happened when running browserify on my own application, which in turn required('matter.js'). I'm guessing what's going on is that if you're running a node app, require('matter.js') works fine with the standalone matter-js module, but if you're building your own browserified app, browserify's static analysis can't handle the (redefined) require statements in the standalone module. (There's some irony in there somewhere.)

So, yes, I think the package.json main reference should be changed. It'll make for more local file-system access for people running matter under node, but I don't imagine that should matter. I also think it's just cleaner. (If you disagree, you could leave the main reference the same and add a "browser" field to the package.js instead, that only browserify will pay attention to.)

**Comment by msfeldstein** [comment]
requiring src/module/main worked like a charm for me, and yes i think it should be the default in package.json, as is standard for npm modules for maximum compatibility.

**Comment by msfeldstein** [comment]
More local file-system access for people running it under node shouldn't be an issue, that's an optimization your build tools should make, not each library.

**Comment by liabru** [comment]
I've updated the main reference and I'll push a new release with it in soon. Thanks for the input guys.

**Comment by msfeldstein** [comment]
Thanks for the library.

**Comment by liabru** [comment]
I just pushed `0.9.1` can you try it out?

**Comment by msfeldstein** [comment]
Works great!
