### ISSUE TITLE
Removed bodies still collide

### ISSUE THREAD

**Issue by msfeldstein** [liabru/matter-js#206]
If I add a body to the world, then remove it, it disappears but still causes other objects to bounce around.  Here is a simplified test case that shows a ball falling and stopping once it hits the removed ghost object.'

```
var Matter = require('matter-js')
console.log(Matter)

var engine = Matter.Engine.create({
  render: {
    element: document.body,
    options: {
      width: window.innerWidth,
      height: window.innerHeight
    }
  }
})

var ghost = Matter.Bodies.rectangle(window.innerWidth / 2, window.innerHeight - 100, 110, 15, {isStatic: true})
var ball = Matter.Bodies.circle(window.innerWidth / 2, window.innerHeight - 300, 50)
Matter.World.add(engine.world, [ghost, ball]);
Matter.World.remove(engine.world, [ghost])
Matter.Engine.run(engine);
```

**Comment by liabru** [comment]
Couldn't reproduce this using your example and 0.9.0, what version are you using?

**Comment by msfeldstein** [comment]
Looks like it was an issue on 0.8, i just updated to 0.9 and it seems fine now.  Thanks!

**Comment by RobertHerhold** [comment]
@liabru This is still an issue (just ran into it). I will update with a Pen sometime
