### ISSUE TITLE
Bodies slow down after collisions

### ISSUE THREAD

**Issue by shakiba** [liabru/matter-js#21]
I have added this example to demos, the ball slows down after each collision even with friction=0 and restitution=1, is this an expected behavior?

``` javascript
      var ball = Bodies.circle(400, 300, 20, { frictionAir: 0, friction: 0, restitution: 1});
      World.add(_world, [ball]);
      var a = Math.random() * Math.PI * 2;
      Body.applyForce(ball, { x: 0, y: 0 }, {x: 0.2 * Math.cos(a), y: 0.2 * Math.sin(a)});
```

**Comment by beetrandahiya** [comment]
hey, i set inertia to infinity but still, its losing energy, i also being a physics student , dont have anything else other than friction due to normal force on contact , i turned friction and frictionAir both to 0, still, not the ideal outcome
