### ISSUE TITLE
Magnetism property for objects.

### ISSUE THREAD

**Issue by dlinx** [liabru/matter-js#212]
I would like to suggest a new feature. 
Can we add new object property which converts that object into a magnet. 
Creating magnetic objects having north and south pole exactly same properties which a original magnet has.

**Comment by liabru** [comment]
More generally these are known as attractors. My thoughts on this are as mentioned in #132:

> I'll consider merging this but what I'd really like here are generalized attractor objects, rather than just a special case. That said, this feels like scope creep to me - I'd prefer this to live in a game engine.

I'm currently investigating patterns for creating plugins for matter.js, which would make it easier for people to create extensions like this.

**Comment by liabru** [comment]
Just opened a thread on a possible [plugins approach](https://github.com/liabru/matter-js/issues/213) that may be useful here.

**Comment by liabru** [comment]
I've just updated the plugins approach thread, including an attractors plugin, see [this comment](https://github.com/liabru/matter-js/issues/213#issuecomment-244613052). This is not yet available in the master branch but it should be merged soon.

**Comment by liabru** [comment]
The plugin is now ready, check it out at [matter-attractors](https://github.com/liabru/matter-attractors).

**Comment by dlinx** [comment]
Awesome, Thanks
