### ISSUE TITLE
matter.js and p2.js

### ISSUE THREAD

**Issue by josephrocca** [liabru/matter-js#214]
Hello,

Has anyone done any investigation into how matter.js compares to p2.js? Specifically differences in their:
1. goals and motivations
2. feature set
3. performance

I love the look of both projects, and I'm just trying to get a sense for which one fits my particular use case. @liabru and @schteppe, your input would be super handy here :)

**Comment by ttencate** [comment]
Also interested in this. I searched around the web and all I can find is speculation.

**Comment by 20zinnm** [comment]
Interested too.

**Comment by crazyyi** [comment]
Many people are interested but no one is actually doing anything for it, including me...

**Comment by liabru** [comment]
Closing this due to age and also because it's pretty out of scope as an issue here.
