### ISSUE TITLE
Can't get a properly colored background with RenderPixi

### ISSUE THREAD

**Issue by RobertHerhold** [liabru/matter-js#215]
I'm trying to get the background to be basically anything other than black, but I can't manage to get it to work. [This is what I have so far.](http://codepen.io/anon/pen/PZroQR) Any ideas?

EDIT: [This](https://github.com/liabru/matter-js/wiki/Rendering) is what I'm looking at.

**Comment by stonebranch** [comment]
@RobertHerhold the wireframes property defaults to true, set `wireframes:true` in render options and your background color will appear. 
[Fork on your pen](http://codepen.io/anon/pen/dMYbqR)

**Comment by RobertHerhold** [comment]
@stonebranch Thanks :)

**Comment by liabru** [comment]
@stonebranch ah of course, thanks!
