### ISSUE TITLE
Matter.JS and Pixi looping nicely?

### ISSUE THREAD

**Issue by RobertHerhold** [liabru/matter-js#217]
So basically, I'm trying to let Matter handle pretty much everything as far as rendering bodies with Pixi. However, I also need to use just plain Pixi elements such as tiling sprites for the ground in my game. I am unable to do so in a way that isn't hacky and frankly doesn't work. [This is what I currently have.](http://codepen.io/RobertHerhold/pen/dMbBME?editors=0010) So the bodies are working just fine, but to make the tiling sprite work I need my `animate` function running (ticking from `requestAnimationFrame`). The tiling sprite, however, does not animate properly unless I use `Engine.update(engine, 1000 / 60)`. As I might imagine, using `Engine.run` concurrently with `Engine.update` has some pretty interesting effects, which you can see by the varying distances of the bunnies as they move left in my Pen. What is the proper way to do this?

EDIT: I have thought about making my own custom game loop, but I would rather not do this because I would have to store the Sprites linked to my Bodies and render them on each tick, etc. I'd rather let Matter do this for me.

**Comment by liabru** [comment]
Have you tried copying `RenderPixi` and then customizing it as you need? Or you could just render using your own loop, like in this [example](http://codepen.io/BakerCo/pen/ojKJJb). Maybe then you can implement what you need?

**Comment by RobertHerhold** [comment]
@liabru In the Pen you linked me, is there any way to disable Matter.js's rendering on the top and just keep the canvas rendered by Pixi?

**Comment by xAvarice** [comment]
Did you get this figured out?
