### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by liabru** [liabru/matter-js#22]
The project is still in an alpha state and the API has not yet solidified, so documentation is currently patchy as usage can change release to release. Some time is required to improve it before the first non-alpha release.

In the mean time, please use the following resources if you'd like to start using the engine despite the alpha status:

- [Examples on CodePen](http://codepen.io/collection/Fuagy/) show minimal but complete usage examples e.g. [Newton's Cradle](http://codepen.io/liabru/pen/abFml)
- [Demo.js](https://github.com/liabru/matter-js/blob/master/demo/js/Demo.js) contains the source for all of the [demos](http://brm.io/matter-js-demo)
- [API Docs](http://brm.io/matter-js-docs/), not complete yet but give a good impression of the architecture of the engine and the methods available

**Comment by joetsuihk** [comment]
I would kindly request demo/doc for manipulating body after added to world. Imagine case like using keyboard to move a body/car.

**Comment by liabru** [comment]
@joetsuihk 

If you clone the repo and use the edge build, there's two new manipulation demos that may be helpful:
https://github.com/liabru/matter-js/blob/master/demo/js/Demo.js#L218-L317

**Comment by joetsuihk** [comment]
Thanks a lot @liabru ! What I ultimately want to do is click on a body and manipulate that body, can you share some code to look for the body being clicked? I tried Query.ray but the collisions returned cannot apply Body.translate

**Comment by liabru** [comment]
@joetsuihk take a look at how it's done in [MouseConstraint](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js#L84-L98)

**Comment by liabru** [comment]
An updated version of the docs is now at http://brm.io/matter-js/docs/
