### ISSUE TITLE
Why does Engine.create take an HTML element? What is MatterJs?

### ISSUE THREAD

**Issue by DelvarWorld** [liabru/matter-js#226]
> "Matter.js is a 2D physics engine for the web"
> *- http://brm.io/matter-js/*

[But then](https://github.com/liabru/matter-js/wiki/Getting-started):

```js
// create a Matter.js engine
var engine = Engine.create(document.body);
```

Also [the documentation](http://brm.io/matter-js/docs/classes/Engine.html#method_create) says that an HTML element is a required parameter.

I'm confused here, why do I need to pass in an HTML element to use a physics engine? Is MatterJs a physics engine, or a rendering engine? Or a game engine? Or something else?

I want to use matterjs outside of drawing on a canvas but it doesn't look like I can because the renderer code looks intimately tied to the physics code?

What I'm doing now is using an entirely independent game loop, I'm querying my physics engine for body positions. I'm looking into matterjs but it doesn't look like I can do that?

The scope of this library is further confusing by the fact that the core of matterjs [seems to know about other renderers, like Pixi](http://brm.io/matter-js/docs/classes/RenderPixi.html)?

**Comment by liabru** [comment]
The docs are wrong here, sorry about that! An element is not required nor is any type of renderer. It's just a helper for creating a debug renderer. I'm working on deprecating this and making the separation clearer. The scope of this project is purely a physics engine.

The included renderers are for debugging and example purposes and are entirely optional. Same goes for the runner, you don't have to use it either. Both are well separated in the codebase, but there are some helpers in the engine constructor. But these will be removed in coming versions.

> What I'm doing now is using an entirely independent game loop, I'm querying my physics engine for body positions. I'm looking into matterjs but it doesn't look like I can do that?

Why not?

**Comment by liabru** [comment]
The `0.10.0` release decouples rendering and deprecates the old approach. I've updated the [docs](http://brm.io/matter-js/docs/index.html), the [demo](https://github.com/liabru/matter-js/blob/master/demo/js/Demo.js#L68-L75) and the [wiki](https://github.com/liabru/matter-js/wiki) with new examples. Hopefully this makes things clearer?

**Comment by mbchang** [comment]
I have installed the 0.10.0 version, and I am using matter-js purely as a physics engine. I have a version of your demo code without the renderer: 

```
var Matter = require('matter-js')

// module aliases
var Engine = Matter.Engine,
    World = Matter.World,
    Bodies = Matter.Bodies;

// create an engine
var engine = Engine.create();

// create two boxes and a ground
var boxA = Bodies.rectangle(400, 200, 80, 80);
var boxB = Bodies.rectangle(450, 50, 80, 80);
var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

// add all of the bodies to the world
World.add(engine.world, [boxA, boxB, ground]);

// run the engine
Engine.run(engine);
``` 
that I have saved in a file ```hello.js```. I run it with ```node hello.js```.

Perhaps I'm missing something, but I notice that the the engine is still not completely decoupled from the renderer because I get this error in ```Runner.js``` when I run: 

```
            runner.frameRequestId = _requestAnimationFrame(render); 
                                    ^
TypeError: undefined is not a function
```

Specifically, this is in the ```run``` function in ```Runner.js```:
```
    Runner.run = function(runner, engine) {
        // create runner if engine is first argument
        if (typeof runner.positionIterations !== 'undefined') {
            engine = runner;
            runner = Runner.create();
        }

        (function render(time){
            runner.frameRequestId = _requestAnimationFrame(render);  // Dependency on renderer

            if (time && runner.enabled) {
                Runner.tick(runner, engine, time);
            }
        })();

        return runner;
    };
```
It looks like ```runner.frameRequestId``` requires a renderer to be present. Is there a design choice behind this, and is there a way to make the runner completely decoupled from the renderer? Thanks!

**Comment by liabru** [comment]
Hopefully my last post helped you resolve your issue, so closing this. Feel free to reply if you need more help.
