### ISSUE TITLE
Matter.js doesn't update body properties if Pixi.js renderer is used

### ISSUE THREAD

**Issue by ser10us** [liabru/matter-js#227]
I want to update certain body properties if user clicks on it, e.g. `body.render.lineWidth = 5;` It works just fine if the default canvas renderer is used. If I switch to Pixi.js renderer it stops working and doesn't seem to reflect any properties at all. I also tried with the `Matter.Body.set` function but with no luck either. Properties are set actually to a body but the body keeps showing the initial style which was provided at the construction time.

What is the proper way to set those properties?

SO question: http://stackoverflow.com/questions/36236288/matter-js-doesnt-update-body-properties-if-pixi-js-renderer-is-used

**Comment by liabru** [comment]
RenderPixi creates primitives only once when the body first gets rendered and this gets cached.

To remove it from the cache, you should be able to do something like:

    engine.render.primitives['b-' + body.id] = null;

Then it should get created again.

**Comment by ser10us** [comment]
It kind of works, but the problem is that the old state of the body is not getting erased or refreshed.
Here is the example:
![matter js](https://cloud.githubusercontent.com/assets/9109205/14587931/8d0fd224-04bc-11e6-9658-2a1d05265c36.jpg)

**Comment by liabru** [comment]
Ah I think you will also need to do this first:

engine.render.container.removeChild(engine.render.primitives['b-' + body.id]);
engine.render.primitives['b-' + body.id] = null;

**Comment by ser10us** [comment]
It did the trick, thanks!

**Comment by liabru** [comment]
Reopening as it will be useful to fix this :)

**Comment by liabru** [comment]
Closing this as `Matter.RenderPixi` has been deprecated.
