### ISSUE TITLE
How do you resize a body?

### ISSUE THREAD

**Issue by WAYOFFprod** [liabru/matter-js#228]
I did not find a way to resize the body simply. I see there is a setPosition but no setSize for the body.

I guess it would be possible to recreate the body but I'd rather avoid that. What is the best way to resize a body on the fly?

**Comment by liabru** [comment]
Did you try [Body.scale](http://brm.io/matter-js/docs/classes/Body.html#method_scale)?

**Comment by Deadalusmask** [comment]
Is there a way to scale body based on initial size instead of current size? It will be convenient in my case.

**Comment by jakub-gawryl** [comment]
I have issue with scale: when: `isStatic = true ` then mass and inertia becomes `Infinity`. I'm new to matter and not sure if this is expected? If so, how would I resize body in different way? (I need to have static circle body, and changing it's position. After object reach screen edge, i'd like to resize it. Now i need to re-create it each time).
