### ISSUE TITLE
drawing a line into a world

### ISSUE THREAD

**Issue by millerthegorilla** [liabru/matter-js#233]
Hi, I have a vine that animates its growth using stroke() on a canvas.  I tried to transfer this to a matter body but I couldn't find an easy way to do it.
The closest that I came was to make a circle and add it to a composite.  However, when the composite becomes large, the method Matter.Composite.Add(composite, body) has such a high overhead that it progressively slows down the animation.
Is there a better way to achieve the progressive drawing of a linear object?
If there isn't currently. could I make a pull request and attempt to write a method?

**Comment by RobertHerhold** [comment]
Why does this need to be done with matter-js? It seems to me that that would be more of a rendering concern rather than a physics engine concern, unless the vine needs to interact with other bodies in the world

**Comment by millerthegorilla** [comment]
You've answered your own question.  I want the vine to be springy and move with a wind, with leaves/petal descending.  Its relatively trivial to draw the vine, but finding some way of incorporating it into matter as an object is more difficult.  I've tired body.setvertices, Bodies.fromVertices, and composite.add.  The last of these with an update loop adding each increment as a circle to a composite that is already added to the world works fine until about 500 circles have been added at which point the size of the composite passed to Composite.Add(composite, body) is so large that the whole animation slows down.  My idea was to finish that composite and then use Composites.chain to chain all the composites together, which I suspect would also be too computationally expensive.  I wondered if there was an easy solution, perhaps waiting until the delta becomes too large and then making a new composite and then adding these composites to the total vine composite.
I've also considered using Vertices.fromPath and its just occurred to me now to use the before and after add events of composite somehow.
The reason that I might make a pull request is to try and create in matter a set of api calls that are identical to the canvas api, and that serve this function without causing a problem with animation speed.  It would be nice to be able to switch between apis with ease, and also I have found it difficult to draw a curving line with any width that isn't pixellated.  Calls like bezierCurveTo or simply just lineTo, moveTo and stroke() would be great to have, just so that existing code can be transferred.  For instance, I thought that I might be able to draw the vine, as I am doing, storing the vertices and then adding it to the canvas, and disappearing the initial drawing.

**Comment by millerthegorilla** [comment]
*Doh* - my bad.  I think I've understood now.  The structures that Matter.js 'draws' are wireframes to take sprites, hence the difficulty currently of creating concave hulls.  I think what I will do is make a chained bridge and then create the sprite texture to add to it, by drawing a rectangle onto a canvas and then creating  a sprite from that.  
Alternatively if it is possible to create a convex hull from a set of vertices that will approximate a line of a certain width drawing as curves, that will then be able to interact with other objects,  this would make things a lot easier.  I'm guessing that vertices need to be oriented in a certain fashion, so I am perhaps going to draw the line, recording the vertices as I go, then pass those vertices to Vertices.hull. and create a body from those vertices to which I will then attach the sprite of the line gained from Image.createBitmap which works in firefox, and newer chrome, potentially opera but not IE/Edge where I will just have the vine as a static image as it is at the moment.  I'm thinking out loud, but does that make sense?

**Comment by liabru** [comment]
I think this is a bit out of the scope of a single question... unless you have an example (jsfiddle or animation) of what you're looking for it will be hard for me to suggest something. All I can say is 500 bodies sounds like a lot, especially if they are all colliding, so you may want to rethink your approach. Either that or go for a constraint / point mass based engine rather than a rigid body engine? Something like [this](http://subprotocol.com/system/tree.html) maybe?

**Comment by millerthegorilla** [comment]
www.fontevraud.co.uk has an old flash animation I did.  I like the verlet animation (esp the spider web!), but wanted to integrate the line drawing functionality into a sort of visual animation drawing studio project that I am doing that will have object collisions and physics so I wanted to try and keep to using matter as I'm getting more interested in the algorithms underlying animated approximations of natural phenonena (I'm definitely going to read that paper on verlet integration), and I wanted to have leaves with gravity falling from the vine.
By the way, do you know of a good javascript engine for inverse kinematics?  Do you think matterjs could be extended to provide the types of constraints necessary to perform IK?  I'm guessing so, but I haven't yet done any reading.... cheers!

**Comment by millerthegorilla** [comment]
Thanks for your help
