### ISSUE TITLE
Please Publish

### ISSUE THREAD

**Issue by MarkHerhold** [liabru/matter-js#236]
There are fixes on master that would be great to have as a patch release.

Until then... Release process
![](http://www.relatably.com/m/img/still-waiting-meme-computer/404710d1403818426-slate-digital-vmr-almost-here-channel-strip-your-dreams-skeletonmeme.jpg)

Thanks :smile:

**Comment by liabru** [comment]
Sorry for the delay guys, I've been meaning to merge in a few more features for this release but keep getting knocked back. I'll save them for the next one I guess!

**Comment by liabru** [comment]
Managed to sort the issue, check the new release!
