### ISSUE TITLE
constraint.angularStiffness

### ISSUE THREAD

**Issue by millerthegorilla** [liabru/matter-js#239]
Hi, I'm just looking through the matter source code at where constraints are [created](https://github.com/liabru/matter-js/blob/master/build/matter.js#L3489)
  and I wondered if you could explain how angularStiffness is implemented with regards to its effect on the body/ies in question?
I see that angularStiffness is related to [torque](https://github.com/liabru/matter-js/blob/master/build/matter.js#L3623).
The reason that I ask is that I am interested if there is anyway to constrain the movement of a body about a point in terms of its angular rotation about that point, such that I can create a simple kinematic chain.  If angularStiffness allows some maximum angle of rotation to be applied per body then all well and good, but if not then I thought that I might extend the constraint object with angular rotation limits.

**Comment by millerthegorilla** [comment]
I'm guessing that angularStiffness is a measure of the degree to which the body springs back to its initial position when chained/constrained to another body.  If angularStiffness is 1 then torque = 0, and there is no angular movement.
angularStiffness is not currently documented in the [api reference](http://brm.io/matter-js/docs/classes/Constraint.html), although Constraint.stiffness is which I see is a measure of the bodies return to its resting point along the axis of the constraint.  Have you considered adding IK to matterjs?  There aren't currently any good javascript libraries that I know of that implement it, although there are some demos of using phaser:
http://codepen.io/codevinsky/pen/QbojGG
http://codepen.io/codevinsky/pen/BNboWj

I am implementing a vine which I hope to animate using matterjs.  I put another question earlier in which  I asked about drawing lines to the canvas - I have uploaded the vine as a work in progress to www.jerlesey.co.uk   -  although I like the verlet library, I wanted to interact with other objects and want to learn to use the matterjs library properly - its tres cool!   After the vine is drawn with the flowers, the flowers disappear (as I haven't added them as matter objects yet) and the vine is shown in segments.  Although I am currently editing to hide the segments by making them overlap, it is these that I want to animate, probably immediately by adding constraints to the four corners and treating each main vine side as in the matterjs bridge example, and then constraining the branches at either end before bombarding the whole thing with random invisible objects to simulate wind.  I see in  matterjs (on the todo list) is the idea of [implementing breakable constraints](https://github.com/liabru/matter-js/blob/master/build/matter.js#L3429).  I'd love to use this for dropping flowers/petals or branches on a windy day etc.
I was wondering if, adding the code to draw a line to matterjs would be cool?  It is the implementation of a polyline, such that if one draws a line on the canvas as a set of vertices using context.moveTo/lineTo, that line can be turned into a segmented line with a specified width.  It doesn't have to have segments - I have implemented it as a non-segmented convex hull of a line.
The alternative is that I know you have considered a plugin system.  Perhaps I could add it via that.  I'd also like to implement ellipses, providing an api in Bodies.ellipse for instance.

Ps, the vine at jerlesey.co.uk is very definitely a work in progress and hasn't been optimised yet.

**Comment by liabru** [comment]
The `constraint.angularStiffness` just allows you to adjust how quickly rotation is corrected, similar to how `constraint.stiffness` allows you to adjust how quickly distance is corrected.

Currently angular constraints are not implemented, but there is an existing issue #71 for discussion on them.
