### ISSUE TITLE
Problems adding texture

### ISSUE THREAD

**Issue by pvieira-label** [liabru/matter-js#246]
Hi! I'm trying to add a texture to my experiment but my rectangle keeps the original stroke.

Is the code correct?

```
var letter = Bodies.rectangle(150, 150, 98, 90, {
			render: {				
				sprite: {
					texture: 'blue.png'
				}
			}
		});

World.add(game_world, letter);

```
I looked into the slingshot and the beachballs examples and copied the code from there. Do I need to add any option to the Engine? Thanks in advance.

**Comment by liabru** [comment]
Did you set `render.wireframes = false`?
