### ISSUE TITLE
Collision Sphere

### ISSUE THREAD

**Issue by mjparinas** [liabru/matter-js#247]
Hello,

Is there plans to create functionality similar to the CollisionSphere in Unity?
http://docs.unity3d.com/ScriptReference/Physics.OverlapSphere.html

The reason I ask is how would you recommend making something like a stargate using Matter.js? Where the player and stargate are both "Bodies.circle". I'd like to detect when there is a collision however I don't want them to actually physically collide and bounce off each other. I would just like to know when they overlap so then I can teleport the player.

Thanks

**Comment by liabru** [comment]
I think what you want is to set `body.isSensor = true` ([docs](http://brm.io/matter-js/docs/classes/Body.html#property_isSensor)) and then use the engine `collisionStart` ([docs](http://brm.io/matter-js/docs/classes/Engine.html#event_collisionStart)) event to find the collision you are interested in. Check out the [sensors example](https://github.com/liabru/matter-js/blob/master/examples/sensors.js).

**Comment by liabru** [comment]
Hopefully my last post helped you resolve your issue, so closing this. Feel free to reply if you need more help.
