### ISSUE TITLE
Running a headless simulation as fast as possible?

### ISSUE THREAD

**Issue by TobLoef** [liabru/matter-js#249]
For a project I'm working on I would like to do some "off-camera", or headless, physics simulations, as fast as possible of course. The simulation loop wouldn't be tied to any graphics update and should go as fast as the CPU would allow. How can I do this?

Thank you.

**Comment by liabru** [comment]
Check out the wiki page on [running](https://github.com/liabru/matter-js/wiki/Running), but basically just do `Engine.update(engine, timestep)` as fast as you can.

**Comment by TobLoef** [comment]
Great, thanks!
