### ISSUE TITLE
List of all collisions that occured

### ISSUE THREAD

**Issue by oli414** [liabru/matter-js#250]
Hi folks,

In order to check whether or not my player collided with another body I need a list of all the collisions that occurred and see if the player's body is somewhere in there. In the p2.js physics engine, all the collisions that happened in the last update are stored in a variable, however, when I look at the source of Matter.js it looks like the collisions are simply thrown away after they've been resolved.

I was wondering if there was a way to get all the collisions that occurred in the last update, otherwise, wouldn't it be nice to store them like p2.js does?
Or am I going about this in the wrong way?

At the moment I'm thinking about adding a line in the Engine.update which stores the collision variable that is being used within that scope so that I can access it from outside.

**Comment by plurry** [comment]
`Engine` reports collisions in the `pairs` property of the `collisionStart`, `collisionActive`, and `collisionEnd` events.

http://brm.io/matter-js/docs/classes/Engine.html

**Comment by oli414** [comment]
@plurry Thanks, that's what I needed
