### ISSUE TITLE
Offset option for render

### ISSUE THREAD

**Issue by xoorath** [liabru/matter-js#251]
Hey, 

I'm working on a game where my origin is in the center of my canvas, making some object positions negative when they're in view.

This makes using the render module as a debug drawing a bit tricky, because I can't seem to tell it to render starting at the same position as my game world. The render view will have my world centered on the top left (0, 0) where as my game view renders where I expect (centered on 0, 0).

I'd like it if I could have an option along these lines:

```
var render = Matter.Render.create({
    element: document.getElementById('physicsPreview'),
    engine: engine
    options: {
        width: 1920,
        height: 1080,
        x: -960,
        y: -540
    }
});
```

If there is an option along these lines, then I must have missed it. I was following this doc to reference options that are available: https://github.com/liabru/matter-js/wiki/Rendering

**Comment by liabru** [comment]
I think what you may be looking for is [render.bounds](http://brm.io/matter-js/docs/classes/Render.html#property_bounds)?

    var render = Matter.Render.create({
        element: document.getElementById('physicsPreview'),
        engine: engine,
        bounds: {
           min: { 
               x: -960, 
               y: -540 
           },
           max: { 
               x: -960 + 1920, 
               y: -540 + 1080 
           }
        },
        options: {
            hasBounds: true,
            width: 1920,
            height: 1080
        }
    });

**Comment by xoorath** [comment]
Worked like a charm, thanks.
