### ISSUE TITLE
Physics Engine Dependency on Renderer

### ISSUE THREAD

**Issue by mbchang** [liabru/matter-js#252]
From #226, it looks like version 0.10.0 should decouple the physics engine from the rendering component, but unless I'm mistaken there still seems to be a rendering dependency in the ```Runner.js``` file. 

I have installed the 0.10.0 version, and I am using matter-js purely as a physics engine. I have a version of your demo code without the renderer:
```
var Matter = require('matter-js')

// module aliases
var Engine = Matter.Engine,
    World = Matter.World,
    Bodies = Matter.Bodies;

// create an engine
var engine = Engine.create();

// create two boxes and a ground
var boxA = Bodies.rectangle(400, 200, 80, 80);
var boxB = Bodies.rectangle(450, 50, 80, 80);
var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

// add all of the bodies to the world
World.add(engine.world, [boxA, boxB, ground]);

// run the engine
Engine.run(engine);
```
that I have saved in a file ```hello.js```. I run it with ```node hello.js```.

Perhaps I'm missing something, but I notice that the the engine is still not completely decoupled from the renderer because I get this error in ```Runner.js``` when I run:
```
            runner.frameRequestId = _requestAnimationFrame(render); 
                                    ^
TypeError: undefined is not a function
```
Specifically, this is in the run function in Runner.js:
```
    Runner.run = function(runner, engine) {
        // create runner if engine is first argument
        if (typeof runner.positionIterations !== 'undefined') {
            engine = runner;
            runner = Runner.create();
        }

        (function render(time){
            runner.frameRequestId = _requestAnimationFrame(render);  // Dependency on renderer

            if (time && runner.enabled) {
                Runner.tick(runner, engine, time);
            }
        })();

        return runner;
    };
```
It looks like ```runner.frameRequestId``` requires a renderer to be present. Is there a design choice behind this, and is there a way to make the runner completely decoupled from the renderer? At the moment to get around the issue I'm just commenting out the line 
``` runner.frameRequestId = _requestAnimationFrame(render); ``` 

Thanks!

**Comment by liabru** [comment]
Actually this is because `Matter.Runner` is designed for use in the browser where the `window.requestAnimationFrame` function is available. Though, it's supposed to fallback to using a timeout for environments that don't have it. I will have a look and see why it isn't doing it.

Despite this though, in node it's better to handle updating the engine manually since you wouldn't normally want to run it in real-time anyway, see #249.

**Comment by liabru** [comment]
The polyfill wasn't being applied correctly, so that should be fixed on the next release. Thanks.
