### ISSUE TITLE
Unclear examples

### ISSUE THREAD

**Issue by KokoDoko** [liabru/matter-js#253]
I am having some trouble navigating the documentation and finding examples of proper usage of MatterJS. In the examples folder, there is this [code for creating an engine](https://github.com/liabru/matter-js/blob/master/examples/engine.js):

```
    var Engine = Matter.Engine;
    Example.engine = function(demo) {
    }
```

But, it's not clear what "Example" is, nor what the 'demo' parameter should contain.
This makes it hard to just copy>paste some basic code to learn the fundamentals.

Perhaps a simple explanation of "Example" and "demo" would suffice to solve this issue!

**Comment by liabru** [comment]
It's true that this could be made clearer so I will see what I can do. For now, see the [wiki](https://github.com/liabru/matter-js/wiki) for minimal usage examples.

**Comment by liabru** [comment]
All [examples](https://github.com/liabru/matter-js/tree/master/examples) are now fully self contained!

**Comment by liabru** [comment]
All [examples](https://github.com/liabru/matter-js/tree/master/examples) are now fully self contained!
