### ISSUE TITLE
Can I make objects respond to gravity as they are being dragged?

### ISSUE THREAD

**Issue by treforcoster** [liabru/matter-js#254]
Loving this am only a day or so into it but liking what I see.

I've had a quick look through and I can't seem to see a way to do this but it could be there glaring me in the face. Currently all demos I've looked through when ever an object is interacted with it doesn't respond to gravity. ie. if i pick something up by the corner I would expect it to rotate around to hang with the heaviest point below. 

Have i missed something simple?

**Comment by liabru** [comment]
The main reason is that it is disabled is because it's not very stable. This should be resolved when pin constraints are implemented, but for now try this:

    mouseConstraint.constraint.length = 20;
    mouseConstraint.constraint.stiffness = 0.08;
    mouseConstraint.constraint.angularStiffness = 0;

It's not that great, so I'll look into sorting out pin constraints.

**Comment by treforcoster** [comment]
Thank you

**Comment by liabru** [comment]
This is solved as of `0.13.0`, you can see how it's done in this [example](https://github.com/liabru/matter-js/blob/master/examples/constraints.js#L146-L156).
