### ISSUE TITLE
Serialize and transfer/set world state

### ISSUE THREAD

**Issue by wyaeiga** [liabru/matter-js#255]
I'm wondering if there is a way to serialize and transfer or set the state of the world. I know the [features](https://github.com/liabru/matter-js#features) mentioned serialization, but I couldn't find anything mentioning how to do that or how to then set the world state to be something else. 

For instance, say I want to be able to reset the world state to be however it was N loops ago, is this something doable? I'm asking mostly since I'm trying to develop an app where there's a server that will maintain the "master" state of the world, then all the clients can stay in sync with the "master" state of the world that exists on the server.

Thanks!

**Comment by liabru** [comment]
Check out the source for [matter-tools Gui.js](https://github.com/liabru/matter-tools/blob/master/src/tools/Gui.js#L116-L172) which has this built in, it's using [resurrect-js](https://github.com/skeeto/resurrect-js) to serialise the world.

> For instance, say I want to be able to reset the world state to be however it was N loops ago, is this something doable?

Should be possible using the above I think. Also check out [TestDemo.js](https://github.com/liabru/matter-js/blob/master/test/node/TestDemo.js) which also uses serialisation.

**Comment by liabru** [comment]
Hopefully my last post helped you resolve your issue, so closing this. Feel free to reply if you need more help.

**Comment by eirikb** [comment]
Here is a quick and dirty way to clone bodies:
```JavaScript
const { Body } = Matter;
const body = ...

// Remove specific keywords. Either circular or not wanted
const bodyAsJson = JSON.stringify(body, (key, value) =>
  (key === 'parent' || key === 'parts' || key === 'body') ? undefined : value);

const newBody = Body.create(JSON.parse(bodyAsJson));
```
It's not perfect, and it only copies bodies, but it's simple, and doesn't require any library.
Demo: https://jsfiddle.net/msud7kxc/

**Comment by liabru** [comment]
Nice! Circular values are usually the main issue with cloning, but skipping them like this can do the trick sometimes.

**Comment by eirikb** [comment]
@liabru I noticed (at least in my test) that `parts` didn't work with _json-stringify-safe_ because it would remove the circularity, but leave an empty array, which didn't seem to work (had to remove the property).
