### ISSUE TITLE
Circles sliding along (sticking to) edges of larger polygon even though restitution is set to 1

### ISSUE THREAD

**Issue by M-FF-M** [liabru/matter-js#259]
I'm new to Matter.js but as I tried to create a billiard game the issue replicated in the following JSFiddle [(https://jsfiddle.net/wL5y9sux/)](https://jsfiddle.net/wL5y9sux/) came to my attention.

The circle bounces back correctly from almost all edges of the polygon except for one (even though it also bounces back correctly from a parallel edge of an rectangle).

**Comment by liabru** [comment]
Thanks for the test case, this may be related to #63.

**Comment by liabru** [comment]
I discovered the issue here, your vertices are in anti-clockwise order where instead they must be made clock-wise. You can reverse them by hand or just use the function `Matter.Vertices.clockwiseSort`. I'll make this clearer in the documentation. Thanks.

**Comment by M-FF-M** [comment]
Thanks for resolving this issue for me! I believe I actually read that the vertices must be in clockwise order anywhere in the documentation but by the time I started programming I had forgotten about it.
