### ISSUE TITLE
Examples Broken on GH pages - Concave SVG Paths, Concave Terrain

### ISSUE THREAD

**Issue by zischwartz** [liabru/matter-js#260]
[E.g.](http://brm.io/matter-js/demo/#svg) Master works fine.

```
matter-dev.js:6702 Uncaught TypeError: Cannot read property 'numberOfItems' of undefined
```

**Comment by liabru** [comment]
Ah this is because the polyfill for pathSegList is missing from the live demos (but should be fixed in the repo already). I'll update the live demos soon.

**Comment by eliteproxy7** [comment]
have you updated this?

**Comment by liabru** [comment]
This has now been fixed on the live demos.
