### ISSUE TITLE
Cannot read property 'mouse' of undefined

### ISSUE THREAD

**Issue by romualdo97** [liabru/matter-js#261]
`engine.input.mouse.button`

there's no property input in engine instance i'm using matter 0.10

**Comment by liabru** [comment]
Is the error coming from in matter.js or one of the examples? Or is it your own code?

**Comment by romualdo97** [comment]
is from a codepen example, in your example works but when i paste it in local doesnot exists input object

**Comment by jacprada** [comment]
I had a similar issue. Double check that the example you are referring to is actually based on Matter 0.10.0 and not a previous version. In my case using the 0.9.3 version solved it.

**Comment by liabru** [comment]
The codepen examples are pretty out of date, sorry! I need to update them. 

For now please refer to the [examples](https://github.com/liabru/matter-js/tree/master/examples) in the repo which includes all of them. I'd suggest this over using old versions!

**Comment by liabru** [comment]
I've added a task for [updating the codepen examples](https://github.com/liabru/matter-js/issues/265). As mentioned, always refer to the [examples](https://github.com/liabru/matter-js/tree/master/examples) in this repo as they are always up to date, thanks.
