### ISSUE TITLE
Svg.pathToVertices breaking in chrome

### ISSUE THREAD

**Issue by nclevine** [liabru/matter-js#262]
calling `Matter.Svg.pathToVertices` works fine in mobile safari, but in desktop Chrome it returns the error `Uncaught TypeError: Cannot read property 'numberOfItems' of undefined`

I haven't tested in all browsers. I'm calling the function using an svg `path` element and an integer for `sampleLength` as per the docs

**Comment by liabru** [comment]
You need [this polyfill](https://github.com/jarek-foksa/path-data-polyfill.js).

**Comment by janverhulst** [comment]
Hi @liabru Awesome work on the library.
I'm having the exact same problem as described above, using the polyfill. Both in safari and chrome, latest. Is this still supposed to be working?

**Comment by marffinn** [comment]
So I want my SVG to load into scene. What do I do  ?

**Comment by Roar1827** [comment]
@janverhulst @marffinn - did you end up getting this to work?

**Comment by johnparrott** [comment]
Looked at the svg example below in chrome and there are no svg's loading.
http://brm.io/matter-js/demo/#svg

Working on a project now using svg's and it loads fine in both Firefox and Safari when using localhost but in Chrome "Cannot read property 'numberOfItems' of undefined".

**Comment by liabru** [comment]
Seems that the polyfill is currently broken in recent versions of Chrome, see my comment in this [thread](https://github.com/liabru/matter-js/issues/548#issuecomment-356563543).
