### ISSUE TITLE
Svg.pathToVertices element as part of compound body

### ISSUE THREAD

**Issue by jacprada** [liabru/matter-js#263]
Is it possible to add an element generated through Svg.pathToVertices to a compound body as a _part_?

I have been trying this for a while now, but the element always appears very distorted, not looking like the original SVG at all. I have no problem adding parts that refer to regular elements (Bodies.circle, for instance). If I add the SVG body to the _world_ as a single element it shows up fine, it just renders wrongly as part of a compound body.

My purpose is to have a circle body containing an SVG-originated element that includes holes. The reason is that this specific body gets stuck on static elements because of its holes, whereas I would like it to behave "normally". I have been trying to adjust this behaviour for a while now without success and I thought that a compound body formed by the SVG-originated element with a regular circle body around it would be a decent solution. Any help would be greatly appreciated, thank you!

**Comment by liabru** [comment]
Have you tried using [Body.setParts](http://brm.io/matter-js/docs/classes/Body.html#method_setParts)? You could probably also do `Body.create({ parts: [..] ...})` too. See if that helps!
