### ISSUE TITLE
Collision and damage&destroy

### ISSUE THREAD

**Issue by pstefanowski** [liabru/matter-js#264]
I haven't found in examples and in documentation damage&destroy issue..or somethink I missed? Are matter.js support/not support/will support this as box2d?

**Comment by liabru** [comment]
Not sure exactly what you mean, but you can track collisions using events, see the [events](https://github.com/liabru/matter-js/blob/master/examples/events.js) example.

**Comment by liabru** [comment]
Hopefully that answered your question so I'll close this, but feel free to comment if you still need more info.
