### ISSUE TITLE
How to move a bodie from one position to another without using a mouse. [Question]

### ISSUE THREAD

**Issue by jdrofl** [liabru/matter-js#266]
Having trouble with this, an example would be very helpful. Wondering if its possible to just move say a circle object along a path without dragging it with the mouse. 

Thanks

**Comment by liabru** [comment]
Check out the [body manipulation demo](http://brm.io/matter-js/demo/#manipulation) and the [code](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js).

**Comment by jdrofl** [comment]
yea thanks man, i have been looking through the code for that demo. But i am a bit confused, so the movement im trying to replicate in the controlled movement of bodyA (the square that is moving up and down) i just dont understand how its staying on that path. Is there anyway i could get a little more explaination?

Thanks so much, really i appreciate it!

**Comment by liabru** [comment]
Hopefully that answered your question so I'll close this, but feel free to comment if you still need more info.
