### ISSUE TITLE
Drag elasticity

### ISSUE THREAD

**Issue by XaviGIT** [liabru/matter-js#268]
The drag action has this elastic animation by default. I searched but couldn't find a way to disable or at least minimize the effect. Is there an option for that or a place where I can change it in the code? Thanks.

**Comment by liabru** [comment]
Try something like this:

    var mouseConstraint = MouseConstraint.create(engine);
    mouseConstraint.constraint.stiffness = 1;
    mouseConstraint.constraint.length = 0.1;

**Comment by liabru** [comment]
Hopefully that answered your question so I'll close this, but feel free to comment if you still need more info.
