### ISSUE TITLE
Matter js body rotating

### ISSUE THREAD

**Issue by sowmyavetrikannan** [liabru/matter-js#269]
Hi,

I am having two chains with the following constraints. I am positioning a body in that constraint.

chainLeftEnd = Constraint.create({
            stiffness: .9,
            length: 0.1,
            render: {
                lineWidth: 0,
                visible: false,
            },
            pointA: {
                x: 0,
                y: 0
            },
            pointB: {
                x: connectingPoint,
                y: 0
            },
            bodyB: chainLeft.bodies[89],
            bodyA: symbol.bodies[0],
        });

chainRightEnd = Constraint.create({
            stiffness: .9,
            render: {
                lineWidth: 0,
                visible: false,
            },
            length: 0.1,
            pointA: {
                x: 0,
                y: 0
            },
            pointB: {
                x: connectingPoint,
                y: 0
            },
            bodyA: chainRight.bodies[89],
            bodyB: symbol.bodies[0],
        });

if chainLeftEnd.pointA.y = 0 and chainRightEnd.pointB.y = 0, the symbol is positioning properly ( as in beforeChanging.png).

if chainLeftEnd.pointA.y = -23 and chainRightEnd.pointB.y = -23, the symbol rotates slowly to some angle. Is there any way to stop that rotation. (as in afterChanging.png)

Thanks.

![afterchanging](https://cloud.githubusercontent.com/assets/16798538/16266143/f7121e26-38a0-11e6-982d-3b61bcfa8ee9.png)
![beforechanging](https://cloud.githubusercontent.com/assets/16798538/16266142/f71122b4-38a0-11e6-8260-4db93b860adb.png)

)

**Comment by liabru** [comment]
Does it help to set `body.inertia = Infinity` on the body that's rotating? It might be able to stop any rotation.  Otherwise it's a tricky one because it's down to how constraints get resolved. I'm not sure I can help much without being able to debug this directly, could you send a link privately?

**Comment by sowmyavetrikannan** [comment]
Yeah it is working. Thanks.:-)
