### ISSUE TITLE
Start drag and enddrag not working

### ISSUE THREAD

**Issue by sowmyavetrikannan** [liabru/matter-js#270]
Hi,

When  drag a body startdrag and enddrag are not fired. Is there any working examples for startdrag and end drag and how to use that? I am using the version 0.8.0

**Comment by liabru** [comment]
Those events are not available in 0.8.0, I suggest upgrading as that version is very outdated.

**Comment by sowmyavetrikannan** [comment]
Which version i can you for drag??

**Comment by sowmyavetrikannan** [comment]
Is there any examples of start drag and end drag?
I am having a code for start and end drag event as follows.

 var engine = Engine.create({
        render: {
            element: document.getElementById("module"),
            options: {
                background: "rgba(0, 0, 0, 0)",
                showAngleIndicator: false,
                wireframes: false,
                visible: false,
                lineWidth: 0,
                width: canvasWidth,
                height: canvasHeight,
                hasBounds: true,
                showShadows: false,
            }
        }

    });
    engine.enableSleeping = false;
    engine.positionIterations = 1;
    engine.velocityIterations = 1;
    // gravity direction
    engine.world.gravity.x = 0;
    engine.world.gravity.y = 0.5;

    // add a mouse controlled constraint
    var mouseConstraint = MouseConstraint.create(engine, {
        constraint: {
            stiffness: 0.01,
            render: {
                visible: false,
                lineWidth: 0
            }
        }
    });

    //Adding engine and mouseconstraint to world
    World.add(engine.world, mouseConstraint);
//startdrag event
 Events.on(engine, 'startdrag', function (event) {
        console.log('start drag');
    });
//end drag event
     Events.on(engine, 'enddrag', function (event) {
        console.log('end drag');
    });

**Comment by liabru** [comment]
The events are fired on the `mouseConstraint` not the `engine`, see the [docs](http://brm.io/matter-js/docs/classes/MouseConstraint.html#events).

**Comment by sowmyavetrikannan** [comment]
Yeah it is working. Thank you.. But if i use this version some of the functionalities are not working... such as when i am trying to change the texture of a body the page becomes unresponsive
