### ISSUE TITLE
Matter js body rotating

### ISSUE THREAD

**Issue by sowmyavetrikannan** [liabru/matter-js#271]
Hi,

I am having two chains with the following constraints. I am positioning a body in that constraint.

chainLeftEnd = Constraint.create({
stiffness: .9,
length: 0.1,
render: {
lineWidth: 0,
visible: false,
},
pointA: {
x: 0,
y: 0
},
pointB: {
x: connectingPoint,
y: 0
},
bodyB: chainLeft.bodies[89],
bodyA: symbol.bodies[0],
});

chainRightEnd = Constraint.create({
stiffness: .9,
render: {
lineWidth: 0,
visible: false,
},
length: 0.1,
pointA: {
x: 0,
y: 0
},
pointB: {
x: connectingPoint,
y: 0
},
bodyA: chainRight.bodies[89],
bodyB: symbol.bodies[0],
});

if chainLeftEnd.pointA.y = 0 and chainRightEnd.pointB.y = 0, the symbol is positioning properly.

if chainLeftEnd.pointA.y = -23 and chainRightEnd.pointB.y = -23, the symbol rotates slowly to some angle. Is there any way to stop that rotation.

Thanks.

**Comment by liabru** [comment]
Please do not post duplicates. I will look at your other thread when I have time, thanks.
