### ISSUE TITLE
getting started with examples

### ISSUE THREAD

**Issue by mironcaius** [liabru/matter-js#273]
Hello,
First I want to say that you did good work with this engine. BUT..
1. If i download the project and try to load index.html from the demo folder.. matter-dev.js is missing, so I guess you are missing an extra step in the install
2. Even if the examples work with the demo.js or examples.js.. it is very difficult to make them work without using these 2 js because the examples rely on code from demo or example which is wrong.
views.js
`var engine = demo.engine,
            world = engine.world,
            sceneEvents = demo.sceneEvents,
            mouseConstraint = demo.mouseConstraint;

.....
var viewportCentre = {
            x: demo.render.options.width \* 0.5,
            y: demo.render.options.height \* 0.5
        };
`
Can you create a simple example that allows us to test the js code from the examples folder ?

**Comment by liabru** [comment]
See #253 and #198, I think these cover both your points, if so please +1 them.
