### ISSUE TITLE
[Question] Saving frames as .png

### ISSUE THREAD

**Issue by mbchang** [liabru/matter-js#274]
Does Renderer have support to save canvas as .png frames with every iteration of Engine.update()? Help much appreciated!

**Comment by liabru** [comment]
Not built in, but you can use [render events](http://brm.io/matter-js/docs/classes/Render.html#events) and then[capture the canvas](https://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf).

**Comment by liabru** [comment]
Hopefully that answered your question so I'll close this, but feel free to comment if you still need more info.
