### ISSUE TITLE
Non-rigid pivot constraint

### ISSUE THREAD

**Issue by KrisKlip** [liabru/matter-js#275]
Hi, I am working with objects that are constrained to and rotate around specific pivot points in the world. 
`Constraint.create({pointA: { x: 400, y: 400 },
      bodyB: circleBody, 
      length: 0.01,
      stiffness: 1
    })`
I seem to be having an issue where when there is a collision or stress on the object that the constraint between the object and pivot point stretches and acts like a strong spring. What I am going for is a completely rigid pivot constraint that keeps the constrained object at the same point regardless of collisions or pulling stress.  Is there a way to get rid of all of the elastic properties of the constraint?
I currently have stiffness = 1 and length = 0.01 for all constraints.

Thanks for an amazing engine!

**Comment by liabru** [comment]
See issues #139 and #71, I think these are what you are asking for? If so please +1 them. These are high priority so I will be working on them when I've finished #213 and #5.

**Comment by liabru** [comment]
Closed as #139 covers this.
