### ISSUE TITLE
sprite.texture not working on safari

### ISSUE THREAD

**Issue by sowmyavetrikannan** [liabru/matter-js#276]
Hi,
i am having two chains and a symbol to make a chain design as in the screenshot attached. i am using the following constraints to position the symbol on the chain. when i am changing the texture of a symbol, it is coming properly on chrome and firefox. But in mac safari, the texture is not coming properly. here i have attached the screen shots. Kindly let me know what i am doing wrong. Thanks in advance. 

chainLeftStart = Constraint.create({
            length: 0.1,
            render: {
                lineWidth: 0,
                visible: false,
            },
            bodyB: chainLeft.bodies[0],
            //Setting left chain X and Y positions 
            pointA: {
                x: canvasLeftChainX,
                y: -150
            },
            stiffness: .9
        });
        chainRightStart = Constraint.create({
            stiffness: .9,
            length: 0.1,
            render: {
                lineWidth: 0,
                visible: false,
            },
            bodyB: chainRight.bodies[0],
            //Setting Right chain X and Y positions
            pointA: {
                x: canvasRightChainX,
                y: -150
            },
        });
        chainLeftEnd = Constraint.create({
            stiffness: .9,
            length: 0.1,
            render: {
                lineWidth: 0,
                visible: false,
            },
            pointA: {
                x: 0,
                y: anchorPosition
            },
            pointB: {
                x: connectingPoint,
                y: 0
            },
            bodyB: chainLeft.bodies[chainLeftLength - 1],
            //// CENTER SYMBOL
            bodyA: symbol.bodies[0],
        });
        chainRightEnd = Constraint.create({
            stiffness: .9,
            render: {
                lineWidth: 0,
                visible: false,
            },
            length: 0.1,
            pointA: {
                x: 0,
                y: 0
            },
            pointB: {
                x: connectingPoint,
                y: anchorPosition
            },
            bodyA: chainRight.bodies[chainRightLength - 1], //// CENTER SYMBOL
            bodyB: symbol.bodies[0],
        });
![correctposition](https://cloud.githubusercontent.com/assets/16798538/16875333/8a80f25e-4abc-11e6-90b8-bd9cb557fe97.png)
![wrongposition](https://cloud.githubusercontent.com/assets/16798538/16875334/8a82a112-4abc-11e6-80a8-253a46505f91.PNG)

**Comment by liabru** [comment]
Sprites appear to be working fine for me in the [sprites demo](http://brm.io/matter-js/demo/#sprites) on mac safari. Your screenshot seems to show safari on an ipad though? So I also tested it on an ipad and it also seems to work. Check the console for errors?

**Comment by sowmyavetrikannan** [comment]
Hi,

Yeah it is because of the resolution and size of the image. It is working now. Thank you.
