### ISSUE TITLE
Very erratic bouncing

### ISSUE THREAD

**Issue by Woolfe** [liabru/matter-js#277]
I'm getting to grips with matterjs and I have made a very simple program where pressing any key applies some force to a circle. However, I'm getting very erratic bouncing. Try my code for yourself and you should see what I mean. Any ideas as to why I'm getting this?

Attached the code as a text file as it wouldn't let me upload a html file (new to github, not really sure what I'm doing...)

[erraticBouncing.txt](https://github.com/liabru/matter-js/files/368172/erraticBouncing.txt)

Version used: 0.10.0

**Comment by liabru** [comment]
Can you try set it up on [jsfiddle](https://jsfiddle.net/)?

**Comment by Woolfe** [comment]
https://jsfiddle.net/5qre6a9f/

**Comment by liabru** [comment]
Thanks for the demo, it does look strange. There may be an issue here I will need to investigate.

**Comment by Woolfe** [comment]
I fixed this by adding inertia:Infinity to the circle because I think it was bouncing strangely as a result of spin.

**Comment by liabru** [comment]
Ah yes of course, you can see this if you set `render.options.showAngleIndicator = true`. Thanks for clearing that up.
