### ISSUE TITLE
Change rectangle body to circle

### ISSUE THREAD

**Issue by sowmyavetrikannan** [liabru/matter-js#278]
HI,
I am having a chain with rectangle bodies. i am having 90 bodies in that chain. I have to change a single body of that chain to circle. Is there any way to do this? Thanks in advance.

**Comment by liabru** [comment]
Remove the constraints from the old body and attach them to the new body should work.

**Comment by sowmyavetrikannan** [comment]
I am having a chain as follows.

chain = Composites.stack(xPosition, yPosition, 90, Rows, columnGap, rowGap, function (x, y, column, row) {
            return Bodies.rectangle(x, y, 1, 1, {
                groupId: groupId,
                restitution: restitution,
                frictionAir: airfriction,
                friction: friction,
                frictionStatic : frictionStatic,
                density: density,
                render: {
                    lineWidth: 0,
                    sprite: {
                        texture: chainImg,
                        xScale: 0.3,
                        yScale: 0.3
                    }
                }
            });
        });


Composites.chain(chain, xOffsetA, yOffsetA, xOffsetB, yOffsetB, {
            length: 0.1,
            render: {
                lineWidth: 0,
                visible: false,
            },
        });

I have to change the chain's 30th body to circle from rectangle.

**Comment by liabru** [comment]
Do `var chain = Composites.chain(...)`. Then you can get the 30th body like so `var body = chain.bodies[29]`, then get the 29th constraint in the chain like this `var constraint = composite.constraints[28]` and then do `Composite.remove(chain, body)`, then add the rectangle body and then set `constraint.bodyB = rectangle`.
