### ISSUE TITLE
[Question] Apply Constant force

### ISSUE THREAD

**Issue by tevch** [liabru/matter-js#279]
I know how to apply force, but looks like it applies once, losing momentum with time

what i want to ask is - how to apply(introduce) constant force, like gravity. for instance - lift, or thrust, or drag of flying body.

Thanks

**Comment by liabru** [comment]
You should use an [engine event](http://brm.io/matter-js/docs/classes/Engine.html#events) to apply it on every update.

**Comment by liabru** [comment]
Hopefully that answered your question so I'll close this, but feel free to comment if you still need more info.

**Comment by courtneyvigo** [comment]
I have a similar question where i would like to add gravity once an animated object reaches the center of the screen. Is this possible?

**Comment by liabru** [comment]
Sure you can use events for this, check the distance of `body.position` to the target point, when it gets lower than a threshold set a flag and then add forces.

**Comment by courtneyvigo** [comment]
Thank you! Ill be trying this today :)

**Comment by courtneyvigo** [comment]
I am trying to do this:

var shapeA = Bodies.rectangle(200, 00, 25, 25, {
	//restitution: how bouncy an object is
    restitution : .7,
    render: {
        sprite: {
        	texture: './img/purple.png'
        }
    }
    //if statement: if body is between 134 and 318
    if (Body.position >= 134 && <= 318) {
    	console.log("should run");
    }
});

**Comment by courtneyvigo** [comment]
I think I might be confused as to how to check the position of the body (no _if_ statements) and how to apply the gravity force once it is in the ideal position. 

goal: 

[example.zip](https://github.com/liabru/matter-js/files/622787/example.zip)

**Comment by beetrandahiya** [comment]
Hey, I have a question, can u please just take a second and tell me how to use the engine event to apply constant force, for instance say , I want to apply force on a particle in electric field, so, How do I apply the force on that particle.
Thanks

**Comment by bouraqadi** [comment]
```
Matter.Events.on(engine, 'beforeUpdate', function(event) {
//Apply force
});
```
This event is sent on every iteration of the simulation loop. 
More at: https://brm.io/matter-js/docs/classes/Engine.html#events

**Comment by VinamraGoyal29** [comment]
How to applyForce on an circular object

**Comment by bouraqadi** [comment]
https://brm.io/matter-js/docs/classes/Body.html#method_applyForce

**Comment by davidreis97** [comment]
I feel like this is a bit weird. Why do I have to iterate and set force in all my physics entities with forces applied to them before an engine update? I feel like body.force shouldn't be reset to (0,0) after a physics step.

**Comment by liabru** [comment]
@davidreis97 there's a plugin that makes things easier check out [matter-attractors](https://github.com/liabru/matter-attractors)
