### ISSUE TITLE
How to move camera to position

### ISSUE THREAD

**Issue by liam-b** [liabru/matter-js#281]
So I'm working on a game where I need the camera to follow a character and from looking around in the demos I can't find any way to do it. I looked at the [views](http://brm.io/matter-js/demo/#views) example but Its very unclear how the camera is actually moving. Please help!

**Comment by liabru** [comment]
Take a look at this part of the code for the [views example](https://github.com/liabru/matter-js/blob/master/examples/views.js#L96-L126). Note that this is being updated inside an [engine event](https://github.com/liabru/matter-js/blob/master/examples/views.js#L58). You need to make sure you also set `render.options.hasBounds = true`.

**Comment by liabru** [comment]
Hopefully that answered your question so I'll close this, but feel free to comment if you still need more info.

**Comment by beetrandahiya** [comment]
Hey liabru , its about the camera, is there a way we can click and drag the view ?

**Comment by liabru** [comment]
@beetrandahiya check out the [views](https://brm.io/matter-js/demo/#views) example which should get you started, also see the function [Render.lookAt](https://brm.io/matter-js/docs/classes/Render.html#method_lookAt).
