### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by nolakat** [liabru/matter-js#282]
I've tried both downloading the zip file and cloning the release into GitHub. Whenever I try to run the demo I receive the following errors in the console:

File Not Found - js/build/matter-dev.js
File Not Found -  demo/js/Examples.js

I tried fixing the paths but it doesn't seem to solve the issue.

**Comment by liabru** [comment]
Yeah you need to build the project to run the demo from source, see #198.

**Comment by nolakat** [comment]
Got it - Thanks!
