### ISSUE TITLE
One-sided platforms. Best way to implement?

### ISSUE THREAD

**Issue by redsparkzone** [liabru/matter-js#284]
One-sided platforms are special types of bodies that collide with dynamic bodies depending on relative velocity / movement direction of the latter.

As a simplified special case, one can imagine a static rectangle which collides with dynamic circle only if the Y velocity of the latter is < 0, i.e. it's falling. But if its Y velocity is > 0 (i.e. it's jumping) then collision doesn't happen.

What is the best way to implement such behavior?

**Comment by redsparkzone** [comment]
My current solution is switching a dynamic body's collision mask depending on it's Y velocity, essentially making it either skip all platforms during collision detection stage or not. Not sure if there is any more elegant solution to this.

**Comment by liabru** [comment]
There's nothing built in for this, what you described is what I'd suggest, does it work well?

**Comment by redsparkzone** [comment]
Yep, works pretty much as expected, provided all platforms are oкiented the same way (which is always the case anyways). Still need to test some fringe cases, like when dynamic body's velocity / collision mask switches just right when it passes through the platform.
