### ISSUE TITLE
Best way to clamp velocity / implement max speed?

### ISSUE THREAD

**Issue by ChubbRck** [liabru/matter-js#285]
Hi there,

Couldn't find a body property for max speed or any examples where velocity was clamped. Is the 'best' way to accomplish this just iterating through all bodies per frame and clamping velocity manually? Thanks for any guidance you can provide -

**Comment by liabru** [comment]
Nothing built in for this I'm afraid, as you said just use an engine event and then clamp the velocity of the body every update. This sounds like a neat idea for a plugin though (see #213).

**Comment by ChubbRck** [comment]
Thanks for your thoughts on this -- it would indeed be a good idea for a plugin. One thing I noticed using body.setVelocity is that you seem to have to define a both an x and y value. Would it make more sense to be able to set velocities for just one dimension and leave the other component of the velocity unchanged? (for instance, in my use case, I am just trying to clamp both the x and y values individually and don't really care about the overall magnitude of the velocity)

**Comment by liabru** [comment]
They should be set together, if you want to change just one component then:

```js
Body.setVelocity(body, {
  x: 10,
  y: body.velocity.y
});
```
