### ISSUE TITLE
poly-decomp API has changed

### ISSUE THREAD

**Issue by fzembow** [liabru/matter-js#287]
Looks like poly-decomp API changed slightly in the newest version

Trying to instantiate a Polygon body from concave vertices results in an error: `decomp.Polygon is not a constructor`

As a workaround it's possible to use the old version: https://github.com/schteppe/poly-decomp.js/commit/4558762effada60404c10c46d1d995c9512d87f5

**Comment by liabru** [comment]
Thanks for the heads up!
