### ISSUE TITLE
Styles of Demos and Examples

### ISSUE THREAD

**Issue by trebor** [liabru/matter-js#289]
as a now heavy user of D3, one HUGE leg up for me was its style of examples.  they are complete and self contained.  thus i can get one, already working set of html/js files and be on my way.

sadly this isn't true with matter-js.  the result is a significant speed bump exactly at the moment when i'd rather be executing and learning.  i see a lovely set of examples.  but because of the way they are structured, it takes thinking and understanding the system to isolate them into usable code.  i know it is easy for [YOU](https://en.wikipedia.org/wiki/Curse_of_knowledge) to do this task, as you already understand how things wire together, but for a new user it's tough.

**Comment by liabru** [comment]
I understand that this can be tricky and it's a known issue that I need to improve (see #253). I'll be making this one my next priority.

In the meantime I'd suggest reading [Getting Started](https://github.com/liabru/matter-js/wiki/Getting-started) and then looking at the [examples on codepen](http://codepen.io/collection/Fuagy/6/) which are fully self contained.

**Comment by trebor** [comment]
i'd not see the codepen stuff that looks super helpful.  i'll start there.  thanks!

**Comment by liabru** [comment]
All [examples](https://github.com/liabru/matter-js/tree/master/examples) are now fully self contained!
