### ISSUE TITLE
poly-decomp got new version (node)

### ISSUE THREAD

**Issue by Cr4xy** [liabru/matter-js#292]
Hello, I wanted to make my own vertices, but it didn't work.

I found out that the poly-decomp version has already been updated to 0.2.1 while the `Bodies.fromVertices` function still uses a code that works for version 0.1.0 of poly-decomp.

Also there should be a check if there is a window object. http://brm.io/matter-js/docs/files/src_factory_Bodies.js.html#l216

Thanks alot!

**Comment by liabru** [comment]
Closing as duplicate of #287, thanks.
