### ISSUE TITLE
Rendering Characters.

### ISSUE THREAD

**Issue by voodoo2345** [liabru/matter-js#293]
I tried finding the solution on my own, but couldn't really, how do I create characters ? Like say 'A' 'B'  instead of squares or may be have texts written in squares. Please guide.

**Comment by liam-b** [comment]
What do you mean by characters? Like text on the screen?

**Comment by voodoo2345** [comment]
Yes, exactly. I want to display texts instead of rigid bodies, or if possible , a rigid body with a letter in it, say a square containing letter A. It can be done with images, but I was thinking if I could do it using matter, by drawing the letter on the rigid body.

**Comment by voodoo2345** [comment]
I think I wasn't looking hard enough, found some inspiration on matter's page. Thanks.

**Comment by liam-b** [comment]
No problem, not that I did much :D
