### ISSUE TITLE
Set position origin to the left top of an object.

### ISSUE THREAD

**Issue by christianmalek** [liabru/matter-js#294]
Hi,

How am I able to change the position's origin of a body? And how can I change the position?

I tried to access `body.position` but unfortunately this doesn't change the rendering.

**Comment by christianmalek** [comment]
After a few hours of searching I found the http://brm.io/matter-js/docs/classes/Body.html#method_setPosition method.

**Comment by liabru** [comment]
Yeah to move the body use `Body.setPosition` or `Body.translate`. Changing `body.position` directly should move the origin (centre of mass).
