### ISSUE TITLE
Adding an angular force to circles

### ISSUE THREAD

**Issue by christianmalek** [liabru/matter-js#295]
Hey,

How can i add an angular force to a body like a circle?
I just found the Body.setAngularVelocity method. But this overrides the velocity. I just want to add an angular force.

**Comment by landgreen** [comment]
.torque

**Comment by christianmalek** [comment]
@landgreen Thanks! `body.torque` did the trick.

**Comment by liabru** [comment]
@landgreen exactly, thanks for helping. A `Body.applyTorque` function might be a nice addition though.
