### ISSUE TITLE
Demo folder of release 0.10.0 incomplete

### ISSUE THREAD

**Issue by yafp** [liabru/matter-js#296]
Please correct me if i am wrong, but it seems like the demo folder of the latest release (0.10.0) is incomplete.

I noticed that at least the following files are missing:

- demo/js/Examples.js
- demo/js/lib/decomp.js
- demo/js/lib/pixi.js
- demo/css/style.css

I was able to fetch them manually via the demo-instance at:  http://brm.io/matter-js/demo/
But even with those files the demo is not working.

- demo/js/lib/pathseg.js

seems to miss as well - in both places - release and demo installation

After adding the files mentioned above and running the demo (index.html) i get the following error: 

```
Matter.js: Engine.create: engine.render is deprecated (see docs)
matter.js (line 4356)
too much recursion
matter.js (line 4111, col 16)
```

Is that a known issue - am i just doing it wrong? Any help is appreciated

**Comment by yafp** [comment]
Just realizing this might be related to #273 and #282 and #198 and #253

**Comment by liabru** [comment]
Exactly, you need to build the project first to get the demos to work.
