### ISSUE TITLE
Vertices.centre failing on exact rectangles

### ISSUE THREAD

**Issue by Woolfe** [liabru/matter-js#299]
`var vertices = [{ x: 100, y: 250 }, { x: 400, y: 250 }, { x: 100, y: 200 }, {x : 400, y : 200}];
alert(Matter.Vertices.centre(vertices).x + " , " + Matter.Vertices.centre(vertices).y);`

The above returns x as NaN and y as -Infinity.

`var vertices = [{ x: 100, y: 250 }, { x: 400, y: 250 }, { x: 100, y: 200 }, {x : 401, y : 201}];
alert(Matter.Vertices.centre(vertices).x + " , " + Matter.Vertices.centre(vertices).y);`

The above returns coordinates as expected, though. I also think this is causing problems when creating exact rectangles via Matter.Body.create

**Comment by Woolfe** [comment]
@liabru just a follow-up, did you ever get a chance to look at this?

**Comment by liabru** [comment]
Hey, sorry this one got a bit lost. The reason is that vertices must always be in clockwise order. 
Try this:

```js
var vertices = Matter.Vertices.clockwiseSort([{ x: 100, y: 250 }, { x: 400, y: 250 }, { x: 100, y: 200 }, {x : 400, y : 200}]);
console.log(Matter.Vertices.centre(vertices));
```

Guess this needs to be made clear in the docs!

**Comment by Woolfe** [comment]
@liabru Yep, that worked a charm. Thanks!
