### ISSUE TITLE
Options parameter is badly documented

### ISSUE THREAD

**Issue by TiagoMarinho** [liabru/matter-js#304]
While this physics engine has the best documentation for javascript I've ever seen, almost every function takes an `options` parameter that can take a lot of arguments, but there's almost no information about them in the docs.

See the `Matter.Render` class for reference. It's `.create()` constructor has an `options` parameter that can take several arguments:

```
this._matterRender = Matter.Render.create({
    element: document.body,
    engine: this._matterEngine,
    options: {
        width: innerWidth,
        height: innerHeight,
        pixelRatio: 1,
        background: 'transparent',
        wireframeBackground: '#222',
        hasBounds: false,
        enabled: true,
        wireframes: false,
        showSleeping: true,
        showDebug: false,
        showBroadphase: false,
        showBounds: false,
        showVelocity: false,
        showCollisions: true,
        showSeparations: false,
        showAxes: false,
        showPositions: false,
        showAngleIndicator: true,
        showIds: false,
        showShadows: false,
        showVertexNumbers: false,
        showConvexHulls: false,
        showInternalEdges: false,
        showMousePosition: false
    }
})
```

But in the docs it's not possible to find pretty much any of this stuff. It reads:

>  See the properties section below for detailed information on what you can pass via the options object.

And at the `properties` section it's difficult to tell what can be passed as an option and it's missing like 90% of the arguments above.

Obviously this is low-priority. Bugs should have precedence here.

**Comment by liabru** [comment]
You're totally right, this is something to be improved. It's a big task I've been holding off on for a while because since the options relate directly to class properties, they naturally change often and there will be a large amount of repetition in the docs.

So I was looking for a way to automate this, possibly by adding some helpers directly into the documentation builder, but since you say this tends to be a lower priority to invest that amount of effort. Help here would be appreciated!

**Comment by TiagoMarinho** [comment]
@liabru I really appreciate the work you're doing here. I'll be creating more issues than helping you out mostly because math scares me and I'm not that of an experienced developer.

I've just noticed a problem with restitution so I'm apologizing for creating too many issues in such short period of time (3 issues in about a week).

**Comment by vivasvan1** [comment]
I am just checking if there are any updates on this topic??

**Comment by liabru** [comment]
I think most properties should be covered by now and the docs have much improved since, so closing this one.
