### ISSUE TITLE
how can i make my image to adapt the shape ? thank you for answer~~

### ISSUE THREAD

**Issue by bobhfut** [liabru/matter-js#306]

**Comment by liabru** [comment]
Can you explain a bit more?

Do you mean like the [sprites](http://brm.io/matter-js/demo/#sprites) demo?

**Comment by bobhfut** [comment]
Yes , after i set my image i found that the image is larger than shape , can i adjust the image size without change the image it self .

like:
World.add(world, Bodies.circle(100, 100, 50, {
    render: {
        strokeStyle: '#ffffff'
        sprite: '../xxx.png'
    },
    restitution: 0.5
}));
but the image is larger than the circle

**Comment by bobhfut** [comment]
I have find that in api ,thank you for answer~~
