### ISSUE TITLE
How to cancel a collision

### ISSUE THREAD

**Issue by edmlin** [liabru/matter-js#307]
Hi,
First of all, thanks for the great work!
This is a question rather than an issue. In my test, I want to move a body with the mouse by changing the body's position in the mousemove event. When I move the body and it touches another body, I want it to stop instead of pushing the other body and bouncing back. It's like in a pool game, when I'm moving the white ball, I don't want it to bounce other balls. After I stop moving it, I can apply a force to it and it can bounce other balls. Is it possible to cancel the collision in the collisionStart event or I should do it in a different way?
Thanks.

**Comment by liabru** [comment]
Try listen for `collisionStart` event on the engine, then find the `pair` for the collision with the bodies you're interested in (from the event payload), then set `pair.isActive = false`. Hopefully that should stop that collision being resolved.

Also take a look at body [sensors](http://brm.io/matter-js/docs/classes/Body.html#property_isSensor) and [collision filters](http://brm.io/matter-js/docs/classes/Body.html#property_collisionFilter) ([demo](http://brm.io/matter-js/demo/#collisionFiltering)) they may be helpful to you too.
