### ISSUE TITLE
Can one change variables mid-simulation?

### ISSUE THREAD

**Issue by Krimik** [liabru/matter-js#310]
How would I go if I want to change the Velocity of an object every X seconds of the simulation? Something like this:

```
...
    var circleA = Bodies.circle(400, 400, 20);
    circleA.frictionAir = 0;
    engine.world.gravity.y = 0.

    World.add(engine.world, [circleA, circleB]);
    Engine.run(engine);
    Render.run(render);

    for (x = -1; x < 1; x++); {
        Matter.Body.setVelocity(circleA, { x: 1, y: 0 });
    }
```

I want to be able to change Velocity or any other property like frictionAir while simulation is running, but so far only the last change affects the simulation and I have no control over it afterwards.

**Comment by liabru** [comment]
You need to set the velocity on every engine update, which you can do by using engine events e.g.

    Events.on(engine, 'beforeUpdate', function() {
        Matter.Body.setVelocity(circleA, { x: 1, y: 0 });
    });

See the [events demo](http://brm.io/matter-js/demo/#events) and [code](https://github.com/liabru/matter-js/blob/master/examples/events.js) and [docs](http://brm.io/matter-js/docs/classes/Engine.html#events).
