### ISSUE TITLE
Check if world is sleeping

### ISSUE THREAD

**Issue by codeclown** [liabru/matter-js#313]
First of all, simply amazing work on the library and maintainment, bravo!

Question: is there a built-in method/event to detect when the world is still/sleeping, as in there is no movement on any body? I'm aware it can be detected for bodies individually.

**Comment by liabru** [comment]
Nothing built in for this, I'd suggest something like:

```js
let bodies = Composite.allBodies(world);
let sleeping = bodies.filter((body) => body.isSleeping);
let isWorldSleeping = bodies.length === sleeping.length;
```

**Comment by codeclown** [comment]
Thank you for the answer!

**Comment by codeclown** [comment]
@liabru Another question. Isn't `isSleeping === true` supposed to mean that a body has stopped movement? In my tests bodies actually never end up in this state.

I'm simply trying to detect when all objects in the world have stopped moving.

**Comment by codeclown** [comment]
Okay, it simply seems that, while being invisible to the eye, the objects actually maintain just a tiny amount of speed. What I did for now:

```
        let isAwake = false;
        const bodies = Matter.Composite.allBodies(game.engine.world);
        for(let i = 0; i < bodies.length; i++) {
            if(bodies[i].speed > 0.005) {
                isAwake = true;
                break;
            }
        }
```

**Comment by liabru** [comment]
Do you mean actual sleeping, [which you have to enable](http://brm.io/matter-js/docs/classes/Engine.html#property_enableSleeping) or do you just mean 'come to rest'? If it's the latter then try something like this in the filter:

```js
let motion = body.speed * body.speed + body.angularSpeed * body.angularSpeed;
let isResting = motion < 0.1;
```

**Comment by codeclown** [comment]
I meant detecting when all objects/bodies have stopped moving. My bad on confusing the terms. Thank you again.
