### ISSUE TITLE
How to add plugins via npm?

### ISSUE THREAD

**Issue by cmalven** [liabru/matter-js#314]
None of the Matter.js plugins are included in the `matter-js` bundle installed via npm, and these plugins don't seem to have their own packages on npm, so how are we expected to install and use plugins with webpack/browserify + npm?

**Comment by liabru** [comment]
Just finishing work on the plugin boilerplate first, then plugins will have their own separate packages. Hopefully this weekend!

In the meantime, try making a local copy and then change the reference when they are released.

**Comment by liabru** [comment]
These plugins are now fully packaged!

- [matter-attractors](https://github.com/liabru/matter-attractors)
- [matter-wrap](https://github.com/liabru/matter-wrap)

Also check out the [matter-plugin-boilerplate](https://github.com/liabru/matter-plugin-boilerplate).
