### ISSUE TITLE
Closed system, without losing velocity

### ISSUE THREAD

**Issue by kujma10** [liabru/matter-js#316]
I'm creating the same system as it is described [here,](https://github.com/liabru/matter-js/issues/144) however I need to have many objects (balls) instead of one. At first they move and hit each other (I want this to continued forever), but then they are getting slow and are losing the force.  `inertia: Infinity `  is helpful but there is still something that make balls to lose velocity. 

Do you have any suggestions how to make this kind of world 'ideal' ?
Thank you.

**Comment by liabru** [comment]
See #256 which discusses the same problem and leave a comment with a jsfiddle example if you can. This will help me when I investigate. For now make sure that `body.friction` and `body.airFriction` are both set to `0` and see if it helps. Thanks!

**Comment by kujma10** [comment]
Left a comment there with jsfiddle example, thanks.
