### ISSUE TITLE
How to stop sensor rotating with circle

### ISSUE THREAD

**Issue by EikaMikiku** [liabru/matter-js#317]
Say i have a circle, and i want to move left/right, and i want it to rotate when it moves around.
I want to add a sensor for jump detection, so it should always be at the bottom

But when doing Body.create with circle and sensor, it creates a uniform body, so my sensor is also rotated with the circle
Setting inertia on circle will stop rotation of the circle, which i do not want

I could set the sensor to be static and keep updating it's position each frame, just asking if there is a better way to do it

**Comment by liabru** [comment]
The way sensors are implemented is that the body _is_ the sensor rather than it being something separate, so as you suggest create another static body for the sensor and make it follow the other body.
