### ISSUE TITLE
Question: Way to move rectangle back and forth?

### ISSUE THREAD

**Issue by KennethCooney** [liabru/matter-js#320]
Hi I am using your engine for a class project and wanted to make a game where a rectangle is moving back and forth along X-axis where it would drop a balls onto pins (plinko) when the user hits spacebar. Do you know how I would go about having an object move back and forth? I have set the rectangle to isStatic: false and messed with the applyForce and setVelocity, but am having trouble getting it to do what I want.

**Comment by liabru** [comment]
Check out the [body manipulation demo](http://brm.io/matter-js/demo/#manipulation) and the [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js) which might have what you need.

**Comment by KennethCooney** [comment]
Thank you liabru! That is perfect. I can't believe I missed that in the demo examples!
