### ISSUE TITLE
Matter.js does not comply with latest decomp.js

### ISSUE THREAD

**Issue by BorisKozo** [liabru/matter-js#322]
I am trying to use Matter.js with concave polygons but it seems that at some point the API of decomp.js was changed completely and is no longer compatible. 

Looking at the code it seems that it won't be hard to align the two.
Would you take a PR that fixes the problem?

**Comment by davherrmann** [comment]
I think there is already an open issue and a pending (conflicting) pull request for that: #287 #288 👍

**Comment by liabru** [comment]
Closing this as there are two existing issues. I'll try to prioritise this, thanks!

**Comment by BorisKozo** [comment]
Cool. Tag me if you need any help.
