### ISSUE TITLE
is there a way to add additional animation to a body? Example: polygon fades in as it falls or animates in from the side before gravity takes effect

### ISSUE THREAD

**Issue by courtneyvigo** [liabru/matter-js#323]

**Comment by liabru** [comment]
Not with the built in debug renderer, if you need to do anything fancy I'd suggest creating your own, see [Rendering](https://github.com/liabru/matter-js/wiki/Rendering). A place to start is to copy the code of `Matter.Render`.

**Comment by courtneyvigo** [comment]
so with this:

var render = Render.create({
    element: document.body,
    engine: engine,
    options: {
        width: 500,
        height: 500,
        pixelRatio: 5,
        background: (250, 250, 250, 0),
        wireframeBackground: '#222',
        hasBounds: true,
        enabled: true,
        wireframes: false,
        showSleeping: true,
        showDebug: false,
        showBroadphase: false,
        showBounds: false,
        showVelocity: false,
        showCollisions: false,
        showSeparations: false,
        showAxes: false,
        showPositions: true,
        showAngleIndicator: false,
        showIds: true,
        showShadows: false,
        showVertexNumbers: false,
        showConvexHulls: false,
        showInternalEdges: false,
        showMousePosition: false,
    }

});

should be able to? What is the syntax for something like a fade in animation?

**Comment by liabru** [comment]
There's nothing built in for animations. This library focuses on just the physics, for anything other than basic rendering you'll need to build it or use some rendering library like [THREE.js](https://github.com/mrdoob/three.js/) or [Pixi.js](https://github.com/pixijs/pixi.js?utm_source=html5weekly).
