### ISSUE TITLE
body vs bodies

### ISSUE THREAD

**Issue by courtneyvigo** [liabru/matter-js#324]
Hi :) I am a little confused when to use body vs bodies...

**Comment by liabru** [comment]
`Matter.Body` is the module for creating body instances, but it doesn't specify what sort of shape (i.e. no vertices, you must pass these yourself). Whereas `Matter.Bodies` is a module that makes it easy to create common body shapes such as circles or rectangles (all of which return a `Matter.Body`). See the docs for [Matter.Body](http://brm.io/matter-js/docs/classes/Body.html) and [Matter.Bodies](http://brm.io/matter-js/docs/classes/Bodies.html) for more info.
