### ISSUE TITLE
How to change where canvas will be rendered in DOM?

### ISSUE THREAD

**Issue by KennethCooney** [liabru/matter-js#325]
I am using the default Render.js and cannot figure out how to create my own canvas and have the game take place in there. I just want to center the canvas in the DOM and stylize around it. Thanks.

**Comment by kroko** [comment]
```
Render.create({
  canvas: document.querySelector('.canvas-physics')
});
```

source: http://brm.io/matter-js/docs/classes/Render.html#properties

**Comment by liabru** [comment]
What @kroko shows should work (thanks). Also take a look at the [Rendering](https://github.com/liabru/matter-js/wiki/Rendering) wiki page.

**Comment by KennethCooney** [comment]
Thank you kroko and liabru. I tried what you suggested, but I am still getting an error:

> matter.js:7536 Uncaught TypeError: render.canvas.getContext is not a function
>     at Object.Render.create 

This is what I have: 

> // create a renderer
> var render = Render.create({
> 	element: document.body,
> 	canvas: document.querySelector('#myCanvas'),
> 	engine: engine,
> 	options: {
> 		background:"#2b2b2b",
> 		width: 600,
> 		height: 960,
> 		wireframes: false,
> 		showPositions: false,
> 		showAxes: false,
> 		hasBounds: false,
> 		showDebug: false
> 	}
> });

**Comment by kroko** [comment]
Show the HTML.
Does it have
```html
<canvas id="myCanvas"></canvas>
```
and do you load javascript after DOM has been loaded.

**Comment by KennethCooney** [comment]
Thank you @kroko ! It was a stupid mistake. I had 
<div id = "myCanvas></div>
instead of 
<canvas id = "myCanvas'></canvas>

Its working now!
