### ISSUE TITLE
change the radius of a circle body

### ISSUE THREAD

**Issue by jeffersoncarpenter** [liabru/matter-js#326]
Is it possible to change the radius of a circle body?

**Comment by thatdutchguy** [comment]
You could use Body.scale: [link to doc](http://brm.io/matter-js/docs/classes/Body.html#method_scale)

**Comment by liabru** [comment]
As @thatdutchguy said, you can use `Body.scale` but two things to note:

- if using `Matter.Render` you also need to scale `body.render.circleRadius`
- scaling circles will make them lose precision, see #301
