### ISSUE TITLE
Bug in constraints between two bodies when one of the bodies is constrained to static or hits static.

### ISSUE THREAD

**Issue by kroko** [liabru/matter-js#327]
Hi,

Say we want to design a hat and the hat has that puffy dangling _sphere_ on top.

As an example I have created a static body as an anchor.
To the static body I have linked dynamic head/hat base body with 4 constraints to keep it in place. User can interact with head. And I added a debug body just to show that gravity works.
To the dynamic head/hat base body I have linked dynamic puff body with 1 constraint to keep the puff constrained RELATIVELY to the hat. User can interact with the puff.
So whenever user grabs and drags hat or puff, both follow.

See example
http://jsbin.com/hazumud/10/edit?js,output

It behaves unexpectedly.
Whenever I grab the hat body (largest circle) I expect the puff (top right) to follow (with "elastic dealy" of course as the puff has some inertia) as well as to puff dangle because there is gravity. However it seems it wants to stay in place in some absolute coordinate space. Why?

I thought

```javascript

// this.circle2BodyDynamic is head puff
// this.circle1BodyDynamic is overall hat/head

    this.circle2ConstraintToCircle1 = Constraint.create({
      bodyA: this.circle2BodyDynamic,
      bodyB: this.circle1BodyDynamic,
      pointA: {x: 0, y: 0},
      pointB: {
        x: 80.0,
        y: -80.0
      },
      length: 1.0,
      stiffness: 0.5,
      label: 'circle2ConstraintToCircle1'
    });
```

would make `this.circle2BodyDynamic` (puff) relative to `circle2ConstraintToCircle1` (head) wherever head goes, but it seems it isn't, `this.circle2BodyDynamic` (puff) want's to stay in place (it does follow a little bit, but the feeling is that there is yet another invisible constraint that wants to keep it back in the original position). And confusion grows, because there is gravity, puff should try to drop down, only thing holding it should be constraint to head, which itself is constrained to static.

As each Physics engine has its way of doing things, what would be the right way to make puff react to gravity and follow head (with inertia) wherever it goes as it would in real physics world?

Thanks!

**Comment by BorisKozo** [comment]
All I see in the example is a blue rectangle :(

**Comment by kroko** [comment]
Push "run"!

**Comment by BorisKozo** [comment]
I did :).... It just says 
dehujicide.js:14 Uncaught TypeError: Cannot read property 'Engine' of undefined(…)

And all is shown is a blue rectangle

**Comment by kroko** [comment]
Ah, that is Chrome (I wrote it in Safari) security issue (CORS, as i include script from raw.githubusercontent.com). Fixed - http://jsbin.com/hazumud/10/edit?js,output

**Comment by kroko** [comment]
I added another test, where the head is not constrained in place and the puff follows as expected http://jsbin.com/hazumud/12/edit?js,output
Thus things break if one of the object has other constraints (here - constrain to static) applied to it?

**Comment by kroko** [comment]
It seems, that if constraints would be divided between mouse (external interaction) and world (inner interaction) then code [here](https://github.com/liabru/matter-js/blob/c72a9d017f3a1e543c37d42cd7a9f54b5cd2f524/src/core/Engine.js#L151-L155
) would be solving only mouse, but all other constraints would be solved later after collisions introduced by mouse (external) are solved and normalised. thus lot of things needs two passes to cope with _external_ stuff.

**Comment by liabru** [comment]
Thank you for all the test cases, they are very helpful. There are clearly some issues with constraints, especially with more complex systems (also see #93). 

There's quite a lot to look over here but something I notice is that you set the constraint length to be too short and the stiffness too high for the effect I think you're looking for? For example try this for your first example:

```js
this.circle2ConstraintToCircle1 = Constraint.create({
  // ...
  length: 10.0,
  stiffness: 0.1,
  // ...
});
```

Is that closer to what you want?

**Comment by kroko** [comment]
Hi & welcome back from the weekend :) Thanks for the really nice lib!
No, length has nothing to do with the issue (and I do understand the effect of joints being short and having great stiffness).
Basically my scene has configuration something like this
http://jsbin.com/hazumud/28/edit?js,output
which is 4th case and the original question.

Firstly, when I drag head, due to the fact that it is constrained to static so that the _character_ would be kept in place, the head puff behaves unexpectedly. Drag head vertically down or right, observe that puff does not follow, as it should (as it does in 1st example http://jsbin.com/hazumud/21/edit?js,output unless one drags the pair it into some static body).

Secondly there exists other static objects in the scene, close enough, that you can _bang the character on them_ although character is kept in place via constraints to the static. Whenever one drags character into static (here _pole_), the puff behaves unexpectedly again (also observed in 1st using mouse, 3rd using some constraint in place).

Whenever there is static somewhere - either one of the objects is constrained to the static and/or object bangs into static, the dynamic constraints (that should keep 2 objects relatively positioned) break.

I would not say it is due to complex systems as examples show, that would be wishful thinking :)
In 1st example there are 2 dynamic bodies and one static body (forget gravity checker). There are 2 constraints, one keeping body pair relatively locked, other is introduced by mouse interaction. 3 bodies, 2 constraints. Whenever dynamic bodies are collided/pushed into static due to interaction (mouse constraint), constraint between dynamic bodies does not behave.
Same in 3rd case, only here mouse is replaced by constant constraint.
The seemingly complex 4th case can be simplified with using one constraint to keep head in place, but the defect still occurs.

**Comment by kroko** [comment]
The code is very well written (although dunno why you are not using ES6 features + babel).

First thoughts are that one way might be in `Constraint.solve` to tinker with force vector if bodyA | bodyB is in contact with static. But then bodies need that information. Now at the point where constraints are solved there is no contact solved yet (`totalContacts === 0`) and you actually reset it anyways in `postSolvePosition` later. And body object holds no information about its collisions (if it had, one could look at them, see if contact is with static, undo the forces that are in pair with the static, so that constraint is correct) .
```javascript
  offsetA = {
                x: pointAWorld.x - bodyA.position.x + force.x + CORRECTION.x,
                y: pointAWorld.y - bodyA.position.y + force.y + CORRECTION.y
            };
```
But I haven't got that far to see the place that could be changed for the original question (although related) that eventually interests me more - constraining to static and issues that arise.

It is busy jingle bells project time. Do you have any plans on this (imho it would be much faster, if you took a look at this, as you might know everything by heart)? I have currently implemented a project with Matter.js, it went really nice and smooth, but I am quite worried now where to go next, as it does not work, this bug is a _physics killer_ :). Project due date is coming really fast (~10 days left), if this cannot be solved, then I have to look back to the things I wanted to get rid of (read - painful Box2D port) and rewrite everything from ground zero up (physics, interaction math and gluing physics together with responsive rendering engine also has to be redone then). :( I know that all open source _rules_ apply here :), but I don't know if I can manage to try to help to solve this in the given timeframe (week or so). Anyways big thanks for the easy to work with lib, but maybe you could just comment on your plans?

**Comment by liabru** [comment]
> Drag head vertically down or right, observe that puff does not follow, as it should

When I move the head around the puff seems to follow as I'd expect it to given the set up you have.
I need to know more about what you are expecting here (a diagram might help).

> Whenever there is static somewhere - either one of the objects is constrained to the static and/or object bangs into static, the dynamic constraints (that should keep 2 objects relatively positioned) break.

I can see what you mean about this and it is a problem. I think it has something to do with the order constraints are being resolved, it's possible that all constraints attached to dynamic objects need to be resolved before resolving constraints attached to static points. It could also be due to a problem with propagating constraints among all connected bodies (multiple iterations helps up to a point).

> The code is very well written (although dunno why you are not using ES6 features + babel).

Thanks. The majority of this project's code was written a few years before these things had matured!

> And body object holds no information about its collisions (if it had, one could look at them, see if contact is with static, undo the forces that are in pair with the static, so that constraint is correct) .

Collision information is maintained in `engine.pairs`, you can find a particular pair by doing `engine.pairs.table[Pair.id(bodyA, bodyB)]` which gives you a pair object containing a bunch of collision information. You can also trying filtering `engine.pairs.list` to get all collisions for a single body. 

Maybe this might be helpful for your temporary fix idea?

> Anyways big thanks for the easy to work with lib, but maybe you could just comment on your plans?

Changes to the constraint and collision resolvers are pretty fundamental changes and require a lot of investigation and testing, especially since they will be affecting all users. 

I realise that there are bugs here and I'd like to do something about them, but it will take me more time than you have here to fix them fully I think.

For now I'll see if optimising the order of constraint resolution helps.

**Comment by kroko** [comment]
http://jsbin.com/hazumud/31/edit?js,output
Note the small circle and big circle relative positions.
I have positioned them so that small circle origin in the resting position is ~ on the big circle circumference.
I grab the big circle with mouse.
Move it somewhere, stop movement, do not release mouse.
The small circle will follow (having its own inertia), it is constrained to the big circle.
When system stabilises (it will take time as the stiffness is small, so it will fluctuate before stabilising), the small circle will be relatively positioned to the big circle as it was in the beginning. As it should be, because constraint is about relative positioning of small circle to the big circle.
Release the mouse. Done.
This is what I expect.

http://jsbin.com/hazumud/32/edit?js,output
Note the small circle and big circle relative positions.
I have positioned them so that small circle origin in the resting position is ~ on the big circle circumference.
I grab the big circle with mouse.
Move it somewhere (as far as you can down or right, as there is pole to the left), stop movement, do not release mouse.
The small circle _should_ follow (having its own inertia), it is constrained to the big circle. 
When system stabilises (it will take time as the stiffness is small, so it will fluctuate before stabilising), the small circle _should_ be relatively positioned to the big circle as it was in the beginning. But it is not, although constraint is about relative positioning of small circle to the big circle.
Release the mouse. Done.

Screenshot
![screen shot 2016-12-06 at 01 13 18](https://cloud.githubusercontent.com/assets/720976/20906548/4ae072b8-bb51-11e6-8e2f-d9b870ec0b57.png)
At this point I have grabbed the big circle, pushed it down, haven't released the mouse and waited for some seconds. The small circle is not correctly relatively positioned to the big circle, it is more upwards than it has to be!

Hope you understood. In all cases, whether big circle is pushed into static objects or is constrained to some static object, the small circle and big circle should have their relative positions kept when system  stabilises after the movement (during movement of course the small circle position is "delayed" as the constraint has stiffness and small circle has inertia, after the movement end there is also elastic fluctuation before it stabilises). Just like it does in the first case in this comment, when moving-stopping-moving... the big circle around the air. If not, I can come up with extra diagrams.

Please keep updated how it goes with reordering constraint calculations.

**Comment by liabru** [comment]
Thanks for clarifying. Can you try adding `this.mouseConstraint` to the world _before_ anything else (rather than adding it last). This seems to resolve at least some of the problems?

**Comment by kroko** [comment]
Adding mouse constraint as first does help in the case of my screenshot, but only.

I did combine all tests in one place
http://jsbin.com/qemafab/3/edit?js,output


---

1.

I have grabbed the dynamic pair (largest circle) in air, haven't released mouse, waited for constraint to settle. The relative constraint is **correct**.

![01](https://cloud.githubusercontent.com/assets/720976/20925612/a49f4ea4-bbc0-11e6-8b7f-1c97e44b97f5.png)

---

2.

I have grabbed dynamic pair (largest circle) and pushed into the the ground, haven't released mouse, waited for constraint to settle. The relative constraint is **INCORRECT**.

![02](https://cloud.githubusercontent.com/assets/720976/20925652/b91fc052-bbc0-11e6-94ab-71a9ee3e7678.png)

---

3.

I have grabbed dynamic pair (largest circle) that is constrained to static and pushed biggest circle down, haven't released mouse, waited for constraint to settle. The relative constraint is **correct**. This has changed because as you can see in jsbin, I added mouse constraint as the very first to the world.

![03](https://cloud.githubusercontent.com/assets/720976/20925684/e3dd95bc-bbc0-11e6-8c17-4b0081f6ebb8.png)

---

4.

I have grabbed dynamic pair (largest circle) that is constrained to static and pushed biggest circle into the static to the left (pole), haven't released mouse, waited for constraint to settle. The relative constraint is **INCORRECT**. Also note, how the gravity checker behaves, it thinks that the bounds of the biggest circle are somewhere else (it seems that the gravity checker "sees" bigger circle  position as as if the biggest circle was pushed into the static).

![04](https://cloud.githubusercontent.com/assets/720976/20925713/168c57aa-bbc1-11e6-9b18-23dd83348773.png)


If you are doing some testing, just download the jsbin or change

```html
<script src="https://rawgit.com/liabru/matter-js/master/build/matter.js"></script>
```

in the jsbin.

I also added some basic checking westerday in https://github.com/WARP-LAB/matter-js/blob/dev-constraints/examples/constraintTest.js  
If you want I can put the whole jsbin example into  that `constraintTest.js`, do a PR for that branch, so you have this `dev-constraints` branch in your hands with all tests for constraint bug cases in one place that you can run on gulp dev watch locally on your dev machine.

I'm still full of hope that this somehow can be managed although there's a Latvian saying that translates to smth like "hope is consolation/comfort for the stupid"  😄

**Comment by Technostalgic** [comment]
I think I understand what is happening here as I have run into many similar problems making game loops. What it looks like is happening is that each body is being iterated through and updated as a separate entity. I can understand how it looks like an issue but I think it's more of a matter of perspective. Let me try to explain what I think is going on:

1. The big body (the hat) is getting called for an update first, when this happens, for this specific case, you are dragging the body as far downward as you can, this adds a certain force on the body and changes it's velocity. It then calculates the position and reports that to the render device which later renders it at that position.
2: The constraints on the hat are then iterated through and since there are four of them pulling back upwards, this then acts as another force and changes the velocity of the body again. The body then recalculates it's position based on the different velocity and sends it's new position to the engine, but not the render device.
3: The puff then finally gets called for an update, and checks it's constraints. It sees that it has a constraint on the hat and it's constrained to the body's relative position according to the engine, which is different to that of the body position on the render device. 

this would cause the apparent disposition that I see in your example. And while this is complete speculation, as I haven't used matter.js at all yet (just looked into it today for the first time), I have noticed very similar things happening with other rigid body physics engines and simulations.

**Comment by kroko** [comment]
In the end I somehow tamed the beast to get that [head and puff working](http://helpsanta.panic.lv).
I do appreciate the huge work put into this, but honestly 99% I had to work against the lib 😢 Meaning that the API is super great and super fast to code with!, the results are the ones that need to go back and start applying hacks all over the place. I mean, take `n` constraints and hang an object in it, so it settles. Some kind of swing. Swap the constraints in the world (order they are added). In Real world physics it does not matter, object settles in the same position. Here it matters. Kind of pun, right. 😄 There are also issues with events, especially touch. Anyways, thanks @liabru, I wish I had time instead of just bugreporting actually contribute to this. Happy holidays!
@Technostalgic my "main" language is C++ and I have used Box2D ever so many times as well as Bullet and some misc verlet types (also in Processing/Java). There are glitches in B2D, but they are predictable.

**Comment by liabru** [comment]
@kroko I'm glad you got it working (it's awesome!) and I apologise for the issues you had here. FYI I spent a number of hours on this over the past week on this issue and while I had a few promising results they failed for many other cases which made it unusable. I'll still continue to investigate here so this will stay open.

> There are also issues with events, especially touch.

Would appreciate if you could log any bugs on this too.
