### ISSUE TITLE
Using element bounds as walls, on resize

### ISSUE THREAD

**Issue by clarklab** [liabru/matter-js#331]
Hello! I've got a matter scene working, but I've got a few questions.

First: I see multiple ways to make walls/bounds, all manually defined. Is there a way to turn on automated bounds at the edge of the canvas? If not, what's the cleanest way to enable something similar?

Next: I've tried a bunch of things to make the canvas resize when the window is resized (responsive). I see the effect on the main matter.js page, but can't figure out how it's working. I saw  body.scale but couldn't quite figure it out (especially entering a specific X and Y scale, when I'd just want it to fit to the available space).

Can someone point me in the right direction? Thanks!

**Comment by clarklab** [comment]
Ok, so I'm an idiot, and figured out the resizing part, which is to *simply use CSS* to make the canvas element max-width:100%. Not sure how I missed something so simple. Leaving the answer here for future dummies.

The automated walls would still be handy.

**Comment by liabru** [comment]
> First: I see multiple ways to make walls/bounds, all manually defined. Is there a way to turn on automated bounds at the edge of the canvas? If not, what's the cleanest way to enable something similar?

There's nothing built in for this, everything must be created as a body. 

> Ok, so I'm an idiot, and figured out the resizing part, which is to simply use CSS to make the canvas element max-width:100%. Not sure how I missed something so simple. Leaving the answer here for future dummies.

Yep :)

> The automated walls would still be handy.

This might be a neat idea for a [plugin](https://github.com/liabru/matter-js/wiki/Creating-plugins).
