### ISSUE TITLE
Progress on CCD?

### ISSUE THREAD

**Issue by TrentWDB** [liabru/matter-js#336]
I see that there is currently a branch (https://github.com/liabru/matter-js/tree/ccd) for continuous collision implementation. How stable is this branch currently? What is yet to be done and what bugs can be expected?

I'm interested in using this library but I'm concerned that CCD won't work properly, leading to unreliable physics simulations. As an alternative, would it be better to run this library on master, but step the physics simulation times so each iteration is limited to ~4 milliseconds or so each step? I believe this is basically a simple CCD implementation.

Thanks!

**Comment by liabru** [comment]
The ccd branch has some bugs and I wouldn't consider it usable yet sadly. I think the idea behind it works but there are some edge cases to resolve.

> As an alternative, would it be better to run this library on master, but step the physics simulation times so each iteration is limited to ~4 milliseconds or so each step? I believe this is basically a simple CCD implementation.

Yeah I think this should be viable as it should increase the amount of collision checks and hopefully catch fast moving bodies before they pass through other bodies. Though there are reports of issues regarding changing the timestep (#332) so leave a comment there if you find issues.

**Comment by TrentWDB** [comment]
Thanks!

**Comment by ggmendez** [comment]
Any progress on the implementation of this feature?

**Comment by bobhaslett** [comment]
The same question as above, I'm developing a project using matter.js engine and the CCD issue is really hampering my progress. It looks as if I'll have to switch to a javascript port of liquid fun which I'm finding difficult to get to grips with so was hoping that some progress may have been made
