### ISSUE TITLE
Agar.io Style Game Laggin

### ISSUE THREAD

**Issue by deniskrop** [liabru/matter-js#338]
Hello, I used Matter.js as the engine for my agario style game, but it starts lagging when I get 100+ players. Can anyone suggestion some practical tips for optimization for matter.js to reduce the CPU load?

**Comment by liabru** [comment]
I suggest using a [profiler in devtools](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/js-execution) to try identify the functions that are taking up time.

I can't really give any particular advice without knowing any details of your implementation though. Is there a link to the game?

**Comment by issy123** [comment]
If you are running matterjs in node.js:
I highly suggest changing from the  'ws'  npm module to 'uws'.  This is one of the most cases why it lags (I for example had lag with 70 players, now with uws I can have 250+ players)

**Comment by deniskrop** [comment]
Thanks @issy123 indeed I am. It did seem to help but I am still having major lag issues. Any further help would be highly appreciated
