### ISSUE TITLE
Seems to be issues with Matter.Bodies.fromVertices. Concave shapes are incorrect.

### ISSUE THREAD

**Issue by TrentWDB** [liabru/matter-js#339]
I was attempting to use Matter.Bodies.fromVertices on this shape:

`             {
                 "id":21,
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":32,
                         "y":96
                        }, 
                        {
                         "x":64,
                         "y":160
                        }, 
                        {
                         "x":96,
                         "y":192
                        }, 
                        {
                         "x":160,
                         "y":224
                        }, 
                        {
                         "x":256,
                         "y":256
                        }, 
                        {
                         "x":0,
                         "y":256
                        }, 
                        {
                         "x":0,
                         "y":0
                        }],
                 "rotation":0,
                 "x":3200,
                 "y":2464
                }, `

and the shape was around ~64 pixels off from where it should have been and was transformed into a convex shape (just a triangle in this case.) It just stripped all vertices except those necessary to form a convex triangle out of the previously concave triangle-ish slope thing.

I ended up just using some earcut algorithm I found online to convert the shape into triangles before plugging it into the fromVertices function and that worked fine.

Also through experimenting it seems like the x, y values you provide must be the average of all vertices? Not sure if this is true but seems like a second glitch might have been occurring when I used the x, y values as is.

**Comment by davherrmann** [comment]
Is `poly-decomp.js` available as a global variable (see [Bodies.fromVertices](http://brm.io/matter-js/docs/classes/Bodies.html#method_fromVertices))?

```javascript
import decomp from 'poly-decomp'
window.decomp = decomp
```

The origin of the body is the center of mass, you maybe could translate the body after creation as suggested in #186?

Hope this helps!

**Comment by TrentWDB** [comment]
Yup, poly-decomp is not available. Whoops!
