### ISSUE TITLE
[Question] Bodies positions.

### ISSUE THREAD

**Issue by Xlander11** [liabru/matter-js#34]
Hi!

Is there a way to modify a body's position before it is drawn?

e.g (Which do not work)

```
Events.on(_engine, 'tick', function (event){
  var circle_pos = circle.position;
  circle_pos = {x: circle_pos.x - viewPort.x, y : circle_pos.y - viewPort.y};
});
```

Where I want to actually do:

```
context.arc(x - viewPort.x, y - viewPort.y, radius, sAngle, eAngle);
```

**Comment by Rodeoclash** [comment]
Just wanted to say that I got the camera tracking working well with that snippet you posted. An example here:

http://game.richardson.co.nz/

Thanks for a great library. I'll drop you another line when the game is done :)

**Comment by Xlander11** [comment]
Nice! Keep it up.

**Comment by liabru** [comment]
Looking good, please do :) Check out this [codepen](http://codepen.io/lilgreenland/pen/jrMvaB) I found the other day that's using the engine for a spaceship type game, might be helpful.
