### ISSUE TITLE
A question about the code style of matter-js

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#342]
I'm a newbie of matter-js. There is a question puzzle me.

One common code style of OOP is like this：
```
var foo = new FooClass(options);
foo.methodA(a, b, c);
```
But matter-js is :  
```
var foo = FooClass.create(options);
FooClass.methodA(foo, a, b, c);
```

That's Why ? 
Is it just a personal habit ？or are there some reasons else ？ 

Thanks , @liabru .

**Comment by liabru** [comment]
The codebase uses a functional style of programming rather than OOP, check out thread #78 for some info.

**Comment by finscn** [comment]
I see .  Thanks :)
