### ISSUE TITLE
Incorrect collision detection if sensors density set to 0

### ISSUE THREAD

**Issue by dufia** [liabru/matter-js#345]
I want to implement range of vision.

Heres a fiddle https://jsfiddle.net/01zabra5/3/. Use up and down arrows to move, collison will be detected after the sensor is already over the ball. If sensors density **isn't set to 0**, collision detection works fine.

Is it a bug or I am doing it wrong?

In the example I used version 0.10.0 but with 0.11.1 its basicly the same.

**Comment by liabru** [comment]
Looks like your `thrust` value is way too small. Try `thrust: 100`?

**Comment by dufia** [comment]
Hey @liabru 

I think the thrust is fine, you can move the ball easily with arrows. The problem is I cannot get the collision detection to work. I already spent couple of hours on it. Please have a closer look at the fiddle.

Looks like, if you have a mass-less part within a compound body there are problems.
The way I programmed it, collision detection doesn't work. Maybe I am doing something completely wrong?

**Comment by dufia** [comment]
Not being able to fix it, I changed my approach. I dropped the compound body idea and I render these few pieces separately now. Its not perfect but will be sufficient. Thanks.
