### ISSUE TITLE
Filter collision by object position / direction 

### ISSUE THREAD

**Issue by hatsumatsu** [liabru/matter-js#352]
Is it possible to disable the collision of objects based on their direction or position?

Let's say an object collides with another only when moving towards it from the top, but goes through it when coming from the bottom?

**Comment by liabru** [comment]
Sure, you can use [collision filters](http://brm.io/matter-js/demo/#collisionFiltering) and change them based on velocity.

**Comment by liabru** [comment]
@stursby you could do that inside an engine event like [beforeUpdate](https://brm.io/matter-js/docs/classes/Engine.html#event_beforeUpdate), but from your description I guess just check if it is inside the viewport?

**Comment by stursby** [comment]
@liabru I was able to solve it by tapping into the engine `collisionStart` event and then change the bodies collision category accordingly. See example snippet:

```
Events.on(this.engine, 'collisionStart', (event) => {
    const { bodyA, bodyB } = event.pairs.slice()[0]
    if (bodyA.label === 'superball') {
        bodyA.collisionFilter.category = collisionCategoryBottom
    }
    if (bodyB.label === 'superball') {
        bodyB.collisionFilter.category = collisionCategoryBottom
    }
})
```

By default the balls have a higher collision category so they can "pass through" walls, but once the event is fired, I update that value to be the same as the walls, and therefor they now bounce off the walls as intended!

```
const collisionCategoryBottom = 0x0001
const collisionCategoryTop = 0x0002
```
