### ISSUE TITLE
What does Sleeping do?

### ISSUE THREAD

**Issue by deniskrop** [liabru/matter-js#354]
I'm trying to optimize my game. I came across sleeping: http://brm.io/matter-js/docs/classes/Sleeping.html and was wondering exactly what it was for. I have an agario style game. Will this help with optimization? Should I put it in? Any suggestions on how to implement it? Also, how frequently should the sleeping state be set, every frame?

**Comment by liabru** [comment]
See the [sleeping](http://brm.io/matter-js/demo/#sleeping) demo and [source](https://github.com/liabru/matter-js/blob/master/examples/sleeping.js). What this does is it tells the engine to stop updating and collision checking bodies that have come to rest.

This is a big performance boost if you have a lot of bodies in collision at rest (e.g. a stack of boxes). Sleeping bodies are woken up when a non-sleeping body collides with them. The downside is that the result not always exactly the same as if they were not sleeping, but it's usually good enough.

All you need to do is set `engine.enableSleeping = true` once when you create your engine. It will automatically handle the rest.

**Comment by deniskrop** [comment]
Thank you liabru! I was doing it it in every frame in update before!
