### ISSUE TITLE
Optimization tips? And how does Matterjs test for collisions?

### ISSUE THREAD

**Issue by deniskrop** [liabru/matter-js#355]
I have been using matterjs for an Agar.io style game, and am looking for optimization tips. Are there any guidelines for best practices? I just found out about sleeping, which wasn't obvious to me that I should enable it, so anything like that would really help.

Can anyone describe how matter js decides what to test for collisions and how to do it? How does matter js decides whether two things collide? Is it using AABB tests or what? Also, where in the source can I find it? I would like tips on how to optimize in general, as well as to optimize the source of matter js its self, any additional information would be appreciated.

**Comment by liabru** [comment]
> Are there any guidelines for best practices?

Nothing particularly specific to matter-js, just apply most of the usual performance optimisations and techniques you'd normally use with games and physics engines.

> Can anyone describe how matter js decides what to test for collisions and how to do it? How does matter js decides whether two things collide?

The collision detector performs a grid (broadphase) test, then an AABB (midphase) test and finally an SAT (narrowphase) test. If all of these pass, a collision is generated. You can find the source for these in the [collision directory](https://github.com/liabru/matter-js/tree/master/src/collision).

If you're interested in how physics engines and collisions work in depth, then check out this [article](http://brm.io/game-physics-for-beginners/).
