### ISSUE TITLE
How to make collision check less often?

### ISSUE THREAD

**Issue by deniskrop** [liabru/matter-js#356]
I have many objects, and want to try to optimize my game by lowering the amount of collisions checks on some objects. On some objects that collide less often, I want to check for collision only 1/10 times. Can anyone suggest a way to do this?

**Comment by liabru** [comment]
Try changing `engine.constraintIterations`, `engine.positionIterations` and `engine.velocityIterations`. You can also write [your own runner](https://github.com/liabru/matter-js/wiki/Running) and call `Engine.update` less often. For anything more granular than that, you should piece together your own version of [Engine.update](https://github.com/liabru/matter-js/blob/master/src/core/Engine.js#L112-L226).
