### ISSUE TITLE
Lowest positionIterations and velocityIterations variables?

### ISSUE THREAD

**Issue by deniskrop** [liabru/matter-js#357]
If I understand correctly, lowering the positionIterations and velocityIterations values increases performance, and uses less CPU. I have a multiplayer game with graphics, thousands of objects, which all uses a lot of CPU so I am looking to optimize wherever possible.

I have set the following values when I create the engine:

>     // Physics engine
>     this.engine = Matter.Engine.create({
>         positionIterations: 0.01,
>         velocityIterations: 0.01
>     });
>     this.engine.enableSleeping = true;

Is it acceptable to set these values this low? I am not sure if it helping, my game still works, but my performance is still not great. I set them to 1 before this.

**Comment by liabru** [comment]
Those values must be integer (because they represent a number of loops of code) so the lowest they can be is `1`. I would not suggest that though, they should really be at least `3`, ideally they'd be `8` or more. The lower they are the less accurate and spongier the physics will be.

**Comment by deniskrop** [comment]
Thanks @liabru ! What changes do you recommend for monkey patching in Matter.Grid?

**Comment by liabru** [comment]
Replace the whole thing with another algorithm or library. For example [box-intersect](https://github.com/mikolalysenko/box-intersect) or a [quadtree](https://github.com/timohausmann/quadtree-js) or a sweep and prune implementation. I'm considering implementing box-intersect myself but I can't say when yet.
