### ISSUE TITLE
Transfer Momentum (Question)

### ISSUE THREAD

**Issue by herohamp** [liabru/matter-js#361]
So I am working on a game. I have 2 circles. One of them will move at one. how can I transfer the momentum of the moving one to the one it hits on contact? Sorry I am new to matter.js

**Comment by liabru** [comment]
By default collisions are inelastic, so you need to set `body.restitution` to something high like `0.9` which will make them act like pool balls, see the [newtons cradle](http://brm.io/matter-js/demo/#newtonsCradle) demo.

**Comment by herohamp** [comment]
thank you :D

**Comment by herohamp** [comment]
Also how can I reset a variable if a circle has any collision on the bottom?

**Comment by liabru** [comment]
You can use [collision events](http://brm.io/matter-js/demo/#events).

**Comment by mikhail** [comment]
@liabru even setting restitution to 1.0 and even more does not transfer 100% of the momentum. The unwanted effect is that the two circles collide and then both continue going in the same direction. I can only reproduce this when two objects are moving slowly. With fast movement its either not there or not noticeable. Is there another parameter that achieves full momentum transfer?

Even the newton's cradle example does not behave perfectly.

**Comment by liabru** [comment]
You should try increasing the precision of the circles (see `maxSides` argument of `Bodies.circle`), set their `inertia` to `Infinity`, lower the circle's `slop` value, set `friction`, `frictionStatic`, `frictionAir` to `0`,  also see #710 and #394.

Then if you need even more precision, you should increase the iterations values in `Engine` and also do multiple `Engine.update` calls per step. Hopefully those help!
