### ISSUE TITLE
Sleeping?

### ISSUE THREAD

**Issue by deniskrop** [liabru/matter-js#364]
In order to enable sleeping, is all I have to do is put:
    this.engine.enableSleeping = true;
when I create the engine, and it makes objects go to sleep automatically? Or do I have to set each object that I want to sleep to "sleeping" somehow thought the code individually?

**Comment by liabru** [comment]
Yes, the former, see #354 (you can still comment there).

**Comment by dfiverr** [comment]
Oh yes my apologies somehow I forgot about this
