### ISSUE TITLE
am i not setting render options correctly?

### ISSUE THREAD

**Issue by slolobdill44** [liabru/matter-js#370]
I have my render options set like so:

`  var landingPad =  Matter.Bodies.rectangle(750, 500, 315, 50, {`
                        `  render: {`
                          `  strokeStyle: "#EE964B",`
                         `  fillStyle: "#EE964B",`
                          `lineWidth: 5,`
                         `},`
                        `chamfer: { radius: [25, 25, 25, 25] },`
                        `isStatic: true,`
                    `});`

The `chamfer` and `isStatic` options work for me, but nothing in the `render` options seem to work. Am I writing this incorrectly?

**Comment by liabru** [comment]
Yeah I think so, are you using `Matter.Render`?

**Comment by slolobdill44** [comment]
Aha! my `render.options.wireframes` was `render.options.wireFrames`

**Comment by rfong** [comment]
Thanks, this fixed my problem! But don't see `render.options.wireframes` documented in http://brm.io/matter-js/docs/classes/Render.html

**Comment by liabru** [comment]
You're right, these need documenting!

**Comment by liabru** [comment]
Actually, I've opened #398 for this, thanks.
