### ISSUE TITLE
Would the bodies accelerate if they are dropping from heights?

### ISSUE THREAD

**Issue by imvetri** [liabru/matter-js#372]
I tried increasing the drop height of objects and I was hoping the body would be accelerating while they are descending. Unfortunately it wasn't

Is there any way I could turn it on?

Sample link : http://codepen.io/iminui/pen/ryVrMx
Notes : Drop height can be changed by increasing/decreasing the height at line number 16

**Comment by liabru** [comment]
They do accelerate already, but you can change `body.frictionAir = 0` if you want them to reach terminal velocity faster. If the terminal velocity is too slow, then you should increase the gravity force.
