### ISSUE TITLE
How to draw curve

### ISSUE THREAD

**Issue by zzbo** [liabru/matter-js#375]
how to draw curve as ground without svg?

**Comment by liabru** [comment]
Try using the [chamfer](http://brm.io/matter-js/demo/#rounded) feature. Alternatively, you can try using [Bodies.fromVertices](http://brm.io/matter-js/docs/classes/Bodies.html#method_fromVertices) where you can pass any vertices you'd like.

**Comment by zzbo** [comment]
thanks for your help!
