### ISSUE TITLE
Question: how to texture the cloth/softbody example?

### ISSUE THREAD

**Issue by davidjeliba** [liabru/matter-js#377]
Hi @liabru,

I am attempting to add texture to each of the squares in the cloth example. I can see from enabling the wireframes that the cloth is actually a series of circles:

![Imgur](http://i.imgur.com/X4atGvh.png)

When I apply a texture, I get:

![Imgur](http://i.imgur.com/lHYJzWB.jpg)

Which adds the textures to the circles with no cropping. The second screenshot highlights what I would like to do. If the cloth is stretched I would like for the texture to be applied to the warped square, not to the circle.

Is there a way to achieve this?

**Comment by liabru** [comment]
Texturing a 'mesh' like this isn't built in (it's out of the scope of the project), so you'll need to write your own renderer to do this. I suggest reading the [rendering](https://github.com/liabru/matter-js/wiki/Rendering) wiki page. To render a textured mesh you could either use a 2d canvas and [fillStyle](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle) with set to a [CanvasPattern](https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern) (like in this [example](http://www.williammalone.com/briefs/how-to-fill-pattern-html5-canvas/)) or look into something like three.js.

**Comment by davidjeliba** [comment]
Thanks for your reply, the fill style on the 2d canvas seems to be in the right direction!

**Comment by Nikistorm** [comment]
Could u please show how to solve?

**Comment by 7ammer** [comment]
Perhaps you could use pixi.js as the renderer and matter.js for the physics?

Here is an example of pixi warping a snake texture
https://pixijs.io/examples/?v=next#/basics/textured-mesh.js

**Comment by gevgeny** [comment]
I solved it via applying `PIXI.mesh.Plane` to `softBody` but FPS became much lower.

**Comment by robksawyer** [comment]
@gevgeny can you provide a link to your solve? I’d like to see how you implemented it. Thanks and nice work!

**Comment by gevgeny** [comment]
Sorry I cannot publish source, but basic idea I have found here https://codepen.io/shshaw/pen/JbrQrW.
