### ISSUE TITLE
Any way to "inflate" a body (increase its size and animate the change)?

### ISSUE THREAD

**Issue by keithpickering** [liabru/matter-js#379]
Wondering if there's any method to increase a body's size, preferably while animating the size change. I'm using SVG sprites.

**Comment by liabru** [comment]
See [Matter.Body.scale](http://brm.io/matter-js/docs/classes/Body.html#method_scale) and the [Body Maniuplation demo](http://brm.io/matter-js/demo/#manipulation) which includes a body that grows over time.
