### ISSUE TITLE
Creating hollow objects

### ISSUE THREAD

**Issue by treforcoster** [liabru/matter-js#380]
I'm trying to create and object that is essentially a ring.

Originally I created an object from SVGs but this renders awfully. Its a very jagged shape and it doesn't close correctly. 

Next I created a circle with inner transparent and increased line with. But the collision detection isn't great with this.

Finally I created a compound object of two circles one on top of each other. This works fine but I need the inside to be transparent. 

So is there anyway to do this?

**Comment by treforcoster** [comment]
I've got round this now by creating a compound object. Transparent circle for hit detection then a smaller circle on top of this with a thick line width and transparent fill. But not sure if this is the best way to do it.

**Comment by liabru** [comment]
This should be possible, to do it you'll need to construct a compound body made of many small wedges shaped in a ring. Here's an example of this type of construction:

<img src="https://2.bp.blogspot.com/-SLgd587C0U0/UZKcz_KAZdI/AAAAAAAABtQ/Pf0e_ZaXKPk/s1600/HA+Bricks+2.jpg" width="200">

You can create each part individually and then use `Body.setParts` on another body to contain them all.

**Comment by liabru** [comment]
I just came across this [codepen example](https://codepen.io/Alca/pen/GWEWja) that happens to do almost exactly this!

**Comment by arjuaman** [comment]
@liabru This is done using p5 library, shouldn't the answer be independent of extra libraries?
