### ISSUE TITLE
Placing text on Body.circle

### ISSUE THREAD

**Issue by kujma10** [liabru/matter-js#383]
Hello,

Is there any way to place the text on the `body.circle`? 
Want to have something similar in this picture:
<img width="67" alt="screen shot 2017-03-10 at 3 56 19 pm" src="https://cloud.githubusercontent.com/assets/2605976/23797793/31c418a4-05aa-11e7-9ba5-0450bca5dd19.png">

I also want it to modify often and easily , for example change "A0" text  with "A1" and so on

Thank you

**Comment by liabru** [comment]
There's nothing built in for this, you'll need to write your own renderer. See [Rendering](https://github.com/liabru/matter-js/wiki/Rendering).
