### ISSUE TITLE
Where star? Code from example

### ISSUE THREAD

**Issue by Edisoni** [liabru/matter-js#386]
![2017-03-11 17 50 26](https://cloud.githubusercontent.com/assets/10086099/23824227/750704bc-0683-11e7-9fc8-4e758c8b07e7.png)
   var vertices = [{
            x : 50,
            y : 0
        },{
            x : 63,
            y : 38
        },{
            x : 100,
            y : 38
        },{
            x : 69,
            y : 59
        },{
            x : 82 ,
            y : 100
        },{
            x : 50,
            y : 75
        },{
            x : 18,
            y : 100
        },{
            x : 31,
            y : 59
        },{
            x : 0,
            y : 38
        },{
            x : 37,
            y : 38
        }];

        var star = Matter.Vertices.create(vertices);
        var ground = Bodies.fromVertices(300, 300, star, {isStatic: true}, true);

**Comment by liabru** [comment]
You need to load [polydecomp](https://github.com/schteppe/poly-decomp.js) to use concave vertices.
