### ISSUE TITLE
Translate a rectangle

### ISSUE THREAD

**Issue by Saurabh0707** [liabru/matter-js#388]
i want to translate top and bottom bars when mousemove is along x axis and translate left and right bar when mousemove is along y axis.
But major problem is that 'x' on mousemove is added to the previous 'x'. 

CODE:
 Events.on(this.mouseConstraint, 'mousemove', function(e) 
        {
            let mousePosition = e.mouse.position;
                      
            if(mousePosition.x>mousePosition.y)
            {
                Body.translate(bars.top_bar,{x:10,y:0});
                Body.translate(bars.bottom_bar,{x:10,y:0});
                               
            }
            else if(mousePosition.x<mousePosition.y)
            {
           
                Body.translate(bars.left_bar,{x:0,y:10});
                Body.translate(bars.right_bar,{x:0,y:10});
                        
            }
            if(mousePosition.x>mousePosition.y)
            {
                
               
                Body.translate(bars.top_bar,{x:10,y:0});
                Body.translate(bars.bottom_bar,{x:10,y:0});
                               
            }
            else if(mousePosition.x<mousePosition.y)
            {
           
                Body.translate(bars.left_bar,{x:0,y:10});
                Body.translate(bars.right_bar,{x:0,y:10});
                        
            }

        });

**Comment by liabru** [comment]
I'm not sure what you mean, can you explain a bit more?
