### ISSUE TITLE
0.12 release

### ISSUE THREAD

**Issue by lplume** [liabru/matter-js#390]
Shouldn't you tag the latest 0.12 release? Just try to install throug bower, find out the installed version is 0.10.

Regards,

m.p.

**Comment by liabru** [comment]
Doh, the tags were not pushed by my release script like they usually are. Good catch, thanks. Does it work now?

**Comment by lplume** [comment]
Gonna try tomorrow ^^ not sure how i get it to download the 0.12 version in the end btw. I discover it while trying to add matter's attractors plugin btw. So, ttul =)

**Comment by lplume** [comment]
Confirmed, now bower install the 0.12.0 release =)

regards,

m.p.
