### ISSUE TITLE
Create chain between objects with enabling collision

### ISSUE THREAD

**Issue by kujma10** [liabru/matter-js#393]
Hello,
I want to have Constraint like object between two bodies, however I don't want it to prevent collision. So basically I want just a chain between two bodies (with some length) which does not make bodies to loose a speed and make them collide to each other (i.e a chain should be elastic). I know Constraints are meant to fix the distance between two bodies,  but maybe there is a way to implement such kind of behavior.
Thanks

**Comment by liabru** [comment]
Did you try removing the `collisionFilter` options from the [chains example](https://github.com/liabru/matter-js/blob/master/examples/chains.js#L42-L60)? That might be what you need?
