### ISSUE TITLE
Possible to draw a curve / rope / rubber band like in the bridge example?

### ISSUE THREAD

**Issue by thomasduenser** [liabru/matter-js#396]
Hello,

is it possible to draw a curve/rope/rubber band like in the bridge example with only one element?
http://brm.io/matter-js/demo/#bridge

It should be a straight line at first and act like the bridge when some bodies are falling on it. Right now I have used the bridge example and modified it, but I haven't found a solution to make it perfect when chaining the rectangles together.

I would appreciate each hint and help very much!

**Comment by liabru** [comment]
Not possible using one element (it's a rigid body engine after all!), it has to be segmented and connected with constraints for it to act springy. Maybe when pin constraints (#71) are finished the bridge will be more stable (but at the cost of any springy-ness, it will be more like solid rope).

As for curved lines, [this project](http://superblob.org/) managed to do them pretty well, maybe try to examine their code!

**Comment by thomasduenser** [comment]
Thank you for the fast answer and for your awesome work on this engine!
