### ISSUE TITLE
Strange behavior with constraint between 2 non-static objects

### ISSUE THREAD

**Issue by DavidLanderosAlcala** [liabru/matter-js#397]
Hello
as you can see in the following example:
    https://jsfiddle.net/3q28tfa0/10/

I have 2 shapes connected with a simple constraint and it works properly. but...
if i modify the "wall" by making it no-static the constraint starts to behaves strege as if there was a lot of friction between them; Here the example :
    https://jsfiddle.net/3q28tfa0/11/

does anyone knows how to prevent that behavior ?

**Comment by liabru** [comment]
See #139 where I've just posted a new solution, closing as this is a duplicate.
