### ISSUE TITLE
How to change the shape of the curve?

### ISSUE THREAD

**Issue by zzbo** [liabru/matter-js#399]
I have drawn a curve grid body with method ```Bodies.fromVertices``` , I want to change the shape of the curve when I click a button, there are have some method to update it?

**Comment by liabru** [comment]
If the vertices are convex you can use [Body.setVertices](http://brm.io/matter-js/docs/classes/Body.html#method_setVertices). Depending on your situation, after you have used  `Bodies.fromVertices` you may be able to just loop through `body.parts` and use `Body.setVertices` on each part, so long as you guarantee each part stays convex.

If they're concave then this won't work, you'll need to use `Bodies.fromVertices` or write your own function that can decompose the vertices and update the body parts. See the source for [Bodies.fromVertices](https://github.com/liabru/matter-js/blob/master/src/factory/Bodies.js#L200-L328) to see what I mean.
