### ISSUE TITLE
Event type for detecting click on a specific body

### ISSUE THREAD

**Issue by gamecubate** [liabru/matter-js#400]
Something is not clear to me, despite reading of docs and browsing of examples code:

How does one listen for mouse clicks (or touches) on specific bodies?

```
Events.on(?, my-handler)
```

Is there a place where one can get a list of supported events?

**Comment by gamecubate** [comment]
Some more searches hint at the need to use DOM events for that. Not a big deal. Will close issue. But please add more Wiki content. Docs are pretty much useless in their current form.

**Comment by leohowl** [comment]
> Some more searches hint at the need to use DOM events for that. Not a big deal. Will close issue. But please add more Wiki content. Docs are pretty much useless in their current form.

I have the same problem, Can you provide me some ideas about using DOM events?

**Comment by df257** [comment]
Hello, I have the same problem

**Comment by bouraqadi** [comment]
Use `Events.on(aMouseConstraint, "mousedown", callback)`.  In the `callback` function  you can access the `aMouseConstraint.body`. It references the clicked body or `null` if you clicked the background.

See https://brm.io/matter-js/docs/classes/MouseConstraint.html#event_mousedown
