### ISSUE TITLE
How do I create (hinge) joints?

### ISSUE THREAD

**Issue by TheGreatYamcha** [liabru/matter-js#401]
I want to emulate a hinge joint on two bodies. My only idea was to use a `Constraint` on that point.
It works, however, it quickly slows down, even though I've set thee `friction` and `frictionAir` to `0`. I also tried to change the constraint's `stiffness`, but that didn't seem to help.
Is there a better way to do this?

**Comment by crazyyi** [comment]
I have the same question. Did you manage to work that out? I see someone did that with Box2D. I think matter.js can do this. I just don't know how. Also it would be great if there is a group for discussion rather than ask question in the issues tab.

**Comment by DavidLanderosAlcala** [comment]
Hello, Matter.js does not support revolute joints, I was traying to emulate the same behavior with distance contraints but i got into an issue #397. As i see, this "work around" only works with static objects connected to dinamic objects

example: https://jsfiddle.net/3q28tfa0/11/

**Comment by liabru** [comment]
See #139 where I've just posted a new solution, closing as this is a duplicate.
