### ISSUE TITLE
Translation animation more smoothly

### ISSUE THREAD

**Issue by fefe69** [liabru/matter-js#402]
Hello,

Firstable, thanks for this great library. It is very impressive.

I am working on a project which have a hundred balls in a box. We have a buttton "draw a ball". When we click on the button, we draw a ball from a box and we normally have an animation to take the ball and translate to a plate close to the box. 
We can also click many times on the button "draw a ball". If we had already taken a ball, the ball will translate from the plate to the box and we will draw a new ball.

My problem is that I am not using the velocity/force/inertia to translate the box but I change manually the position of the ball. As you can see, the result is far from the perfection. 

I have two questions:
    - Could you help to use the matter-js functions to have a perfect, smooth translation for each ball ?
    - Sometimes, a ball have a bug/conflict and it move from the box directly trough the right wall. Can i fix the bug ? 
  
You can see an example here : https://goo.gl/WmsCKi.

Thanks for your help.

**Comment by liabru** [comment]
Take a look at the [body maniuplation demo](http://brm.io/matter-js/demo/#manipulation) and the [code](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js).

Basically when moving a body like this, you should:

1. Set it static like `Body.setStatic(ball, true)`
1. Move its position using `Body.setPosition(ball, position)` _and_ set its velocity `Body.setVelocity(ball, velocity)` every frame, where `velocity` is the vector between positions
1. Disable static when putting it back `Body.setStatic(ball, false)`

**Comment by fefe69** [comment]
Thanks for your help.

I updated the translation with your recommandations (setPosition, setVelocity, setStatic) **but I do not know how I can do a curve translation (like a semi circle).**
**_Is there a function to do it ?_**

After, I will put a translation from the top to the plate next to the box.

**Comment by liabru** [comment]
There's nothing built in, it's a bit out of scope of the project, you'll need to use your own formulas for doing this. A common way is to use [Bézier curves](https://en.wikipedia.org/wiki/B%C3%A9zier_curve).

**Comment by codehacker101** [comment]
I need to smoothly translate a square to { x : 10, y : 10} of world. What am I doing wrong?
Body.setStatic(square, true);
Body.setPosition(square, {x : 10, y : 10});
Body.setVelocity(square, {x : 0.01, y : 0.01});
Body.setStatic(square, false);
