### ISSUE TITLE
Position canvas and make it responsive 

### ISSUE THREAD

**Issue by 2hands10fingers** [liabru/matter-js#403]
I have spent days trying to figure this out. The features claim the canvas can be responsive, but I haven't been able to figure out how to do that. I also, can't seem to position canvas to my HTML document. How would I go about doing these things?  Really appreciate any insight or help.

**Comment by liabru** [comment]
> I have spent days trying to figure this out. The features claim the canvas can be responsive, but I haven't been able to figure out how to do that.

What have you tried? Does `canvas { width: 100%; }` not work?

> I also, can't seem to position canvas to my HTML document. How would I go about doing these things?

Using CSS as you would to position any element. This isn't really anything specific to do with Matter.js?
