### ISSUE TITLE
FrictionAir Realistic

### ISSUE THREAD

**Issue by DestroyerPlays** [liabru/matter-js#404]
I am trying to make a simulation with your physics engine, each pixel represents a centimeter, and I need to know the details of frictionAir because I need to make it realistic and change with altitude, reflecting real air resistance, any help on the subject would be great.

**Comment by liabru** [comment]
The built in implementation is very simple and designed for use in things like games where it only needs to look reasonable. I'd suggest disabling it and applying your own air friction forces if you need something more realistic.

**Comment by DestroyerPlays** [comment]
May I ask how it works? So I can modify it to fit my needs, it will make it much easier. How much does it slow objects down and what are the parameters for it like does it count in area? Thank you in advance

**Comment by liabru** [comment]
Sure, here are the relevant lines in [Matter.Body](https://github.com/liabru/matter-js/blob/master/src/body/Body.js#L562-L568). It doesn't take area into account or anything like that, it's just a decay factor (e.g. subtract 1% of the body velocity per step) that looks pretty reasonable. If you find something similarly simple that works better please share!
