### ISSUE TITLE
How to repeat sprite in rectangle

### ISSUE THREAD

**Issue by lehoangvu** [liabru/matter-js#405]
Hi, I use rectangle and texture to create background, but I cannot repeat it.
Someone help me ? Thanks.

**Comment by liabru** [comment]
Unfortunately there's nothing built in for this, you'll need to write a renderer to do it. See the [Rendering](https://github.com/liabru/matter-js/wiki/Rendering) wiki page.

**Comment by lehoangvu** [comment]
Thankyou for your anwser.
