### ISSUE TITLE
[Enhancement] Add option for strokeStyle in the Renderer object

### ISSUE THREAD

**Issue by djipco** [liabru/matter-js#406]
It would be nice to have an option for `strokeStyle` in the `Renderer`. This way, when using wireframes, we could change the color which sometimes is hard to see against content underneath (when using transparent background).

**Comment by liabru** [comment]
Hmm, are you talking about specifically customising the colours for wireframe mode?

**Comment by cotejp** [comment]
> Hmm, are you talking about specifically customising the colours for wireframe mode?

Yes.
