### ISSUE TITLE
Renderer warns about options.element when canvas is explicitely specified

### ISSUE THREAD

**Issue by cotejp** [liabru/matter-js#407]
When I create a new `Renderer` by specifying the `canvas` property and leaving the `element` property empty, I get a warning saying:

```
Matter.js: Render.create: options.element was undefined, render.canvas was created but not appended
```
As far as I'm concerned, I do not see why we would specify `element` if we are already telling it the canvas to use.

**Comment by mrspeaker** [comment]
Looking at the code, it [always prints if no element is provided](https://github.com/liabru/matter-js/blob/0895d81fa1a8ab06b35d5fefe9f2160c2f3a4c4b/src/render/Render.js#L107). Also, if you have `canvas` AND `element`, it will be moved from it's original location to a child of the element (perhaps this is desired?).

I personally think that the "element" and "canvas" should be merged into just "element". If `element` is a canvas element, it is used in place - otherwise a new canvas is created and appended as a child of `element`.

**Comment by cotejp** [comment]
> but perhaps the "element" and "canvas" could be merged into just "element". If element is a canvas element, it is used in place - otherwise a new canvas is created and appended as a child of element. Though then this would be an API change.

This makes sense!

**Comment by liabru** [comment]
I think the error message was in there because some people were confused, but maybe I should review this if I can think of a way to avoid any breaking API change.

**Comment by cotejp** [comment]
As far as I can tell, this has been fixed in edge release (0.14.1). Therefore, I'm going to close this issue. Thanks!

**Comment by jyeann** [comment]
i tried copy paste from the code documentation to test out. the error appear
matter-js: Render.create: options.element was undefined, render.canvas was created but not appended warn...

@djipco how did you solve this? i'm having matter-js-0.16.1 ver

**Comment by djipco** [comment]
This was a long time ago but I believe I simply used v0.14.1.

**Comment by liabru** [comment]
@jyeann could you show share the code for your setup here?

**Comment by BigbrainNgl** [comment]
yea I'm having the same issue

**Comment by jewelsonn** [comment]
Render.create: options.element was undefined, render.canvas was created but not appended warn,
I don't know why is it breaking even now.. shouldn't this be fix till now? if I do 
`var render = Render.create({
     element: document.getElementById('canvas'),
     engine: engine,
     options: {
         width: 150,
         height: 150,
         showStats: false,
         showPerformance: false
     }
 });`

And if even I do 
` 
var canvas = document.getElementById('canvas');
var render = Render.create({
     canvas: canvas,
     engine: engine,
     options: {
         width: 150,
         height: 150,
         showStats: false,
         showPerformance: false
     }
 });`
	I get the same error.. I just want to move the Renderer in the specified Canvas, not inside BODY

**Comment by it6aid** [comment]
This come back:
matter-js: Render.create: options.element was undefined, render.canvas was created but not appended warn
My version: 0.18.0
```
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Rush</title>
	<style>
		html,
		body {
			height: 100%;
			margin: 0;
			width: 100%;
		}
	</style>
	<script src="assets/lib/matter/0.18.0/matter.min.js"></script>
</head>
<body>

</body>
<script>
	// module aliases
	var Engine = Matter.Engine,
		Render = Matter.Render,
		Runner = Matter.Runner,
		Bodies = Matter.Bodies,
		Composite = Matter.Composite;

	// create an engine
	var engine = Engine.create();

	// create a renderer
	var render = Render.create({
		element: document.body,
		engine: engine
	});

	// create two boxes and a ground
	var boxA = Bodies.rectangle(400, 200, 80, 80);
	var boxB = Bodies.rectangle(450, 50, 80, 80);
	var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

	// add all of the bodies to the world
	Composite.add(engine.world, [boxA, boxB, ground]);

	// run the renderer
	Render.run(render);

	// create runner
	var runner = Runner.create();

	// run the engine
	Runner.run(runner, engine);

</script>
</html>
```
