### ISSUE TITLE
Render bounds

### ISSUE THREAD

**Issue by Rodeoclash** [liabru/matter-js#408]
Hey @liabru. This isn't an issue but a request for help, so let me know how I can buy you a beer.

I have a strange problem that you can see in action on: http://richardson.co.nz/

On initial render, everything works great. However something in my resize code is not behaving correctly. If you load the page with a short browser window and expand it vertically, you'll notice elements in the game will be removed as if the canvas was in the old location.

I'm pretty sure this is something to do with `render.bounds`. I'm resizing the canvas element to fit the screen but I can't figure out how the `render.bounds` should be calculated. Any time I try to recalculate them based on canvas size, it distorts the rendering. `world.bounds` are set to Infinity in all directions so it doesn't seem to be that either.

I was hoping you might look at it for five seconds and point me in the direction I should be looking. Again, sorry for the request for help ☹️

**Comment by liabru** [comment]
Not sure I can replicate a problem so maybe you fixed it? 

This is a long shot but take a look at the new [Render.lookAt](https://github.com/liabru/matter-js/blob/master/src/render/Render.js#L161-L174) function which handles fitting objects in view no matter what the canvas aspect ratio is by scaling.

You can use it like this:

```js
    Render.lookAt(render, {
        min: { x: 0, y: 0 },
        max: { x: 800, y: 600 }
    });
```

You can also pass it a body or array of bodies and then set a padding e.g.:

```js
    Render.lookAt(render, player, {
        x: 400,
        y: 300
    });
```

**Comment by nukadelic** [comment]
Can you reopen this issue? I'm facing similar problem and haven't solved it yet. My objective is to preserve aspect ratio while user resizes browser window ( this is needed for portrait / landscape orientation support for mobile ). I have included the code below: 

### CSS 
```
html, body 
{
  padding: 0;
  margin: 0;
  min-height: 100%;
  overflow: hidden;
}
```

### HTML
```
<body>
  <div><canvas></canvas></div>
</body>
```

### Script

**Constructor**
```
// ...
    this.container = container; // div element reference 
    this.canvas = canvas; // canvas element reference 
    this.engine = Engine.create();
    this.render = Render.create({
      element: container,
      canvas: this.canvas,
      engine: this.engine,
      options: 
      {
        hasBounds: true,
        width: 400,
        height: 400,
        background: '#AAA',
      }
    });
    Render.run(this.render);
    Engine.run(this.engine);
 
   // ... 
   // add a simple physics object
   // ...

   // reset min bounds ( ? )
    this.render.bounds.min = { x:0,y:0 };
    
    // Save starting render bounds to calc scale ratio later  
    this.renderBounds = 
    // Autofit max bounds to current render bounds
    this.render.bounds.max = 
    { 
      x : this.render.options.width,
      y : this.render.options.height 
    };

    // Initial render bounds ratio 
    this.renderRatio = this.renderBounds.x / this.renderBounds.y;

    // attach event listener & force event resize
    window.addEventListener("resize", this.eResize.bind( this ) );
    this.eResize();
// ...
```
**Resize event**
```
// On browser resize, change canvas size to fit full width
function eResize() 
{  
    // resize canvas
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerWidth * this.renderRatio;

    // Current screen scale ratio relative to starting canvas size
    var screenRatio = this.renderBounds.x / window.innerWidth;
    
    // calculate new render bounds based on old size times new ratio
    this.render.bounds.max = 
    { 
      x : this.renderBounds.x * screenRatio,
      y : this.renderBounds.y * screenRatio
    };

    // Doesn't fix problem : 
    // Render.lookAt( this.render, {
    //   min: {x:0,y:0},
    //   max: {x:10000,y:10000}
    // });

    // Doesn't fix problem : 
    // Expend world bounds on resize
    // this.world.bounds.min = { x: -333, y:-333 };
    // this.world.bounds.max = { 
    //   x : 10000,
    //   y : ( 333 + this.renderBounds.y ) * screenRatio
    // };
}
```
