### ISSUE TITLE
On mousemove i am dragging a polygon with the help of mouse.position . the problem is that when i move the mouse a bit fast , their seems to be a lag. I want to make sure that the movement is elastic. 

### ISSUE THREAD

**Issue by akshay1bajaj** [liabru/matter-js#411]

**Comment by liabru** [comment]
I suspect this is probably just because mouse events have inherent lag due to browser implementation. It's often a good idea to interpolate between two mouse points and add extra points. Unless you give any code examples, there's not much more I can help with.
