### ISSUE TITLE
Matter.Composite.allBodies does not seem to go recursive

### ISSUE THREAD

**Issue by frenchfaso** [liabru/matter-js#413]
Create a group of bodies like the cross in the Compounds example,
Add the group to the world
call "Matter.Composite.allBodies(engine.world)" and you get only the parent object.
Shouldn't you get an array of bodies, containing recursively also all parts bodies?
Thanks, and btw great lib!!!

**Comment by liabru** [comment]
This is intentional because parts are not considered bodies themselves, they're not independent. So you'll need to loop through each parts array too if this is what you need.

**Comment by frenchfaso** [comment]
Thank you for the superfast reply :-D
I was trying to do all the rendering in 1 loop with p5.js and since I added a "group" object, I stumbled upon this issue.
I'll do the parts array looping, one last question, I should skip the first object in the parts array, correct?
It's a reference to itself?
Thanks!

**Comment by liabru** [comment]
Exactly the first object is a self reference.
