### ISSUE TITLE
Is it possible to render a new image at run-time repeatedly,after at the initial phase an image was already loaded. Plus is it possible to render animated gifs.

### ISSUE THREAD

**Issue by akshay1bajaj** [liabru/matter-js#414]
Matter.Body.set(test.render.sprite,"texture", './img/ball.png');

So, we have taken this approach . is this right or not? Or a better approach is also possible.
And any help on animated gifs?

**Comment by liabru** [comment]
I think that approach should work fine. There's no built in support for animated gifs, you might want to look at something like [pixi.js](http://www.pixijs.com/) and build a custom renderer.

**Comment by TimuJiang** [comment]
Matter.Body.set(test.render.sprite,"texture", './img/ball.png');

**Comment by TimuJiang** [comment]
Matter.Body.set(test.render.sprite,"texture", './img/ball.png');
I try this  and it's not work

**Comment by liabru** [comment]
If it doesn't then maybe you need to do it like this:

```js
return Bodies.rectangle(x, y, 64, 64, {
    render: {
        sprite: {
            texture: './img/ball.png'
        }
    }
});
```

**Comment by RomanSkrypnik** [comment]
@liabru looks like a crutch
