### ISSUE TITLE
Tutorial for integration into React.js

### ISSUE THREAD

**Issue by gavinpatkinson** [liabru/matter-js#415]
Are there plans to make such a tutorial? Does anyone have a project that they'd be willing to share that does this? #

**Comment by lur9622** [comment]
I bump this. I have same problem. It was a good idea to have some support for React.

*For the moment, I use the react-konva package. He allows integration of "react" with the canvas.

*By the way, you just put the stuff into Matter js. React-konva functions as a representation of these elements. You draw these elements on the right map. You give the angle, the position, the size.

*But there are still a lot of problems. Like:
- drawing an SVG object(isommetric map for example). Its hard to make but possible.
- Moving "camera" behind the player.
etc.

**Comment by liabru** [comment]
As mentioned, there's [react-game-kit](https://github.com/FormidableLabs/react-game-kit) that seems to integrate react. It's out of the scope of this project though so it's not something I'll personally tackle but others may be interested in creating some sort of plugin?

**Comment by lur9622** [comment]
Great pity but I understand. If anyone would be interested in creating such a plugin or have an idea how to do it in a simple way then I'm looking forward to :D. best regards.

**Comment by liabru** [comment]
Closing this as it's out of scope of the project.
