### ISSUE TITLE
Clipping textures of a body?

### ISSUE THREAD

**Issue by voydz** [liabru/matter-js#416]
Hey,

I am playing around with matter. Recently I faced the problem, that I need to clip a given textures to the bounds of the body.

Anybody got an idea how to tackle this? I searched the docs, but I can't find an option for this.

Thanks in advance.

**Comment by liabru** [comment]
There's nothing for this in the built in renderer unfortunately. I suggest you fork it and add the feature, see [rendering](https://github.com/liabru/matter-js/wiki/Rendering). There's an [example on codepen](https://codepen.io/majman/pen/reqzBW) that does something similar, check it out.

**Comment by voydz** [comment]
Hi @liabru,
thanks for the information.

I got myself a working implementation. For now its way to specific and dirty to contribute back to matter-js. 

For anyone who is curious, or wants to implement this in matter-js, I made a gist containing my current renderer code [here](https://gist.github.com/voydz/3d36d8c3a7021707100fff8449ee4d39).  This is basically a quick an dirty extend/override of matter's default renderer.

**P.S.:** I know it does not belong here @liabru, but I would be very glad if you could take a look at https://github.com/liabru/matter-attractors/issues/1 (PR is included).
