### ISSUE TITLE
So , i have used isSensor : true for a body (A). And i have another body (B) that i am moving on the mousemove. When i drag the body(B) then the second Body(A) also starts moving and keep getting dragged in Ipad only. Any leads on this. Is their any resolution to this particular issue? 

### ISSUE THREAD

**Issue by akshay1bajaj** [liabru/matter-js#417]
Events.on(mouseConstraint, 'mousemove', function(e) {
        var Body = Matter.Body;
        var $mouseX = 0;
        var mousePosition = e.mouse.position;
        if (poly) {
            var compound = poly;
            Body.setVelocity(compound, { x: 0, y: 0 });
            Body.setPosition(compound, { x: mousePosition.x, y: mousePosition.y });
            Body.setStatic(poly, false);
        }
    });

  var stack = Composites.stack(20, 0, 1, 1, 0, 0, function(x, y) {
            test = Bodies.circle(x, y, 46, {
                density: 0.0005,
                frictionAir: 0.06,
                restitution: 0.3,
                friction: 0.01,
                render: renderbg()

            });
            return test
        });

        function renderbg() {
            return {
                sprite: {
                    texture: './img/sprit.png'
                }
            }
        }
        World.add(world, stack);
The gravity for y axis has been set to zero.
Any resolution to this issue?

**Comment by liabru** [comment]
Can you put this in a codepen on jsfiddle?

**Comment by akshay1bajaj** [comment]
@liabru Yeah, so the issue has been fixed. It was a small error on my end . I didn't set isStatic: true for the Body(A). Doing so removed the above issue. Thanks!!
