### ISSUE TITLE
Collision not working as expected

### ISSUE THREAD

**Issue by Titozzz** [liabru/matter-js#418]
Hello, I'm planning on using MatterJS to power all physics behind my game, let's say that right now i'm trying to achieve something like a simple terraria-like world. I tried 2 approches :

- having my world as a big compound object and using setParts to remove the blocks, but I have trouble splitting compounds objects into 2.

- having all the world as static different blocks, but then I ran into this issue :
![bug](https://cloud.githubusercontent.com/assets/6181446/25977154/44194476-366e-11e7-9104-5b9df3bd3635.gif)

After a timeout, i remove the static from one cube and it goes inside the ground and falls. I've checked the solidity of the ground by letting a sphere fall on it... Is there a way my block could stay there ?

PS: If I give a big lift to my free block it will fly and land back on the ground, but I don't want to do that ..

**Comment by liabru** [comment]
Are you using `Body.setStatic(body, false)` or `body.isStatic = false`? As it needs to be the former.

**Comment by Titozzz** [comment]
I am doing the first one. 
I tried a new approach that is now working tho. 
I'm creating empty static objects, and using setParts after their creation instead of usings parts option because it was doing a lot of weird stuff.

**Comment by liabru** [comment]
I'd appreciate a jsfiddle or codepen if you have time? Thanks

**Comment by Titozzz** [comment]
All right I think the bug was coming from me not giving the good part in the setParts function ( It Must be a reference to the parent object, even if we give the parent object as a parameter .. )
