### ISSUE TITLE
Add support for transparent backgrounds?

### ISSUE THREAD

**Issue by azarus** [liabru/matter-js#421]
Hey,

I am using your renderer to display nice physics debuggings in my engine, but In the renderer the transaprent option is not quite working.

`	background: 'transparent',`

This way i could align the debug renderer with what my engine is drawing, But it is hard to overlay.
My current tricky way:
document.getElementById("physicsDebugger").childNodes[0].style.opacity = "0.5";

 But it would be great if the renderer could be added to a custom canvas.

Thanks a lot for the great work :)

a fan of Matter.js

**Comment by liabru** [comment]
Late reply! You need to also set the `wireframeBackground` too:

```js
background: 'transparent',
wireframeBackground: 'transparent'
```
