### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by Tarnadas** [liabru/matter-js#422]
Hi,

I know that WebAssembly is still very young, but will you support it? I guess it would make a big performance change in a physics engine like this.

**Comment by liabru** [comment]
Well as far as I know to use WebAssembly it would require manually porting the codebase to into assembly to get much benefit. This is a huge task and it would essentially be a new project. Though, if it is possible to port only the most performance intensive parts of the engine (like collisions) it might be worth it.
