### ISSUE TITLE
Double Pendulum not working as expected

### ISSUE THREAD

**Issue by SaarLevy** [liabru/matter-js#423]
So I write simulation for a double pendulum (something like this: https://www.youtube.com/watch?v=hXOEoH5q3Hw&t) and it just doesn't seem to work, it's really slow and not chaotic at all.

I think it has to do with fine tuning the parameters but I'm not sure, does anyone have any input?

Double pendulum repo: https://github.com/SaarLevy/double-pendulum

**Comment by liabru** [comment]
Sorry I forgot to reply here, as of `0.13.0` constraints were improved and I actually put together an example showing a [double pendulum](http://brm.io/matter-js/demo/#doublePendulum). It's still far from perfect and it doesn't run forever like it should, but it does seem to show chaotic patterns.

**Comment by SaarLevy** [comment]
Wow, forgot I had this issue open.

Thanks for the answer and as always thank you for your work!
