### ISSUE TITLE
MouseConstraint not working in React

### ISSUE THREAD

**Issue by byjoh** [liabru/matter-js#427]
The MouseConstraint doesn't seem to be working in React.  The same code works outside of React, but when I drop it into a React component, everything works fine except for the MouseConstraint... here is the code for that piece: 

```
        let mouse = Matter.Mouse.create(render.canvas);
        let mc = Matter.MouseConstraint.create(engine, {
            mouse: mouse,
            constraint: {
                render: {
                    visible: false,
                },
                stiffness:1.0
            }
        });

        Matter.World.add(world, mc);
        render.mouse = mouse;
```

Am I doing something wrong or is it not supported in React?

**Comment by liabru** [comment]
I've not used the engine with react so I'm not able to say, but I don't see why it shouldn't work.
If it helps, there's a guy who built a [react game engine](https://github.com/FormidableLabs/react-game-kit) using matter-js maybe take a look at what he did.

**Comment by jenish-jain** [comment]
@byjoh were you able to find out the issue? i was trying the same and not able to use mouseConstraint in react

**Comment by liabru** [comment]
@jenish-jain I'm going to guess the solution is going to involve something like `Matter.Mouse.setElement(mouseConstraint.mouse, canvasRef.current)` inside a React `useEffect`?

**Comment by lilmart210** [comment]
If you are having this problem in react, check your element configuration.
`
<div ref={parent}>
    <canvas ref={child}/>
</div>
`
In this default configuration mouse events on canvas won't reach the element. 
wrong
`
const mouse = Matter.Mouse.create(child.current);
`
right
`
const mouse = Matter.Mouse.create(parent.current);
`
Full Example
`
    const mouse = Matter.Mouse.create(parent.current);
    const mconstraint = Matter.MouseConstraint.create(engine,{
      mouse : mouse,
      constraint : {
        stiffness : .2,
        render : {
          visible : false
        }
      }
    });
`
