### ISSUE TITLE
Matter overwrites canvas size

### ISSUE THREAD

**Issue by kevinkace** [liabru/matter-js#429]
Likely related to https://github.com/liabru/matter-js/issues/168

When providing a canvas to draw on, Matter overwrites the existing canvas dimensions even when none are provided.

eg:
```js
const canvas = document.getElementById("canvas"); // has height and width attrs
engine = M.Engine.create({
    render : {
        canvas
    }
}); // canvas is now resized to default 800x600
```

I wish to set/manage the canvas size outside of Matter.

**Comment by xehpuk** [comment]
Any updates on this?

**Comment by unicitee** [comment]
Please, try to assign the size of the canvas after the engine initialization
`
    canvas = document.getElementById("canvas") ;
    // create an engine
    var engine = Engine.create();

    // create a renderer
    var render = Render.create({
        // element: document.body,
        canvas : canvas ,
        engine: engine
    });
    canvas.height = 400 ;
  
`

**Comment by kevinkace** [comment]
I haven't used MatterJs in quite some time, but I think adding the height/width in the `options` property would work for my case. I'm going to close this. :)
