### ISSUE TITLE
setStatic method bug

### ISSUE THREAD

**Issue by hyunsooda** [liabru/matter-js#430]
Hello, I’m Korean universty student that using well your library.
I have been used your library but, I found that there is a bug so, I am writting article for you.
Bug is below.
for example,

const a = Bodies.rectangle(10,10,10,10);
Events.on(engine,’mouseConstraint’, (e) => {
	if(e.mouse.position.x > 300 && e.mouse.position.x < 500)
		Body.setStatic(a,true);
	else
		Body.setStatic(a,false);
});

In that case, incur error that body of a is erase without intention.

I’ll wait your response.

**Comment by liabru** [comment]
Closing this one, as it should be covered by #641.
