### ISSUE TITLE
Friction?

### ISSUE THREAD

**Issue by dxu** [liabru/matter-js#432]
Hi, sorry for the basic question, but I'm having trouble understanding how friction actually works with Matter.js. 

My world has a gravity of 10 in the `y` direction. Currently I have three objects: Ground, BoxA, and BoxB, with these attributes:

1. All of them have both `frictionStatic` and `friction` values of 1. 
2. Ground is static, BoxA and BoxB are not
3. BoxA is 32x32, BoxB is 50x50.
3. BoxA has a density of 0.001, BoxB has a density of 100000, and Ground has a density of 1000

I have set up some key handlers to call applyForce on keydown. on BoxA, so that it pushes into BoxB.

No matter how large of a mass or density I give Box B, whenever BoxA touches BoxB, BoxB starts moving instantly. I would expect that the higher i set the density or mass of BoxB, the static friction would prevent me from budging BoxB at all.

I originally also did this by just calling `setVelocity` on BoxA (which would be preferable), but I was running into the same issue.

Am I misunderstanding how friction is being simulated here? I would assume that higher gravity or higher mass would increase normal force, which should prevent the box from being pushed, but that does't seem to be the case?

**Comment by liabru** [comment]
> Am I misunderstanding how friction is being simulated here? I would assume that higher gravity or higher mass would increase normal force, which should prevent the box from being pushed, but that does't seem to be the case?

To some extent yes, the static friction will increase with more normal force but the effect is unlikely to be as large as you might be hoping for. It is implemented but the effect is purposely limited for stability reasons.

I feel like your values for friction, density and gravity are too large and too diverse. Also a mass difference that large will cause instability. I'd need to experiment with your code to get the result you want, can you provide a jsfiddle?
