### ISSUE TITLE
matter.js doesn't appear to want to initiate

### ISSUE THREAD

**Issue by BenPav** [liabru/matter-js#435]
I am trying to create a hailstorm, but I'm starting with the sprite example:

http://dev-know-what-to-do.pantheonsite.io/   

It's not rendering at all.  Any suggestions?  Thanks!

**Comment by liabru** [comment]
You're missing a call to `Example.sprites`?

**Comment by BenPav** [comment]
uh, what?  This is your exact code from your pin.

**Comment by BenPav** [comment]
Ok, I saw the problem and fixed it.
