### ISSUE TITLE
Why constraint doesn't work?

### ISSUE THREAD

**Issue by jackandjohn** [liabru/matter-js#442]
[Here](https://jsbin.com/qacuzebegi/edit?html,output) is my code.

**Comment by liabru** [comment]
It's because you attached it to a body part instead of the parent body.
So you should change your code to use `bodyA: metalFrame` instead.

**Comment by jackandjohn** [comment]
Is there any way to attach it to the center of `metalFrameA`? Thanks.

**Comment by liabru** [comment]
Sure try using `pointA: Vector.sub(metalFrameA.position, metalFrame.position)`.
