### ISSUE TITLE
Contributing [getting started]

### ISSUE THREAD

**Issue by alireza-a** [liabru/matter-js#445]
Hi, I enjoyed reading the codebase, and I'd like to contribute. I've looked into the issues, but I am not sure where to get started. I'd appreciate if you can point me to something.

**Comment by liabru** [comment]
Hey, what sort of thing are you interested in working helping with? Features? Bugs? Documentation? Examples?

**Comment by alireza-a** [comment]
Right now I am occupied with final exams, so I like to work on something with low priority. I prefer working on features, examples, documentation, and bugs and in that order.
