### ISSUE TITLE
How to destory bodies or reuse bodies or reset bodies?

### ISSUE THREAD

**Issue by milhous** [liabru/matter-js#446]
Hi, Liabru:

How to destory bodies or reuse bodies or reset bodies in matterJS?

Creating  more than a thousand rigid bodies causes memory leaks and slow down performance.

thanks.

**Comment by liabru** [comment]
I'd suggest using `Composite.remove(world, body)` and keeping a pool of removed bodies. When you need to create a new body, recycling one from the pool if it is not empty. You should just need to set the correct properties again using `Body.set({ .... })` which will automatically use the correct setters for a batch of properties. Remember to reset other properties back to their defaults too (read the source / docs). I'd also suggest changing the id too using `id: Common.nextId()`.

**Comment by milhous** [comment]
Hi, Liabru:

Thank you for your advice, my problem has been solved. : )
