### ISSUE TITLE
Changing the size of just one body in a newton's cradle.

### ISSUE THREAD

**Issue by tmarasco125** [liabru/matter-js#447]
I was wondering if there is a way to change just a single body in a Newton's Cradle composite, since making a new composite has you decide on a universal body size for each body. Is it possible to make the last body much larger than the rest of them while still using a newtonsCradle composite and not having to build one from scratch?

Thank you!

**Comment by liabru** [comment]
Sure, you should make your own copy of the code for [Composites.newtonsCradle](https://github.com/liabru/matter-js/blob/master/src/factory/Composites.js#L214-L228) and then modify the creation of the circles as you see fit.

**Comment by tmarasco125** [comment]
HI! Thank you, but could you show me an example? I understand what you're saying but I'm still having trouble figuring out how to use that concept to make individual weights a different size.

**Comment by liabru** [comment]
The link shows exactly the code that creates the cradle, just change the `size` in each iteration of the loop as needed.
