### ISSUE TITLE
Trying to make more than one Composites.stack results in only the first stack being added to the world

### ISSUE THREAD

**Issue by Nickh90** [liabru/matter-js#450]
Hello. I'm still getting started with matter.js and ran into a slight problem. I'm sure I made some silly mistake.

I'm trying to add multiple stacks of balls 1 for each size and color. unfortunately it is only adding the first stack to the world.
```javascript   
var stack = Composites.stack(100, 100, 5, 10, 50, 50, function(x, y) {
        return Bodies.circle(x, y, 15, { restitution: 1, render: ballStyle });
    });
	    var stack1 = Composites.stack(120, 120, 5, 10, 75, 75, function(x, y) {
        return Bodies.circle(x,y, 10, { restitution: 1, render: ball2Style });
    });
		    var stack2 = Composites.stack(140, 140, 5, 10, 25, 25, function(x, y) {
        return Bodies.circle(x, y, 5, { restitution: 1, render: ball3Style });
    });
    World.add(world, stack,stack1,stack2);```

**Comment by Nickh90** [comment]
I resolved it. Here's what I came up with
`    var bodyStyle = {
    	fillStyle: 'transparent'
    };
    var ballStyle = {
    	fillStyle: 'rgba(0,0,0,0.45)'
    };
    var ball2Style = {
    	fillStyle: 'rgba(0,0,0,0.45)'
    };
    var ball3Style = {
    	fillStyle: 'rgba(0,0,0,0.45)'
    };
    // scene code
    World.add(world, [
    	Bodies.rectangle(0, 0, 1920, 100, {
    		isStatic: true,
    		render: bodyStyle
    	}),
    	Bodies.rectangle(0, window.innerHeight,
    		window.innerWidth * 2, 100, {
    			isStatic: true,
    			render: bodyStyle
    		}),
    	Bodies.rectangle(0, 0, 100,
    		window.innerHeight * 2, {
    			isStatic: true,
    			render: bodyStyle
    		}),
    	Bodies.rectangle(window.innerWidth,
    		0, 500, window.innerHeight * 2, {
    			isStatic: true,
    			render: bodyStyle
    		}),
    	Composites.stack(100, 100, 5, 10,
    		50, 50,
    		function(x, y) {
    			return Bodies.circle(x, y, 15, {
    				restitution: 1,
    				render: ballStyle
    			});
    		}),
    	Composites.stack(120, 120, 5, 10,
    		75, 75,
    		function(x, y) {
    			return Bodies.circle(x, y, 10, {
    				restitution: 1,
    				render: ball2Style
    			});
    		}),
    	Composites.stack(140, 140, 5, 10,
    		25, 25,
    		function(x, y) {
    			return Bodies.circle(x, y, 5, {
    				restitution: 1,
    				render: ball3Style
    			});
    		})
    ]);`

**Comment by liabru** [comment]
Looks like you solved it, but just in case: if you want to add multiple bodies in one call you need to pass an array, like this:

    World.add(world, [stack, stack1, stack2]);
