### ISSUE TITLE
Question: Struggling to understand collision with a boundary - Example given

### ISSUE THREAD

**Issue by cluber22** [liabru/matter-js#452]
I am struggling to understand why my simple test case of a ball bouncing off 4 boundaries is giving these results.

At the end of the simulation can any one explain what is happening i.e. why is the ball sticking to the right boundary and rolling down it. I thought it would would off the boundary like earlier in the simulation at higher speed.

The bottom line is that I always want it to bounce off the boundary according to The Law of Reflection. Angle of incidence = angle of reflection.

https://jsfiddle.net/8exLLLv6/35/

My question on SO: https://stackoverflow.com/questions/45224130/body-not-respecting-the-law-of-reflection-at-lower-speeds

Thank you

**Comment by liabru** [comment]
Try this out:

    Matter.Resolver._restingThresh = 0.1;

This is a known issue, for more info refer to #394. If you have any more questions please reply in that thread, thanks.

**Comment by cluber22** [comment]
Hi liabru,

I am not currently using **Matter.Resolver** currently in my example. Do I have to introduce this to solve the issue? Thanks.

**Comment by cluber22** [comment]
Thank you this did fix the issue! Great project.
