### ISSUE TITLE
How do I make a 'one way platform' collision?

### ISSUE THREAD

**Issue by praiseTheKek** [liabru/matter-js#456]
I would like moving object to collide when hitting quad body from one side. 

I also don't want to hit onCollide event listener on quad if possible.

e.g.
![a](https://user-images.githubusercontent.com/30218512/28803402-42bfbfdc-762a-11e7-9b53-68bf2217ed41.gif)

Best

**Comment by MarioDabrowski** [comment]
Looks like a similar question to https://github.com/liabru/matter-js/issues/352

You should be able to use velocity and [collisionFilters](http://brm.io/matter-js/demo/#collisionFiltering).

**Comment by liabru** [comment]
Exactly, also take a look at #284.
