### ISSUE TITLE
[Question] How to apply forces to bodies inside of a composite?

### ISSUE THREAD

**Issue by chasekap** [liabru/matter-js#458]
Syntactically, how could I apply forces to bodies inside of a composite? Is this even possible? 
Thanks

**Comment by liabru** [comment]
Sure, like this `Body.applyForce(composite.bodies[i], { ... }`

**Comment by chasekap** [comment]
I'm trying something like this : 
Matter.Body.applyForce(population[0].comp.bodies[0] , {position : { x : 100, y :100}} , {force : {x : 100, y : 100}}
and it doesn't seem to be applying. 
my console isn't throwing any errors. 
Thanks for your help!

**Comment by chasekap** [comment]
For reference , I am using p5.js as my renderer, and once the force is applied the body disappears

**Comment by chasekap** [comment]
![screen shot 2017-08-04 at 11 09 06 am](https://user-images.githubusercontent.com/19560435/28981166-833d4704-7905-11e7-9ac8-eb3a02a6a144.png)

**Comment by chasekap** [comment]
This is the object

**Comment by liabru** [comment]
The force is far too large, try something like `{ x: 0.01, y: 0.01 }`.

**Comment by chasekap** [comment]
Hey, I figured out the issue. {position : { x : 100, y :100}} should just be {x:100, y:100} and the same with the force vector. Thanks
