### ISSUE TITLE
Is it possible to make safe check to HTMLElement in Common.isElement

### ISSUE THREAD

**Issue by Mirodil** [liabru/matter-js#459]
Hi,

I'm trying to run matter-js in `react-native` environment and it fields to create Engine object because of this line https://github.com/liabru/matter-js/blob/master/src/core/Common.js#L179-L181 .

is it possible to make it for more safe check to DOM elements?

**Comment by liabru** [comment]
Can you provide the exact error message?

**Comment by Mirodil** [comment]
here is screenshot:
<img width="385" alt="screen shot 2017-08-09 at 1 41 20 pm" src="https://user-images.githubusercontent.com/1898801/29135568-9350a3dc-7d08-11e7-9ccd-b50781c5f676.png">

**Comment by jpagand** [comment]
FYI this commit added a regression because it was working prior to this
https://github.com/liabru/matter-js/commit/295cffeacfaf01af83bd19ea3710cf58e50843ed#diff-b31b513f97c8db0b0c9e3c8f7780b231

**Comment by liabru** [comment]
Ah! Maybe a merge went wrong somewhere then. Thanks for the info.
