### ISSUE TITLE
Adding retina support

### ISSUE THREAD

**Issue by pvienneau** [liabru/matter-js#46]
Have finished using the matter.js 0.8.0 build for a project, very nice. However, did attempt to add support for screen pixel ratio above 1 (such as retina) by hacking the library abit. Would be great to have this supported out of the box.

**Comment by pvienneau** [comment]
@liabru Very nice, thank you!

**Comment by liabru** [comment]
If you find any issues, please report them here, cheers

**Comment by SaFrMo** [comment]
For future reference, the `Engine.create` solution has been deprecated, and pixel ratio is set directly on the Renderer now ([link](https://brm.io/matter-js/docs/classes/Render.html#method_setPixelRatio)).

**Comment by yanballas** [comment]
> @pvienneau @aroman
> 
> This is now implemented if you wish to try it!
> 
> https://github.com/liabru/matter-js/blob/master/build/matter.min.js
> 
> There is a new option for the renderer `render.options.pixelRatio`. By default this is set to `1` which will still give the same results as before.
> 
> If you want to enable hidpi by automatic detection you should pass this option as `'auto'` when the renderer is created e.g.
> 
> ```
> Engine.create({
>     render: {
>         options: {
>             pixelRatio: 'auto'
>         }
>     }
> });
> ```
> 
> You can also use a fixed decimal value to vary render quality (e.g. `0.5`, `1`, `2`).
> 
> Note that hidpi is very processor intensive. While implementing this I found that using hidpi really starts churning my processor and it got hot quickly, so use with care!

Hi! I try to use that, cause i have a problem with sprite in mobile but then I actually lose the  wall and ground of the canvas and just zoom it in
