### ISSUE TITLE
[Deprecation] SVGPathElement.getPathSegAtLength

### ISSUE THREAD

**Issue by jackandjohn** [liabru/matter-js#460]
In Chrome 60.0.3112.90, there is a deprecation warning:
> matter.js:7433 [Deprecation] SVGPathElement.getPathSegAtLength is deprecated and will be removed in M62, around October 2017. See https://www.chromestatus.com/features/5638783282184192 for more details.

![image](https://user-images.githubusercontent.com/10008741/29164326-a2eb8b2e-7df1-11e7-8051-a8bbb70d5899.png)

**Comment by LittleMorakot** [comment]
Chrome 62 deprecated this API, but using the latest version pathseg can solve this problem

**Comment by liabru** [comment]
Thanks for the report, please refer to #196 for this issue which I will reopen.
