### ISSUE TITLE
How to change the center of mass / anchor point of a body?

### ISSUE THREAD

**Issue by AndreasRef** [liabru/matter-js#461]
Hi 

I want to be able to rotate a elongated rectangle not relative to its center, but relative to one of its end points. 
I have looked at this similar issue:
https://github.com/liabru/matter-js/issues/149

And it seems like I need to change the centre of mass of the rectangle to be at the pivot point

But how is that done? How do I set the anchor point (or change the center of mass) of a body? I cannot find it anywhere in the documentation.

**Comment by liabru** [comment]
Try this:

```js
body.position.x += offset.x;
body.position.y += offset.y;
body.positionPrev.x += offset.x;
body.positionPrev.y += offset.y;
```

Where `offset` is the vector of the new centre, relative to the current centre of mass.

**Comment by ajay1773** [comment]
@liabru  what is the positionPrev here?
