### ISSUE TITLE
How make gravityScale for body like in P2

### ISSUE THREAD

**Issue by Mirodil** [liabru/matter-js#462]
Hi,

I'm trying to do floating balloon with matter-js and every time body falls toward gravity. I tried to change `applyForce`, `friction` and `frictionAir`, `mass`, `density` but does not help. 

How to make like a `gravityScale` for body like in P2 library?

**Comment by liabru** [comment]
You should apply an upwards force (buoyancy) on every step, then it will rise.

**Comment by Mirodil** [comment]
Thank you for answer.
How to calculate that force, because `negative(gravity * mass)` it really big it kicks object out of screen immediately.
