### ISSUE TITLE
[HOW TO] create tearable cloth?

### ISSUE THREAD

**Issue by MegaUITeam** [liabru/matter-js#466]
How to create tearable cloth or tearable soft body ?

like this http://wellcaffeinated.net/PhysicsJS/#demo-6

**Comment by liabru** [comment]
Calculate the amount of 'stress' on each constraint, so something like the difference of its current length to its rest length, then if it's larger than some threshold 'break' it by removing that constraint from the world.

**Comment by MegaUITeam** [comment]
@liabru create demo)))) This would cause a wow effect

**Comment by liabru** [comment]
Too many other things to focus on for now, but I'd be interested in a pull request :)
