### ISSUE TITLE
How to change Rectangle width or height after creating?

### ISSUE THREAD

**Issue by MegaUITeam** [liabru/matter-js#469]
How to change Rectangle width or height after creating? I know that I can just move the vertices by hand, but why do it manually? Surely there is some special method for this? 

By the way, why do not you use classes or inheritance?

**Comment by liabru** [comment]
You need to create the new vertices and use `Body.setVertices(body, vertices)`. There's nothing built in for this specifically because there is no real notion of 'rectangle' or any other shape, it's all just vertices. Anything in `Bodies.*` are just helper factories to create common shapes.

**Comment by MegaUITeam** [comment]
Create 'rectangle' or any other shape classes, and add helper methods to control him =) No?

**Comment by liabru** [comment]
Sorry but this is something I'd rather leave to game engine developers, as I prefer to focus my time on the physics simulation and I also prefer the simplicity of just vertices rather than adding more abstractions on top.
