### ISSUE TITLE
Vector.angle don't work correctly

### ISSUE THREAD

**Issue by Qriva** [liabru/matter-js#471]
After hours of happy debugging of magic code I think that function is just bad or I don't understand the Math (it can be true actually 🥇 )

Your function currently do something like `atan2(y1-y2, x1-x2)` but [according to this site ](http://www.euclideanspace.com/maths/algebra/vectors/angleBetween/) this should be `atan2(v2.y,v2.x) - atan2(v1.y,v1.x)`

**Comment by liabru** [comment]
It depends on which angle you're looking for, see my answer in this [thread](https://github.com/photonstorm/phaser/issues/3009). Hopefully that answers it for you!

**Comment by Qriva** [comment]
So as I understand well - This is correct function but with misleading name ?
Description and name of function says clearly "it's angle between two vectors".
I understand that we can't change everything now because it used somewhere but it should be possible to change description of funtion at least and describe it better, something like:
`Returns the angle in radians between the vector/line created from provided two vectors and the x-axis (counter-clockwise)`

Also would be nice to see also the correct function but this is just nice addition.

**Comment by liabru** [comment]
You're right it should be documented clearer, maybe there could be an argument to choose which angle.
