### ISSUE TITLE
How do I get the code for the mobile demo?

### ISSUE THREAD

**Issue by Alina92** [liabru/matter-js#473]

**Comment by liabru** [comment]
It was turned into an example called gyro here is the [code](https://github.com/liabru/matter-js/blob/master/examples/gyro.js).

**Comment by Alina92** [comment]
Thank you very much, but I also want to consult, I met problems when doing the project, add a set of ice with the world. The add (world, the stack), and then delete the remove one by one, and then continue to add also with the world. The add (world, stack) ice can not good to add, what reason be?

**Comment by liabru** [comment]
Please can you open a new thread that includes an example for your issue? Thanks.
