### ISSUE TITLE
[FEATURE] Bullet test

### ISSUE THREAD

**Issue by MegaUITeam** [liabru/matter-js#475]
Your framework can do this? http://piqnt.com/planck.js/BulletTest

In this framework, the number of steps of the iteration is not sky-high. They just have an advanced collision detection system, like in Box2D https://github.com/shakiba/planck.js/tree/master/lib/collision

**Comment by liabru** [comment]
Please see thread #5 about continuous collisions, when the feature is complete there will be a test like this.
