### ISSUE TITLE
Strange behaviour if gravity is low ?

### ISSUE THREAD

**Issue by Qriva** [liabru/matter-js#476]
I seen somewhere that high friction values can casue bugs or strange movement (also tested it a little) but now I set `gravity `to `0.1` and my circles act very strange. Im not sure it's because gravity but this is the only factor i can see.
[Fiddle with example](https://jsfiddle.net/6poz3srf/1/)
How to fix it? and actually what cause this strange collision? is that bug or I did something wrong?

**Comment by JonathanMaes** [comment]
0.1 is actually a very large value for the gravity. I think the default is 0.001.
Having such a high gravity has your bodies accelerate very quickly to high velocities, so you get bugs like bodies flying through walls/ground because they just 'teleport' past them in 1 tick.
So, lower the gravity even more since it isn't "low" like you said in the title.

:)

**Comment by Qriva** [comment]
No way, look at [docs](http://brm.io/matter-js/docs/classes/World.html), default gravity for Y axis is `1`
```
World.gravity.y
- The gravity y component.
- Default: 1
```
This is actually way lower than default and all demo pages has gravity at 1.
There is also gravity scale factor what is `0.001` but I didnt touch this.
```
World.gravity.scale
- The gravity scale factor.
- Default: 0.001
```

**Comment by JonathanMaes** [comment]
I always modify the World.gravity.scale, that might be why.

**Comment by Qriva** [comment]
but still this exists anyway. I see, this happen when bodies moving slowly so it can be that low gravity helps to see it because simply bodies move slow.

**Comment by liabru** [comment]
Hey looks like your issue is mostly the same as #63?

**Comment by Qriva** [comment]
I think yes.
It looks like body "collide" as long as bounds of the body collide.

**Comment by liabru** [comment]
Thanks for the additional example, it's something I need to figure out a fix for! For now try to avoid things that will make the bodies move very slowly.
