### ISSUE TITLE
How to reset rotation of a Composite?

### ISSUE THREAD

**Issue by kittykatattack** [liabru/matter-js#477]
Hello!

I'm using a composite `car` object.
In the game that I'm making, it sometimes flips over. 
I'm trying to add a button that lets players restore the car to its original, unrotated state.
I'm aware of the `Composite.translate` method, but I'm unsure of how to use it in this case:

```
Composite.rotate(car, rotationValue, { x: targetX, y: targetY });
```

My questions are:

1. Is the `rotationValue` a number in Radians?
2. I believe that setting the `rotationValue` will rotate the composite relative to its current rotation.
How can I use this to find the composite's original, unrotated angle?
3. Does the x/y vector refer to a point on the composite object or in the World?

Any help much appreciated! 😄 🙏

**Comment by kittykatattack** [comment]
Here's what I've discovered so far:

1. Yes, it's in Radians.
2. You need to set this to difference between the current angle of rotation and your target rotation value. However, Composite objects do not have a `rotation` or `angle` property, so it doesn't seem possible to find out what it's current rotation angle is?
3. It's a point in the world, not the body.

Does anyone know how to find the current rotation value of a Composite?

**Comment by liabru** [comment]
There can be no strict definition for an angle of a composite, since it's just a set of bodies / constraints. It will depend on your use case! I'd suggest using the angle of the body of the car?
