### ISSUE TITLE
Pendulum that swings forever

### ISSUE THREAD

**Issue by kittykatattack** [liabru/matter-js#480]
Hello!

It is possible to create a pendulum that swings forever, without any loss of energy?
Can anyone which settings I should use?

Thanks! 🙏

**Comment by Qriva** [comment]
If you set `frictionAir `to 0 it still stops?

**Comment by liabru** [comment]
Yes set `frictionAir: 0` and also set `inertia: Infinity`. Though, this still probably won't make it last forever due to limitations of precision and accuracy of the solver. The best solution would be to periodically add back in a small force to counteract the loss.

**Comment by kittykatattack** [comment]
Interesting! Thank you!
This is for a mathematically precise simulation of a frictionless pendulum that should swing forever.
I will try those suggestions and return with my findings 😄

**Comment by liabru** [comment]
In that case you may want to go with a more direct simulation specifically for pendulums rather than a generic physics engine, but try it out!

**Comment by kittykatattack** [comment]
@liabru Thank you sir, yes this is what I was contemplating 😄

**Comment by rafaelcastrocouto** [comment]
I was trying to improve the double pendulum example https://codepen.io/rafaelcastrocouto/pen/NWajBgM and stumbled on this same issue.
I'm I missing something here or ain't making it fristionless easier then damping? 
There must be some paremeter to make angular constraints actually frictionless.
