### ISSUE TITLE
Stop rotation (delete pivot) in a constraint

### ISSUE THREAD

**Issue by DiabloiqueJS** [liabru/matter-js#484]
Hello,
I'm trying to make an js Game Engine and matter is my choice for the physic engine.
The Engine is fully integrated and now i need to make parent and child of an Object.

For this i need the parent and the childs linked by a constraint, but the childs positions need to be at the same relative position from the parent every physic update.

My solution of choice is that i need to delete the pivot of the constraint on bodyA and keep the pivot on bodyB.

Is there any solution yet, or this is not possible in the actual version of matter?

**Comment by liabru** [comment]
Try using `Matter.Composite.remove(world, constraint, true)` which should delete the pivot.

**Comment by DiabloiqueJS** [comment]
I've tried your solution, but it just delete the constraint. I don't want to do that. i just want to stop the rotation of the constraint on bodyA.

**Comment by DiabloiqueJS** [comment]
Hello @liabru is there a solution yet? i've update my version of matter but i can't find a constraint that work for my problem.

I think i poorly expressed myself the last time. So i made a figure.

![explication](https://user-images.githubusercontent.com/5888043/44957278-bf41ef00-aed0-11e8-89f5-09e54eea017a.jpg)

**Comment by liabru** [comment]
Maybe try using two or more constraints spaced slightly apart from the centre of mass, that might be one way to get this effect?
