### ISSUE TITLE
How to flip orientation of a Composite?

### ISSUE THREAD

**Issue by kittykatattack** [liabru/matter-js#485]
Hi Everyone!

I'm working on a 2D side scrolling car game using a car composite.
When the player presses the left or right arrow keys, the car needs to flip around to point in the correct direction.
Can anyone suggest the best (simplest!) way to do this?

Thanks!

**Comment by liabru** [comment]
Probably just flip the sprite and then invert the controls?

**Comment by kittykatattack** [comment]
@liabru My custom car composite isn't symmetrical. It looks a bit like this: 

http://piqnt.com/planck.js/Car

So I would at least need at least flip the body around.
Also, I'd like to maintain the car's momentum when it changes direction, so that, for example, if it's travelling to the left, and then flips to the right, it still maintains it's current speed.

There might be a few different systems at play here, but the first thing I would need to do is invert the orientation of the composite, which I haven't yet figured out how to do.

**Comment by liabru** [comment]
You could try scaling the body like this `Body.scale(body, -1, 1)` but be aware this might have a few issues see #443?

**Comment by kittykatattack** [comment]
@liabru Amazing, that just works! Thank you! 😄 

Here's the code I'm using that does the trick:

```
  let carBody = car.bodies[0],
      leftWheel = car.bodies[1],
      rightWheel = car.bodies[2];

  Body.scale(carBody, -1, 1);
  carBodySprite.scale.x = -carBodySprite.scale.x;
  Body.setAngularVelocity(leftWheel, -leftWheel.angularVelocity);
  Body.setAngularVelocity(rightWheel, -rightWheel.angularVelocity);
  carPower = -carPower;
```

It's a very natural looking effect.

**Comment by kittykatattack** [comment]
@liabru Oh no!
More testing uncovered an unexpected side-effect.
My car starts off life like this:

![screen shot 2017-09-22 at 1 37 24 pm](https://user-images.githubusercontent.com/2936104/30757173-aa89b1d2-9f9b-11e7-9f21-1d68cbdcff3f.png)

If it hits a wall, its rotation changes as it bumps against the wall surface.
But, if the user inverts the car's orientation by pressing the the "left" button at the same time as its rotation changes, the car body's current rotation is locked into the composite:

![screen shot 2017-09-22 at 1 40 18 pm](https://user-images.githubusercontent.com/2936104/30757280-16265b98-9f9c-11e7-96b0-69ebfa970466.png)

Eventually, if its scale changes enough times while it's rotating, the car looks something like this:

![screen shot 2017-09-22 at 1 37 46 pm](https://user-images.githubusercontent.com/2936104/30757348-5e85962e-9f9c-11e7-98ce-3f7e13b80ab8.png)

So my next question is:

 "Is there a way to normalize the rotation of the body to 0 Radians before scaling it?"

(It seems `Body.rotate` is only used to set a relative angle - how could I set an absolute angle? Or, and am I just thinking about the problem in the wrong way?)

**Comment by kittykatattack** [comment]
@liabru Solved!

I used `setAngle` to set the `carBody` to 0 Radians before inverting the scale:

```
Body.setAngle(carBody, 0);
Body.scale(carBody, -1, 1);
```

**Comment by PiotrSzlagura** [comment]
@liabru @kittykatattack I'm trying to utilize this technique by I ran into some issues - I have a composite which consists of a torso, a "hand" and a constraint between them. My problem is that the constraint is not being flipped at all (its position doesn't change). Any ideas how I could achieve that? 

I use following code for my flipping:
```js
Matter.Composite.scale(this.body, -1, 1, this.torso.position, true);
```
