### ISSUE TITLE
create concave objects and svg curves

### ISSUE THREAD

**Issue by Cdvalencia** [liabru/matter-js#487]
Hi!.
i am having a problems creating objects concave vertices and svg curves, so:

**1.** _I´ve tried create the next vertices:_
 `Vertices.fromPath('40 0 40 20 100 20 100 80 40 80 40 100 0 50')`
![image](https://user-images.githubusercontent.com/4379656/30257377-5fafae14-9677-11e7-955e-b5bf2e5fd772.png)
but, i am gotting the next object.
![image](https://user-images.githubusercontent.com/4379656/30257405-8cc1278e-9677-11e7-9805-d572ab4dd46e.png)

**2.** _Also, it is happening when i wanna load a svg file, so:_
![image](https://user-images.githubusercontent.com/4379656/30257486-1864734a-9678-11e7-873a-3b0132822696.png)
![image](https://user-images.githubusercontent.com/4379656/30257543-806c7550-9678-11e7-9c67-f3373aa2f5e6.png)
and result is:
![image](https://user-images.githubusercontent.com/4379656/30257551-8d431f72-9678-11e7-9954-08b4c26b11d9.png)

**Comment by Qriva** [comment]
I think the problem is:
> Converts an SVG path into an array of vector points. If the input path forms a concave shape, you must decompose the result into convex parts before use. See Bodies.fromVertices which provides support for this. Note that this function is not guaranteed to support complex paths (such as those with holes).

I'm not sure how your code looks lso check [this demo first if you did not.](http://brm.io/matter-js/demo/#svg)
It is not possible to create concave shape in matter so to do it you need to decompose it to smaller convex shape and bring whole shape as composite. Also read the docs and when you use `fromVerticies` don't forget about poly-decomp library or you are going to get again sinagle convex shape

**Comment by Cdvalencia** [comment]
justly it is my problem, on the demo all work normally, but on my local files happen the error showing.
i've tried changing the versión dev "0.13.0", but it continuous happening.

also, i tired using several browsers (firefox, chrome, IE), but i haven´t found the error.

**Comment by Qriva** [comment]
Not sure why I got mail in english and now your comment is in spanish :D 
As I said if your code is the same as in demo page i bet it can be poly-decomp.
If not then make code fiddle

**Comment by Cdvalencia** [comment]
@Qriva Thanks for your answer.
justly it is my problem, on the demo all work normally, but on my local files happen the error showed.
i've tried changing the versión dev "0.13.0", but it continuous happening.

also, i tired using several browsers (firefox, chrome, IE), but i haven´t found the error.

**Comment by Cdvalencia** [comment]
This is a [solution](https://github.com/liabru/matter-js/issues/449#issuecomment-317380352)
using [polydecomp ](https://github.com/schteppe/poly-decomp.js)

**Comment by wooseopkim** [comment]
I enabled `poly-decomp` (with `import decomp from 'poly-decomp'`, `window.decomp = decomp`) but I'm not getting concave figures even when using the path from [the example](https://github.com/liabru/matter-js/blob/master/examples/concave.js). I made sure that `decomp.quickDecomp()` is actually getting called. My Matter.js version is 0.14.2 and I've tried poly-decomp 0.2.1 and 0.3.0. No progress so far.

**Comment by Cdvalencia** [comment]
@wooseopkim. i was searching so time this solution, and the best solution is my previous answer. Because, i think matterjs no soppourt concave polygons..

you must build multiples elements and create a special-concave-element. see [solution](https://github.com/liabru/matter-js/issues/449#issuecomment-317380352)
