### ISSUE TITLE
Bodies factories do not include methods on returned body

### ISSUE THREAD

**Issue by oliverbenns** [liabru/matter-js#488]
Hi, not sure what I'm doing wrong here.

When I create Bodies with the factories, I don't get any methods. Despite the fact they return a Matter.Body.

e.g.

```
import { Bodies } from 'matter-js';

const foo = Bodies.rectangle(10, 10, 10, 10);
console.log(foo.setPosition); // undefined
console.log(foo.setAngle); // undefined

const bar = Bodies.circle(10, 10, 10);
console.log(bar.setPosition); // undefined
```

Running `0.13.0`.

**Comment by oliverbenns** [comment]
Not on obj or prototype... `Matter.Body.setPosition(body, position)`

**Comment by liabru** [comment]
Just to confirm, the engine uses a functional approach rather than an object orientated one, so there are no prototypes or methods directly on objects.
