### ISSUE TITLE
Prevent wheels sinking into ground?

### ISSUE THREAD

**Issue by kittykatattack** [liabru/matter-js#489]
Hi EveryoneI

I have dump truck that looks like this:

![screen shot 2017-09-14 at 1 10 54 pm](https://user-images.githubusercontent.com/2936104/30443640-3d5d2786-994e-11e7-8410-5d43c25ac4c4.png)

But when I add some weights for it to carry, it looks like this:

![screen shot 2017-09-14 at 1 09 54 pm](https://user-images.githubusercontent.com/2936104/30443679-5bace848-994e-11e7-8ba0-420c3d41239f.png)

... and starts bouncing around.

Is there any way I can prevent the wheels from sinking into the ground?

Just for reference, here's the code that creates the truck (it's based on the car composite in the examples.)

```
function customTruck(xx, yy, width, height, wheelSize) {
  var group = Body.nextGroup(true),
      wheelBase = 5,
      wheelAOffset = -width * 0.8 + wheelBase,
      wheelBOffset = width * 0.5 - wheelBase,
      wheelYOffset = 18;
      xStart = xx - (width / 2);
      yStart = yy - (height / 2);
  
  var vertices = [
   {x: xStart, y: yStart},           //A
   {x: xStart + 4, y: yStart + 23},  //B
   {x: xStart + 13, y: yStart + 27},  //C
   {x: xStart + 60, y: yStart + 27}, //D
   {x: xStart + 57, y: yStart + 9},  //E
   {x: xStart + 48, y: yStart},      //F
   {x: xStart + 43, y: yStart},       //G
   {x: xStart + 43, y: yStart + 22},  //H
   {x: xStart + 10, y: yStart + 22},   //I
   {x: xStart + 10, y: yStart},        //J
   {x: xStart, y: yStart}           //A
  ];

  var body = Bodies.fromVertices(xx, yy, vertices, {
      collisionFilter: {
          group: group
      },
     density: 0.005,//0.0005,
      render: {
          fillStyle: '#008B8B',
          strokeStyle: '#008B8B',
          lineWidth: 1,
      },
  }, true);

  var car = Composite.create({ label: 'Car' });

  var wheelA = Bodies.circle(xx + wheelAOffset, yy + wheelYOffset, wheelSize, { 
      collisionFilter: {
          group: group
      },
  });
              
  var wheelB = Bodies.circle(xx + wheelBOffset, yy + wheelYOffset, wheelSize, { 
      collisionFilter: {
          group: group
      },
  });
              
  var axelA = Constraint.create({
      bodyB: body,
      pointB: { x: wheelAOffset, y: wheelYOffset },
      bodyA: wheelA,
      stiffness: 0.5, //0.1,
      length: 0,
  });
                  
  var axelB = Constraint.create({
      bodyB: body,
      pointB: { x: wheelBOffset, y: wheelYOffset },
      bodyA: wheelB,
      stiffness: 0.5, //0.1,
      length: 0,
  });
  
  Composite.addBody(car, body);
  Composite.addBody(car, wheelA);
  Composite.addBody(car, wheelB);
  Composite.addConstraint(car, axelA);
  Composite.addConstraint(car, axelB);

  return car;
}
```

The weights that I'm adding look like this:

```
let weightBody = Bodies.rectangle(sprite.x - 11, sprite.y - 100, 10, 10, { 
      friction: 1,
      frictionStatic: 1,
      density: 0.02,
      restitution: 0,
    });
```

Thank you! 🙏

**Comment by liabru** [comment]
Looks like your weights are far heavier than the car? If so this will likely be unstable. Did you try making the weights much less dense instead?

**Comment by kittykatattack** [comment]
@liabru Yes, I did try that, which helped, but the weights bounced out of the back of the truck.
This particular simulation is designed as a visualization tool to help students understand how mass affects constant acceleration.
So, each weight needs to be pretty heavy to illustrate how it slows the truck down.
(Ideally, if the truck alone weighs 1kg, each weight would also need to weight 1 kg to clearly show the affect it's having on acceleration.)

I didn't manage to solve this with the physics engine, but did eventually achieve the simulation I was looking for simply by using image sprites to represent the weights.
Then I just adjusted the car's acceleration value when each weight was added - it's a kind of a "cheat" works perfectly!
Also, it solved the other problem I was having where the weights were changing the truck's balance, and thus adding another variable to the car's acceleration which was difficult to control.

**Comment by liabru** [comment]
Good to hear you figured out something that worked. Trickery is often the case with game physics!

I forgot to say, you could also try increasing solver iterations e.g.

```js
Engine.create({
  positionIterations: 10,
  velocityIterations: 10,
  constraintIterations: 5
})
```
