### ISSUE TITLE
Hey liabru, How can I constrain a force in the y axis between two values?

### ISSUE THREAD

**Issue by msal4** [liabru/matter-js#490]
I tried this but it didn't work
`this.jump = function() {
        Matter.Body.applyForce(this.body, pos, { x: 0, y: -0.05 });
        constrain(this.body.velocity.y, -0.5, 1);
    };`

**Comment by liabru** [comment]
You'll need to change this to use `Body.setVelocity` instead.

**Comment by msal4** [comment]
thanks
