### ISSUE TITLE
Release build documentation

### ISSUE THREAD

**Issue by psaxton** [liabru/matter-js#493]
Currently, when I go to http://brm.io/matter-js/, I can get the documentation for the edge build. I can see no where to find the documentation for the release build. Could a link be added either to the release page or the navigation for people wanting to develop against a "stable" version?

**Comment by liabru** [comment]
The current stable version is `0.13.0` and the docs for the stable build are always at http://brm.io/matter-js/docs/. To clarify, the current 'edge' build is actually just the same as `0.13.0` as there have been no changes since.

**Comment by psaxton** [comment]
Perhaps the site should then update the release link to 0.13.0 rather than
0.10.0?

**Comment by liabru** [comment]
Actually it looks like the [releases](https://github.com/liabru/matter-js/releases) page is just not up to date, I think my release build system must have stopped working, will look into it.

**Comment by liabru** [comment]
I have revisited this and resolved, see #697. Also to be clear, after this was originally posted the hosted docs are always for the latest release (rather than edge builds).
