### ISSUE TITLE
Typo in URL on demo page

### ISSUE THREAD

**Issue by gkjpettet** [liabru/matter-js#495]
There is a type in the URL for the [terrain demo][1]. Clicking the brackets icon to get the source code directs you to `https://github.com/liabru/matter-js/blob/master/examples/terraing.js` instead of  `https://github.com/liabru/matter-js/blob/master/examples/terrain.js`.

[1]: http://brm.io/matter-js/demo/#terrain

**Comment by liabru** [comment]
Thanks for reporting, but this is covered by #463, so please track it there.
