### ISSUE TITLE
Computing precision between browser

### ISSUE THREAD

**Issue by Manu33** [liabru/matter-js#499]
Hi,

Excuse for my poor english...

So i see some differences in computing the physics of bodies between Safari and Chrome.

And after some collisions, the final result isn't the same. Which is not good for a game.

Can we put a precision computing parameter in matter.js ?

Regards,

**Comment by Manu33** [comment]
So the author care about the difference between browser in calculation ?

**Comment by liabru** [comment]
Are both simulations running with exactly the same timestep for each frame?

**Comment by Manu33** [comment]
You say for the Engine.update(engine, interval); command ? Or the really time between each frame ?

I give an fixed interval in the engine.update instruction like 16 for both.

But i see some number in chrome for example having value like xxx,000000000009 for position or velocity

This "noise" grow in some case and finally see difference for the final result. This is the case for example in my test for 4 or 5 final result on 400 tests. So this is not all the time but with some case.

This is annoying to make game which have differences in some cases between browser.

**Comment by liabru** [comment]
For them to be exactly in sync, they'd both need to be on the same browser, OS and hardware, run exactly the same frame rate and start at exactly the same time.

So it isn't really possible to sync two clients in this way, you always have to use some networking code to keep them in sync (this is not just for matter.js, the same issues apply in general for any physics engine).

**Comment by Manu33** [comment]
This is perhaps a javascript issue for some browser, i will test something and tell you.

**Comment by liabru** [comment]
Closing as I assume you solved this, in general floating point numbers can not be fully relied upon to be exact across different platforms, it's best to use rounding or fixed point in comparisons, with some tolerance factor.
