### ISSUE TITLE
PIXI as render engine for Matter

### ISSUE THREAD

**Issue by Umca** [liabru/matter-js#509]
I am new with Matter.js. So I am a little bit confused how to render matter bodies with PIXI.js. I know that PIXI elements 0,0 coords are at the top left corner of it, while matter bodies has mass center (that is definatly not in the top-left corner). 

My first thought was to change center point of pixi elements with the help of anchor/ pivot.  These manipulations move  0,0 coords to the center of the element. 

In the demo https://jsfiddle.net/olga_akinshyna/ma4ma3yb/3/  I want the width of the boundary equals canvas width.   In jsfiddle I have couple variants in comments, but the result is not what I have expected.

There was similar issue https://github.com/liabru/matter-js/issues/211, but there people tried to bind matter to html element and some recommends to change matter body mass center, but I think it can break physics laws, and it is not desired.

**Comment by liabru** [comment]
Check out [RenderPixi](https://github.com/liabru/matter-js/blob/master/src/render/RenderPixi.js), which although it is deprecated it should be a good reference.

**Comment by celsowhite** [comment]
Created a codepen for how to do this https://codepen.io/celsowhite/pen/XWbEzpx. It includes Pixi sprites following Matter bodies and setting up canvas boundaries for the objects.
