### ISSUE TITLE
How do I get the rotation of a body?

### ISSUE THREAD

**Issue by singerbj** [liabru/matter-js#513]
I am running matter-js on a node server, and then serializing the objects to send to a client also running matter-js to render the objects. I scoured the documentation and google but couldn't find an answer...how do I get the rotation of a body?

**Comment by liabru** [comment]
You can use `body.angle` which is in radians.

**Comment by singerbj** [comment]
Ugh I feel dumb. I was staring at that property for hours last night. Thanks @liabru
