### ISSUE TITLE
Circle disable rotation

### ISSUE THREAD

**Issue by Kattoor** [liabru/matter-js#514]
I have a circle falling on a static rectangle (ground). Somehow it starts rotating whilst falling (gains angular velocity?) which makes it 'roll' on the rectangle's surface.

What would be the best / most performant / cleanest way of disabling the rotation on a circle body?

**Comment by liabru** [comment]
Try this:

```js
var circle = Bodies.circle(x, y, 10, { inertia: Infinity });
```
