### ISSUE TITLE
separate the Engine from the Render

### ISSUE THREAD

**Issue by alpha-xdream** [liabru/matter-js#517]
I want to run the Engine in H5 Worker and run the Render in the main JS. What should I do?

**Comment by liabru** [comment]
The renderer is separate from the engine already, can you be more specific? If you mean running the engine in a web worker, it should be possible but you will need to serialise the world to pass it between threads. Have a look at the [serializer](https://github.com/liabru/matter-tools/blob/master/src/tools/Serializer.js) in matter-tools which should help you start.

**Comment by alpha-xdream** [comment]
I just want to make the matter-js keep running when switching the tab. My idea is running the engine in a web worker, but it show errors when I created an engine in a web worker because a worker isn't allowed to access html dom.

> need to serialise the world to pass it between threads. 

Does it mean serialising the world in a worker and passing it to the main js? I don't know how to make an engine in a web worker. /(ㄒoㄒ)/~~

**Comment by alpha-xdream** [comment]
I had solved my problem. Just used [HackTimer](https://github.com/turuslan/HackTimer) that override by using a web worker. see details at [this](https://stackoverflow.com/a/31105348).
Thanks for your answer!

**Comment by liabru** [comment]
>I had solved my problem. Just used HackTimer that override by using a web worker. 

Looks like a pretty wild hack, but if it works then why not!

> it show errors when I created an engine in a web worker because a worker isn't allowed to access html dom

Would you mind posting those errors?

> Does it mean serialising the world in a worker and passing it to the main js?

Yeah exactly, I think that's how you need to do it if you wanted to render on the main thread.
Although, there's possibly a better way using [transferables](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) where you could even render from a worker too.

**Comment by alpha-xdream** [comment]
> Would you mind posting those errors?

Of course!

my worker.js
```
importScripts('matter.js')
var engine = Matter.Engine.create();
```

and my js in the main thread

`var w = new Worker('worker.js')`

the error is

![image](https://github.com/alpha-xdream/SW-/raw/master/matterjs_in_worker.png)

**Comment by Nathan-Devery** [comment]
Had this same issue and adding hacker time worked, thanks so much.
https://evolutionary-fighters.azurewebsites.net/

**Comment by koraysels** [comment]
can we find an example of this working ? Ans does it have a performance improvement?

**Comment by liabru** [comment]
@koraysels do you mean running in a worker? There's no official example of this yet (it's on my list!) but it should be possible to do as discussed here and in other threads.

As for performance, you'd only see a boost if you can make use more than one thread, which is not straightforward (on my list too). 

Usually this starts with rendering on one thread and running physics on another thread, which might give a small boost depending on how complex your rendering is more than anything else. It might also be a slight detriment depending on how you implement the data sharing between threads (sending minimal data through shared memory is probably the way to go).
