### ISSUE TITLE
decomp.Polygon is not a constructor

### ISSUE THREAD

**Issue by YanDevDe** [liabru/matter-js#518]
When I'm using Bodies.fromVertices, I receive this error:

```Uncaught TypeError: decomp.Polygon is not a constructor at Object.n.fromVertices (matter.min.js:49)```

I've already included decomp.min.js at index.html:

``` 
<script src="js/matterjs/decomp.min.js" type="text/javascript"></script>
  <script src="js/matterjs/matter.min.js"></script>
```

I'm using this code:

``` 
Bodies.fromVertices(0, 0, [], {
    isStatic: true
});
```

What is wrong?

**Comment by Chinafreak** [comment]
Any update of this?

**Comment by liabru** [comment]
I couldn't find `decomp.Polygon` referenced in the code, what matter.js version are you using?

**Comment by Chinafreak** [comment]
I'm using the latest version of matter.js

https://github.com/liabru/matter-js/tree/master/build

This error appear when I'm trying to create an concave polygon (but error does still appear on empty array) from fromVertices

**Comment by liabru** [comment]
I just realised so you said you're doing this:

```js
Bodies.fromVertices(0, 0, [], {
    isStatic: true
});
```

Since you're not passing any vertices so this will fail.
Is there a reason you need a body with no vertices?

**Comment by Chinafreak** [comment]
Yes because I want to create later Vertices. However, even if I initialize directly in vertices, then I'm still getting this error.

I can upload an example project where this errors appear

**Comment by Chinafreak** [comment]
[MatterJS-Example-decompPolygon-Issue.zip](https://github.com/liabru/matter-js/files/1498547/MatterJS-Example-decompPolygon-Issue.zip)

There we go!

I got this error:
https://puu.sh/yrSUs/b5bdff0fff.png

Bodies.fromVertices is at line 69 in main.js

matter.js and decomp.js is the latest version

**Comment by liabru** [comment]
You should just directly use `Body.create` for this instead (though it's really not designed to handle empty vertices).

That said, try this:

```js
var body = Matter.Body.create({ vertices: [{}] });

// later

Body.setVertices(body, [...]);
```

**Comment by Chinafreak** [comment]
can ".setVertices" use concave polygons? I don't think so

**Comment by liabru** [comment]
It can't unfortunately. Is there not a way you can just create the body at the time you need it? It's what I'd recommend.

**Comment by Chinafreak** [comment]
Fine, I could write that I can create body at the same time when I need it. But however, this doesn't fix issue due decomp.Polygon from Bodies.fromVertices where I can create concave polygons. Look up at example where I uploaded here.

**Comment by photonstorm** [comment]
@Chinafreak the version of Matter.js in the zip file you uploaded above is _really_ old, it's version 0.10.0. You need 0.13.0. You said you had the latest version from the build folder here, but that is not what is in your zip file, so I think something got mixed up somewhere.

Put the proper version in and you won't get this error.

**Comment by Chinafreak** [comment]
Ah, I got it from releases where the build is old I guess. https://github.com/liabru/matter-js/releases
Sorry for that! Thanks for the hint @photonstorm!

**Comment by Chinafreak** [comment]
might want to update at Release

**Comment by clankill3r** [comment]
Yeah I hit the same error, would be good to update the Release

**Comment by liabru** [comment]
See my latest [comment on #559](https://github.com/liabru/matter-js/issues/559#issuecomment-752182778) for an update on this, but essentially try using `0.15.0` as that should solve problems with the require. Let me know in that thread if there are other problems, so closing this one.
