### ISSUE TITLE
How to reinitialize or responsive

### ISSUE THREAD

**Issue by aentan** [liabru/matter-js#521]
I’m constructing my world based on browser width and height. So when it’s resized I need to either reinitialize everything or better make it responsive.

Googling led me to think there is a reset example but perhaps it’s not there in the latest.

Any help would be appreciated.

**Comment by liabru** [comment]
Do you need to change the world or just change the renderer?

**Comment by aentan** [comment]
I added walls to all edges of the browser. Every time I resize my browser I want the walls to follow. They can either be responsive and change position and dimensions according to browser or at the end of resize everything is redrawn.

**Comment by liabru** [comment]
You can use [Engine.clear(engine)](http://brm.io/matter-js/docs/classes/Engine.html#method_clear) and then add all of your bodies again. Otherwise you could use some combination of `Body.translate` and `Body.setVertices` or `Body.scale` to resize existing bodies.

**Comment by aentan** [comment]
Thanks you!

**Comment by aentan** [comment]
I managed to use `setPosition` to move the wall. How do I change their width and height?

**Comment by aentan** [comment]
Ah now I understand wha
