### ISSUE TITLE
Expose _bodiesApplyGravity function

### ISSUE THREAD

**Issue by photonstorm** [liabru/matter-js#523]
At the moment `_bodiesApplyGravity` is a local var within Engine, making it impossible to replace without changing the source within Engine itself. Is there any way you could change the scope of this var so it can be easily replaced?

For my own use I want to add a property to Body which is `ignoreGravity`, but in order to have it implemented, I need to modify the `_bodiesApplyGravity` function. Based on its current scope though, I can't do this.

Any chance this could be hoisted?

**Comment by liabru** [comment]
Good call, I've now moved all private functions into module namespace so they can be patched where needed. Should be in a release soon.
