### ISSUE TITLE
Best way to handle large sets of tiles?

### ISSUE THREAD

**Issue by jussch** [liabru/matter-js#525]
I'm writing a top-down shooter using a tile-based map system. Each tile is its own body, which makes it incredibly slow when I've got 64 tiles by 64 tiles on a single map. I've been looking at Matter-JS docs for awhile, and I haven't found many in-house solutions to this. My best guess so far is that I should convert all the tiles to a single body using `fromVertices(...)`.

Is this a good idea? Or is there something more efficient or easier I can explore, like a `mergeBodies(...)` function?

Thanks

**Comment by liabru** [comment]
> My best guess so far is that I should convert all the tiles to a single body using fromVertices(...).

Probably not a good idea, in this case it's better to use multiple bodies so that the broad-phase can be more efficient.

I'm interested to know what exactly is slow, since I assume the tile bodies are static? How many dynamic bodies do you have?

**Comment by jussch** [comment]
Whoops, I think I was under the assumption that having multiple tiles would always be slower than one big object. I could not reproduce my slow issue. 

Thanks!
