### ISSUE TITLE
How to control the collision and path of the object moving to the desired point.

### ISSUE THREAD

**Issue by angiagia** [liabru/matter-js#529]
I am developing a game like Pachinko of Japan, currently I am stuck in the calculation based on the results of the server returned. I tried applying the MatterAttractors plugin to create marbles that move to the right place where the server wants to but it's pretty bad and not as natural as the real physical collision. I'm trying to use paperjs for creating marble paths based on given results and ignoring collisions between marbles. However, this is really bad when ignoring the collision. Do you have a way to control the path of objects when collisions occur? Please tell me a little about it! 
Thanks you so much!

**Comment by liabru** [comment]
Have a look at the [manipulation example](http://brm.io/matter-js/demo/#manipulation) which shows how you can move bodies exactly as needed. As for changing the outcome of collisions, well that's pretty fundamental stuff so it's very hard to change.

**Comment by angiagia** [comment]
Thanks for your help!
