### ISSUE TITLE
Restoring serialised objects / Multiplayer

### ISSUE THREAD

**Issue by Rodeoclash** [liabru/matter-js#53]
I've got a basic multiplayer implementation of MatterJS going. Essentially I'm taking the body component, converting it to JSON (I tried resurrect-js but got put off with the lack of NPM, json-stringify-safe seemed to handle the circular references ok) then sending it over the wire. On the other machine, I'm creating a new body object then updating it as data is sent.

I couldn't find a built in update function so I simple used lodash's "extend" to overwrite the properties of the object from the re-serialised JSON data.

This seems to work pretty good, the objects stay nicely in sync. The problem is that theirs no interactivity between them. I had a few questions (and would be happy to update the docs with a pull request or create a demo). They are:
- Is using resurrect-js a requirement for serialisation? I didn't have any problems not using it but might be setting myself up for trouble later.
- How do I take a serialised object / world and restore it? Just feed it into the create function?
- Is their a way of "updating" a created object or is just overwriting the properties sufficient?
- I haven't given any serious thought to debugging the issue were the objects don't interact with each other but does anything spring into mind about where I might start?

Sorry for the dump of questions :( I just couldn't find too much documentation on world serialisation / restoration.

**Comment by Rodeoclash** [comment]
That's awesome. To be honest, I've been a bit distracted with Clojure/ClojureScript recently so haven't looked at my game since I left it. When I get back onto it though I'll look at using the body set function though, it looks perfect.

I wound up using a different JSON serialiser in the end, I didn't have a good result with resurrect-js. Besides that, it didn't have any AMD / CommonJS integration making it a pain to use with WebPack. I've gotten as far as serialiser the objects and sending them over the wire, I still had a few bits to debug with the interactions with the created objects.

I should finish up my Clojure stuff soon so I'll be back on the game :)

**Comment by Rodeoclash** [comment]
For what it's worth - here's the start of the game. I've built a scaled down, single player, version for my CV but ideally would like to adapt into a multiplayer game at some stage.

http://richardson-homepage.s3-website-ap-southeast-2.amazonaws.com/

**Comment by liabru** [comment]
Nice! Interesting concept for story telling. The ship seems a little hard to control though, I'd probably prevent it from rotating and just have upwards motion against gravity, maybe allow a little side to side motion at a slower rate when pressing the left and right keys.

**Comment by Rodeoclash** [comment]
That's great feedback. All the feedback has been that it's too difficult. I've tweaked it a bit and removed the rotation (like you comment) and it plays a lot easier. Try refreshing that heroku site to see what I mean.

Shame though. The original control scheme was similar to "Gravity Power" on the Amiga. I'd like to build some kind of dog fighting or racing game using that control schema still - but for previous version, well I don't think I'd ever get another job due to the difficulty of it, haha.
