### ISSUE TITLE
Is it possible to cut the rope !?

### ISSUE THREAD

**Issue by HoseinGhanbari** [liabru/matter-js#530]
Hello !
First of all, thank you so much for this great open-source engine!

Please let me know that, is this library support simulating the rope tearing, when it stretched by the mouse dragging?

I really hope I can use this engine in my physics report.
Any help would be appreciated.
Thanks !

**Comment by liabru** [comment]
One way to do this by checking the length of each constraint in the chain, if any goes over say 2x its rest length for more than say 0.5s then remove that constraint from the chain.

**Comment by HoseinGhanbari** [comment]
Thanks for your quick response!
I will try to implement the simulation in the way you said.

Is there any way to check whether the rope is stretched fastly or not? I mean, how can I determine if the rope is stretched (and reached the critical tearing point) in a short time or the user's stretching takes a long time until reaching the tearing point?

If there will be some code snippet or even implementation keyword(s) to show me the way, it will be really fantastic!

Thanks!

**Comment by liabru** [comment]
Closing as this is beyond the scope of issues I can support, I hope you figured it out.
