### ISSUE TITLE
Waking up objects around another one that is moved programmatically

### ISSUE THREAD

**Issue by ggmendez** [liabru/matter-js#532]
I need the objects of my world to sleep unless another 'special' object passes by and touches them. For technical reasons, I am setting the position of this special objects programmatically (not using mouse events).

Suppose I position the special object `obj` at a certain point `(x,y)` around which there many other sleeping objects. `obj` is located properly (I can see it moving) but it does not seem to awake the surrounding objects when touching them. Instead, it just overlaps them and is just drawn on top of them.

In my setting, `obj` is awake; I am printing its `isSleeping` property and it appears as `false`. Also, I am executing `Matter.Sleeping.set(obj, false)` to awake it every time I change its position.

What am I missing here? I suspect sleeping/awaking has to do with motion, but the only thing I have at hand is the desired location of the object I need to move programmatically. Thus `obj.motion` is always zero. I have tried setting it to other values (1, for example) but the objects around `obj` do not awake anyway and, thus, do not react to the changes in its new position.

**Comment by liabru** [comment]
When moving objects around manually like that, you need to manually update their velocities after you set their position, as you can see in the [manipulation](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L83-L93) example code. This way `motion` should get updated correctly.
