### ISSUE TITLE
Why the inertia still hasn't stopped immediately

### ISSUE THREAD

**Issue by whaqzhzd** [liabru/matter-js#534]
https://plnkr.co/edit/R3IDtpb0w7ZX74zhRomr?p=preview

**Comment by liabru** [comment]
I'm not sure what you mean. Can you give some more explanation?

**Comment by davo** [comment]
Not sure what it means, here is the same code (tested on v0.10.0 and 0.12.0) on [codepen](https://codepen.io/davo/pen/dZEJZw).

Inertia works as expected.
