### ISSUE TITLE
deltaTimeSquared in equations

### ISSUE THREAD

**Issue by raaymax** [liabru/matter-js#538]
Hi, 
I have some question about equations in body update function. I was trying to implement some simple top-down car model and my computed forces was giving some strange effects. I looked into the code and found this:
```javascript
Body.update = function(body, deltaTime, timeScale, correction) {
    var deltaTimeSquared = Math.pow(deltaTime * timeScale * body.timeScale, 2);

    // from the previous step
    var frictionAir = 1 - body.frictionAir * timeScale * body.timeScale,
        velocityPrevX = body.position.x - body.positionPrev.x,
        velocityPrevY = body.position.y - body.positionPrev.y;

    // update velocity with Verlet integration
    body.velocity.x = (velocityPrevX * frictionAir * correction) + (body.force.x / body.mass) * deltaTimeSquared;
    body.velocity.y = (velocityPrevY * frictionAir * correction) + (body.force.y / body.mass) * deltaTimeSquared;

    body.positionPrev.x = body.position.x;
    body.positionPrev.y = body.position.y;
    body.position.x += body.velocity.x;
    body.position.y += body.velocity.y;

    // update angular velocity with Verlet integration
    body.angularVelocity = ((body.angle - body.anglePrev) * frictionAir * correction) + (body.torque / body.inertia) * deltaTimeSquared;
    body.anglePrev = body.angle;
```

velocity and angularVelocity are computed based on squared delta time i don't have deep knowledge about physics or physics engines but i thing this velocities are not actually velocities but distances.
From units calculation we get meters: [kg\*m/s^2]/[kg]\*[s^2] = [m].

**Comment by liabru** [comment]
The `deltaTimeSquared` term is part of the Verlet integration scheme which the engine uses, you can read about it in the classic [Advanced Character Physics](http://web.archive.org/web/20080410171619/http://www.teknikus.dk/tj/gdc2001.htm) paper.
