### ISSUE TITLE
Are all modules in the docs considered "public"?

### ISSUE THREAD

**Issue by sulcata** [liabru/matter-js#541]
I was trying my hand at updating the TypeScript definitions over at DefinitelyTyped and noticed there were modules missing, such as Resolver, Pair, SAT, Detector, Contact, Common, and Plugin. Perhaps a bit of a strange question to ask, but are these intended to be public facing APIs? They're all mentioned in the docs, but a few of them seem more primitive and possibly not as thoroughly documented.

edit: it looks like the docs weren't updated yet, still says 0.13.0

**Comment by liabru** [comment]
All modules are considered public but you're right that some are used much more than others. Those you listed are quite low level and are not likely to be used much by end users.

**Comment by sulcata** [comment]
Alright, going to see if I can get decent typings for plugins and the other things I mentioned.

Great work by the way, really impressed with how smoothly this runs.
