### ISSUE TITLE
Is it possible to simulate dropping spring ?

### ISSUE THREAD

**Issue by HoseinGhanbari** [liabru/matter-js#543]
Hello !
I'm going to simulate a simple dropping spring from a specific height, actually a spring with *mass*.
But as I saw the examples & read the docs, I can't make a `constraint ` without two bodies, or one body and a fixed point.
I just need the `constraint` (spring), without the bodies that should be attached to it.
Is it possible to implement sth like that ?
Is it possible to remove the fixed point to simulate the falling spring ?
Thanks !

**Comment by liabru** [comment]
You mean like a slinky? Probably hard to do in an accurate way. I'd suggest creating a [chain](http://brm.io/matter-js/demo/#chains) of bodies (with pin constraints, like in the chains demo) and then attaching another soft constraint between each pair (at the opposite end, alternating every pair).
