### ISSUE TITLE
in google ,SVG is bad loading

### ISSUE THREAD

**Issue by pumpkinp** [liabru/matter-js#546]
I run the demo ,but in google63.0,it is error of 
![1](https://user-images.githubusercontent.com/21173134/34205600-fac3578a-e5bd-11e7-91cb-d662ee1d514d.png)
need polyfill???

**Comment by liabru** [comment]
Yes, see #196.

**Comment by pumpkinp** [comment]
@liabru I add the polyfill,it is no working ,and I see you demo add polyfill,but that's no working on Chrome......

**Comment by pumpkinp** [comment]
@liabru oo，polyfill is need update ,perfect
