### ISSUE TITLE
Could matter-js run in WebWorker ? 

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#547]
If it could , is there an example for it ?  
Thanks

**Comment by finscn** [comment]
I tried a simple example , it could run.
I don't when the example become complex , whether still could run correct.

**Comment by bchevalier** [comment]
Hey, I was wondering, how do you send instructions to the webworker?

**Comment by finscn** [comment]
run matter.js in webworker.

pass data with  postMessage & ArrayBuffer

**Comment by bchevalier** [comment]
Sorry, I know that postMessage and ArrayBuffer can be used to send instructions. What I meant is how do you interface it with `matter-js`?
What does the messages or the array buffer look like?

**Comment by finscn** [comment]
I custom a protocol for a arraybuffer.
arraybuffer[0] is cmd flag . in the webworker , Accord to different cmd , do different case.

And there is another arraybuffer save the engine's all bodies. (just position, angle, vertex)

**Comment by liabru** [comment]
To confirm, yeah it should work fine in a web worker. Though I've not tried it yet myself. Check out the [OffscreenCanvas API](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) which might be a way to render directly from the worker too so you don't need to worry about transferring the world to the main thread to render (which is a viable approach too, it's not that much data).

**Comment by Weedshaker** [comment]
I wouldn't dare to send async messages back and forth... but probably a SharedArrayBuffer (https://lucasfcosta.com/2017/04/30/JavaScript-From-Workers-to-Shared-Memory.html) works.

**Comment by bchevalier** [comment]
Problem with SharedArrayBuffer is support coverage: https://caniuse.com/#search=Shared%20Array%20Buffer

**Comment by Weedshaker** [comment]
true, but there would have to be a fallback anyways.
