### ISSUE TITLE
How to prevent body from moving right after a collision? 

### ISSUE THREAD

**Issue by nmwood** [liabru/matter-js#562]
I am trying to detect a collision between two bodies but I don't want them to interfere in the movement of the bodies. I tried to setting the pair.isActive in the collision to false but the body still gets pushed.

**Comment by liabru** [comment]
Check out the [sensors](http://brm.io/matter-js/demo/#sensors) demo and the [code](https://github.com/liabru/matter-js/blob/master/examples/sensors.js), I think this might be what you need.

**Comment by nmwood** [comment]
Is it possible to have a body act as a sensor to a particular object and not others?

**Comment by liabru** [comment]
Yeah, you should be able to use [Body.collisionFilter](http://brm.io/matter-js/docs/classes/Body.html#property_collisionFilter) for that I think.
