### ISSUE TITLE
How to prevent objects from dragging over the specified area？

### ISSUE THREAD

**Issue by ManfredHu** [liabru/matter-js#565]
How do I achieve if I want to let the object be released when the object is dragged beyond the boundary?
When I reach the border, I want to release the dragged object and let it move by inertia

**Comment by ManfredHu** [comment]
Solution：
I found the drag is an object moving with the mouse.
I broke the constraint between them
```js
mousemove: function({name,mouse,source}){
    if(source.body){
        let {y} = source.body.position;
        if(y < lastDieArea.y){
            source.body._ballObject.canTouch = false;
            source.body.collisionFilter.category = 0x0004;
            source.constraint.bodyB = null;
        }
    }
}
```
It's right?

**Comment by liabru** [comment]
Yeah removing `constraint.bodyB` is a good way to do it!
