### ISSUE TITLE
How to change the star size?

### ISSUE THREAD

**Issue by yuanzhhh** [liabru/matter-js#567]
Demo [http://brm.io/matter-js/demo/#concave](url)
I wanted to change the size of the stars, and I didn't find the corresponding size API.

Including the Bodies.FromVertices API, I introduced SVG as a terrain, but I didn't find the API to change the size.

**Comment by yuanzhhh** [comment]
I found it
Vertices.Scale.

**Comment by SamSverko** [comment]
Any help on how you actually implemented this?

(for anyone else coming across this, here is the [Vertices documentation](http://brm.io/matter-js/docs/classes/Vertices.html)).
