### ISSUE TITLE
Collision Information to determine forces/energies involved in resolution

### ISSUE THREAD

**Issue by sroboubi** [liabru/matter-js#569]
I'm trying to get information about collisions so that I can apply damage to the bodies that were involved. Is there a way I can get the impulse or force being applied as a _result_ of a collision, or the delta velocity produced by the collision resolution? I've been looking at the collision start/active/end events but they don't seem to contain the information I need. 
Thanks in advance.

**Comment by liabru** [comment]
Please see the comments in #155.

**Comment by sroboubi** [comment]
Thanks for the quick response. I think collision depth will not be very accurate because of the discrete time-steps and using something like relative velocities does not take into account angular velocity or restitution.
Currently I added one line to Resolver.solveVelocity to send a new event each time a collision impulse is applied:

`Events.trigger(engine, 'collisionImpulseApplied', { impulse: impulse, bodyA: pair.bodyA, bodyB: pair.bodyB, position: contactVertex });`

I then listen to these and sum them up for each body/position across a physics step. This is not super efficient but seems to work for now. I'm not sure if you would want to add something like this as a feature, or if you have a better idea?

**Comment by liabru** [comment]
Closing as I hope you've solved this, another approach might be to listen to collision events and track the velocities of both bodies at every step of the collision until it ends (`collisionEnd` event or both bodies at rest) then work out energies from there.
