### ISSUE TITLE
Unclear documentation about RenderPixi

### ISSUE THREAD

**Issue by knod** [liabru/matter-js#57]
It would be very helpful to have that note about needing pixi.js right there in the RenderPixi documentation section. It was hard to track down. Also, http://brm.io/matter-js-docs/classes/RenderPixi.html points me to Demo.js for usage examples, but I can't find RenderPixi anywhere in Demo.js. If you do end up including it there, including a comment that explains the use of pixi.js could be very clarifying.

**Comment by liabru** [comment]
You're right, the documentation for renderers needs work. 

I've started to write some information on the wiki though, take a look at the [Rendering page](https://github.com/liabru/matter-js/wiki/Rendering).

It shows how to pass through the `RenderPixi` controller to an engine, hopefully that helps?

**Comment by knod** [comment]
Thanks for that, that clears up a few things. I was actually reading the docs at http://brm.io/matter-js-docs and completely forgot about the wiki. I'll look through that a bit and get some more information.

**Comment by dcrockwell** [comment]
+1

Spent 6 hours trying to figure out pixijs + matterjs. Still not sure why the physics library has anything to do with instantiating my pixi canvas. Not sure where to go to figure out if I'm doing it wrong.

**Comment by liabru** [comment]
You use pixi.js and matterjs the same way you'd use any physics engine with any other renderer... the included RenderPixi is just for demo purposes. There's no reason you can't handle rendering and game loop in your own way. Check out this [example](http://codepen.io/BakerCo/pen/ojKJJb) on codepen for an alternate way to use pixijs.

**Comment by dcrockwell** [comment]
@liabru thank you very much for the prompt response. I'll start from the example code :)

**Comment by liabru** [comment]
No problem, I understand that it may not be that clear. I'm working on decoupling and moving the renderers to a separate project :)

**Comment by dcrockwell** [comment]
I'm writing a fully open-source game with a community of folks to serve as a defacto example of bringing custom geometry into matter-js and rendering it with pixijs. When it's in a non-confusing state, I'll be sure to send it to you as a learning aide.

**Comment by liabru** [comment]
Awesome. I've been keeping an eye on your channel, it's looking good. Keep me posted!

**Comment by crazyyi** [comment]
Since RenderPIXI is going to be deprecated, what should I do to use matter.js with PIXI renderer? I use something like this:

```
app.ticker.add(function(delta) {
  play();
});
```
The app is a PIXI.Application and there is a ticker function in the module so I just run frame update in the ticker.

**Comment by liabru** [comment]
Looks like PIXI's value for `delta` is not in `ms` but instead scaled relative to a target FPS (e.g. 60), since most of the time it is `1`, so instead try using `play(delta * 16.666)` (I think).

**Comment by crazyyi** [comment]
@liabru Thanks your solution is perfect. You have a much deeper understanding in PIXI than I do.

**Comment by liabru** [comment]
Thanks for the info @jcyuan. Closing this thread now though since `Matter.RenderPixi` is deprecated.
