### ISSUE TITLE
Why are polygons all mapped to the center???

### ISSUE THREAD

**Issue by CodeAndWeb** [liabru/matter-js#570]
I currently try to build a compound body with Bodies.fromVertices(). I use 2 squares for this: 1 from (0/0)-(100/100) and the second one (100/100)-(200/100):

```
var polydata = [
            Vertices.fromPath('0 0 0 100 100 100 100 0'),
            Vertices.fromPath('100 100 100 200 200 200 200 100'),
];
var poly = Bodies.fromVertices(200, 50,  polydata);
```

I now get a compound body - but I see only 1 square instead of 2 - both squares are overlapping now.

The same happens with more complex bodies like this one:

This is a sprite in [PhysicsEditor](https://www.codeandweb.com/physicseditor):
<img width="285" alt="betty" src="https://user-images.githubusercontent.com/716009/36033900-8135991a-0db2-11e8-9ee8-84924c80375d.png">

adding it as a set of convex polygons results in a pile of trash:

<img width="203" alt="trash" src="https://user-images.githubusercontent.com/716009/36033906-85d7c146-0db2-11e8-8af9-5499492e26a0.png">

**Comment by liabru** [comment]
Will need to try this out, but for now please look at the comments in #248, which I think has a temporary [solution](https://github.com/liabru/matter-js/issues/248#issuecomment-361983251).

**Comment by CodeAndWeb** [comment]
Ok - thanks.
