### ISSUE TITLE
Rope style constraint

### ISSUE THREAD

**Issue by paperjack93** [liabru/matter-js#571]
I'm trying to setup a constraint so that it limits only the maximum distance between two points, without having the overhead of several other bodies to simulate the rope constraint piece by piece.
I made an example but I am not sure if it is the best way to go around it?
https://codepen.io/paperjack/pen/KQmYGK
I'm checking every frame for the distance between my two bodies and changing the stiffness as necessary...

**Comment by strahius** [comment]
I am looking for the same feature, I don't think it currently exists. Your solution though @paperjack93 is pretty neat, I will do something like this for now as well, thanks.
