### ISSUE TITLE
Maintaining stability for arbitrary body+constraint structures.

### ISSUE THREAD

**Issue by probityrules** [liabru/matter-js#572]
Does anyone have recommendations on how to create stable complex structures using a nodes and edges framework? I'm working on something that's along the lines of "World of Goo" or "Fantastic Contraption". I tried using rectangular bodies for edges pinned to circular bodies for nodes by using zero-length constraints, but once a structure gets reasonably complex I'm seeing erratically unstable behavior like this:

![unstable](https://user-images.githubusercontent.com/1324745/36129572-da7b442c-1035-11e8-80f6-d269bd61825b.gif)

Any thoughts or advice would be appreciated!

**Comment by liabru** [comment]
Try these out:

- increase engine constraint iterations e.g. `engine.constraintIterations = 10`
- relax the pin constraint stiffness e.g. `constraint.stiffness = 0.01`
- in addition to the rectangle bodies also add constraints between the same points

**Comment by probityrules** [comment]
Thanks!

I already tried reducing the stiffness, but that didn't help too much and had the side effect of making the structure collapse into itself.

I tried increasing the iterations and that helped make it less likely to happen, so it gets me closer! I can make the structure more complex now, but it eventually breaks as I add more to it.

I'll try adding constraints between nodes and see how that does. I've noticed that the instability seems to occur first on a node with 4 or more constraints, especially when there's a decent amount of stress on one or more of the constraints. Nodes with 3 or fewer are generally fine until the rest of the structure goes berserk.

![unstable-2](https://user-images.githubusercontent.com/1324745/36158350-237775fa-10aa-11e8-8aa4-86cd326f0ffd.gif)

**Comment by probityrules** [comment]
Thanks for your help @liabru! 
Using a combination of your recommendations, I was able to get it to function correctly with much more consistency:

1. I set the iterations back to the default. I may bump it up if things start breaking again, but it's working well with the following changes.
2. I set constraints between node bodies that match the length of the edge bodies. The stiffness on these constraints is set to `1` to maintain structural integrity.
3. I retained the constraints between the node bodies and the ends of the edge bodies, but reduced their stiffness to `0.1`: this removed the erratic instability, but keeps the edge bodies nearly in place for collision effects.

**Comment by liabru** [comment]
Great, this type of thing is usually takes a bit of trickery in physics engines to get right. You might also want to try varying the mass of each body (less mass as it goes up?), increasing air friction and even enabling sleeping.

Keep me posted, will be cool to see where you take this!
