### ISSUE TITLE
Bodies collide with bounding boxes of compound body's parts instead of actual bodies...

### ISSUE THREAD

**Issue by probityrules** [liabru/matter-js#573]
I'm having an issue with solid collision resolution. It seems that occasionally bodies collide with the bounding box as if it were a solid collision. (At least I think that's what I'm seeing here.) Note this GIF:

![bounding](https://user-images.githubusercontent.com/1324745/36170876-ba12830a-10ce-11e8-88fa-b52c11cf120e.gif)

This first time it runs correctly, but on the second run it acts as if the terrain body's parts' bounding boxes are the colliding element. The only notable difference is that in the first one, the circle bodies are earlier on the `world.bodies` list than the terrain body, and in the second the terrain body is earlier on the `world.bodies` list than the circle bodies.

**Comment by probityrules** [comment]
So I tried removing the compound body from the world and then re-adding the same body so that it comes last in the list of world bodies, but this seems to have no effect on this issue.

Since the order does seem to matter in some sense as shown above, I then tried removing the compound body from the world and recreated an identical copy of the compound body to add back into the world instead of re-adding the original. Using a copy does workaround the issue: collision behaves correctly when adding this second compound body to the `world.bodies` list.

**Comment by liabru** [comment]
Have a look at #63 and tell me if that seems related? If so I will see if there is a workaround I can think of.

**Comment by probityrules** [comment]
Hmm, that  may indeed be the issue. I created a test where the collision behavior fails if the wheel goes over the corner slowly as in the example shown above, but if I drop the wheel back farther so that it gathers more momentum, it doesn't exhibit the issue:

![bounding-2](https://user-images.githubusercontent.com/1324745/36290320-95b0d3ac-1292-11e8-87f8-054f46ade118.gif)

**Comment by liabru** [comment]
Looks like that was likely the issue here then, so expecting to be solved at least as of `0.18.0`. Thanks for the report on this.
