### ISSUE TITLE
Possible to clone a body?

### ISSUE THREAD

**Issue by MaLuci** [liabru/matter-js#574]
My project uses many copies of basically the same body. Is it possible to use Matter.Common.clone( body ) and would it make the operation faster?

```
var starvertices = Vertices.fromPath('50 0 63 38 100 38 69 59 82 100 50 75 18 100 31 59 0 38 37 38');

this.body = Bodies.fromVertices(_x, _y, starvertices, {
				render: {
					fillStyle: '#ff00ff',
					strokeStyle: '#000000',
					lineWidth: 1
				}
			}, true);

**Comment by liabru** [comment]
Looks like it may be faster since you're decomposing those vertices every time. So yeah try out using the `Common.clone(body, true);` function, make sure you also do `body.id  = Common.nextId()`.

There's actually this [great blog post](https://dassur.ma/things/deep-copy/) on fast cloning, you should try those methods out too (don't for get to change the id too).

**Comment by MaLuci** [comment]
Thanks a lot!

**Comment by MaLuci** [comment]
I'm getting an error when calling Matter.Common.clone(starBody):

```
var starvertices = Matter.Vertices.fromPath('50 0 63 38 100 38 69 59 82 100 50 75 18 100 31 59 0 38 37 38');
var starBody = Bodies.fromVertices(200, 200, starvertices, {
                           render: {
                                    fillStyle: '#ff00ff',
                                    strokeStyle: '#000000',
                                    lineWidth: 1
                            }
                      }, true);
Matter.Body.scale(starBody, 1.5, 1.5);

var starClone = Matter.Common.clone(starBody);
starClone.id = Matter.Common.nextId();
```
![screen shot 2018-02-16 at 17 18 46](https://user-images.githubusercontent.com/34343729/36317638-e6141ccc-133d-11e8-9a7b-2eb17d0a86fd.png)

**Comment by MaLuci** [comment]
console.log(starBody) returns an empty object {} ?

**Comment by MaLuci** [comment]
I managed to do the cloning using this: https://www.npmjs.com/package/clone

Thanks for pointing me in the right direction!

**Comment by MaLuci** [comment]
I managed to do the cloning using this: https://www.npmjs.com/package/clone

Thanks for pointing me in the right direction :)

**Comment by SollyBunny** [comment]
> I'm getting an error when calling Matter.Common.clone(starBody):
> 
> ```
> var starvertices = Matter.Vertices.fromPath('50 0 63 38 100 38 69 59 82 100 50 75 18 100 31 59 0 38 37 38');
> var starBody = Bodies.fromVertices(200, 200, starvertices, {
>                            render: {
>                                     fillStyle: '#ff00ff',
>                                     strokeStyle: '#000000',
>                                     lineWidth: 1
>                             }
>                       }, true);
> Matter.Body.scale(starBody, 1.5, 1.5);
> 
> var starClone = Matter.Common.clone(starBody);
> starClone.id = Matter.Common.nextId();
> ```
> 
> ![screen shot 2018-02-16 at 17 18 46](https://user-images.githubusercontent.com/34343729/36317638-e6141ccc-133d-11e8-9a7b-2eb17d0a86fd.png)

You can fix this by doing `delete body.parent`

**Comment by mikhail** [comment]
@SollyBunny, 

Is there some rotational component that needs to be cleared as well? My new body B object spins around the original body A's axis when A is rotated around its own axis. x and y components seem unrelated, but rotating A causes B to rotate as well around A.

**Comment by SollyBunny** [comment]
> Is there some rotational component that needs to be cleared as well?

Fuck around and find out. :D
This is just what worked for me

**Comment by mikhail** [comment]
I ended up copying individual values rather than  copying all and then deleting certain ones.
