### ISSUE TITLE
What is the best way to create "balloon" objects that oppose gravity?

### ISSUE THREAD

**Issue by probityrules** [liabru/matter-js#576]
I tried to create balloon objects by creating an opposing force to gravity that's slightly stronger than gravity by doing something like this:

     Matter.Events.on(engine, "beforeUpdate", function () {
       var lift = 1.15;
         
       Matter.Body.applyForce(balloon, {x: 0, y: 0}, {
         x: -gravity.x * balloon.mass * gravity.scale * lift,
         y: -gravity.y * balloon.mass * gravity.scale * lift
       });
     });

But that results in some very peculiar collision effects as shown here:
![inverse-gravity](https://user-images.githubusercontent.com/1324745/36393744-d62c6592-157e-11e8-94e3-1e07a0f374fc.gif)

Is there a better way to achieve a "balloon" behavior that doesn't create odd collision rebounding when touching static bodies? For reference, I was able to recreate the rebounding effect in a simpler jsfiddle here: http://jsfiddle.net/derekdetweiler/19k5dhgu/

**Comment by liabru** [comment]
I think the issue is that the second argument to `Matter.Body.applyForce` is a world-space position, so instead you should use `balloon.position` there?

**Comment by probityrules** [comment]
That was exactly it! Thanks for the quick response: I suppose I need to re-read the documentation next time. 🤦

**Comment by liabru** [comment]
No worries, not the first person to have the issue! It's natural to think of it from a body-relative point of view. I think the reason it isn't is mostly for consistency with the rest of the engine.
