### ISSUE TITLE
How to distinguish the similar radius of the ball in order to get a different feel

### ISSUE THREAD

**Issue by ManfredHu** [liabru/matter-js#578]
There are two types of balls, a and b, which have the same radius.
In a gravity-free environment, I want to make it difficult for a type of ball to be dragged so that class b ball can be easily dragged.
**I set them different density values, but the difference is not obvious.**
```js
//world
this.engine.world.gravity.y = 0;
this.engine.world.gravity.x = 0;
//ball property
let ballOption = {
    density: 10000,
    frictionStatic: 10,
    frictionAir: 0.03,
    restitution: 0.4
};
```
**There are other ways to make the two drag the ball feel different?**

**Comment by hexus** [comment]
Try giving them different air friction instead. Increasing `frictionAir` should increase their resistance to moving.

**Comment by liabru** [comment]
You can also try making the `MouseConstraint` have a lower stiffness, if it ends up being too much even for the lighter ball then change the stiffness only when moving the heavy ball and then switch it back after release.
