### ISSUE TITLE
Synchronizing Two Instances of matter-js: Velocity Per Tick vs. Velocity Per Time

### ISSUE THREAD

**Issue by singerbj** [liabru/matter-js#580]
In regards to your initial response to https://github.com/liabru/matter-js/issues/157, I'm looking at the Body Manipulation Demo... but I'm not seeing how the example applies to moving bodies accurately for a top down multiplayer game.

I have successfully synchronized two instances of matter-js, but since one is the server and one is the client they don't run at the same speeds (The server does more processing per tick than the client). This causes the issue mentioned in https://github.com/liabru/matter-js/issues/157 (I think) where the host player moves slower than the client player despite having the same velocities. I'm struggling to find the right way to force all bodies' velocities to be relative to actual time rather than the engine's tick interval (which I think is what's causing my problem? Correct me if I'm wrong). Do you have any guidance on this matter?

**Comment by liabru** [comment]
Networked physics is very difficult topic, so I suggest taking a look at [this article](https://gafferongames.com/post/introduction_to_networked_physics/) and the many other great [posts](https://gafferongames.com/) by the same author. It's really too big of a topic for me to discuss here (and I'm really no expert).

I will say though, are you using a fixed delta time or a dynamic one? Try using the former if not.

**Comment by singerbj** [comment]
Thanks for your response @libaru...I think I tried that but I'll give it another go!
