### ISSUE TITLE
`Body.setPosition` and sensor-inside-sensor collision detection...

### ISSUE THREAD

**Issue by probityrules** [liabru/matter-js#582]
I am experiencing an issue with using `Body.setPosition` to set a body's position and getting collision to be detected correctly for two sensors. I have a large sensor (bottom light blue area below). If a small sensor body is created outside the large sensor, it seems to behave correctly (the left-most circle). It's red when there is no collision, but yellow when there is.

However, note the behavior of the other two circle bodies that are created inside the large sensor. Their behavior is incorrect: sometimes they're colliding (yellow), but randomly they're not (red), when moved around using `setPosition` inside the large sensor. Interestingly, if I move the body outside the large sensor and back in, it begins to work correctly (as shown by the center circle). Also, if I stay within the bounds of the large sensor, but move the circle very quickly, it seems to begin behaving correctly (as shown by the right-most circle).

![setposition](https://user-images.githubusercontent.com/1324745/37186173-1ed2be7c-2312-11e8-8af0-840757e94e61.gif)

Any suggestions on how to work around this? I noticed that using constraints instead of `setPosition` didn't exhibit this issue, but I want to use `setPosition` so I can handle positions a little more precisely. I suppose I could create the bodies outside the sensor area for a tick and then move them into position or move the body quickly between two positions, but I'm hoping there might be a cleaner way to handle it.

**Comment by probityrules** [comment]
I just determined what caused the above issue: I initially set up all the bodies as static until they need to be moved. As such, the `Grid._bucketAddBody` method was not creating a pair between the two static bodies on initial creation. Thus, as the small body was moved within the larger body across buckets, the pair count is sporadically off for various regions' bucket combinations. As such, collision is occasionally not tested when a pair is assumed to not exist for a given region, resulting in no collision.

I'm not sure how this impacts performance, but I was able to fix the issue by removing the pair static check so that the initial pairing is established (changed code commented below):

```
    Grid._bucketAddBody = function(grid, bucket, body) {
        for (var i = 0; i < bucket.length; i++) {
            var bodyB = bucket[i];

            // Removed the second part of this check so static pairs won't drop out.
            if (body.id === bodyB.id /* || (body.isStatic && bodyB.isStatic) */ )
                continue;

            var pairId = Pair.id(body, bodyB),
                pair = grid.pairs[pairId];

            if (pair) {
                pair[2] += 1;
            } else {
                grid.pairs[pairId] = [body, bodyB, 1];
            }
        }

        bucket.push(body);
    };
```

I assume there may be a better way to handle this, maybe by double-checking pairs for a body's region when it transitions to/from static?

**Comment by liabru** [comment]
You may be right, it's possible that the grid class doesn't properly handle bodies that are changed from static (that code was written long before the latter feature was implemented). So I guess this needs testing, thanks!

**Comment by liabru** [comment]
As of the latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) the grid broadphase has been replaced, so I'll close this one as I'd expect it to be resolved since it seemed to be related.
