### ISSUE TITLE
Outdated @types/matter-js

### ISSUE THREAD

**Issue by jared83** [liabru/matter-js#585]
Very outdated. Current version of matter is 0.14.1 - typed version 0.10.0
For instance, take a look at IRendererOptions - [many options](https://github.com/liabru/matter-js/wiki/Rendering#options) are missing type definitions.
[@DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/matter-js)
[@npm repo](https://www.npmjs.com/package/@types/matter-js)

**Comment by jared83** [comment]
Ah... just realised that you are not the creator / maintainer of these definitions at DefinitelyTyped.
It would be nice if you were though :)

**Comment by liabru** [comment]
Yeah you'll need to contact them, I don't maintain it, cheers.
