### ISSUE TITLE
How do I check if the engine is running? Where's `engine.enabled` flag? Runner can't be stopped? Or always reporting 'enabled === true'?

### ISSUE THREAD

**Issue by jared83** [liabru/matter-js#586]
The following illustrates and documents problems I am experiencing:
```javascript
this.engine = Engine.create()
...
		let runner = Runner.create()
		Runner.run(runner,this.engine) // even if commented out...
		Runner.stop(runner) // even if commented out...
		console.log(runner.enabled) // ...true, true, still true, always true...
		console.log(this.engine.enabled) // undefined Why? How do I check if the engine is running?
		console.log(runner)
		runner.enabled = false
		console.log(runner.enabled) // now it's false, but has it really stopped (and stopped the engine too)?
```
Basically, I am writing unit tests for my app, and I need to know that the engine is running at a given point in the app's execution.

**Comment by liabru** [comment]
There's nothing built in to track this, the `engine.enabled` property is just used for pausing during running, so it will always be `true` unless you set it to `false` to pause. You'll have to track it yourself for now, but I'll add this as a feature request.

**Comment by jared83** [comment]
Lovely! Thank you so much liabru!
BTW. Looking forward to those cued PR to be merged into the next ver. of Matter.js.
Looks to me like many of them will give it a nice performance boost.
Currently, even about 100 bodies bouncing around make a slightly aged mobile to stutter.
cheers

**Comment by bouraqadi** [comment]
There is no more  in  .
To pause/resume simulation I am using `Runner.stop()` and `Runner.start()`. But, according to the documentation, I should be using `engine.enabled` property. However, it is `undefined` in 0.14.2 and in 0.10 too.
