### ISSUE TITLE
Bodies and positions from SVG image

### ISSUE THREAD

**Issue by earthican** [liabru/matter-js#587]
Hi,

I've created an SVG image of elements I want to display. I want to make a video game, so say this image has multiple elements that create platformer level scene. In the image, all the elements are positionally laid out, e.g. the ground is at `y=10`, the next platform is at `y=25` etc.

Does matter-js have the capability to create bodies from vertices from path with their specified positions as laid out in the SVG image?

I hope my question makes sense. Thanks in advance.

**Comment by liabru** [comment]
It can only create one body from per SVG using the `Svg.pathToVertices` function, so you'll have to handle creating multiple bodies yourself I'm afraid.

**Comment by earthican** [comment]
Alright good to know, thanks for your help!
