### ISSUE TITLE
Drag & Drop a static body

### ISSUE THREAD

**Issue by bluehipy** [liabru/matter-js#589]
This might be a very simple thing to do but I have troubles getting around it.

How do I drag and drop a static body?

I know that the idea of static solid might be outside of the dragging concept but somehow I need this ability of positioning some statics, otherwise, with the mouse.

Thank you!

**Comment by liabru** [comment]
Look into the source of [Matter.MouseConstraint](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js#L93-L131) I think you can do something similar but use `Body.setPosition` rather than using a constraint.

**Comment by bluehipy** [comment]
Looking in the Matter.MouseConstraint source is very helpful!

Thank you!
