### ISSUE TITLE
Compound body made of parts that are compound bodies

### ISSUE THREAD

**Issue by sroboubi** [liabru/matter-js#591]
I assumed that I can create any body (including a compound) and use it as a part when creating another body. However it seems like this doesn't work. In the example below, body1 is correctly decomposed into 2 convex parts, however body2 is a single square... the decomposition is not maintained. I expect both of these bodies to look the same:
```javascript
var engine = Matter.Engine.create();
engine.world.gravity = { x: 0, y: 0 };

var render = Matter.Render.create({
    element: document.body,
    engine: engine
});

var bounds = [{x: -50, y: 50}, {x: -50, y: -50}, {x: 0, y: 0}, {x: 50, y: -50}, {x: 50, y: 50}];

var body1 = Matter.Bodies.fromVertices(200, 200, bounds, {}, true);
Matter.World.add(engine.world, body1);

var part = Matter.Bodies.fromVertices(400, 200, bounds, {}, true);
var body2 = Matter.Body.create({parts: [part]});
Matter.World.add(engine.world, body2);

Matter.Engine.run(engine);
Matter.Render.run(render);
```
What am I doing wrong and what is the correct way to get what I want?

**Comment by yungzhu** [comment]
I met the same problem,Is there a solution

**Comment by sroboubi** [comment]
Well I think for now you'll have to decompose the body yourself and create convex parts manually... I might write a wrapper to abstract that for me (which is what matter.js should probably be doing anyway if it weren't for this bug).

**Comment by liabru** [comment]
Compound body parts don't support parts themselves (it isn't recursive, it only goes one level deep). So what you should do is flatten all your parts into a single array rather than nesting them.

**Comment by yungzhu** [comment]
Many times, a polygon may be a complex
It may contain rectangles, polygons
