### ISSUE TITLE
Require poly-decomp.js  in node.js - Fallback to convex hull

### ISSUE THREAD

**Issue by L3mmAa** [liabru/matter-js#593]
How do i properply require and use poly-decomp.js on the serverside of node.js. Its easy to setup in the browser, just import it in the html file before i import matter-js but how do i do it on the server side?

**Comment by nukadelic** [comment]
Can you store a local copy of [decomp](https://rawgit.com/schteppe/poly-decomp.js/master/build/decomp.js) ?

**Comment by adapap** [comment]
I am having the same issue. How can I reference the poly-decomp.js file in a way that matter-js can use it?
