### ISSUE TITLE
Collision sometimes skips 'start' event with sensors

### ISSUE THREAD

**Issue by kirillbunin** [liabru/matter-js#598]
I'm experiencing irregular issue, with `collisionstart` sometimes not triggering, I suppose it is when the object is too fast. What is a standard workaround for this? Now I'm using `collisionactive` and checking whether collision has been triggered for the first time, but I'm not sure this is the best solution. Is there a config for collision tick rate?

**Comment by kirillbunin** [comment]
Anyone got thoughts on this? I couldn't find anything useful so far :/

**Comment by kirillbunin** [comment]
Still an issue in 3.4.0

**Comment by liabru** [comment]
Closing issue due to age, feel free to comment if still applicable.
