### ISSUE TITLE
Issue w/ Settling and Constraints

### ISSUE THREAD

**Issue by GopherwoodTodd** [liabru/matter-js#601]
I'm working on a project with @probityrules and we're running into issues with the physics never settling down. 

We are creating structures with constraints and we find when colliding either with static bodies (like the ground) or with non-static bodies (e.g. the balls in the gif) the simulation continually vibrates.

![unstable_structure](https://user-images.githubusercontent.com/5168916/38833438-82727f4a-4193-11e8-8bdc-98a20ad167be.gif)

I played a little with the density of the balls since I know sometimes having heavy objects on top of lighter once can cause issues in some physics engines, but it seemed to have no effect.

**Comment by liabru** [comment]
Can you show me all the settings for all bodies involved?
