### ISSUE TITLE
Minimal Example does not work in Node.

### ISSUE THREAD

**Issue by kd8azz** [liabru/matter-js#604]
I understand that I ought to look into writing my own event loop, in order to decouple from e.g. _requestAnimationFrame, but I thought I should mention that the Minimal Example does not work in Node, currently, given that the README says it "should".

Steps I went through before posting:

-   First, document is not defined.
-   I concluded `element: document.body` is not required, in the render config, so I removed it.  Now matter.js:9636 fails with "document is not defined".  `var canvas = document.createElement('canvas');`
-   Then, when I passed in my own canvas to the render config (made via the npm 'canvas' package), matter-js fails on initializing _requestAnimationFrame.

**Comment by ellipticaldoor** [comment]
Just don't use the render on node.

**Comment by liabru** [comment]
Actually there's no support for node with the built in renderer, it requires the browser. So what are you using as your canvas? Maybe there's a way to make it work.

**Comment by kd8azz** [comment]
@ellipticaldoor My app was server-side only, and I was trying to render a video.  Besides, the README said it should work.

@liabru 
> So what are you using as your canvas?
As I said in the bug, I was using the npm 'canvas' package.

In any case this doesn't matter.  I found something else and/or abandoned it; it's been long enough that I neither remember nor care.  Sorry I didn't see your follow-up when you originally posted it.  Feel free to leave this closed.
