### ISSUE TITLE
Help!!! I need to  save the state of the game.

### ISSUE THREAD

**Issue by OrigamiKill** [liabru/matter-js#605]
can I keep the bodies and their vectors and speed....when I reload the page? I use metter.js + PHP. is that even possible without changing your code very much?(very cool library, bro)

**Comment by liabru** [comment]
Try using [MatterTools.Serializer](https://github.com/liabru/matter-tools/blob/master/src/tools/Serializer.js) on your world.

**Comment by OrigamiKill** [comment]
thanks)
