### ISSUE TITLE
Online real time (multiplayer) with Sockets question

### ISSUE THREAD

**Issue by cain** [liabru/matter-js#606]
Hey just curious if anyone has somehow stored matter-js info, just curious how they did it.

I'm looking to create a multiplayer game!
Thanks

**Comment by liabru** [comment]
This is really a bit of a large question and is out of scope for discussion here (please see my response to #580). That said, if you're looking for how to serialise have a look [here](https://github.com/liabru/matter-tools/blob/master/src/tools/Serializer.js).

**Comment by vnglst** [comment]
I stumbled across your post @cain as I'm also looking into doing something with sockets.io and serialising the matter-js world data. Did you get it to work?

**Comment by cain** [comment]
@vnglst checkout https://github.com/lance-gg/lance

deals with all the complicated latency issues that you could face. I havent got around to creating anything yet tho :(

**Comment by vnglst** [comment]
very cool man! Thanks.
