### ISSUE TITLE
About `triangles can be a little unstable`

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#607]
In the demo , there is a comment : 
```
// triangles can be a little unstable, so avoid until fixed
```

Has this issue  been fixed ?  

Thanks

**Comment by finscn** [comment]
@bchevalier ,  could you help me ?

**Comment by liabru** [comment]
This is generally far less of an issue than it was when I wrote that comment, they should work fine now. But still in general (and this applies to most physics engines) you should try to avoid shapes with sharp spikes because they can get stuck inside other bodies.

**Comment by finscn** [comment]
Thanks,  I see.
