### ISSUE TITLE
[REQUEST] Add `gravityScale` to Body

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#609]
`body.gravityScale` could make the different bodies with different falling speed.

Then, change
```
            body.force.y += body.mass * gravity.y * gravityScale;
            body.force.x += body.mass * gravity.x * gravityScale;
```
to 
```
            body.force.y += body.mass * gravity.y * body.gravityScale * gravityScale;
            body.force.x += body.mass * gravity.x * body.gravityScale * gravityScale;
```

**Comment by liabru** [comment]
I'd prefer not to add this because it would no longer be acting like gravity. If you need custom 'gravity' like this it's much better to disable the built in gravity and apply your own, by looping through each body and adding the force you need, hope that makes sense.

**Comment by finscn** [comment]
Ok , I see ,and  I agree with you. thanks.
