### ISSUE TITLE
How to make a static body rotate  automatically?

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#610]
I set  `angularVelocity` to the static body , but it doesn't rotate.

**Comment by liabru** [comment]
Check out the [body manipulation example](http://brm.io/matter-js/demo/#manipulation) which shows this.

**Comment by liabru** [comment]
As far as the engine is concerned, static bodies never move so they never have velocity. You must move them manually (using `setPosition` and `rotate`). For collisions to work correctly, you must also inform the engine what the static body's 'velocity' was based on the position change (using `setVelocity` and `setAngularVelocity`).

**Comment by finscn** [comment]
In some physics engines , static bodies could move or rotate when set velocity .
And in some other physics engines , there is a type called `kinematic body` .

Why does  matter.js  not do the same thing ? for performance ?

**Comment by photonstorm** [comment]
It's quite unusual for a 'static' body to ever move. Box2D, Corona, P2, Unreal 4 static bodies cannot be moved at all (same as Colliders in Unity) so I think the term makes sense and keeps it consistent.

Like you said, a static body that can be moved is a kinematic body. matter provides this by letting you set the position of a static body, but you have to account for the motion too. I guess it could make it bit easier to handle and introduce a new kinematic body type that did it for you, and then disallow a static body from moving at all - but personally, I'd rather see @liabru time spent on more useful things, like merging in all the recent speed improvements from Brice :)

**Comment by finscn** [comment]
Hi @photonstorm , you are better than me at physics engine.
Could you help me for this question ?  https://github.com/flyover/box2d.ts/issues/9  thanks
