### ISSUE TITLE
How to create a  kinematic body ?

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#611]
In the  most physics engines , there are 3 types of body : static  , dynamic , and kinematic.

I know in matter.js , the `isStatic` could make a body as static or dynamic , but how to create a kinematic body ?

**Comment by liabru** [comment]
I gave you the answer in your thread #610, there's also a feature request open for this #498 which you should +1. Please remember to search the issues before you post to avoid duplicates, thanks!

**Comment by finscn** [comment]
@liabru , Sorry , my english is very weak. I often can't find the right 'key words' for searching.
