### ISSUE TITLE
Why does matterJS use polygon to simulate circle ,not use real circle ?

### ISSUE THREAD

**Issue by finscn** [liabru/matter-js#615]
I'm a newbie of Physics Engine . 
I found box2d use real circle , but matterJS use   polygon to simulate circle .

Why do this ? 
it could supply a better performance ? 
thanks

**Comment by liabru** [comment]
Originally because it simplifies the code base a lot, since circles are a special case in the collision detection phase. That said, I do hope to implement some time, there's a feature request open for this see #301.
