### ISSUE TITLE
How can I have my bodies look the same size at any zoom level?

### ISSUE THREAD

**Issue by geajack** [liabru/matter-js#617]
I want to simulate a bunch of small objects moving around. When you zoom in or out (via the rendering object's "bounds" object), they shouldn't change size in the view, they should basically act as if they're just points. As it is, when I want to create a whole cluster of them in a small space (less then 2x2 in world coordinates), when I zoom in, I just get a whole bunch of circles all crammed into one spot.

Can I create some kind of custom rendering in order to make this happen?

**Comment by liabru** [comment]
Yeah exactly I'd suggest custom rendering, you could start by forking `Matter.Render` and changing the way it renders circles, I think the easiest way would be to just scale the radius [here](https://github.com/liabru/matter-js/blob/master/src/render/Render.js#L579) by the inverse of view zoom factor.
