### ISSUE TITLE
The lineWidth body's render option doesn't work as expected

### ISSUE THREAD

**Issue by nilscox** [liabru/matter-js#618]
Hi,

I want to modify the `lineWidth` property for all my bodies, but it always renders the same, whatever value I put for the [`render.lineWidth`](http://brm.io/matter-js/docs/classes/Body.html#property_render.lineWidth) option when creating the body.

[Here](https://codepen.io/nilscox/pen/XqYRdK) is a working example of the problem, but maybe I didn't understand how to set this value correctly.

Thanks!

**Comment by nilscox** [comment]
As far as I understand, the `lineWidth` option should be used with `wireframe: true` when creating the `Render` object. But I can't find any documentation about this option, only the introduction in the [`Render`](http://brm.io/matter-js/docs/classes/Render.html) docs.
Is there more information available for the `Render`'s options?

**Comment by liabru** [comment]
Actually the `lineWidth` option does not work in wireframe mode, you should set `wireframe: false` to use it. You can still get a wireframe look using `render.fillStyle = 'transparent'`, if that's what you're after.

**Comment by nilscox** [comment]
Yup, that should work. Thanks!
