### ISSUE TITLE
Weird behavior when body reaches x coordinate of over ~800

### ISSUE THREAD

**Issue by jakobmulvad** [liabru/matter-js#62]
Hi!

I tried using matter-js for a little spaceship game i made for fun, but my spaceship seems to hit an invisible wall at around x=800.

I have isolated the problem in a codepen here: http://codepen.io/anon/pen/VYzWRa

As you can see my horizontal gravity moves the body to the right but it stops at some arbitrary point. Also, if you try to drag the body with the mouse at this point you can see that it is being effected by a force of some sort.

**Comment by liabru** [comment]
This is because the engine does not update bodies that go outside the world bounds.

For now, try this for infinite bounds:

    engine.world.bounds = {
      min: {
        x: -Infinity,
        y: -Infinity
      },
      max: {
        x: Infinity,
        y: Infinity
      }
    }

Going forward, maybe I should remove this limitation or maybe make it opt-in.

**Comment by jakobmulvad** [comment]
Thanks that fixed the issue.

Yes, I think you should remove this limitation or at least default it to infinite. I think most users would not expect there to be such a restriction. I didn't at least.

Ok keep up the good work, and gogo speculative contacts :grinning:

**Comment by colinsullivan** [comment]
+1

had no idea why a certain part of the scene made the bodies get "stuck" until I found this.
