### ISSUE TITLE
[question] Do Collision events groups and category affect engine events?

### ISSUE THREAD

**Issue by Qriva** [liabru/matter-js#620]
I wanted to know how exactly engine `event` act. In docs there is a function:
` Events.on(Engine, "collisionActive", callback)`
To listen for collision start, end and when body currently colide but I can't find any information what was checked before providing collision pairs, simply:

Do collision `category` or `group` or any other option of body affect collision results in any way ?
or this event just returns all colliding objects and it does not matter if body is sensor or in different collision group/category. Do I have to check it manually?

**Comment by liabru** [comment]
If the collision filter says two bodies can't collide, there will not be any collision object generated, since those pairs get skipped over before they are checked. So they won't appear in any events, is that what you mean?

**Comment by Qriva** [comment]
Yes, exactly this - thank you for clearing it
