### ISSUE TITLE
How to fixed body angle?

### ISSUE THREAD

**Issue by XESDog** [liabru/matter-js#622]
In Box2d we can set "fixedRotation=true" to fixed body angle. How to do it in Matterjs?

**Comment by liabru** [comment]
The easiest way to do it is to use `Body.setInertia(body, Infinity)`. Maybe an option would be nice to make this more obvious though.

**Comment by thephilwells** [comment]
@liabru sorry to resurrect this but how do I then unlock rotation a body whose inertia I have set to `Infinity`? I can't find a default value in the code.

**Comment by liabru** [comment]
You should be able to use `Body.setMass`, it will set the inertia too.
