### ISSUE TITLE
How to get a Perfect-Elastic-Collision system？ 

### ISSUE THREAD

**Issue by ljt1469** [liabru/matter-js#626]
I tried to get a system of one particle within a container. 

I am sure that the options of the particle and the wall is set correctly, such as friction is 0, restitution is 1. But, I found the velocity of the particle became slow when it collided with the container wall（the wall is a rectangle).It means that the kinetic energy of particle reduce when the collision happen.

So why and how to make the collision between particle and wall Perfect Elastic Collision?

**Comment by jared83** [comment]
This is [an issue](https://stackoverflow.com/questions/48288413/matter-js-how-to-make-bodies-circles-bounce-endlessly-perfect-elasticity-in) I am struggling with myself. Not sure why this is the case, but the problem may be to be related to rounding errors (in the Verlet integration engine of matter.js?). 
The workaround I devised is to transfer velocity manually at each collision. Kinda works, but is very hacky and won't work as expected if masses of collided particles differ (unless you take it under consideration in your custom, perfectly-elastic velocity transferring function). Not to mention the performance impact of such calculations on top of what matter.js is doing...

**Comment by liabru** [comment]
See thread #256, which discusses this with some suggestions around this issue. Please leave any further comments there as I'm closing this as a duplicate, thanks for raising though.
