### ISSUE TITLE
matter-js can't find decomp when imported via ES6

### ISSUE THREAD

**Issue by fiskhandlarn** [liabru/matter-js#629]
Since matter.js tries to evaluate windows.decomp directly when imported ...
```
var decomp = (typeof window !== "undefined" ? window['decomp'] : typeof global !== "undefined" ? global['decomp'] : null);
```
... and all imports are done before any other code is run, this (as implied by [this example](https://github.com/liabru/matter-js/issues/339#issuecomment-269400365)) didn't work for me:

```
import decomp from 'poly-decomp';

window.decomp = decomp;

import Matter from 'matter-js'; // eslint-disable-line import/first
```

matter-js was still evaluated before `window.decomp = decomp`, and thus `var decomp` would still be undefined.

This plugin should check for `window.decomp` first when it's needed (inside `Bodies.fromVertices`) or at least document [this solution](https://github.com/liabru/matter-js/issues/559#issuecomment-395918654) from @rykerrumsey.

**Comment by Qriva** [comment]
I had the same problem but managed to resolved it by adding global decomp in webpack (the same as provided link). I also think it should be changed, back then I was very confused why my code does not work even after adding global decomp.
