### ISSUE TITLE
Slow moving bodies do not tip over edges correctly (collision cache issue)

### ISSUE THREAD

**Issue by liabru** [liabru/matter-js#63]
When a body slowly slides off an edge, it does not gain angular momentum as expected.

See: http://jsfiddle.net/Donk/4uwp42e7/

This is caused by lack of detection of such cases where the collision cache needs to be updated.

**Comment by EskelCz** [comment]
I just ran into this. Both versions do it. Glad you know about it.

**Comment by EskelCz** [comment]
Here is my demo, just in case: https://jsfiddle.net/Eskel/vvo4997m/1/

**Comment by liabru** [comment]
The latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) should resolve issues relating to collision reuse including this one.
