### ISSUE TITLE
Hiding body does not work.

### ISSUE THREAD

**Issue by LazyPlanet** [liabru/matter-js#630]
this._gun = this.Matter.Bodies.rectangle(200, 500, 92, 271, { 
            isStatic: false,
            label: "gun",
            mass: 100,
            width: 92,
            height: 271,
            render: {
                visible: true, 
                sprite: 
                {
                    texture: "res/ak_47.png",
                    width: 92,
                    height: 271,
                },
            },
            collisionFilter: {group: false}
        });

this.Matter.World.add(this._engine.world, [ this._gun ]);

while in heartbeat function, i want to hide this_gun (body), it shows ever.

**this._gun.render.visible = false;**

Does any wrong i am using? Thank u.

**Comment by liabru** [comment]
This looks correct so closing as I guess it must have been another problem.
