### ISSUE TITLE
Rotating a wheel

### ISSUE THREAD

**Issue by manuelheilmeier** [liabru/matter-js#634]
I´m rotating a circe and expect it to roll to the logic direction, but it moves to to opposite direction and almost acts like it has no friction. I played around with friction-settings for the "wheel" and the "ground" but there was almost no change in behaviour. Right now the wheel drops to the ground, spins fast and moves extremly slow.

Thx

There is some code attached.. look for the wheel body..

[wheel.txt](https://github.com/liabru/matter-js/files/2183165/wheel.txt)

**Comment by liabru** [comment]
Closing issue due to age, feel free to comment if still applicable.
