### ISSUE TITLE
how to prevent [circle] body from sliding into 0px gaps between static bodies

### ISSUE THREAD

**Issue by Prozi** [liabru/matter-js#636]
So I have this body that is a circle collider

and it has sometimes a big velocity

the problem is that the tiled map of the boundaries is made of small tiles

and at high velocity the body goes through it

here is my config of all bodies:

```
    const config = {
      inertia: Infinity, // do not spin
      friction: 0, // X*100% stop on hit
      frictionAir: 0, // X*100% slow on move
      restitution: 0.5, // bounce X*100% on hit
      collisionFilter: this.level.getCollisionFilter(), // default collision filter
      isStatic
    }
...
  getCollisionFilter (key = null) {
    switch (key) {
      case 'fly':
        return {
          category: 0x0008,
          mask: 0xFFFFFFF1,
          group: -1
        }
      case 'items':
        return {
          category: 0x0004,
          mask: 0xFFFFFFF1,
          group: -1
        }
      case 'woda':
        return {
          category: 0x0002,
          mask: 0xFFFFFFFF,
          group: -1
        }
      default:
        return {
          category: 0x0001,
          mask: 0xFFFFFFFF,
          group: 0
        }
    }
  }
```

this is between the `default` and `woda`

![screenshot from 2018-07-14 23-04-34](https://user-images.githubusercontent.com/3052357/42728427-4eee929a-87ba-11e8-9463-56c32b83a2fb.png)

**Comment by Prozi** [comment]
it always move according to the blue lines / boundaries of tiles / gaps (they are 0px :( )

**Comment by juancaacuna** [comment]
@Prozi Where you able to fix this issue? I'm having the same problem.

**Comment by Prozi** [comment]
this happens when the step is too big, in my case of multiplayer game a lag could create a step much bigger than anticipated in physics. thats why I added something like frameStep = Math.max(step, 1000) where frameStep is in MS

hope that helps anybody
