### ISSUE TITLE
Calculating overlap between two bodies

### ISSUE THREAD

**Issue by eidge** [liabru/matter-js#638]
Hello!

Newbie to MatterJS and game development in general so excuse me if I am missing some context.

I was wondering if there is anything built-in to calculate the overlap (intersection area) of two bodies. I am building a simple top down gliding simulation game and need to figure out the area of my plane that is inside a circle.

**Comment by liabru** [comment]
You can use collision events and the collision objects they provide to find this, it will be in `collision.depth`. Otherwise you should look into `Matter.SAT.collides` if you need to call it at any given time.
