### ISSUE TITLE
'torque' divided by 'inertia' twice?

### ISSUE THREAD

**Issue by spacemeowx2** [liabru/matter-js#64]
See /src/body/Body.js:433
```
body.angularVelocity = ((body.angle - body.anglePrev) * frictionAir * correction) + (body.torque / body.inertia) * deltaTimeSquared;
```
and /src/body/Body.js:433
```
body.torque += (offset.x * force.y - offset.y * force.x) * body.inverseInertia;
```
(After I called applyForce, body doesn't rotate until I changed the position to {x:0,y:250000}.)

**Comment by liabru** [comment]
This may depend on your particular setup.

Can you provide a jsfiddle please?

**Comment by spacemeowx2** [comment]
http://jsfiddle.net/wafo2qga/1/
It's used to be C/S structs. Matter.js running on my server and send frame data to a browser. The task of the browser is to draw frames. So the code is strange.

**Comment by liabru** [comment]
It looks like you're only applying a (small) force for a single frame?
I think you need to apply a force over a number of frames to get the acceleration you're looking for.

But actually, what you probably need to use is `Body.setAngularVelocity` which is instantaneous, where as forces are much slower acting.

**Comment by spacemeowx2** [comment]
No..  You didn't get my point.
http://jsfiddle.net/wafo2qga/2/
```
Body.applyForce(boxA, Vector.add(boxA.position,{x:80,y:0}), {x:0,y:-0.5});
```
A 'small' force let the box jump so high without any rotation. Isn't it abnormal?

**Comment by liabru** [comment]
I do get your point, it does seem a little strange that there's no rotation given the change in linear velocity.

So there may be an issue with angular force application. I'll investigate further, thanks.

**Comment by slice-beans** [comment]
I ran into this issue today too. Fix seems to be to remove `* body.inverseInertia` from Body.js:570.

Based on my rather limited understanding, this makes sense based on the physics because the torque isn't proportional to inertia, however the angular momentum that results from it is.

**Comment by jstoeffler** [comment]
Wow, I was having so much trouble getting things working, I thought it was because I didn't understand what was going on, but turned out by removing * body.inverseInertia everything makes sense now !

Is the bug still here? Or is it just me?

**Comment by liabru** [comment]
Fixed in the latest master build, thanks guys.
