### ISSUE TITLE
after calling Body.setVertices/setParts, pairs have stale collision data leading to exception

### ISSUE THREAD

**Issue by jmfd** [liabru/matter-js#642]
If a body's vertices or parts are swapped out, the pairs collision data will not be correct. This can lead to an exception:

```
[Error] TypeError: undefined is not an object (evaluating 'vectorB.x')
	dot (HYPE-623.physics.js:8381) return (vectorA.x * vectorB.x) + (vectorA.y * vectorB.y);
	_projectToAxis (HYPE-623.physics.js:4117) var min = Vector.dot(vertices[0], axis),
	_overlapAxes (HYPE-623.physics.js:4088) SAT._projectToAxis(projectionA, verticesA, axis);
	collides (HYPE-623.physics.js:3973) minOverlap = SAT._overlapAxes(axisBodyA.vertices, axisBodyB.vertices, axes);
	collisions (HYPE-623.physics.js:2803) var collision = SAT.collides(partA, partB, previousCollision);
	update (HYPE-623.physics.js:5635) var collisions = broadphase.detector(broadphasePairs, engine);
	heartbeatPhysics (HYPE-623.full.js:9498) _Matter.Engine.update(physicsEnvironment.physicsEngine, fixedDelta);
	heartbeat (HYPE-623.full.js:4957)
	(anonymous function) (HYPE-623.full.js:4613)
```

(sorry for the bad line numbers; I added the relevant code to clarify)

From my investigation, it looks like the culprit in this particular case is that the number of vertices changed, leading to the number of axes changing.  But the collision pair has old information.  This line is called:

```
axes = [axisBodyA.axes[previousCollision.axisNumber]];
```

But `previousCollision.axisNumber` may not be a proper index anymore, so the result is `axes = [undefined]`, leading to the above exception.

My current workaround is that before modifying the body, I am deleting a matching pair from the `pairs.list` and `pairs.table` entries.  (If there's a better way or this will have other consequences, please let me know!)

**Comment by luceleaftea** [comment]
Chiming in to say that I also have run into this issue.  I managed to drill down and isolate the issue to the same line that @jmfd did, which is how I stumbled on this issue.  However, I am using Phaser 3 wrapping Matter.js so sadly I don't have much info right now on what specific calls Phaser is making.  If there's anything I can do to help figure this out please let me know!

**Comment by liabru** [comment]
The latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) should resolve issues relating to collision reuse, closing as I'd expect that includes this one.
