### ISSUE TITLE
Add 'rendering' event

### ISSUE THREAD

**Issue by morganrallen** [liabru/matter-js#650]
I'm looking to build a vertical parallax effect and want to be able to draw image to the canvas that appear behind and in front of the normal scene bodies. The foreground ones are easy, I just use the `afterRender` event. But the problem with the `beforeRender` event is that is it fired *before* the canvas is cleared. I've tested with adding a `rendering` event that occurs just after the canvas is cleared and works for my needs. If this is something interesting I can add documentation for it and submit a PR. 

Another wise what would be the suggested way to accomplish this? Using bodies without collision not only seems overkill but requires one controller to function before and then after several others.

**Comment by fabienjuif** [comment]
I am curious: why don't you plug matter-js to PIXI, so you can fully control the rendering and still use matter-js for the physics purpose (and only for that) ?

**Comment by morganrallen** [comment]
I guess just going to simplicity, as the `beforeRender`/`afterRender` events are emitted from within `Render.js` seemed to make sense. Also, isn't RenderPixi being deprecated?
