### ISSUE TITLE
What happens when 2 or more bodies are created and they intersect?

### ISSUE THREAD

**Issue by xfstef** [liabru/matter-js#651]
So I know what happens. Matter JS immediately splits them apart by applying something different than a force, if I am correct. Now my problem with this is that the movement of the bodies is instantaneous, which makes for poor animations, and they are thrown away from each other far too much, creating huge gaps of space between them.

My question is: How can I control / modify this behavior? As it is messing up the layout of the objects that I want to put on the screen. I tried fixing this by implementing matter-attractors and some special functions which allow for custom orbits but it does seem a bit tedious to apply extra calculations, especially since the device that I'm working on has limited CPU power.

I just want bodies that overlap at first to slowly move away from each other and once they stop overlapping to slow down significantly in their movement and stop.

Thanks for any tips / ideas / explanations!

**Comment by liabru** [comment]
> Matter JS immediately splits them apart by applying something different than a force, if I am correct.

Exactly, the position resolver will always try to separate bodies as quickly as it can.

> My question is: How can I control / modify this behavior?

There's no real way to control it, the engine will all ways try to resolve all overlaps as best it can by design, though in some cases it doesn't do a perfect job. The best thing to do here would be to prevent overlaps before you create the bodies, if possible?

**Comment by xfstef** [comment]
Hi, thanks for the quick reply!
I feared that prevention of overlap would be the best solution. Although this sounds easy enough, it really isn't once the screen gets too busy with other objects. 
I think I'll go for an object growth solution, in which the newly spawned objects grow in size right next to the "parent" objects and so they move away from them more organically once they start bumping into each other.

Thanks again and congratulations on making this wonderful library!
