### ISSUE TITLE
_requestAnimationFrame TypeError when running default engine/render loops in Firefox Extension

### ISSUE THREAD

**Issue by calebchalmers** [liabru/matter-js#652]
I created a script using the minimal example from the [Getting Started](https://github.com/liabru/matter-js/wiki/Getting-started) wiki page, and included it and matter.js as content scripts in a basic Firefox Extension.

When I run the extension on a webpage, the line `Engine.run(engine);` raises the exception `TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window`.

After inspecting the matter.js source I found that the problem comes from this line:
![image](https://user-images.githubusercontent.com/8931442/44884484-31bc9000-ac81-11e8-9f30-717660f6af06.png)

_The same problem occurs with `Render.run(render);` and the corresponding `Runner.run` function in matter.js._

**This seems to be because the global object in the Firefox extension's content scripts is not `window` but rather a different sandbox object, therefore `_requestAnimationFrame` is not being called on `window` and raises the exception.**

To prove this, I replaced `_requestAnimationFrame(render)` with `window.requestAnimationFrame(render)` in both `Runner.run` functions and the loops successfully ran without any errors.

Using `_replaceAnimationFrame.call(window, render)` also works, and still maintains the cross-browser support that the original method provides.

This was tested using Firefox v61.0.2, and both Matter v0.14.2 and v0.10.0.

**Comment by liabru** [comment]
I'm not sure if this is still the case but leaving this here in case someone runs into something similar:

- try polyfill `window.requestAnimationFrame` for your environment
- or fork and customise [Matter.Runner](https://github.com/liabru/matter-js/blob/master/src/core/Runner.js)
- or create your own [game loop](https://github.com/liabru/matter-js/wiki/Running) that calls `Engine.update` as needed

As of [0.20.0](https://github.com/liabru/matter-js/pull/1300) you can also now:

- patch [Matter.Runner._onNextFrame](https://github.com/liabru/matter-js/blob/master/src/core/Runner.js#L230-L252) with a polyfill without needing `window`

Thanks for the report.
