### ISSUE TITLE
Is there a way to send a force in a particular direction from a point that can affect all non-static shapes in the canvas?

### ISSUE THREAD

**Issue by codehacker101** [liabru/matter-js#655]
What I am hoping for is to send a force in the upward direction from a fixed point like x : 150, y : 150 when an event is fired like mousedown, so that any shapes that are not static and above that point when the event is fired, get a push upward. See I know how to apply force to a specific shape but not to all shapes from a point.

**Comment by liabru** [comment]
You should be able to loop through all the bodies and use `Matter.Body.applyForce(body, position, force)`, where `position` is a world-space position. See the [docs](http://brm.io/matter-js/docs/classes/Body.html#method_applyForce).

**Comment by codehacker101** [comment]
First of all, truly honored that the creator of matter.js himself responded to query

**Comment by codehacker101** [comment]
Yep I ended up using some lessons I remembered of coordinate geometry and trigonometry to solve the issue. The force is applied again and again using setInterval and it is calculated each time using a formula before being applied.

**Comment by codehacker101** [comment]
btw I have a feature request, option to convert (0,0) from top-left to bottom-left because that is the way we are thought at school, and top-left causes confusion when you have apply concepts from coordinate geometry, vectors or trigonometry. If you think this is a good idea then I'll try at least try to create it myself (as a plugin perhaps). Just need to know whether you approve.

**Comment by liabru** [comment]
Glad you managed to solve it. As for coordinate systems, the one used here is the same as used in most game engines and graphics libraries, but if you need something else then you could try using a transform when rendering.
