### ISSUE TITLE
I want a rectangle to rotate at the end.

### ISSUE THREAD

**Issue by 1977474741** [liabru/matter-js#656]
I want a rectangle to rotate at the end, and I look at all the issues associated with it, and I find that positionPrev has a high probability of occurrence, but I still don't understand the difference between positionPrev and position. @liabru

**Comment by liabru** [comment]
I assume you mean you'd like to change the origin (i.e. centre of mass)? In which case you should set both `body.position` and `body.positionPrev` at the same time to the desired origin in world space. I've marked this as improve as it would be great to have a function to make this more obvious.

**Comment by liabru** [comment]
The function [Body.setCentre](https://brm.io/matter-js/docs/classes/Body.html#method_setCentre) was added to make this more straightforward.
