### ISSUE TITLE
I want to create a ring, how shuld I do 

### ISSUE THREAD

**Issue by Zhaopengyang** [liabru/matter-js#659]
I created a ring by using SVG path ,but there are two gaps in the left and right of the ring, bodies inside of the ring can get out through gaps. And the ring is not so smooth.

here's the path:
d="m0,0a200,200 0 0 0 400,0a200,200 0 0 0 -400,0m5,0a195, 195 0 0 1 390, 0a195, 195 0 0 1 -390, 0z"

Could you please tell me how can I create a perfect ring.

or is there any way else to create a ring but not by using SVG path.

Thanks.

**Comment by fabienjuif** [comment]
Hi,

Maybe you can use a circle ?
`Bodies.circle(x, y, radius)`

**Comment by Zhaopengyang** [comment]
Circle is not hollow, I want to add some bodies inside of the ring, it can not be realized by using a circle.
