### ISSUE TITLE
Implement sensors

### ISSUE THREAD

**Issue by ayng** [liabru/matter-js#66]
Make it easier to create a body that ignores collision and tells whether it is intersecting another body.

**Comment by liabru** [comment]
I'll consider it, it's also worth checking out this related issue #65 as my thoughts are similar on this.

**Comment by jstoeffler** [comment]
+1

**Comment by iamjoshua** [comment]
+1
I've implemented something like this in my project using collision filters to avoid the actual collision but then using Query to check for other bodies on sleep to avoid the performance hit of constantly polling. This works for my specific case where bodies move incrementally and have "fields of influence" that handle non-physics/matterjs related interactions. 

I'd much prefer this process to happen in real time so I'd definitely love a sensor feature!

**Comment by liabru** [comment]
This is now available as of 0.9.2, by setting the `body.isSensor` to `true`. Thanks guys.

**Comment by Deftwun** [comment]
Just a heads up that this isn't yet in the [API docs](http://brm.io/matter-js/docs/classes/Body.html#properties)

**Comment by bamtheboozle** [comment]
Any idea how someone can access sensor documentation since it's not in the docs?
