### ISSUE TITLE
Can matter-js be used as physics simulation library? (question)

### ISSUE THREAD

**Issue by abaybektursun** [liabru/matter-js#660]
I need to spawn dozens of simple psychics simulations using web-workers. Is  matter-js good library for this? Can physics be separated from DOM?

**Comment by liabru** [comment]
You can run multiple engines, there is no DOM used other than optionally rendering to a canvas with the debug renderer. I've not used the engine in a worker before but it should work.

**Comment by abaybektursun** [comment]
Thanks!
