### ISSUE TITLE
How to improve performance when using workers?

### ISSUE THREAD

**Issue by marioscs** [liabru/matter-js#662]
Hello, i am wondering how should i use web workers in order to achieve the best performance i can. Currently i am posting all the bodies to the parent from the worker and i am seeing some issues on slower machines. Is there a better way?
You can see a simplified example of the strategy i use [here](https://jsfiddle.net/ayrnL0gz/).
Thanks.

P.S. I  can't use OffscreenCanvas in my enviroment.

**Comment by Weedshaker** [comment]
Isn't it possible to only send the changed bodies?

**Comment by liabru** [comment]
Yeah exactly for something like this you only really need to send the position change every frame.

That said these days I'd recommend avoiding that and run everything in a worker and use OffscreenCanvas, otherwise the benefits of using a worker are likely very limited.
