### ISSUE TITLE
How to avoid mouse dragging moving bodies outside static bodies

### ISSUE THREAD

**Issue by eddnav** [liabru/matter-js#663]
I know the title doesn't really explain well my problem:

https://codepen.io/eddnav/pen/LJdBmZ?editors=1010

I'm trying to make ring-like bounds (with a simple version derived from the ring solutions in a recent ticket in this repo) that contain other objects such as that circle. Adding dragging to the mouse I was able to move around the circle within the bounds, but I noticed that after dragging hard outside of the ring, the circle was able to escape. I also noticed that I could lower the stiffness and that would help but it still happens on values as low as `0.1`.

Is there a way to achieve a perfect barrier against this aggressive mouse movement?

**Comment by liabru** [comment]
Thanks for reporting, see issue #5, closing this as duplicate.
