### ISSUE TITLE
how to check if my object is on the "floor"?

### ISSUE THREAD

**Issue by jcyuan** [liabru/matter-js#665]
I currently use `if(myobj.body.velocity.y == 0)` most time this works except if my object is on top of some object like this:

![image](https://user-images.githubusercontent.com/850854/45420606-2b84d580-b6bd-11e8-902c-8ae965bf5a8a.png)

as you can see in the console the `velocity.y` is changed in every frame update even my obj is not moved, I think this can be fixed by setting some parameter for the world?

what caused this problem? and what is the right way to fix? thanks a lot.

**Comment by fabienjuif** [comment]
@jcyuan I am curious: Why didn't you use `Collides` engine on this one ?

**Comment by jcyuan** [comment]
@fabienjuif you mean I should set a flag to indicate whether my object is on floor or not when it collides with the 'floor' right?

**Comment by jcyuan** [comment]
@fabienjuif dud do you have some 2d game tuts? Hero body should be a rectangle or a composite contains a rectangle and a circle? and move it just set angularVelocity for the circle like a wheel?

**Comment by fabienjuif** [comment]
@jcyuan I mean, you can:
1. set a `type` to your floor, body.type = 'floor'
2. use collide events, and then use the flag to detect the floor:
http://brm.io/matter-js/docs/classes/Engine.html#events
 - `collisionStart`
 - `collisionEnd`
 - `collisionActive`
3. Set a boolean into your "player" to mark it "on the floor" indeed

What means `tuts`? 
My game doesn't have gravity, and I use circles for the heros :)

**Comment by jcyuan** [comment]
@fabienjuif 'tuts' means tutorials LOL.  yepp, I changed my game logic, thanks man~
