### ISSUE TITLE
Making width and height defeault for the bounds.

### ISSUE THREAD

**Issue by rgk** [liabru/matter-js#67]
For example if I set the height and width of the render window to 1600 by 600 with the engine.create options, the bounds stay at 800 by 600 (which is the default). What you have to do is update the bounds. I just think for some it might be easier that the height and width defaults to the bounds unless you change it like below.

    engine.world.bounds.max.x = 1600;
    engine.world.bounds.max.y = 600;

**Comment by liabru** [comment]
This is indeed an issue.

I'm likely going to remove world bounds very soon, as their main purpose was to disable out of world bodies to prevent the browser from locking up when simulations glitched in early development.

But if I decide to keep them, I'll add a fix for this. Thanks.

**Comment by simonbw** [comment]
Is there any issue currently with setting the world bounds to be Infinity and -Infinity?

**Comment by liabru** [comment]
Yep that should work fine (or are you having an issue)?

**Comment by simonbw** [comment]
I was not having an issue, I was just asking in case it messed up some calculations somewhere that I might not know about. Thanks for the fast reply!

**Comment by jankovsky** [comment]
Hy. I mean what i have a same problem. I don't undersatand what i do wrong. For example - http://kroteg.com/boxes/   Objects sticks in center of canvas. How i can solved this?

**Comment by liabru** [comment]
@jankovsky 

    engine.world.bounds.min.x = -Infinity;
    engine.world.bounds.min.y = -Infinity;
    engine.world.bounds.max.x = Infinity;
    engine.world.bounds.max.y = Infinity;

**Comment by vostokwork** [comment]
There is no chance to set the boundaries of the world with this:

```js
this.engine = Engine.create()
this.engine.world.bounds = { min: { x: 0, y: 0 }, max: { x: s.width, y: s.height } }
```

**It's just. Doesn't. Work. AT ALL**

**Comment by liabru** [comment]
@vostokwork what are you expecting the worlds bounds to do? They don't really apply to anything in practice (and probably should be removed to be fair). If you need collisions you should use static bodies like in the examples.
