### ISSUE TITLE
Example drop-down text isn't visible.

### ISSUE THREAD

**Issue by chisophugis** [liabru/matter-js#674]
On http://brm.io/matter-js/demo/ if I open the drop-down, I see the following. Notice that only the highlighted example name is visible; the others are invisible for some reason. This makes it hard to navigate the examples.

![screenshot from 2018-10-08 23-00-33](https://user-images.githubusercontent.com/358163/46649503-28f78d80-cb4e-11e8-8c77-19247c651e7e.png)

Ubuntu 18.04, Chromium Version 69.0.3497.100

**Comment by konijn** [comment]
Same on Chrome for Win 10.

**Comment by liabru** [comment]
Ah yes thanks this one does need to be fixed, it's technically a bug in [matter-tools](https://github.com/liabru/matter-tools) but I'll leave it here for the moment.

**Comment by liabru** [comment]
Closing this as it is covered by https://github.com/liabru/matter-tools/pull/5, thanks.
