### ISSUE TITLE
Getting point of collision and normal through collisionStart event

### ISSUE THREAD

**Issue by Kodedyukh** [liabru/matter-js#675]
I'm creating a game with Phaser 3 using MatterJS

I want to start a particle emitter on every collision at a point where the collision took place and in the direction, opposite to normal vector of the collision

Unfortunately, now 'collisionstart' event doesn't provide this information. But as I can understand it calculates it in Engine.update() here https://github.com/liabru/matter-js/blob/7894b4b44d41077200cfe209c01b35b595db90f4/src/core/Engine.js#L179

I'm planning to use 'normal' and 'supports' properties of the collision for my purposes. 'Normal' as normal vector opposite to the particles' speed direction and average of 'supports' as a point where the collision took place

So is it possible to change line (in Engine.update())

`            Events.trigger(engine, 'collisionStart', { pairs: pairs.collisionStart });`

to something like 

`            Events.trigger(engine, 'collisionStart', { pairs: pairs.collisionStart, collision: pairCollision });`

where pairCollision is a collision object, a member of 'collisions' array, corresponding to a given pair?

**Comment by liabru** [comment]
Have a look at the source for [`Render.collisions`](https://github.com/liabru/matter-js/blob/master/src/render/Render.js#L1061) which shows how to use collision points and normals, hopefully that covers what you need (you can see them by setting `render.options.showCollisions = true`).

**Comment by Kodedyukh** [comment]
Thank you! This gives a good overview on how to use `collision` object and how to retrieve it from the `engine` object.

So it looks like using 'engine.pairs.list[i].collision' can solve my issue
