### ISSUE TITLE
I have a hierarchical model in SVG format. How do I import this model?

### ISSUE THREAD

**Issue by turner** [liabru/matter-js#676]
Hello,
I wrote a modeling tool in JS that builds hierarchical tree models (L-Systems) and renders it in SVG. The model I create is hierarchical: groups with transforms at each branching point. So nested transformations.

Is it possible to import this model into matter.js while preserving the hierarchy? Ultimately I will add masses, gravity, perhaps wind forces, etc.

Thank.

**Comment by liabru** [comment]
The built in utilities for SVG are basic, as it is not the focus of the project, so you will probably need to build your own tooling for your needs. The engine supports compound bodies made of multiple convex parts that act as a single solid body, which is then how concave bodies can be made.
