### ISSUE TITLE
Pivot point of multi parts body

### ISSUE THREAD

**Issue by WagnerJakob** [liabru/matter-js#679]
Hi

Love the script!

I'm using this script in a custom application, so I don't use the renderer, but just the simulation. Then applies the data from the simulation to my visual objects.

I have a compound body which is made like this:

```javascript
var body1 = Bodies.rectangle(-75, 0, 50, 50, properties);
var body2 = Bodies.rectangle(-5, 0, 50, 50, properties);
body = Body.create({parts: [body1, body2]});
Body.setPosition(body, { x: 1000, y: 200 });
```

It is giving me trouble because it seems to centre the pivot point, which means my visual object will be misplaced.

This works fine:

```javascript
var body1 = Bodies.rectangle(-35, 0, 50, 50, properties);
var body2 = Bodies.rectangle(35, 0, 50, 50, properties);
body = Body.create({parts: [body1, body2]});
Body.setPosition(body, { x: 1000, y: 200 });
```
... because the the pivot is in the centre on my visual object. Here is an image to give a better overview:

![matterjs_parts_center](https://user-images.githubusercontent.com/44237879/47099563-d85eef00-d235-11e8-8a54-255a87ab6998.gif)

Problem is of course that my pivot point isn't in the centre. Is there a solution for this?
Can I set the pivot of the compound body?
Can I somehow move the body1 and body2 inside the compound body, to make it similar to my visual object?

Let me know if I need to clarify.

Any help is greatly appreciated,
Jakob Wagner

**Comment by liabru** [comment]
See my reply to #673 for and explanation and possible solution. If you actually want to move the pivot point (therefore centre of mass) then you should move both `body.position` and `body.positionPrev` vectors together (so not moving the vertices). Thinking about it this would probably be useful to add as a function!

**Comment by WagnerJakob** [comment]
Thank you for replying. Moving the pivot is what I want, I already tried moving both position and prevPosition, but didn't get it to work. I will try it again, and come back with more info if I still can't get the result.

**Comment by WagnerJakob** [comment]
Got it working now. Using your method. Thanks.
