### ISSUE TITLE
Core/Sleeping allow for negative force

### ISSUE THREAD

**Issue by rfoligno** [liabru/matter-js#68]
Should core/sleeping.js allow for negative force when it decides whether or not to take a body out of its sleeping state?

Line in question: [/core/Sleeping.js#L30](https://github.com/liabru/matter-js/blob/5770013b9083cf912e604739d85f5039b9ea4c44/src/core/Sleeping.js#L30)

With the line above, [running this code](https://gist.github.com/rfoligno/d0226f99a1206db42243) results in the body remaining stationary ([jsfiddle](http://jsfiddle.net/vttopxn0/) example here) when the W key is pressed (desired result: object jumps upwards). I understand that I might not be using the lib in the desired fashion, but it would increase flexibility of the code to change this condition to the following:

```
if (body.force.x != 0 || body.force.y != 0) {
```

Thoughts? If I'm just using it plain wrong, advice would also be welcome.

**Comment by liabru** [comment]
Good spot! 

I'm kind of wondering how sleeping even works well enough that I didn't even spot this mistake :)
I'll get this fixed, cheers.

**Comment by rfoligno** [comment]
Created a [PR](https://github.com/liabru/matter-js/pull/69) for it.
