### ISSUE TITLE
Change mass of one of a bodys parts

### ISSUE THREAD

**Issue by Mazn1191** [liabru/matter-js#684]
I've created a body using

```
var myBody = Matter.Body.create({
                parts: [
                    bodyPart1,
                    bodyPart2
                ]
            }
        );
```

I did so because I want to shift the center of mass of this body by changing the mass of one of the body parts.
I did so by using  

`Matter.Body.setMass(myBody.parts[2], newMass);`

Unfortunately this doesn't have any effect on the behaviour of `myBody`. The mass property of my compund body in fact remains unchanged (and therefore doesn't reflect the sum of its parts masses anymore).

Setting the mass prior to creating the compound body I get exactly the result I want. Unfortunately I have to change the center of this body mass constantly.

I've looked into the code and apparently it's not possible to change the mass of a bodies part after creation, since `_totalProperties(body)` is only called whenever a part is added.

Calling this piece of code with `myBody` as parameter whenever I changed the mass of a part only resulted in weird behaviour:

```
var total = _totalProperties(body);

body.area = total.area;
body.parent = body;
body.position.x = total.centre.x;
body.position.y = total.centre.y;
body.positionPrev.x = total.centre.x;
body.positionPrev.y = total.centre.y;

Body.setMass(body, total.mass);
Body.setInertia(body, total.inertia);
Body.setPosition(body, total.centre);
```
Is there something you can suggest? Or can't this bevaviour be achieved with matterjs?

**Comment by liabru** [comment]
Only the parent body's mass is used when running and that gets calculated once from the parts at creation. So what you should do is just set the parent body mass and you can move the centre of mass by setting:

```
body.position.x = x;
body.position.y = y;
body.positionPrev.x = x;
body.positionPrev.y = y;
```

This gets requested a lot so I will look into putting it into a function.

**Comment by Mazn1191** [comment]
Where x and y would be the desired cog in world coordinates? I'll give it a go, thank you.
