### ISSUE TITLE
World bounds (limits)

### ISSUE THREAD

**Issue by juzdepeche** [liabru/matter-js#688]
Is there a way to create limits for a world for any bodies with any mask, category or group? I tried world.bounds but it only defines the limits of collision detections.

**Comment by liabru** [comment]
I think `world.bounds` is actually redundant now, originally it was to prevent processing bodies that had moved off canvas, but this was before the render view feature was implemented and it no longer made sense to keep it. So to restrict bodies to an area you should use static bodies as walls.

**Comment by ZachSaucier** [comment]
I have a situation where I have a circle that follows the mouse position and a bunch of smaller circles that are affected by gravity. All of them can collide with each other. I have set static boundaries around the viewport that are very thick (like 5,000 width). However, if a user moves the mouse quickly, it can knock the smaller circles out of the viewport. Do this a bunch of times and there are few to no small circles left.

Is there a better way to make sure that the circles stay in bounds? Maybe a reset method if their position is outside of a range? How can I check for that?
