### ISSUE TITLE
Question: is there a way for a group of bodies to collide with each other and for another group: the last group is acting like a sensor?

### ISSUE THREAD

**Issue by juzdepeche** [liabru/matter-js#691]
I would something like surviv.io : items on the ground (circles with weapon) collide with each other but for the players, items are only sensors. How can I do this?

![image](https://user-images.githubusercontent.com/40125713/48563746-fe25f500-e8c2-11e8-92d1-4baa2b6eac7e.png)

**Comment by liabru** [comment]
I think you should be able to use [collision filters](http://brm.io/matter-js/docs/classes/Body.html#property_collisionFilter) to do this by using two bodies pinned together for each item,  one is the main body and one is an invisible sensor.

**Comment by juzdepeche** [comment]
It worked! Thank you and congratulations for this amazing physics engine.

![image](https://user-images.githubusercontent.com/40125713/48664542-040c0980-ea6e-11e8-93f7-890b3d3a06cc.png)
