### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by 1ucay** [liabru/matter-js#698]
Hello, matter js not working in IE11? Thank you

**Comment by liabru** [comment]
Closing this due to age and lack of information. If this is still a problem, please open a new issue with example code, version information, error messages and a description of the problem.

**Comment by jblume-chw** [comment]
I've run into this same issue with IE11. I discovered it while using matter as part of phaserjs, but see the same error message when visiting the matter page: https://brm.io/matter-js/. 

![image](https://user-images.githubusercontent.com/770896/75582827-0d866e80-5a32-11ea-80c0-448c2fd9ff25.png)

**Comment by liabru** [comment]
Good catch @jblume-chw, would you mind opening a new issue for that one? Thanks.
