### ISSUE TITLE
Bower install did not update release to 0.14.2,Please can you push the tags

### ISSUE THREAD

**Issue by dharaneesh** [liabru/matter-js#700]
Bower has only following versions with 0.12.0 release latest
Available versions in https://github.com/liabru/matter-js.git: 0.12.0, 0.11.1, 0.11.0, 0.10.0,

Thanks
Dharaneesh

**Comment by liabru** [comment]
The project is no longer supporting Bower since it is outdated in favour of other tools, it is recommended to use the NPM package instead. Thanks for raising this as I will make a note to update the readme.
