### ISSUE TITLE
Matter.Bounds.create is setting min and max to infinity 

### ISSUE THREAD

**Issue by DeclanFinnerty** [liabru/matter-js#703]
Hi, 
I'm using the following code to setup bounds for a viewport:

let viewportBounds = Matter.Bounds.create( { min: { x: 0, y: 0 }, max: { x: 800, y: 600 } });

When I check viewportBounds, after the above code has run, I see viewportBounds max and min are set to infinity, why is that and what is the proper way to create a bounds?

**Comment by PsuFan** [comment]
Why not add static wall bounds?

https://github.com/liabru/matter-js/blob/master/examples/airFriction.js#L41

**Comment by liabru** [comment]
How are you using `viewportBounds`? Can you show some more code?

**Comment by vostokwork** [comment]
@liabru 

```js
var bounds = Bounds.create( { min: { x: 0, y: 0 }, max: { x: s.width, y: s.height } })
World.add(this.engine.world, bounds)
console.log(bounds);
```

![image](https://user-images.githubusercontent.com/37534401/107835524-daf09580-6daa-11eb-8951-2925aceca2bd.png)

**Comment by liabru** [comment]
@vostokwork the API for `Bounds.create` is a little different from the others, check it out in the [docs](https://brm.io/matter-js/docs/classes/Bounds.html#method_create) (check the first argument). I'd like to make it consistent eventually when the project is ready for breaking changes :)

In this case you can just go ahead with `{ min: { x: 0, y: 0 }, max: { x: s.width, y: s.height } }` as your bounds object. 
One other thing, you don't need to add it to the world.

**Comment by vostokwork** [comment]
@liabru But this is doen't work. 

I use p5.js for render. 

Can you give me an example?

**Comment by vostokwork** [comment]
@liabru 

Like this? Doesn't work too.

```js
Bounds.create([
    { x: 0, y: 0 },
    { x: s.width, y: 0 },
    { x: s.width, y: s.height },
    { x: 0, y: s.height },
    { x: 0, y: 0 },
])
```

**Comment by liabru** [comment]
@vostokwork no, if you just need to create some bounds just can just use the plain object:

`const bounds = { min: { x: 0, y: 0 }, max: { x: s.width, y: s.height } }`

The `Bounds.create(vertices)` is meant for automatically calculating bounds from `Bodies.vertices`, which you don't need here.
