### ISSUE TITLE
Body Collision Group Default

### ISSUE THREAD

**Issue by PsuFan** [liabru/matter-js#704]
Why is the default collision group zero? Wouldn't having default 1 collide with everything, ignore category and mask filters and be more efficient?

**Comment by liabru** [comment]
Groups are not used by default, so `0` is a special value which effectively indicates 'no group'. If I remember correctly groups were implemented before collision masks, they were not really intended to be used together (although they can).

I realise collision filters are tricky to understand! There's an issue open here around making them better #341. For more info see the docs for [body.collisionFilter](https://brm.io/matter-js/docs/classes/Body.html#property_collisionFilter) and also the source for [Detector.canCollide](https://github.com/liabru/matter-js/blob/master/src/collision/Detector.js#L92-L105).
