### ISSUE TITLE
Body slides on a horizontal ground.

### ISSUE THREAD

**Issue by adityathebe** [liabru/matter-js#705]
[**Demo**](https://adityathebe.github.io/evolutionSimulator/Demo/Person/)
[**Code**](https://adityathebe.github.io/evolutionSimulator/Models/person.js)

Don't have much to write here. Please find the code in the link above.

I have a complex body, imitating human, which slides indefinitely on a perfectly horizontal ground. I have set the friction on the ground (_boundary.ground_) and feet of the creature (_leggy.leftFoot_, _leggy.rightFoot_) to max, i.e. 1. All the body parts are of uniform density 0.05 (except the feet). The density of the feet is set to 1 to prevent dipping into the ground.

![Low Feet Density](https://i.imgur.com/g72xz9S.png)
**Low Feet Density**

![High Feet Density](https://i.imgur.com/kIktkbm.png)
**High Feet Density**

**Comment by PsuFan** [comment]
Try with a rectangle for ground instead of boundary.ground?

**Comment by liabru** [comment]
Don't set `slop: 0` as there needs to be a small amount of sinking for friction to work, also try increasing `body.frictionStatic` too? Also avoid large differences (e.g. > 10x) in density as this can cause instability.
