### ISSUE TITLE
How to create a perfectly rigid constraint ?

### ISSUE THREAD

**Issue by adityathebe** [liabru/matter-js#706]
I'm trying to create a human and for that I'm using _Bodies.rectangle_ as its bone and _Constraint_ as its muscle. The stiffness of all the muscles are set to max i.e. 1. However, the constraints are very spring like. Provided a certain momentum, the constraint expands.

![Good Position](https://i.imgur.com/HfSW66B.png)
**Good Position**

![Bad position](https://i.imgur.com/KRChy90.png)
**Bad position**

As you can see in the above image, the muscle (constraint) in the left leg has shifted as I rapidly increased the length of the constraint. In fact, the shift doesn't even have to be rapid. Simply lifting the creature will sometime affect the constraint's length.

I tried making the bodies lighter by decreasing the density but that doesn't solve the problem. In fact, it leads to another problem #705

**Comment by PsuFan** [comment]
use game loop programming to prevent body parts from exceeding desired angles...

**Comment by liabru** [comment]
If you need even stiffer constraints then you should try increase `engine.constraintIterations`, use multiple constraints at the same points (instead of just one) or even try a `stiffness` value of > 1 e.g. `1.1` (though this can become unstable).
