### ISSUE TITLE
Glue mouse drag of Body

### ISSUE THREAD

**Issue by meeps123** [liabru/matter-js#712]
Hi Liam, I would like to know how to design a `MouseConstraint` on a specific `Body` such that it will always be under the mouse no matter how fast the user moves the mouse.

Previously, I have commented on #245, but at that time what I wanted was this effect where the `Body` was being "dragged along" by the mouse, as if there was a rope connecting the mouse and the `Body`. 

Now, I'm thinking of this effect where the `Body` is **glued** to the bottom of the mouse, so it can never lag behind the mouse.

I've seen #268 and tried to implement the solution there. No luck. When viewing the `Matter.js` render in wireframe mode, the green line representing the `MouseConstraint` is gone, however when moving the `Body` around the `Body` still lags behind the mouse pointer.

I've put my code here: http://jsfiddle.net/oxj4mgcd/. My code starts on line **10363**.

How should I make sure that the `Body` doesn't lag behind the mouse?

Additionally, I would also like to detect the direction of movement of the `Body`. In the JSFiddle, I change the colour of the `Body` according to what direction it is travelling in. I have used a formula found from [this StackOverFlow post](https://stackoverflow.com/questions/12627532/how-can-i-get-the-direction-of-rotation-relative-to-a-given-point-from-the-mouse?rq=1) in line **10461**. 

I notice this behaviour in the Result panel of the JSFiddle:
- When I drag the mouse quickly from left to right, the detection of direction works because the `Body` lags behind the mouse by a little bit.
- When I drag the mouse slowly towards the right, the direction stays as RIGHT.
- When I leave the mouse pointer stationary, the direction always defaults to RIGHT.
- However, when I drag the mouse slowly towards the left, the direction starts flipping from LEFT to RIGHT. Why?

In the above StackOverFlow post, the author of the accepted answer said:

> You will still get erratic behavior around the midpoint, due to the nature of how rapidly the angles can change. One solution to this is stopping rotation when within a certain distance of the midpoint.

If I implement an effect where the `Body` is glued to the mouse, this means that the mouse pointer will always be very close to the middle of the `Body`. Therefore the likelihood of the direction flipping due to the minute changes in the angles is very high.

In that case, may I know if there is a better way in `Matter.js` to detect the direction of movement in a `Body`?

Thank you very much!

**Comment by meeps123** [comment]
Hi Liam, sorry for the lengthy request and the inconvenience caused. However may I know if you could help me as I have a deadline for this project I am working on in the next 2 weeks?

Thank you very much.

**Comment by liabru** [comment]
I hope you managed to get this sorted, apologies slow response, but if I understand correctly my suggestion would be to just use a static body with `Body.setPosition` so something like:

```js
  var mouse = Mouse.create(render.canvas);
  var body = Bodies.rectangle(0, 0, 10, 10, { isStatic: true });

  Events.on(engine, 'afterUpdate', function() {
      if (!mouse.position.x) {
        return;
      }

      Body.setVelocity(body, {
          x: body.position.x - mouse.position.x,
          y: body.position.y - mouse.position.y
      })

      Body.translate(body, {
          x: mouse.position.x,
          y: mouse.position.y
      });
  });
```

As for getting the direction, that's a little bit out of the scope this project, but I'd look into using `Vector.angle(body.velocity)`, note that there two angles for 'right', 0 and 2 PI.

**Comment by Matthieusch** [comment]
Hi!

I changed the `Body.translate` to `Body.setPosition` in code sample. Now it works fine!

Regards,
Mosa

**Comment by liabru** [comment]
@Matthieusch oh good catch thanks, I've updated the above
