### ISSUE TITLE
Questions about implementation for multiplayer game through an express server.

### ISSUE THREAD

**Issue by romcar** [liabru/matter-js#717]
Hi all,
I have been trying for the past day to figure out how to implement Matter-js in an express server so I could add bodies as players log in. I am not sure at this point how to proceed with this task. If anyone has pointers/guidance, it would be greatly appreciated.

**Comment by romcar** [comment]
My initial thought was to create the `Engine` in the express server then somehow pass that engine into the client when the user opens the homepage, then render the `Engine`. This approach allows me to open an engine but I have `wireframe: false` in the options and what appears on screen makes me believe that the engine is not rendering correctly. I also get this error logging constantly.
<img width="723" alt="screen shot 2019-02-10 at 9 15 49 pm" src="https://user-images.githubusercontent.com/31927972/52567811-28605380-2ddb-11e9-96a5-6da262423c38.png">

**Comment by H4sh3** [comment]
Hey, i am working on a task similar to yours.
Have you gotten any further?
Not sure if passing the engine to the client is the right approach.
My idea was to initialize the engine separately in the server and the client. 
Client inputs are send to the server and update the engine. Afterwards the changes are broadcasted to the other clients.

**Comment by romcar** [comment]
I wasn't able to figure it out then I got busy with work.

**Comment by liabru** [comment]
See my response in your other thread #716, what @H4sh3 said sounds like the right kind of approach.
