### ISSUE TITLE
Trying to make a car with suspension

### ISSUE THREAD

**Issue by Hazelnut03** [liabru/matter-js#718]
Trying to make a Hill Climb Racing copy, and struggling to make a car body with correct suspension.
Relatively new to matter.js and just need a bit of help.
Sorry if this is not the right place to ask

**Comment by Hazelnut03** [comment]
This is the code so far, the rectangles are for testing the car works, and I'm using the p5.js library for drawing. Any help will be appreciated.

var noiseScale=0.002,
    mapdata = [],
    maplength = 4000000,
    offset = 0,
    speed = 5,
    Engine = Matter.Engine,
    Composites = Matter.Composites,
    World = Matter.World,
    Bodies = Matter.Bodies,
    rectangles = [],
    circles = [],
    rect1,
    rect2,
    cir1;

var engine = Engine.create(),
    world = engine.world;

function preload(){
  createMap();
}

function setup(){
  createCanvas(1024, 512);
  rect1 = Bodies.rectangle(200, 150, 400, 20, { isStatic: true, angle: PI * 0.06, friction: 0}),
  rect2 = Bodies.rectangle(500, 350, 650, 20, { isStatic: true, angle: -PI * 0.06, friction: 0}),
  car1 = Composites.car(200, 100, 100, 20, 20)
  World.add(world, [rect1, rect2, car1]);
  fill(255);
  stroke(0);
}

function draw() {
  Engine.update(engine);
  background(100, 150, 255);
  for (let x = 0; x < width; x++) {
    var pos = x + offset;
    stroke(0, 150, 0);
    line(x, mapdata[pos], x, height);
    stroke(210, 105, 30);
    line(x, mapdata[pos] + 5, x, height);
  }

  stroke(0);
  shape(rect1.vertices);
  shape(rect2.vertices);
  shape(car1.bodies[0].vertices)

  for (x = 1; x < car1.bodies.length; x ++){
    ellipse(car1.bodies[x].position.x, car1.bodies[x].position.y, car1.bodies[x].circleRadius * 2);
  }
  // offset += speed;
  // noLoop();
}

function createMap(){
  for (let x = 0; x < maplength; x++){
    let noiseVal = noise(x*noiseScale);
    mapdata[x] = noiseVal * 300 + 200;
    noiseScale += 2 * (10**-8);
  }
}

function shape(arr){
  beginShape();
  for (x = 0; x < arr.length; x ++){
    vertex(arr[x].x, arr[x].y);
    endShape(CLOSE);
  }
}

**Comment by liabru** [comment]
This is too big of a question to ask here unfortunately. As with anything like this, it takes quite a bit of trial and error using different approaches, combinations of bodies and multiple constraints.

**Comment by Hazelnut03** [comment]
Ok thanks though
