### ISSUE TITLE
Removing green drag trail

### ISSUE THREAD

**Issue by InGale** [liabru/matter-js#72]
I'm trying to create a sort of mobile game with Matter.js. I'm using Matter.js mobile demo as reference point. I was able to change a few things and make it work, however I wasn't able to get rid of the green drag trail that's being shown when I drag an object. I tried this:

World.add(_world, MouseConstraint.create(_engine, {
	    render: {
	         visible: false,
	         lineWidth: 0,
	        strokeStyle: 'rgba(0,0,0,0)'
	    }
}));

But that didn't work. Is it possible to remove it?

**Comment by liabru** [comment]
Try this:

	var mouseConstraint = MouseConstraint.create(engine, {
	  constraint: {
	    render: {
	      visible: false
	    }
	  }
	});

**Comment by InGale** [comment]
Yes, that worked, thanks!
