### ISSUE TITLE
Position is not the same across different devices

### ISSUE THREAD

**Issue by anchetaWern** [liabru/matter-js#722]
I'm trying to create a multi-player maze game where the position of the players as they race to the goal is updated in real-time. The problem I have is that the position I'm getting from one player doesn't necessarily translate to the other player. This is because the device size is either bigger or smaller. 

I'm using the following code to get the position of the body at a set interval:

```
this.sendPositionToOpponent(myObject.position.x, myObject.position.y);
```

Then on the opponent's side, I get the position that was passed (I'm using Pusher):

```
this.myChannel.bind('moved-ball', ({ positionX, positionY }) => {
  Matter.Body.setPosition(myObject, {
    x: positionX,
    y: positionY
  });
});
```

Is there a way of normalizing the positions so it can be directly used on devices with different screen sizes? Thanks.

**Comment by liabru** [comment]
It sounds like a problem with your rendering? The position is just a world space point, not related to rendering or the device hardware. You probably need to make sure that you are handling differences in canvas resolution, viewport and display DPI (pixel ratio) when rendering.
