### ISSUE TITLE
Documentation on eventNames and options

### ISSUE THREAD

**Issue by ndangles** [liabru/matter-js#723]
Hello,

I am having a hard time finding documentation on the list of possible eventNames that can be subscribed to on ```Matter.Events.on(object, eventNames, callback)``` http://brm.io/matter-js/docs/classes/Events.html

Also, trying to find documentation on all the possible options that can be passed to something like ```Matter.Bodies.circle(x, y, radius, [options], [maxSides])```http://brm.io/matter-js/docs/classes/Bodies.html

I would appreciate any link to documentation that specifies the list of possible eventNames and options to be passed in. I have found some here and there looking through different demos but was wondering if there is specific page in the documentation that clearly lists them.

Any help is appreciated

Thank you

**Comment by Cameron-Friel** [comment]
I could not find any specific documentation on the event names myself, however, I did find a file https://github.com/liabru/matter-js/blob/master/examples/events.js in the demos that lists them and explains what they do. I hope this helps!

**Comment by xehpuk** [comment]
`maxSides` seems to be an unused parameter?

**Comment by liabru** [comment]
As @Cameron-Friel mentioned, events for a module can be found at the bottom of the page in that module's docs, for example here are the [Engine events](https://brm.io/matter-js/docs/classes/Engine.html#events) you can listen to.
