### ISSUE TITLE
frictionAir - does not push out from the air

### ISSUE THREAD

**Issue by SamProf** [liabru/matter-js#725]
As far as I know, air resistance is equal to the square of the area and speed of the body.

Those. slowly moving and quickly compressed, you can move.

https://jsfiddle.net/cp2d5yz6/1/

But it is not worked.

**Comment by xxdaggerxx** [comment]
good question, any way to fake this? At least a simple approximation would be good.

**Comment by liabru** [comment]
Air is not simulated like this so it won't work unfortunately, you'll need to figure out the thrust forces and apply them directly.
