### ISSUE TITLE
Runner optimistically distributing delta time?

### ISSUE THREAD

**Issue by wmike1987** [liabru/matter-js#726]
From Runner:
```
// optimistically filter delta over a few frames, to improve stability
            runner.deltaHistory.push(delta);
            runner.deltaHistory = runner.deltaHistory.slice(-runner.deltaSampleSize);
            delta = Math.min.apply(null, runner.deltaHistory);
            
            // limit delta
            delta = delta < runner.deltaMin ? runner.deltaMin : delta;
            delta = delta > runner.deltaMax ? runner.deltaMax : delta;

            // correction for delta
            correction = delta / runner.delta;

            // update engine timing object
            runner.delta = delta;
```

I don't see how the runner is distributing the delta here. If there's any spike in framerate that seems to get totally lost by setting the delta to be the min of deltaHistory.

**Comment by wmike1987** [comment]
Closing this issue since apparently I can't read. The code clearly says "filter" yet I assumed it was distributing frame rate spikes. I understand the strategy now.

**Comment by liabru** [comment]
Yes the idea is to average the frame delta over a few frames to help keep the simulation stable. Though as always, it is advised to use a fixed timestep where possible. I will hopefully be updating the runner to use a more advanced approach like time budgeting at some point.
