### ISSUE TITLE
Can I easily put text on objects

### ISSUE THREAD

**Issue by morganthunder** [liabru/matter-js#734]
This is just a question. Sorry if creating an issue is not the appropriate thing to do. I want to create an animation of word tiles that behave like rigid bodies. So move around bouncing off each other. But I need to be able to easily populate the tiles with different strings. Would like to use matter.js to manage the movement. Is this possible?

**Comment by liabru** [comment]
Sure you can render the world how ever you like, please see the wiki on [rendering](https://github.com/liabru/matter-js/wiki/Rendering).
