### ISSUE TITLE
Body position goes to NaN after applying velocity

### ISSUE THREAD

**Issue by Fredolx** [liabru/matter-js#735]
This is how I apply velocity, X or Y goes to NaN directly after in typescript:

```
static startMovingDirection(player: Player, direction: string){
        switch(direction){
            case "left":
                player.speedX = -1; 
                break;
            case "right":
                player.speedX = 1;
                break;
            case "up":
                player.speedY = -1;
                break;
            case "down":
                player.speedY = 1;
                break;
        }
        m.Body.setVelocity(player.body, {x: player.speedX, y: player.speedY});
    }
```

I'm using NodeJS and i'm not rendering using Matter.JS Renderer. This is happening in a completely server-sided physics scenario.

This is how I update the game manually : 

`setInterval(update, 1000/60);`

```
function update(){
    PhysicsHandler.updateAllPortals();
}
```

```
    static updateAllPortals(){
        this.portals.forEach(portal =>{
            this.updatePlayerPositions(portal);
            m.Engine.update(portal.engine);
        });
    }
```

**Comment by KevinFrazier** [comment]
@Fredolx Did you fix this? What was the issue?

**Comment by a-type** [comment]
@Fredolx would help to know what you found.

I get this problem when I set `frictionAir` to `0`. Currently working around it by setting it to a very small value instead.

**Comment by liabru** [comment]
@a-type `frictionAir: 0` should work fine I think, I tested it and it appears to work for me, are you sure there wasn't more to it?

**Comment by a-type** [comment]
I might have also been using badly scaled values. Not sure, I was only testing out the library.

**Comment by OscarLundberg** [comment]
I had this issue too, very frustrating. 
In my case I was simply passing invalid values for width and height when creating a rect. 
After a lot of debugging I realized I was passing a vector2 for both width and height, and for some reason typescript didn't catch it. 

Thought i'd leave a comment here anyway, maybe someone else makes the same mistake!
