### ISSUE TITLE
How to set the background image?

### ISSUE THREAD

**Issue by geriyoga** [liabru/matter-js#737]
How to set the background image in matter?

**Comment by hopemans30** [comment]
To my knowledge, you need to use CSS to define the background.

**Comment by trabucoaluca** [comment]
i hope that this it help you, from js
runner = Runner.create();
  element = $("#viewport")[0];
  width = 1000;
  height = 800;

render = Render.create({
  element: element,
  engine: engine,
  options: {
    width: width,
    height: height,
    wireframes: false,
    background: 'black'
  }
});

**Comment by raphaelbastide** [comment]
I am looking for a way to set a background fixed to the world. In my case, `Render.lookAt` targets a moving body and I need to display a fiexd grid behind it to enhance the body’s movements. Is that possible?
Should I open a new issue for that?

**Comment by liabru** [comment]
If you're using the debug renderer then you can set `engine.options.background` or `engine.options.wireframeBackground` to a CSS background value which will then be applied to the canvas. @raphaelbastide this should work for you too I think.

**Comment by Baraa-Baba** [comment]
`element =  myElement ;

render = Render.create({
element: element,
engine: engine,
options: {
width: width,
height: height,
wireframes: false,
background: 'transparent' 
}
});`
then you can change myElement  background cause now the canvas in matter js is transparent this worked for me
