### ISSUE TITLE
core/Common.js uses window.performance.now which is less efficient then Date.now and in some cases not even more accurate.

### ISSUE THREAD

**Issue by kujukuju** [liabru/matter-js#739]
More on performance.now here: https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

I didn't dive too deep in the code to check out how much this is impacting performance (hopefully not more than a few calls each tick), but in case it is it would be better to use Date.now() rather than +new Date() or window.performance.now().

**Comment by Ekuju** [comment]
Info from the link in case it's removed later:

```
The timestamp is not actually high-resolution. To mitigate security threats such as Spectre, browsers currently round the results to varying degrees. (Firefox started rounding to 1 millisecond in Firefox 60.) Some browsers may also slightly randomize the timestamp. The precision may improve again in future releases; browser developers are still investigating these timing attacks and how best to mitigate them.
```
