### ISSUE TITLE
MouseConstraint visible for nonstatic but hide for static body

### ISSUE THREAD

**Issue by Yahasana** [liabru/matter-js#740]
```js
        // Mouse constraint (touching and moving bodies)
        var mouseConstraint = MouseConstraint.create(engine, {
            mouse: render.mouse,
            constraint: {
                stiffness: 0.2
                //render: { visible: false }
            }
        });
```
constraint will be visible for both static and non-static objects

**Comment by liabru** [comment]
You could try adding a [collisionFilter](http://brm.io/matter-js/docs/classes/MouseConstraint.html#property_collisionFilter) to the `MouseConstraint` so that it filters out collisions with unwanted bodies.

**Comment by Yahasana** [comment]
`collisionFilter` filters them out. but i want they can be collided and invisible drag constraint lines

**Comment by liabru** [comment]
Sorry I didn't have chance to get back at the time! Hope you managed to get something working so closing now.
