### ISSUE TITLE
Compound bodies don't have restitution

### ISSUE THREAD

**Issue by pstkway** [liabru/matter-js#742]
Hi, I have been playing a lot with Matter lately and I have noticed that when I create compound bodies, they lose all restitution. Is this normal? Or am I missing something?

I have tried adjusting restitution settings for each parts, with no success. My scene contains other regular bodies that function perfectly well. They all bounce around nicely except for the compound body. I have also reduced body parts to the bare minimum to make sure it wasn't the issue, with no success either.

I couldn't find a solution among the issues raised here so this is my attempt to get one.

Thank you!

**Comment by liabru** [comment]
I tried it out and it seems to work for me, the `restitution` should be set on the parent body rather than the parts, did you try that?

**Comment by pstkway** [comment]
Ah, yes! So simple I feel stupid. Thank you for the help.
