### ISSUE TITLE
how detect a composite body as only  a body in a sensor?

### ISSUE THREAD

**Issue by trabucoaluca** [liabru/matter-js#744]
I created a composite body with 2 bodies, but when these fallen the sensor detected each one instead that the sensor detect 20 bodies this detect 40 bodies, how can i doing for fix this?

creation of composite body

```
for(let i = 0; i < total_moleculas; i++){
    atomo_rojo = Bodies.circle(280,150, radio_atomo_rojo,{render:{fillStyle:'red',strokeStyle:'red'/*,sprite:{texture:'js/img2/Esfera_Grande.png'}*/}/*,id:"circulo_rojo_"+[i]*/});
    atomo_blanco = Bodies.circle(((atomo_rojo.position.x) + 5),((atomo_rojo.position.y) + 15),radio_atomo_blanco,{render:{fillStyle:'white',strokeStyle:'black'/*,sprite:{texture:'js/img2/Esfera_2.png'*/}/*},id:"circulo_blanco_"+[i]*/});

    moleculas_unidas = Body.create({
    parts: [atomo_rojo,atomo_blanco],
    restitution: 1,
    friction: 0,
    frictionStatic : 0,
    frictionAir: 0,
    inertia: Infinity,
    mass: 1,
    id: "molecula_unida_"+[i],
    });

    Body.setVelocity( moleculas_unidas, {x: velocity, y: -velocity});
    moleculas_unidas.restitution = 0;
    moleculas_unidas.friction = 0;
    moleculas_unidas.frictionStatic = 0;
    moleculas_unidas.frictionAir = 0;
    moleculas_unidas.inertia = Infinity;
    moleculas_unidas.mass = 1;
    cambiar_color(valor_value);

    array_moleculas_unidas.push(moleculas_unidas);
  }

```
sensor

```
function sensor(){
    var a=0;
    var b=0;
    var lectura = "";
    Events.on(engine, 'collisionStart', function(event) {
        var pairs = event.pairs;
        for (let i = 0, j = pairs.length; i != j; ++i) {
            var pair = pairs[i];

            if (pair.bodyA === barra_superior_vaso_agua){
              a=a+1;
              pair.bodyB.render.strokeStyle = "green";
              
            }
       }
   }
```

here the code complete
https://github.com/trabucoaluca/chemistry/blob/master/x.js

**Comment by jonahrosenblum** [comment]
Have you considered looking at pair.bodyA.parent? Each composite body should list which parent body it belongs to, so you can keep track of your bodies that way.

**Comment by liabru** [comment]
As @jonahrosenblum mentioned, the way to do this is to get the `pair.bodyA.parent` and `pair.bodyB.parent` of each pair, put them in a list and filter out the duplicates, as collisions are reported for each `part` of a compound body individually.

**Comment by SamSverko** [comment]
Let's say you have a compound body (bodyB) of two rectangles stacked vertically that slightly overlap, as well as a smaller rectangle body (bodyA) that will fall as soon as the scene loads:
 __
|__| <- rectangle (will fall along the y axis downward, passing through bodyB)

___
|   |
|   |
|__|
|__| <- this is where the compound body parts overlap
|   |
|   |
|__|

Once the ball is finished passing through the top part of bodyB, it will fire a `collisionEnd` event. Then when it is finished passing through the bottom part of bodyB, it will fire another `collisionEnd` event.

I've tried the `pair.bodyB.parent` as you suggested, but the fact that `collisionEnd` is fired twice, this doesn't help. Perhaps I'm interpreting what you said incorrectly.

Any help would be deeply appreciated. Thank you!
