### ISSUE TITLE
Jamming of objects in layering

### ISSUE THREAD

**Issue by BEGEMOT9I** [liabru/matter-js#745]
How to avoid objects getting stuck in a stack of objects with the same `collisionFilter.group`? For example, in a jsfiddle, you can move a ball to a region with layering of rectangles so that the ball gets stuck there.

Example:
https://jsfiddle.net/mad4bzuf/

**Comment by liabru** [comment]
Generally you should merge bodies like these together and avoid gaps as much as possible, I've marked this as improve but it's a tricky problem.
