### ISSUE TITLE
Performance / fps issues on canvas resize

### ISSUE THREAD

**Issue by ORoberts221** [liabru/matter-js#747]
I've managed to get the canvas to resize with the page by following a few other examples, however I'm doing this by clearing and re-creating the engine every time the resize event is fired, which causes severe performance issues. 

Is there another way to reset the engine? I imagine there is something else that needs cleared which I have missed. 

The inital code:
```
 componentDidMount() {
    canvas = document.getElementById("canvas");
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    this.setup();

    Matter.Engine.run(engine);

    window.addEventListener("resize", this.update.bind(this));
  }
```

Setup function (creates the engine and adds bodies):
```
setup(){
    //create engine
    engine = Matter.Engine.create({
      render: {
        canvas: canvas,
        options: {
          width: canvas.width,
          height: canvas.height,
          wireframes: false,
          background: '#ffffff'
        }
      }
    });

    this.draw();
  }
```

update function (updates canvas size then performs the setup again)
```
 update(){
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
   
    Matter.Engine.clear(engine);
    this.setup();
  
    Matter.Engine.run(engine);
  }
```

**Comment by liabru** [comment]
There shouldn't be any need to change the engine, since it isn't involved in rendering, just resizing the canvas should be fine.
