### ISSUE TITLE
Cannot handle too many collisions between particles.In case of too many particles the particles and move through stable bodies.

### ISSUE THREAD

**Issue by Aanisha** [liabru/matter-js#748]
In case of too many particles,the particles can move through the stable bodies defined in the code.

https://code.sololearn.com/W9v3F4LP2YxA/?ref=app

**Comment by liabru** [comment]
There is currently no CCD, see #5, though even with that feature this case would still eventually become unstable. You could try increasing the number of `Engine.update` calls per step which might help, but in general you should avoid having many fast moving bodies with high restitution in a small space (also the value should be max `1`, but ideally less).
