### ISSUE TITLE
Can not stop box from sliding down slope by friction

### ISSUE THREAD

**Issue by patrikturi** [liabru/matter-js#752]
Hello,
I have a box on a slope and I want the box to "stick" to the slope and stop moving down.
No matter how much I increase the friction (1) or frictionStatic (10+) parameters on both bodies, it will still slide down slowly.
Example: [http://brm.io/matter-js/demo/#friction](http://brm.io/matter-js/demo/#friction) (top one)
What parameters do I have to set to stop the box sliding down the slope?

**Comment by hopemans30** [comment]
I found that is one of the disadvantages in matter.js. You might find the solution on your own because it's a known glitch.

**Comment by patrikturi** [comment]
Right, it is a duplicate of #613

**Comment by liabru** [comment]
Friction has its limits. It's often a balancing act between friction values, slop and mass, after that you may need more iterations. I've opened the other issue again to investigate if there's a bigger problem, thanks.

**Comment by frenselw** [comment]
In fact, after logging body.speed and body.velocity, I found that body.speed is not equal to the magnitude of body.velocity. The magnitude of body.velocity seems normal (very very small), but body.speed is quite large.
