### ISSUE TITLE
reusing previous collision results unsafe with (setPosition) changes

### ISSUE THREAD

**Issue by 2chivi** [liabru/matter-js#753]
Matter.js Code::
```            
var parentA = bodyA.parent,
	parentB = bodyB.parent,
	motion = parentA.speed * parentA.speed + parentA.angularSpeed * parentA.angularSpeed
		   + parentB.speed * parentB.speed + parentB.angularSpeed * parentB.angularSpeed;

// we may be able to (partially) reuse collision result 
// but only safe if collision was resting
canReusePrevCol = previousCollision && previousCollision.collided && motion < 0.2;
```

I've noticed a bug in my game where my Composite will act as if it is colliding with the floor even though it has clearly been moved off the edge of a cliff.  I've tracked down the issue to this line of code in combination with using setPosition/Composite.translate .. instead of setVelocity for movement changes.

The Motion variable does not accurately track translations.. only velocity?

**Comment by 2chivi** [comment]
I'm trying to come up with a solution.. but I'm not super familiar with the codebase.  Maybe something like this will work.

```
motion = parentA.angularSpeed * parentA.angularSpeed
	   + parentB.angularSpeed * parentB.angularSpeed
	   + Math.abs(parentA.position.x - parentA.positionPrev.x)
	   + Math.abs(parentA.position.y - parentA.positionPrev.y)
	   + Math.abs(parentB.position.x - parentB.positionPrev.x)
	   + Math.abs(parentB.position.y - parentB.positionPrev.y);
```

**Comment by liabru** [comment]
When moving a body constantly with `setPosition` to simulate motion you should also update its velocity for collisions to work as expected, see the [manipulation](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L83-L104) example.

**Comment by 2chivi** [comment]
There are certain situations with online game-dev, where I would like to translate positions without imparting velocity.. or having to correct velocity changes after translating.  For example.. when smoothly reconciling desyncs between client and server.

That doesn't mean its impossible to to use both setPosition and setVelocity to correct desyncs.  I'm sure I could probably get it to work.  Just a quality of life thing I guess.

I'm using the following change to the "motion" variable instead.  I think its working for me.

```
motion = parentA.angularSpeed * parentA.angularSpeed
        + parentB.angularSpeed * parentB.angularSpeed
        + Math.abs(parentA.position.x - parentA.positionPrev.x)
        + Math.abs(parentA.position.y - parentA.positionPrev.y)
        + Math.abs(parentB.position.x - parentB.positionPrev.x)
        + Math.abs(parentB.position.y - parentB.positionPrev.y);
```

**Comment by liabru** [comment]
Yeah it's fine to use `setPosition` without imparting velocity, it depends on the use case. From the looks of your solution though, it looks more like this is a problem with collision reuse and the speed values not being correct? This could indeed be a problem, so I will open this again, thanks for raising.

**Comment by 2chivi** [comment]
Correct.  The speed values are not correct.  They do not reflect setPosition changes.

Thank You!

**Comment by RichardPoole42** [comment]
Basing collision reuse on position on speed (either directly or computed from position and positionPrev) will always be prone to fail if setPosition is used to teleport a body, which in most respects works perfectly well (and is something that a game, for instance, might reasonably want to do). I think the safe fix would be to have setPosition also set a flag on the body to indicate that collision reuse is forbidden, and have SAT.collides read this flag, redo the calculation, then clear the flag. @liabru, does this seem reasonable to you? I will implement it if so.

**Comment by liabru** [comment]
@RichardPoole42 I think you're right it's definitely a case to be addressed, that idea could work with the existing approach, though I've long wanted to just change it completely to something better all round, if that makes sense.  Open to ideas if you're interested in helping with a new approach.

**Comment by liabru** [comment]
The latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) should resolve issues relating to collision reuse, closing as I'd expect that includes this one.
