### ISSUE TITLE
Examples links to wrong source code

### ISSUE THREAD

**Issue by andrevenancio** [liabru/matter-js#756]
Example on Terrain is linking to https://github.com/liabru/matter-js/blob/master/examples/terraing.js it should link to https://github.com/liabru/matter-js/blob/master/examples/terrain.js

**Comment by RichardPoole42** [comment]
This is a duplicate of #463 - it was fixed in the repository in 2017, but the demos on brm.io are still running an older version.

**Comment by liabru** [comment]
Yeah it's been addressed already but you're right it needs to be updated thanks for the reminder!
