### ISSUE TITLE
Bodies attract each other

### ISSUE THREAD

**Issue by shakiba** [liabru/matter-js#76]
I have not been able to isolate the issue completely, but bodies attract each other when they are close, are moving slowly and there is no gravity. At least circles are attracted to other objects.

To reproduce it create a box (400x400) with four (static) walls, put few balls (r=15) inside and apply some force to them, also set frictionAir to a small value so that they slow down. As they slow down near each other or near walls they are attracted to other bodies.

**Comment by Aralun** [comment]
Could you give us the reproduction code directly?

**Comment by shakiba** [comment]
```js
  var engine = Engine.create({
    world : {
      gravity : {
        x : 0,
        y : 0
      },
      bounds : {
        min : {
          x : -Infinity,
          y : -Infinity
        },
        max : {
          x : Infinity,
          y : Infinity
        }
      }
    },
    positionIterations : 6,
    velocityIterations : 4,
    enableSleeping : true
  });

  var world = engine.world;

  World.add(world, Body.create({
    isStatic : true,
    friction : 0,
    restitution : 1,
    position : {
      x : 180,
      y : 0
    },
    vertices : [ {
      x : 0,
      y : 0
    }, {
      x : 328,
      y : 0
    }, {
      x : 328,
      y : 50
    }, {
      x : 50,
      y : 50
    } ]
  }));

  var ball = Bodies.circle(50, 40, 15, {
    frictionAir : 0.01,
    friction : 0,
    restitution : 1,
    inertia : Infinity,
    mass : 1,
    render : {}
  });
  World.add(world, ball);

  setTimeout(function() {
    Body.applyForce(ball, {
      x : 0,
      y : 0
    }, {
      x : 0.012,
      y : 0
    });
  }, 500);
```

**Comment by liabru** [comment]
Thanks @shakiba I could see the issue in your sample.

Luckily, my recent work on the [compound-concave](https://github.com/liabru/matter-js/tree/compound-concave) branch seems to have also resolved this in my testing with your sample.

Can you check out [compound-concave](https://github.com/liabru/matter-js/tree/compound-concave) branch and test with it to confirm for me?

Or you can try use this recent dev build that worked for me:
http://brm.io/matter-js-demo-master/js/lib/matter-dev.js

**Comment by liabru** [comment]
This fix is now available in master, update this thread if you're still seeing it, thanks.

**Comment by shakiba** [comment]
The issue is fixed for the example that I have provided here, but it is not fixed for another example that I was working on, I will try to reproduce it in another small example and post it here.

**Comment by liabru** [comment]
Are you still having issues here @shakiba?

**Comment by shakiba** [comment]
Following code reproduces this issue with 2015-06-29 build.

By the way, without merging #75 or a similar fix I'm not able to directly use your library.

```js
  var engine = Engine.create({
    world : {
      gravity : { x : 0, y : 0 }
    },
    positionIterations : 6,
    velocityIterations : 4,
    enableSleeping : true
  });

  var world = engine.world;

  World.add(world, Body.create({
    isStatic : true,
    friction : 0,
    restitution : 1,
    position : { x : 180, y : 0 },
    vertices : [
      { x : 0, y : 0 }, 
      { x : 400, y : 0 }, 
      { x : 400, y : 50 },
      { x : 0, y : 50 } 
    ] }));

  var ball = Bodies.circle(0, 100, 15, {
    frictionAir : 0.01,
    friction : 0,
    restitution : 1,
    inertia : Infinity,
    mass : 1
  });
  World.add(world, ball);

  setTimeout(function() {
    Body.applyForce(ball, { x : 0, y : 0 }, { x : 0.015, y : -0.005 });
  }, 500);
```

**Comment by liabru** [comment]
@shakiba please see my update in #75. As for this issue I'll revisit it soon.
