### ISSUE TITLE
how to make that a body is always bouncing and doesnt change its force?

### ISSUE THREAD

**Issue by trabucoaluca** [liabru/matter-js#764]
that properties or values must have a body for that this is always bouncing, doesnt stop and doesnt change its force, the gravity is 0 in both (x,y)

**Comment by liabru** [comment]
Use `{ inertia: Infinity, restitution: 1, friction: 0, frictionAir: 0, frictionStatic: 0 }` and see #256 for potential issues and solutions. Since this has been asked many times, please refer to that issue instead, thanks.
