### ISSUE TITLE
Allowing for constraint to not affect other body

### ISSUE THREAD

**Issue by mobileben** [liabru/matter-js#766]
Let's say I have a "floating" target. For all practical purposes this could be a rectangle On this target, I have what would be a rod coming out represented by a circle. The best way to think of this scenario is the iron rod to play horseshoes, but in this case, the iron rod coming out of the wall ... or rather in my case the floating target.

I want to be able to throw something as a projectile and then have it "hang" on the bar if it hits. When I refer to "rod" it will in actuality be a matter circle.

I currently added in an `ignoreGravity` to the body to support the floating target. But the problem I have now is the iron rod. I am using a constraint with `length=0` for this. When the object hits the rod, it applies a downward force to the target, moving it. I want to the target to behave as if it was "solid" and not move. (note I use `applyForce` to move the target around). I suppose in theory I could give it a very large mass, but then when I move it it would become sluggish. I did do a quick test and it did actually still move it slightly. 

My work around was to add a collision-less constraint to the target. Then in the game loop, I was updating the position of the rod (rod is set with `isStatic=true`) with the constraint position. The problem with this is it ends up drawing/behaving as if it is offset from the constraint (which in actuality it is)

Is there some form of workaround which

- Allows the rod to stay positionally in the correct location on the target whether it be by proxy constraint or direct to the target
- Collision of the object with the rod will not cause the target to move based on the force applied by the object hitting the rod. The object should either bounce off or if done correctly, hang from the rod (like you'd expect a horseshoe to do, for example).

**Comment by mobileben** [comment]
This is no doubt a hack, but I did find I could get around this adding the following to `Engine.update`. Note my code is one line: `Events.trigger(engine, 'postConstraints', event);`. I've included the rest for context.

```
        // update all constraints (first pass)
        Constraint.preSolveAll(allBodies);
        for (i = 0; i < engine.constraintIterations; i++) {
            Constraint.solveAll(allConstraints, timing.timeScale);
        }
        Constraint.postSolveAll(allBodies);

        Events.trigger(engine, 'postConstraints', event);
```

**Comment by liabru** [comment]
I think some diagrams would help here if you could provide, as it really depends on e.g. the orientations of the bodies.
