### ISSUE TITLE
Controlling DOM elements instead of / along with Canvas bodies

### ISSUE THREAD

**Issue by Igal-Kleiner** [liabru/matter-js#77]
I couldn't find a way to control a DOM element instead of generated bodies on canvas. For example: in the beach balls sample, I'd like to have 4 divs instead of 4 canvas circle bodies, but I'd like to keep the same physics behavior - dragging, collision (with "walls" and with each other), perhaps random moving instead of gravity. I'd also like these divs to have a certain onClick behavior, that should not interrupt the dragging. So is it possible to control the DOM elements in such way and how? Perhaps bind a div to a certain body and update its position whenever the body's position changes on drag / gravity change?

**Comment by Aralun** [comment]
I think you'd need to make your own HTML rendering engine.

**Comment by liabru** [comment]
You'll need to create a custom renderer, see the [wiki page](https://github.com/liabru/matter-js/wiki/Rendering#using-a-custom-renderer) for more info.

You may want to use something like [three.js](http://threejs.org/) since it has a built in DOM rendering mode.

**Comment by liabru** [comment]
Someone made an example for this recently, check it out:
https://jsfiddle.net/mikatalk/suj0ymwh/

**Comment by Nashorn** [comment]
> I couldn't find a way to control a DOM element instead of generated bodies on canvas. For example: in the beach balls sample, I'd like to have 4 divs instead of 4 canvas circle bodies, but I'd like to keep the same physics behavior - dragging, collision (with "walls" and with each other), perhaps random moving instead of gravity. I'd also like these divs to have a certain onClick behavior, that should not interrupt the dragging. So is it possible to control the DOM elements in such way and how? Perhaps bind a div to a certain body and update its position whenever the body's position changes on drag / gravity change?

Did you find a solution to this?
