### ISSUE TITLE
Shaking composite body

### ISSUE THREAD

**Issue by ban4e** [liabru/matter-js#772]
I want to do something like that https://stackblitz.com/edit/matter-ragdoll?file=index.ts (falling ragdolls)
The problem is that the ragdolls are shaking on ground. Is any ideas how to make stop it ?

**Comment by mathmakgakpak** [comment]
i have same problem

**Comment by liabru** [comment]
Ragdolls tend to be pretty unstable generally I think but there's a few options to try:

- lower your `Engine.update` delta and increase update iterations
- increase `engine.constraintIterations`, `engine.velocityIterations`, `engine.positionIterations`
- decrease or increase the stiffness (and length) of the constraints
- vary the mass, e.g. try large mass body and low mass limbs or maybe even all exactly the same mass
- disable friction

Hopefully those help.
