### ISSUE TITLE
Spinning problems

### ISSUE THREAD

**Issue by Sanuich** [liabru/matter-js#775]
I want to make a tank 2d on a flat surface (no platformer)

i tried high mass and friction but anyway when it run on to other objects even light weight it starts to spinn

How to disable spinning objects from collisions?

Is there a way to implement kinda angular friction?

**Comment by liabru** [comment]
Take a look at the [body manipulation](http://brm.io/matter-js/demo/#manipulation) example which shows how to precisely control bodies.

**Comment by Sanuich** [comment]
> Take a look at the [body manipulation](http://brm.io/matter-js/demo/#manipulation) example which shows how to precisely control bodies.

Thanks. I did my best
take a look 
http://thesage.org.ua/gamez/tanks/
