### ISSUE TITLE
L shaped rotating body

### ISSUE THREAD

**Issue by labonocl** [liabru/matter-js#780]
Hi,

my question is quite simply: How can I create an L-shaped (rigid) body that rotates? I realize I cannot make an L-shaped body with vertices since it is not convex.

My other strategy is to create two rectangular bodies (one long, one short, make them perpendicular to each other forming an L), affix them to each other by some constraint such that they are rigidly attached to each other, and then set one in motion by using setAngularVelocity - but I cannot work out how to set the constraint! Any ideas?

PS: Eventually, I then need to short rectangle to disappear after the body has been rotating for a while - but we'll cross that bridge when we get to it...

**Comment by morgan3d** [comment]
You can use the hierarchy for this. Put a rectangle with a child part rectangle and they will be rigidly attached to each other. Look at `Matter.Body.setParts()` in the documentation.

**Comment by liabru** [comment]
Exactly, thanks @morgan3d. Bodies can have multiple 'parts' (other bodies, essentially) which allow you to form solid concave bodies. Create a rectangle body and then add another to it as a part and that should work.
