### ISSUE TITLE
How to suspend a body (neutralise gravity)?

### ISSUE THREAD

**Issue by rvanderspuy** [liabru/matter-js#781]
Hello!

I'm trying to suspend a body (a balloon) in space. The body is connected by a constraint to another body, but I don't want the weight of the connected body to pull the balloon down. I essentially want the balloon to suspend, neutrally, whatever it is connected to, without being dragged down by whatever it is carrying.

I'm pretty sure that I need to apply a `y` force to the body, but I'm not sure how to calculate the correct amount of force. I imagine I need to subtract the force of gravity, and also the additional weight of the balloon itself and the body that the balloon is connected to. Something like this:

```
balloonBody.force.y =
      -engine.gravity.y - weightOfBalloonBody - weightOfConnectedBody; 
```
Is there a simple calculation I could use to neutralise the forces acting on the balloon? I've attached a screenshot showing the balloon (the circle) and the weight it is carrying (the rectangle). Essentially I need these to float, suspended freely.

Any help would be much appreciated!

![Screenshot 2019-09-26 at 15 39 24](https://user-images.githubusercontent.com/54589921/65699357-e1775380-e075-11e9-84de-cd60dc4ebd65.png)

**Comment by anthonygood** [comment]
FYI this looks like a good approach to making things float/fly: https://github.com/liabru/matter-js/issues/503
