### ISSUE TITLE
object lineWidth isn't fully solid

### ISSUE THREAD

**Issue by Kurolox** [liabru/matter-js#782]
This is more of a question than anything, but I haven't been able to find anything in the documentation.

I'm trying to make hollow figures by setting `fillStyle: "transparent"` and `lineWidth: x`. While it works, it seems like the objects aren't colliding at the border of the linewidth, but at the middle point between the object width and the border width, causing issues like this one:

![1570872334](https://user-images.githubusercontent.com/13695988/66698982-3dcbab80-ece3-11e9-9326-65e820309ed1.png)

If you activate the wireframes everything is working properly, but I'm not sure if there's any way to make the wireframe account for the border size so this doesn't happen.

![1570872438](https://user-images.githubusercontent.com/13695988/66699012-66ec3c00-ece3-11e9-8a9d-9b8f8d42cc91.png)

**Comment by liabru** [comment]
As far as I know canvas doesn't support stroke alignment other than the centre, so you'd have to adjust for this manually using some custom rendering, the easiest approach might be to set the [canvas scale](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/scale) before drawing the body. See my also my answer to #779 which is a similar issue.
