### ISSUE TITLE
Weird behaviour of non-static objects on React native project.

### ISSUE THREAD

**Issue by artemukolov** [liabru/matter-js#783]
Hello, Sorry. I'm not sure does it really related to matter js. But anyway.

I added matter-js engine to my React native project. And then I noticed pretty weird behaviour of non-static objects. They jump and can't catch static position. Circle objects have same behaviour.

![](https://s3.gifyu.com/images/ezgif-4-df443f481dc1.gif)

This example from virtual Android device.

I started my project via this post

https://medium.com/better-programming/flappy-bird-with-react-native-game-engine-and-matter-js-d5673f50eb9

Did somebody face with this issue? Thanks.

**Comment by MichaelKostin** [comment]
The same issue, the same article on the Medium. @artemukolov did you solve it?

**Comment by artemukolov** [comment]
@MichaelKostin No. I created same ISSUE in react-native-game-engine repository https://github.com/bberak/react-native-game-engine/issues/35

But author closed it. I want to record a video for demonstration, when I will have a time.

**Comment by liabru** [comment]
I'd guess it's because the frame rate is low / not stable, can you try using a fixed timestep?
