### ISSUE TITLE
How to parent/unparent bodies

### ISSUE THREAD

**Issue by rvanderspuy** [liabru/matter-js#784]
Hello!

I'm trying to add a body from the world to a compound body, and then remove that compound and add it back to the world. Simply, parenting and unparenting. Is this possible, and if so, what is the best way of doing it?

This approach seems to work for adding a body from the world to a compound:

```
MATTER.Composite.remove(physicsWorld, childBody);
    parentBody.parts.push(childBody);
    childBody.parent = parentBody;
``` 
I have this working correctly, and it seems OK. However, removing the body from the compound and adding it back to the world is giving me trouble.

I've tried code like this: removing the body from the compound's `parts` array, and then adding it back to the world.
```
if (parentBody.parts.find(x => x === childBody)) {
      parentBody.parts.splice(
        parentBody.parts.findIndex(x => x === childBody),
        1
      );
    }
    this.gameModel.physicsWorld.add(this.gameModel.physicsEngine.world, [
      childBody
    ]);
```
This does not work. I get the error message, `Composite.add: skipped adding a compound body part (you must add its parent instead)`.

What is the best way to achieve this?

Thank you!

**Comment by rvanderspuy** [comment]
Oh, I think I figured it out! `childBody` needs to set itself as `parent`. `childBody.parent = childBody` For example:

```
if (parentBody.parts.find(x => x === childBody)) {
      parentBody.parts.splice(
        parentBody.parts.findIndex(x => x === childBody),
        1
      );
    }

//New:
childBody.parent = childBody

    this.gameModel.physicsWorld.add(this.gameModel.physicsEngine.world, [
      childBody
    ]);

```

**Comment by rvanderspuy** [comment]
... I just noticed my sprite rendering is becoming a bit glitchy using these methods. I'm probably not doing this correctly, so any advice would be much appreciated!

**Comment by liabru** [comment]
I wouldn't recommend reusing parts like this, there will probably be weird behaviour. You should use `Body.setParts` to update the parts on the original body (to remove or add parts), then if you want to add the removed part to the world as a new body, you should instead create a new body by passing through the relevant properties from the removed part in the options.

**Comment by pagesrichie** [comment]
Using body.setParts is causing issues with the physics, see https://github.com/liabru/matter-js/issues/575 - has this been fixed?
