### ISSUE TITLE
Nativescript Renderer

### ISSUE THREAD

**Issue by Jojoshua** [liabru/matter-js#785]
I would like to make a matterjs renderer for Nativescript similar to this from physics js https://github.com/vakrilov/nativescript-physics-js. Is this possible and if so what would be the path forward?

**Comment by liabru** [comment]
I'm not familiar with NativeScript so I can't help with that, but see the wiki page on [rendering](https://github.com/liabru/matter-js/wiki/Rendering) and the source of [Matter.Render](https://github.com/liabru/matter-js/blob/master/src/render/Render.js) which should help you get started with your own renderer.
