### ISSUE TITLE
Preventing the mouse from dragging bodies through other bodies

### ISSUE THREAD

**Issue by rvanderspuy** [liabru/matter-js#787]
Hello!

I have a quick question. Is there a simple way to prevent the mouse from force-dragging bodies through other bodies? 

Perhaps... checking to see if there is a mouse body, and, if there is, wether it's colliding with another world body. If it is, then set the mouse constraint's stiffness to something like 0.0001...?

Before re-inventing the wheel, I just wonder if this is a sensible approach or whether there's something simpler I'm overlooking?

Thank you!

**Comment by rvanderspuy** [comment]
... so having experimented with this, it's much more complex than it might seem at first. Any advice would be welcome! 😄

**Comment by rvanderspuy** [comment]
... Just bumping this issues as it remains my biggest problem so far and I have not yet found a good solution.

**Comment by rvanderspuy** [comment]
There's now a StackOverflow bounty available for anyone interested in attempting a solution 😄:

https://stackoverflow.com/questions/59321773/prevent-force-dragging-bodies-through-other-bodies-with-matterjs/59363981#59363981

**Comment by liabru** [comment]
This is generally related to the CCD problem, see #5. When constraints are involved, things get even more difficult.

Aside from the usual advice of using larger bodies and a smaller timestep, my suggestion is to try adding some sort of force limiting to the mouse constraint by restricting its length every update.

You could go even further by figuring out the force between the mouse body and its colliding pairs, then restrict the mouse constraint length if it's too much.
