### ISSUE TITLE
matter-attractors does not work properly due to uncaught TypeError

### ISSUE THREAD

**Issue by J2thearo** [liabru/matter-js#791]
Has anyone an idea what's causing this error? The matter.js and matter-attractors.js files are inside my project libraries folder. I get the feeling that it has something to do with the Webpack. I also can provide you with further details if needed. I am working with p5.js and matter.js.

![Matter_error](https://user-images.githubusercontent.com/55392372/68125034-f5ce2c00-ff10-11e9-9c71-8ff74cd3704f.PNG)

**Comment by J2thearo** [comment]
I've solved it! It had nothing to do with the Webpack. 

Insinde the index.html I've mentioned the refrence to matter-attractors.js before matter.js, but matter.js has to be refrenced first!

You can even see it in the warning, it says "matter-attractors used by matter-js", but its actually supposed to be the other way around.

**Comment by liabru** [comment]
Glad you solved it, that's right Matter should always be loaded before plugins as they will need to register themselves on it.
