### ISSUE TITLE
Event System

### ISSUE THREAD

**Issue by liabru** [liabru/matter-js#8]
An event system is required for external input into the physics engine.

It should at least include events for
- before and after engine tick
- before and after render

**Comment by df257** [comment]
I want use event like this:
var circleA = Bodies.circle(100, 80, 50, null, 20)
Matter.Events.on(circleA , 'mousedown', function(e) {
            console.log(111);
        });

Can it be achieved？

**Comment by liabru** [comment]
That won't work, probably the easiest way would be the [startdrag event](https://brm.io/matter-js/docs/classes/MouseConstraint.html#event_startdrag) on a `MouseConstraint` though I'd suggest looking at the source to see how it works.
