### ISSUE TITLE
Cross browser consistency

### ISSUE THREAD

**Issue by bagratinho** [liabru/matter-js#802]
I have made a demo on codesandbox describing my issue: https://codesandbox.io/s/matterjs-zz91w

When you click on a canvas the engine adds a circle body to the canvas which then makes its way through plinko grid. 

The issue is that the trajectory of the ball is different between the browsers. 

I have tested with mac safari and chrome and here is the trajectory of the ball fall with exactly same start parameters. 

Shouldnt them be the same?

![chrome](https://user-images.githubusercontent.com/3504419/69762671-bda1be00-1149-11ea-9069-9006e3f42e09.gif) 

chrome 👆safari 👇

![safari](https://user-images.githubusercontent.com/3504419/69762686-c7c3bc80-1149-11ea-8212-68a948be8a74.gif)

**Comment by bagratinho** [comment]
![chrome](https://user-images.githubusercontent.com/3504419/69762671-bda1be00-1149-11ea-9069-9006e3f42e09.gif)
![safari](https://user-images.githubusercontent.com/3504419/69762686-c7c3bc80-1149-11ea-8212-68a948be8a74.gif)

**Comment by liabru** [comment]
Does one of them have a lower FPS? That's the most likely reason when using the built in runner. Can you try using a fixed timestep?
