### ISSUE TITLE
How to glue elements together when they hit each other

### ISSUE THREAD

**Issue by Decombat** [liabru/matter-js#804]
Hi,
I'm looking for a solution to glue two objects together.
here is what I have got so far, I cheated and put the objects in static after the collision to avoid any physic problems before they stick to each other. But it doesn't work that well...
Another problem I can't solve, why when I add the rectangle to the 'compound' object, suddenly it doesn't collide with the rest of the elements? 

```
 var compound = Body.create({
            parts: [ball1]
        })
        World.add(world, [compound, rect1])
        const Smash1 = setInterval(() => {
            collision = Matter.SAT.collides(ball1, rect1)
            if (collision.collided === true) {
                ball1.isStatic = true
                rect1.isStatic = true
                compound.parts.push(rect1)
                clearInterval(Smash1)
            }
        }, 100)
```
Thanks ✌️

edits --

This is better, but I lost the impact move, I'm open to better suggestions :)

```
const Smash1 = setInterval(() => {
            collision = Matter.SAT.collides(ball1, rect1)
            if (collision.collided === true) {
                World.remove(engine.world, [rect1, ball1]);
                var compound = Body.create({
                    parts: [ball1, rect1]
                })
                World.add(world, compound)
                clearInterval(Smash1)
            }
        }, 100);
```

**Comment by rvanderspuy** [comment]
I'm sorry that I don't have an answer for you, but in similar experiments of my own, I've discovered that adding or removing parts to a compound body has a bunch of strange side effects that I haven't been able to debug. I think we may need advice from the maintainer (or a very experienced user) on the correct way to do parenting/unparenting with MatterJS... any advice welcome!

**Comment by Decombat** [comment]
I found this solution, but still I can't know which objects are affected. 
console.log(e.pairs) send an empty array...

```
Events.on(engine, 'collisionStart', e => {   ...   })
```

**Comment by liabru** [comment]
It looks like you found out, but you should use collision events instead of checking for collisions manually. Also parts are not considered to be reusable like this, see my response in #784 for how best to do this kind of thing.
