### ISSUE TITLE
selective sensors?

### ISSUE THREAD

**Issue by Marcus5234** [liabru/matter-js#807]
Say I have bodies A, B, C. I want body A to react physically with B, but not with C. However, I still want body A to detect collisions with C, but react physically **only** with B. Is it possible to achieve this?

Another way of asking this is, is there a way to make a body pass through a body that can react physically?

**Comment by liabru** [comment]
You could try using a separate sensor body that always tracks the position and angle of body A, hopefully that does the trick?
