### ISSUE TITLE
Textures with transparency?

### ISSUE THREAD

**Issue by a-macht** [liabru/matter-js#808]
Hi there

Right now, if I use PNGs or SVGs with transparency as textures for my bodies, the background will always be white.
My goal is to use the built in `fillStyle` option and, at the same time, have a texture with transparency on top of that.

Is this possible? Am I missing something?

Thanks for your help!

**Comment by LeotomasMC** [comment]
I'm pretty sure this would most likely be a limitation of the HTML canvas, as opposed to the matter.js library.

**Comment by liabru** [comment]
The [sprites](https://brm.io/matter-js/demo/#sprites) example shows using transparent PNGs. I've not tried using SVGs as sprites though, but assume it should work the same if canvas supports it. The built in renderer doesn't support using both sprites and filled shapes at the same time unfortunately though, you'd have to add your own support for that.
