### ISSUE TITLE
Engine.run not working on iPhone

### ISSUE THREAD

**Issue by Marcus5234** [liabru/matter-js#809]
For some reason the events Events.on(engine, 'beforeUpdate', () => {}); and Events.on(engine, 'afterUpdate', () => {}); do not trigger on iPhone, but works normally on Android...

EDIT
So actually I discovered that the problem is with Engine.run. Using my own loop it works on iPhone. But on Android it works with Engine.run as well. Why?

**Comment by LeotomasMC** [comment]
Have you tried using
`var runner = Runner.create();
Runner.run(runner, engine);`
instead of `Engine.run();`?

**Comment by liabru** [comment]
Are there any error messages shown in the console? Could you show more of your code? Also as @LeotomasMC said, can you try manually creating the runner?
