### ISSUE TITLE
collision normal failing to detect collision from above if body is too small

### ISSUE THREAD

**Issue by Marcus5234** [liabru/matter-js#810]
I want to detect if a body colides with another from above. For that I check the collision normal, but it seems that if the body is too small the check will fail. 

I have tried
engine.constraintIterations = 100;
engine.positionIterations = 100;
engine.velocityIterations = 100;

to try to increase the simulation quality, but it didn't work. What do I do?

**Comment by liabru** [comment]
Do you mean that the collision does not fire? Or that the normal is wrong?

**Comment by Marcus5234** [comment]
Normal is wrong.

**Comment by liabru** [comment]
Wrong in what way? Is it the opposite direction? See #811 for a possible fix to that.

It's also possible that sometimes the body travels too far into the other body, so it will be pushed out of the opposite side, therefore normal might refer to the opposite edge. Not ideal in this case, but you could maybe find some way to detect that?

Also in general, see the CCD issue #5 for info about collision issues with fast or small bodies.
