### ISSUE TITLE
2D CSG?

### ISSUE THREAD

**Issue by Ziriax** [liabru/matter-js#813]
Hello,

First of all my best wishes for 2020, and congrats for this amazing piece of work!

We are building an educational web-game, where players have to rebuild 2D shapes using CSG operators (intersection, difference, union, ...). These shapes can be animated, so the CSG result is not static. Most basic shapes are simple: circle, square, half-plane, universe, and empty set, but we also support SVG paths.

I fail to find a 2D physics engine that supports this out of the box.

I guess 2D physics with dynamic CSG is very hard? Do you have any tips? 

I could use a polygon clipper that supports CSG of course, like https://github.com/w8r/martinez

But I was wondering if optimized algorithms existed for 2D CSG physics...

Thanks a lot,
Peter

**Comment by liabru** [comment]
This isn't something that is supported as standard I'm afraid, but it is possible to update a bodies geometry on the fly which could achieve this effect, e.g. using `Body.setVertices` and `Body.setParts`, which should be reasonably performant, but dig into what they do as you can probably do something faster in specific cases. If the shapes can go concave, then you'll also need a fast decomposition or triangulation library on top.

**Comment by Ziriax** [comment]
Thanks for the info!
