### ISSUE TITLE
Sleeping.wake

### ISSUE THREAD

**Issue by Aralun** [liabru/matter-js#82]
Just thought it'd be fun to call `Sleeping.wake(body)` as an alias for `Sleeping.set(body, false)`.

**Comment by liabru** [comment]
Cute but for now I prefer maintaining only one way to perform the same task.
Though I do like the idea of literate code!

For those that may want it as an extension:

    Sleeping.sleep = function(body) { Sleeping.set(body, true) };
    Sleeping.wake = function(body) { Sleeping.set(body, false) };
