### ISSUE TITLE
Collisionstart event on multiple bodies same time

### ISSUE THREAD

**Issue by smartnio** [liabru/matter-js#826]
Hello everybody! 
I was fiddeling around for a week now with the framework and enjoying it so far! Good work! :)
I am trying to build a small assembly game with it and now i got stuck a little... Or just wondering...

There is now the situation where i want to detect collisions. It works great and the event gets fired correctly, **except when you use 2 bodies, who are entering the detector-body at the exact same moment. Then the collisionstart event gets only fired once.** Is there a way to trigger 2 collisionstart events even if both collide at the exact same time? Any ideas? :/

I really appreciate it, thanks!

**Comment by LeotomasMC** [comment]
the engine event `collisionStart` ([docs](https://brm.io/matter-js/docs/classes/Engine.html#event_collisionStart)) returns a *list* of pairs of bodies that are colliding, so you should get 1 event, but with multiple collisions. you can iterate over the list to get all the colliding bodies

**Comment by liabru** [comment]
Exactly, check over the pairs, there should be one for each collision. Did that work for you?
