### ISSUE TITLE
Manually setting X and Y of body

### ISSUE THREAD

**Issue by Akiak7** [liabru/matter-js#830]
Hey, so I have a few questions regarding how to use matter.js for my 2D platformer game.

The main character is a box which needs to move forward at all times. For now the way I'm doing this is by setting velocity every frame to x:4,y:0. This works fine although when the box has to fall off of a cliff, it falls extremely slowly, probably because of the velocity, whereas I'd like it to fall realistically according to the gravity value. So if you have a solution for that please let me know :)

However, I have another problem where I need to move the box up by 50 pixels every time the mouse is clicked. If I simply set the Y value to -=50, the box will shoot up into the air, and when it lands, it'll land 50 pixels above the ground, instead of on the ground itself. If I click again, the box will shoot up again and this time land 100 pixels above the ground (and so on).

I really don't understand why this happens, so an explanation and possible solution would be appreciated :)

**Comment by wmike1987** [comment]
For your second question, try using Matter.Body.setPosition(body, position).

**Comment by LeotomasMC** [comment]
this sounds like a geometry dash "clone" (or at the very least, inspired by geometry dash).

for your first issue, to solve the problem of falling, you should use something like `Matter.Body.setVelocity( { x: 4, y: character.velocity.y } )` which will only change the X velocity.

for your second issue, you could use the above method, and swap the x and y, so the vector you pass would then be `{x: character.velocity.x, y: character.jumpVelocity}` . You may also want to look at `Matter.Body.applyForce(body, velocity)` ([docs](https://brm.io/matter-js/docs/classes/Body.html#method_applyForce)), which appears to add to the current velocity, so if you passed in `{x: 0, y: character.jumpVelocity}` as the vector, it will just add the the Y velocity and not change the X velocity.

**Comment by liabru** [comment]
Take a look at the [body manipulation](http://brm.io/matter-js/demo/#manipulation) example which shows how to precisely control bodies. Make sure that you also update the body velocity when moving it with e.g. `Body.setPosition` as shown in the example. Hopefully that helps.
