### ISSUE TITLE
Which collision response method does Matter use?

### ISSUE THREAD

**Issue by jjant** [liabru/matter-js#831]
I browsed through the documentation and I found a few references to Catto's Iterative Dynamics with Temporal Coherence, but looking through the `Resolver` code, it doesn't seem to be using that method. 
Is there any tutorial/article/paper describing the method used here?

**Comment by liabru** [comment]
Check out the references on this [page](https://brm.io/game-physics-for-beginners/). The engine uses a mixture of many techniques rather than any specific approach. Not all of those references are used either, but they should help if you're interested in general.
