### ISSUE TITLE
interact with bodies without mouse

### ISSUE THREAD

**Issue by l3ehfar** [liabru/matter-js#835]
has anyone any idea to interact with bodies without mouse? for example assigning posenet library to interact with the world.

**Comment by liabru** [comment]
Sure you can see an example of how to control bodies in various ways in the [body manipulation](https://brm.io/matter-js/demo/#manipulation) example and [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L90-L93).

A great project called [Les métamorphoses de Mr. Kalia](http://epure.it/les-metamorphoses-de-mr-kalia/) used Kinect and physics in really interesting ways, worth checking out.

**Comment by l3ehfar** [comment]
> Sure you can see an example of how to control bodies in various ways in the [body manipulation](https://brm.io/matter-js/demo/#manipulation) example and [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L90-L93).
> 
> A great project called [Les métamorphoses de Mr. Kalia](http://epure.it/les-metamorphoses-de-mr-kalia/) used Kinect and physics in really interesting ways, worth checking out.

thanks! the mentioned project is amazing.
actually I kinda try to assign the posenet values to my body position, but it seems like when the specific body collide other bodies, the physic's options like gravity and so forth, got issued. is it normal? should I assign the force values manually for that body?

**Comment by liabru** [comment]
Yes you could try disabling the world gravity and then only applying your own gravity forces to the bodies you need, that might help.

**Comment by timtensor** [comment]
Hi @liabru ,  the link provided , does not seem to work.  Is there more tutorials that you can suggest ?  Also @l3ehfar if you had any success , it would be great to know .

**Comment by liabru** [comment]
@timtensor that link was just an example rather than a tutorial, my suggestion is to check out the [body manipulation](https://brm.io/matter-js/demo/#manipulation) example and [source](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js#L90-L93). You can also use constraints as a softer way to move things around.
