### ISSUE TITLE
Can I pause all bodies and drag some bodies?

### ISSUE THREAD

**Issue by yryrark** [liabru/matter-js#836]
Can I pause all bodies, drag some bodies and move their position, and resume bodies' dynamics?
I tried setting all bodies 'static' or using Runner.stop(), but then I couldn't drag them.

**Comment by liabru** [comment]
It really depends on the kind of effect you're after, but if you don't need any collision response then you should just pause the runner and use `Body.setPosition` inside a mouse event handler in your code.

If you need collision response, then you'll need keep the runner going and temporarily disable forces like gravity and apply a high `airFriction`, then move the body in a similar way.
