### ISSUE TITLE
Constraints doing unwanted dampening.

### ISSUE THREAD

**Issue by iMplode-nZ** [liabru/matter-js#839]
For my project, I need an object to bounce with different restitution depending on the other object it is colliding with. I want the object to be able to bounce with a restitution of 1 against a clone of itself while bounce with a restitution of 0 against a certain wall. I decided to do this by using a constraint to tie an object with a restitution of 0 to an object with a restitution of 1, and use collision filters to make these objects only collide against what I want them to collide.

I find that when colliding with a wall of restitution 1, the object does not bounce up to its full height, it is quickly dampened. Here is a demo: https://jsfiddle.net/20jqmgrh/.

**Comment by iMplode-nZ** [comment]
It seems that even with a extremely low stiffness on the axis the ball still refuses to bounce.

**Comment by liabru** [comment]
That approach does sound like it would have problems. My suggestion here is to add a function that runs after `Matter.Pair.update` that looks for the pair and applies the logic you need, something along the lines of this:

```js
Matter.after('Pair.update', (pair, collision, timestamp) => {
  pair.restitution = customRestitution(collision.parentA, collision.parentB);
});
```

You should apply this only once at the start, as it is the basis for [creating a plugin](https://github.com/liabru/matter-js/wiki/Creating-plugins).
