### ISSUE TITLE
How to define a heavy element, hard to be moved by small ones

### ISSUE THREAD

**Issue by dan-merlea** [liabru/matter-js#841]
I've been struggling with Matter JS physics, trying to get them right. I have 2 elements:

```
 Matter.Bodies.rectangle(400, 400, 113, 66, {
    frictionAir: 1,
    friction: 1,
    density: 0.5,
    restitution: 0
})
Matter.Bodies.circle(0, 0, 5, {
    friction: 0.05,
    frictionAir: 0.05,
    density: 0.001,
    restitution: 0.5
})
```

According to the documentation, the first one should be heavy and strong. But adding a force of only 0.004 to the small one, I manage to move the big object quite a lot. I tried various numbers and nothing works.

I basically want to have an object that is very hard to be moved by small ones but still be able to move it by adding force to it.

Any help would be appreciated!

**Comment by liabru** [comment]
I'm not sure what you're looking for exactly, could you provide a more complete example?

**Comment by dan-merlea** [comment]
Ok! I'll try to create a Fiddle soon

**Comment by dan-merlea** [comment]
https://codepen.io/dmerlea/pen/WNQvKyy

I am looking for a way to make an object so heavy that it's impossible to be moved by tiny ones.
Having a difference in size from density 0.5 to 0.001 (  500 times ) + the size difference ( 10px ball compared to ~100x60 rectangle) again ~8-10 times bigger. Adding them up should have 5000 times more weight. It's like a bird hitting a plane.

I'm not saying it's a bug, I'm just looking for a way to treat this case. Thank you!

**Comment by dan-merlea** [comment]
Is somebody looking into this?

**Comment by liabru** [comment]
Apologies for lack of response. I believe this might be a known issue related to #832 and #890. Until that is figured out, I'd suggest avoiding such a large difference in mass since this will be unstable anyway.
