### ISSUE TITLE
Strange gravity behavior with concave bodies

### ISSUE THREAD

**Issue by vncnz** [liabru/matter-js#842]
Hello. If I'm not in mistake, working on my new project I found a bug: inner the empty space of a concave body gravity seems to be wrong.

The behaviour can be seen in this codepen, I've created it to show the bug:
https://codepen.io/vncnz/pen/dyowgWL?editors=1010

Expected behaviour: all squares fall vertically, at least until the first collision.
Seen behaviour: a square rotates madly, another one seems launched horizontally. A third one, placed outside the concave body, fall as I expected.

**Comment by liabru** [comment]
Here I think you should use `Bodies.fromVertices` since `Matter.Body` doesn't do any decomposition. Try this:

`let body = Matter.Bodies.fromVertices(center.x, center.y, vertices, { isStatic: true });`
