### ISSUE TITLE
Change coordinate system to left bottom

### ISSUE THREAD

**Issue by APeltick** [liabru/matter-js#843]
Hi! I create game use only matter without game engine for now, and it's make some discomfort to count the distance from top, can I change the coordinate system so that the (0,0) will be from left bottom. I see that in Phaser tutorials, or I'm wrong about that?

**Comment by liabru** [comment]
There's no feature for this, if it's something you'd like I'd suggest flipping during rendering, e.g. using a context transform at the start and end of all drawing. 

That said though, I'd encourage you to try get used to it as you'll likely see the same coordinate system used in many other projects, with the top left of the screen considered as the origin `(0, 0)`.

**Comment by APeltick** [comment]
Okay, thanks.
