### ISSUE TITLE
some questions about fromVertices

### ISSUE THREAD

**Issue by zmhuihuihui** [liabru/matter-js#844]
Hello!
I want to use fromVertices to draw triangle, but i can't understand the meaning of 'x' and 'y'. They are neither incenter nor circumcenter. How to determine the 'x'and 'y' through three vertices.Or there are other ways to draw triangles.
Thanks!

**Comment by GreysonR** [comment]
The x and y are the positions for each of the points in the shape. If you want to make a triangle, you would do something like this:

	let vertices = [
		{ x: 0, y: 0 },
		{ x: 10, y: 0 },
		{ x: 10, y: 10 },
	];
	let triangle = Bodies.fromVertices(10, 15, vertices);
	World.add(world, triangle);

You can add more points to the array in the order the should be drawn if you want more points on your shape. If any of the the lines cross, the shape won't be drawn.

**Comment by zmhuihuihui** [comment]
> The x and y are the positions for each of the points in the shape. If you want to make a triangle, you would do something like this:
> 
> ```
> let vertices = [
> 	{ x: 0, y: 0 },
> 	{ x: 10, y: 0 },
> 	{ x: 10, y: 10 },
> ];
> let triangle = Bodies.fromVertices(10, 15, vertices);
> World.add(world, triangle);
> ```
> 
> You can add more points to the array in the order the should be drawn if you want more points on your shape. If any of the the lines cross, the shape won't be drawn.

thank you, i know the meaning of  'vertices', but i want to know how to ensure '10' and '15'  in fromVertices ,i discover that points in 'vertices' will move if  'x' and 'y' in 'fromVertices' changed.
What makes me wonder is that 'vertices' can uniquely determine a triangle , why need 'x' and 'y' in fromVertices.

**Comment by GreysonR** [comment]
Matter.js will get an average position of the vertices and point that midpoint on the x/y position.
