### ISSUE TITLE
The terrain example is not working

### ISSUE THREAD

**Issue by anderslatif** [liabru/matter-js#846]
1. The demo page doesn't link to the source code in the Examples folder. 

2. After running it locally I see the following error: 

```path.createSVGPathSegMovetoAbs is not a function```

This could be semi-related to the following (closed) issue though the errors are different:

https://github.com/liabru/matter-js/issues/548

**Comment by liabru** [comment]
Which browser is this? Looks like it's still working for me, but it's entirely possible that I need to update to the latest polyfill from https://github.com/progers/pathseg
