### ISSUE TITLE
Am I understanding the scale origin property correctly?

### ISSUE THREAD

**Issue by tonychan96** [liabru/matter-js#848]
Hello, 

So I'm trying to create an effect where an object grows in height then back down continuously.  I couldn't find any methods to manipulate the height directly but saw some threads about using Body.scale().  It works but it scales from the center of the object...  I tried setting the origin property to the bottom of the object but it doesn't seem to do anything.  Here is my code: 
`

for (let i = 0; i < expBodies.length; i++) {

      const { min, max } = expBodies[i].bounds;

      const width = max.x - min.x;

      const height = max.y - min.y;

      // console.log(expBodies[i])
      if (height < 100) {
        // flip 
        scaleDirection = 1.01;
      }
      else if (height > 300) {
        scaleDirection = .99;
      }
      Body.scale(expBodies[i], 1, scaleDirection, { x: min.x, y: min.y });
}
`

I'm aware that the origin is set to the bottom left not the bottom center of the object but I don't think it should affect it since it's only scaling up/down and not left/right

**Comment by tonychan96** [comment]
jk we gucci

**Comment by ggorlen** [comment]
> jk we gucci

An explanation of exactly what you did to fix the problem would help future visitors.
