### ISSUE TITLE
Movement speed depends on framerate

### ISSUE THREAD

**Issue by Feavy** [liabru/matter-js#851]
Hello,

I was very surprised to see that body position updates don't depend on time passed between two update calls. It makes bodies' speed depending on framerate which is not what we want in most cases.

![image](https://user-images.githubusercontent.com/34109688/79216967-519cc980-7e4e-11ea-9f95-589704f6ee01.png)
*Extracted from https://github.com/liabru/matter-js/blob/master/src/body/Body.js*

I wrote a simple example that shows the problem: https://codepen.io/Feavy/pen/BaoopVw

See the difference:

## 60 Hz screen
![image](https://user-images.githubusercontent.com/34109688/79216329-47c69680-7e4d-11ea-8301-91d5a20e357c.png)

Speed = 800px / 3.444s ~= 232 px/s

## 144 Hz screen
![image](https://user-images.githubusercontent.com/34109688/79216277-33829980-7e4d-11ea-8711-95f8729f3c86.png)

Speed = 800px / 1.389s = ~575 px/s

Do you have a solution for this problem?

Thanks,
Feavy

**Comment by ColinEspinas** [comment]
I also have some problems, I'm building a game engine using matter for physics and when I'm not using delta and correction, when fps are uncapped (At ~400/500 fps), the speed of all the objects is so fast that it is not usable but seems constant. 

Also using delta and correction actually gives me non-constant results. Maybe I'm doing something wrong. But the physics seems off and slow.

Here is my little code : 
```javascript
// In my time manager:
this._lastDeltaTime = this._deltaTime;
this._deltaTime = (performance.now() - this._lastUpdate)/1000;

// In my physic manager:
const delta = this.timeManager.deltaTime * 1000;
const lastdelta = this.timeManager.lastDeltaTime * 1000;
Matter.Engine.update(this.engine, delta, delta / lastdelta);
```

It drives me crazy, looks good with `1000/60` at 60fps. I don't want to lock my engine framerate too.

**Comment by liabru** [comment]
If I understand what you mean, the built in runner by default uses a semi-dynamic timestep to avoid slow downs, but this comes at a cost of simulation quality. The built in runner is mostly aimed at demonstration purposes rather than games, but I would like to improve it.

Did you try using a fixed timestep instead? You can do this with the runner or with your own calls to `Engine.update`.

**Comment by Feavy** [comment]
Yes, using a fixed timestep fixes the problem. I didn't know how it worked when I opened this issue but now I understand it is an obvious solution.
I think you can close this issue.

**Comment by dFrance** [comment]
Hi @Feavy, i hope you are doing well. Could you share your final code? I am facing the same issue.

**Comment by Feavy** [comment]
> Hi @Feavy, i hope you are doing well. Could you share your final code? I am facing the same issue.

Hello, I don't remember exactly how I coded it but basically the idea is to trigger a world update every X ms, X depending on the number of world updates you want per second.
