### ISSUE TITLE
multiple textures in stacks

### ISSUE THREAD

**Issue by pepeballesteros** [liabru/matter-js#858]
I've been trying a little script in matterjs using different stacks with different textures each.
this works perfectly on my computer, but not when I upload it to my server.
the complete code can be seen in
[https://stackoverflow.com/questions/60812725/multiple-textures-for-body-stacks-matter-js](url)

Since I did not get it I have also tried
`for(let i = 0; i < 10; i++)
{
   var bodyE = Bodies.rectangle(0,0, 90, 90,
  {friction: 1, restitution: 1, density: 5.5, 
      render: {sprite :{ texture : "imagenes/E.png", xScale : .2, yScale: .2}}} );
  bodyE.position = {x: (i*10), y: 200};
  E1.push(bodyE);
}`
using an array to create bodys
and adding all to the world
`World.add(engine.world, [ground, paredIzq, paredDcha, E1, E2, E3, E4 ]);`
it doesn t work too
I wonder why and how can I solve

**Comment by liabru** [comment]
What is the error message you are getting?

**Comment by pepeballesteros** [comment]
there are no error messages.
simply the textures are not displayed.
it works fine on my computer.
in the test going through an array of bodies no one is shown
(not on my computer either)
in the test of assigning textures by stacks (stackoverflow question) only the last one is shown

**Comment by liabru** [comment]
Apologies for the lack of response. The textures seem to appear for me, did you solve it? If not I'd suggest looking in your developer tools network tab to see if the textures are being blocked for some reason.
