### ISSUE TITLE
permanent movement?

### ISSUE THREAD

**Issue by gontis** [liabru/matter-js#862]
basically I want to achieve brownian motion, ie, particles bouncing endlessly in 0 gavity.

even when I set
          frictionAir: 0,
            friction: 0,
            frictionStatic: 0,
systems seems to lose momentum and slow down?

what I am doing wrong, an/or there is a way to hack around it?

**Comment by michael-garofalo** [comment]
> what I am doing wrong

I don't think it's something you're doing wrong. I ran into this problem while working on the "Physics" (Hype) template...

https://photics.com/free-template-tuesday-23-tumult-hype-physics/

I thought it was something Hype might have done. But now that I'm seeing you're having the same problem, maybe it's a Matter.js thing.

> there is a way to hack around it?

You could manage the movement manually. Turn the Physics bodies into sensors. Then, when a body collides with an object, just change their velocity. But what is brownian motion?

https://en.wikipedia.org/wiki/Brownian_motion 

...ah, that's going to be a bit of math. 😄

Maybe this should be reported as an issue? 🤷🏻‍♂️

**Comment by gontis** [comment]
I moved back to box2d instead. that's the matter with matter.js, its just
not precisive and glitchy.

**Comment by alisrn** [comment]
You should check the `slop`property.

```
    /**
     * A `Number` that specifies a tolerance on how far a body is allowed to 'sink' or rotate into other bodies.
     * Avoid changing this value unless you understand the purpose of `slop` in physics engines.
     * The default should generally suffice, although very large bodies may require larger values for stable stacking.
     *
     * @property slop
     * @type number
     * @default 0.05
     */
```

**Comment by liabru** [comment]
This is a known issue, please refer to #256. I see this come up a lot, it's noted and I'll consider it more of a priority for sure.

Thanks for raising though and to those who got back here, but I'll close this one as a duplicate.
