### ISSUE TITLE
How do you allow bodies to be dragged over dom elements?

### ISSUE THREAD

**Issue by Pixney-William** [liabru/matter-js#864]
Considering i would have the markup below, am i able somehow to click/drag a body added to the canvas above/over the meny element. Still keeping the native functionality with hover/click on the li elements if i am not dragging the body?

```
<div id="wrapper">
    <ul id="menu"> <!--position:absolute; z-index:2-->
        <li></li>
        <li></li>
    </ul>
    <div id="canvas"></div> <!-- zindex 1-->
</div>
```

**Comment by liabru** [comment]
This is a little out of scope for this issues board so I'd suggest asking on stackoverflow, but while I'm here I'll suggesting you should look into toggling the CSS property [pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) and hopefully that gets you in the right direction.
