### ISSUE TITLE
Matter js Same positions client server, different results

### ISSUE THREAD

**Issue by car1ot** [liabru/matter-js#867]
I made a game called "plinko". Balls fall from top random coords onto barriers and after a long way around barriers they collected by one of baskets. When clients ready, server quickly spawn balls in random coordinates and run `while` loop with physics to get results. The physics settings is the same on client and on server. But when clients get coords from server to run the same animation, animations have DEVIATION!!! How to fix this problem??? I tried to collect balls speed when collided with walls and pass this speed to clients to change with the same way when collides. But it dont works! Please, someone give an advice

**Comment by liabru** [comment]
Multiplayer physics is a big topic and I can't really suggest much without knowing your implementation, but I'd say to start by [fixing your timestep](https://www.gafferongames.com/post/fix_your_timestep/).

**Comment by car1ot** [comment]
Im glad to see you again
