### ISSUE TITLE
Assign `pointer-events: "none";` to background

### ISSUE THREAD

**Issue by jonahgrindler** [liabru/matter-js#868]
is it possible to allow the mouse to hover & click through the background of a scene to other html elements, while still allowing you to drag the bodies?

I'd love to assign `pointerEvents: "none"` to just the background. 

I have a scene that's full width+height and fixed to the viewport, and a list of links behind.

**Comment by liabru** [comment]
You could either do this just with a CSS selector on your canvas, or if you need it inline then you should be able to just do `render.canvas.style.pointerEvents = 'none'`?

**Comment by jonahgrindler** [comment]
Hey thanks for getting back to this! After I've disabled the canvas, I still want interaction with the bodies, kind of like this:

`render.canvas.style.pointerEvents = "none";
engine.world.bodies[0].style.pointerEvents = "auto";`

**Comment by liabru** [comment]
That might be tricky. I think to achieve that you'd need to listen for [mouse constraint events](https://brm.io/matter-js/docs/classes/MouseConstraint.html#events) to detect when a body is being dragged and apply or remove `pointerEvents` based on that. You might also want to try listen to DOM mouse events and use `preventDefault` and `stopPropagation` if a body is being moved, or something along those lines.

**Comment by ineslucas** [comment]
Did you ever figure out a solution? Having the same problem now
