### ISSUE TITLE
pixi: SpriteBatch does not exist any more, please use the new ParticleContainer instead

### ISSUE THREAD

**Issue by salamanders** [liabru/matter-js#87]
I tried switching over to pixi rendering, when using sprite textures, and got: 
"SpriteBatch does not exist any more, please use the new ParticleContainer instead"

Is there an oldest version of Pixi I can use that is compatible, or better still, is this an easy bug to fix?

**Comment by liabru** [comment]
I couldn't reproduce this using the [demo page](http://brm.io/matter-js-demo-master/#sprites), can you explain more or jsfiddle?

In the meantime maybe check [pixi issue 1039](https://github.com/GoodBoyDigital/pixi.js/issues/1039).

**Comment by salamanders** [comment]
Repro with latest Pixi in CDN -  Pixi.js 3.0.2
http://jsfiddle.net/salamanders/x7ge7u8z/1/

**Comment by liabru** [comment]
Confused me because I'm sure I upgraded pixi recently, I must have forgot to commit it.
Looks like I'll need to do it again and resolve this issue, thanks for the heads up.

**Comment by liabru** [comment]
This should now be resolved as of #95, thanks.
