### ISSUE TITLE
About changing centre of mass of a object

### ISSUE THREAD

**Issue by ajay1773** [liabru/matter-js#871]
@liabru you told to change the centre of mass like thiss...
body.position.x += offset.x;
body.position.y += offset.y;
body.positionPrev.x += offset.x;
body.positionPrev.y += offset.y;
But it seems that as soon as I apply this on a non static object it jumps away from the scene.

**Comment by liabru** [comment]
That sounds like it should work, are you sure your offset isn't too large? I should probably add a function for this!

**Comment by liabru** [comment]
There is now a function for this in `0.15.0`, see [Matter.Body.setCentre(body, centre, relative)](https://brm.io/matter-js/docs/classes/Body.html#method_setCentre).
