### ISSUE TITLE
How to make a particle water effect

### ISSUE THREAD

**Issue by gdmec07150832** [liabru/matter-js#872]
How to make a particle water effect, just like game "Where's My Water?"

**Comment by LeotomasMC** [comment]
you have to make them yourself. Matter.js only does physics, not rendering (unless your using the basic canvas renderer provided by matter.js).

**Comment by liabru** [comment]
Exactly this topic is a bit out of scope for an issue here, but you should look into a technique called `metaballs` which is probably what you're after.
