### ISSUE TITLE
Draggable Objects stuck on canvas edges

### ISSUE THREAD

**Issue by maximiliankiepe** [liabru/matter-js#873]
In the examples the draggable objects are stuck on the edge of the canvas when the mouse leaves the canvas. I was wondering if there Is a way to end the drag function that is connected to this object when the cursor leaves the canvas? Thank you very much for this great plugin.

**Comment by liabru** [comment]
You could try starting with this first, otherwise this is most likely going to take some of your own code to listen to outside mouse events I'm afraid!

```js
const constraint = MouseConstraint.create({ mouse: Mouse.create(document.body) });
```

**Comment by mike-shea** [comment]
@maximiliankiepe. I faced the same issue and found a solution. Posting this to anyone who comes across it:

I added an event listener to the canvas element, and used the 'mouseleave' event to trigger a mouse release from the mouseContraint:

```js
// target canvas element
const canvas = document.querySelector('#canvas')

// add event listener
canvas.addEventListener("mouseleave", () => {
    // fire mouseup event to let go of the dragged item
    mouseConstraint.mouse.mouseup(event);
});
```

**Comment by tochibedford** [comment]
> @maximiliankiepe. I faced the same issue and found a solution. Posting this to anyone who comes across it:
> 
> I added an event listener to the canvas element, and used the 'mouseleave' event to trigger a mouse release from the mouseContraint:
> 
> ```js
> // target canvas element
> const canvas = document.querySelector('#canvas')
> 
> // add event listener
> canvas.addEventListener("mouseleave", () => {
>     // fire mouseup event to let go of the dragged item
>     mouseConstraint.mouse.mouseup(event);
> });
> ```

in addition to @mike-shea's solution:
the `mouseConstraint.mouse.mouseup(event)` function doesn't exist in my version of Matter Js:
![image](https://github.com/liabru/matter-js/assets/34871260/895f4ef1-c1d2-45c6-8f5f-693b06969fb9)

You can do this instead:
```Typescript
    const ev = new Event("mouseup")
    mouseConstraint.mouse.element.dispatchEvent(ev)
```
