### ISSUE TITLE
How to set a static object to an angle in Matter.js!!!

### ISSUE THREAD

**Issue by ARNAVVGUPTAA** [liabru/matter-js#874]
just this much, I don't know why, rotate(). is not working, plz help me with ths

**Comment by LeotomasMC** [comment]
you have to set the angle in the `properties` when you create the object. you can see this [here](https://github.com/liabru/matter-js/blob/master/examples/car.js#L51) in the car example

**Comment by ARNAVVGUPTAA** [comment]
ok thank you for your help, working
