### ISSUE TITLE
O(1) body query / store bodies in a Map rather than Array

### ISSUE THREAD

**Issue by dclipca** [liabru/matter-js#879]
Iterating over the whole array to find a specific body is rather slow. Is there a way to make this library store the bodies in a Map (or something similar)?

**Comment by virtumonde** [comment]
I ended up creating a HashMap at every iteration but it would be nice from the perspective of performance to implement something similar to a HashMap in this library.

**Comment by liabru** [comment]
Can you give the context here? Internally both arrays and maps are used in different parts of the engine, so you may need to dig around a bit depending on what you're doing.

I'd suggest managing your own maps where possible though, as it's most likely that arrays in some particular case are being used for performance reasons and that maintaining a map would be an additional expense most of the time.
