### ISSUE TITLE
Examples for Matter.Body.scale

### ISSUE THREAD

**Issue by salamanders** [liabru/matter-js#88]
I was trying to make some old objects shrink as they aged, and wasn't able to find "scale" used in any of the demos.  

Specifically: 
* what is the right way to look up an object that I want to scale?  
* Is there a way to use easing when scaling, or is each scale step a lot of math?
* Is Pixi the only way to scale a sprite? (It doesn't look like a sprite image texture currently scales to a Rectangle, I only found references to scaling in the Pixi Render code)

**Comment by liabru** [comment]
See [Demo.manipulation](http://brm.io/matter-js-demo-master/#manipulation), the [code](https://github.com/liabru/matter-js/blob/master/demo/js/Demo.js#L218-L275) and the [docs](http://brm.io/matter-js-docs-master/classes/Body.html#method_scale) for it.

You can ease or tween the scale sure, but obviously the effective scale factor will be non-linear if  applied cumulatively over time (this looks fine in the demo though).

The included renderers don't account for any scaling when using sprites (this is out of scope) but you can easily create your [own renderer](https://github.com/liabru/matter-js/wiki/Rendering#using-a-custom-renderer) that can.

**Comment by salamanders** [comment]
Great, missed the one in Demo.manipulation.  It answered my question - best to keep a handle around to the object, rather than looking it up via a "get"
