### ISSUE TITLE
Anti-gravity applyForce didn't work

### ISSUE THREAD

**Issue by alisrn** [liabru/matter-js#881]
Hello, I am trying make a component behave like there is no gravity. I found an issue related to that #765. Yet when I tried to do it, it didn't work. First of all, suggested code in the issue doesn't work because the applyForce is updated and takes another argument now. 
`Body.applyForce = function(body, position, force)`
Also suggested code applies the force in the same direction with gravity. But this is not the issue because it doesn't work when it is applied in contrary direction too.
Here is my code.

```
//Find the created fire bodies. They all started with 'fire' like fire0, fire1, fire2 etc.
let fireList = Object.keys(entities).filter(key => key.slice(0, 4) === "fire" && key != "fireButton");

  if (fireList && fireList.length > 0) {
    fireList.forEach(fire => {
      let fireBody = entities[fire].body;
     //If it is not in the screen, delete the body.
      if (fireBody.position.x - constants.FIRE_SIZE / 2 > constants.MAX_WIDTH) {
        delete (entities[fire]);
      } else
        //if it is in the screen, applyForce in other direction on y dimension.
        Matter.Body.applyForce(fireBody, fireBody.position, { x: fireBody.mass * world.gravity.x , y: -fireBody.mass * world.gravity.y })
        //Matter.Body.translate(entities[fire].body, { x: 2, y: 0 })
    })
  }
```
When I triggered this on the system, body moves up so fast that you don't even see it.

**Comment by liabru** [comment]
Good catch, I've fixed my post to include the missing argument.

I'm not sure if what you're posting here will work exactly, but really instead I'd still recommend you should disable the built in gravity completely and then apply it as needed like in that issue #765, could you try it?
