### ISSUE TITLE
How to get the most-packed state of bodies?

### ISSUE THREAD

**Issue by keto33** [liabru/matter-js#884]
Is it possible to find the most-packed distribution of bodies within the world?

For example, if filling the world with specific body/bodies; is it possible to find a state in which the number of bodies places in the world is the maximum?

In a sense, it is a condition as the system has been well shaken.

**Comment by liabru** [comment]
This isn't really in the scope of an issue here, but you could start with finding the average position over all bodies, then finding the distance from there to from the centre position of some bounds (such as a concave hull) as a simple approximation. But after that I'd suggest looking into [cluster analysis](https://en.wikipedia.org/wiki/Cluster_analysis) and make your way from there.
