### ISSUE TITLE
FPS affects physics!

### ISSUE THREAD

**Issue by car1ot** [liabru/matter-js#885]
Hello. I have simulation (game plinko) - balls falling down from exact coordinates into baskets. Repeating the same simulation over and over, results are different!<br/> 
Also, when I slow down time the simulation results become very different.<br/>
I made this issue, beause I need same results in multiple simulations using same exact fall coordinates.

**Comment by virtumonde** [comment]
Indeed, I experience the same thing.

**Comment by virtumonde** [comment]
Indeed, I experience the same effect.

**Comment by car1ot** [comment]
> Indeed, I experience the same effect.

And what to do? I need the same results on server and client...

**Comment by wmike1987** [comment]
There's a PR all about timing inconsistencies. Regardless, you should fix your timestep to achieve determinism.

https://github.com/liabru/matter-js/pull/777

**Comment by car1ot** [comment]
> 
> 
> There's a PR all about timing inconsistencies. Regardless, you should fix your timestep to achieve determinism.
> 
> #777

help pls, I quoted reply in #777

**Comment by liabru** [comment]
Pretty much as @wmike1987 says (thanks!)

**Comment by DzzD** [comment]
I experience the same problem (wich sound to me logical unless you use fixed time step you IMHO cannot get same results), Ifixed it by using fixed time step (see below), this solution may be added as an option of the Engine.update ?

```
lastFrameTime = frameTime;
frameTime =  Date.now();
let frameDuration = frameTime - lastFrameTime;`
let repeat= Math.floor(frameDuration/maximumFrameInterval); 
let  remainingTime = frameDuration%maximumFrameInterval;
frameTime -= remainingTime;
for(var n=0;n<repeat;n++)
{
   Matter.Engine.update(engine, maximumFrameInterval);
}
```

**Comment by liabru** [comment]
@DzzD good to know that approach is working for you, it's worth trying out branch #777 too if you get chance.

I've got similar prototypes of adaptive fixed timestep for `Matter.Runner` but none are yet production ready, it is something I'll prioritise though when I get back to #777.

**Comment by liabru** [comment]
Closing this thread to refer to updates in #702 on this topic, thanks again for the reports here.
