### ISSUE TITLE
Falling images get "stuck" when using a wide browser window

### ISSUE THREAD

**Issue by salamanders** [liabru/matter-js#89]
I've got a simple "falling random images" setup. http://jsfiddle.net/salamanders/sdnfwm25/  works great.
Until I try to do it full-screen.  Then the images on the right-ish side get stuck, and the images in the left-ish side fall like normal.  Maybe a hidden effect of some canvas size constant?

The problem only happens when the canvas is big enough.

(Best way I've found to try full-screen is the mobile debugger to the right of the "run" button in jsfiddle.)
![screen shot 2015-05-11 at 9 10 59 pm](https://cloud.githubusercontent.com/assets/85366/7580044/61448f6a-f822-11e4-8c97-241896fa0089.png)

**Comment by liabru** [comment]
See issue #67, thanks.
