### ISSUE TITLE
How to make a rigid body that doesn't suffer compression?

### ISSUE THREAD

**Issue by rjoxford** [liabru/matter-js#891]
My project requires that bodies don't get compressed so easily.

The Stress examples show bodies at the bottom of the stack being compressed quite significantly. The situation seems far worse for the circles that I'm using. 

The Slop property seems to suggest it may be a solution, but changing it seems to have no effect.

**Comment by Adamsmashem** [comment]
i think this should answer your question: https://github.com/liabru/matter-js/issues/280

**Comment by liabru** [comment]
Thank you @Adamsmashem, increasing iterations would be my suggestion too, so closing this one.
