### ISSUE TITLE
How to synchronise client-side physics engines 

### ISSUE THREAD

**Issue by joshuba** [liabru/matter-js#892]
I am currently developing a multiplayer game via sockets. A server (Spring with STOMP Websockets) has control over the positions of each client. In the client, a Phaser-application with MatterJS is running.

Problem is the different behavior in each client. After receiving the servers position, little details in each game look different. Is it possible to configure the Physics-engine in a synchronous way? Without that kind of randomness?

I couldn't find any advices to this topic. Hope you can help me.

**Comment by liabru** [comment]
This gets asked a lot, but as this is a complex topic it's currently out of scope of the project, but do check my responses to [similar questions](https://github.com/liabru/matter-js/issues?q=is%3Aissue+multiplayer) as I've included some links that may help. A good start is usually to [fix your timestep](https://www.gafferongames.com/post/fix_your_timestep/).
