### ISSUE TITLE
Unstable "fromVertices Shapes"  on (very) low density materials

### ISSUE THREAD

**Issue by uapv1702675** [liabru/matter-js#893]
I'm pretty new to this physics engine but i discovered a thing that blocked me for hours :

My ground's density is "0.0001" and  my custom shape's density is "0.1" and I discovered that my shape is trying to balance itself on vertex instead of " land a face ".

My english is pretty bad so you can look at this example : 

https://editor.p5js.org/quentinraymondaud84700/sketches/lw5t91HA4

Btw thanx for ur amazing engine and sorry for my little english !

**Comment by liabru** [comment]
Large differences in mass often cause instability, so you should try to keep them in a close range (the same order of magnitude, ideally), even if that isn't physically realistic.
