### ISSUE TITLE
How to find body by id ?

### ISSUE THREAD

**Issue by LyamD** [liabru/matter-js#894]
I'm making a small game where Matter.js is use only to calculate physics and everything else is computed by a self made ECS Engine. Due to ECS, I can't store directly the body object within a entity.

Is it possible to find a body by ID ? 
Or, is a body already data only ? (so i can directly put it as a component)

**Comment by liabru** [comment]
Every body has a unique `body.id` generated when created, so you can use that. If you need to search the world for an object by id (or any other composite) an easy way is to use [Composite.get](https://brm.io/matter-js/docs/classes/Composite.html#method_get).
