### ISSUE TITLE
👩‍🦼 abandoned

### ISSUE THREAD

**Issue by car1ot** [liabru/matter-js#896]
Matter js is abandoned and unsupported now. Didn't get any answers. No fixes and commits more.

**Comment by car1ot** [comment]
No one would delete this useless theme

**Comment by wmike1987** [comment]
i doubt liabru abandoned this project. Covid is a weird time, who knows where he's at. Hope he's well though.

**Comment by liabru** [comment]
Don't worry Matter.js is still around, even if my time is limited on it.

I know I've been taking some (long) breaks away from it, as I don't have as much time for it now unfortunately, but still I feel it's at least mature enough that people can (and do) use it for a bunch of awesome things which I love hearing about.

Hope all are well though and props to those who are helping people out on here with their questions, it's very much appreciated.
