### ISSUE TITLE
Can you draw a heart shape wall

### ISSUE THREAD

**Issue by Simon-Bin** [liabru/matter-js#897]
All the examples are square walls. Can you draw a heart shape

**Comment by Simon-Bin** [comment]
💗 this shap

**Comment by liabru** [comment]
Sure, take a look at the [concave](http://localhost:8000/#concave) and [SVG](http://localhost:8000/#svg) examples which should help you start.

**Comment by Simon-Bin** [comment]
how to put balls into the Wall which is   a heart shape  ;  can do it

**Comment by Simon-Bin** [comment]
also circle shape

**Comment by Simon-Bin** [comment]
So is the circle shape，

**Comment by Simon-Bin** [comment]
thank you very much
