### ISSUE TITLE
Demos are broken

### ISSUE THREAD

**Issue by jeffmcmahan** [liabru/matter-js#90]
Download the repo zip, launch the demo, and select chains. On Chrome (Mac), one encounters a reference error. body.nextGroup is not a function.

The dev demo doesn't even run. At all. No part of it works. Black screen.

**Comment by liabru** [comment]
To run the demos from source you'll need to build first, see [CONTRIBUTING.md](https://github.com/liabru/matter-js/blob/master/CONTRIBUTING.md) for instructions.

**Comment by jeffmcmahan** [comment]
Ah, got it. Thanks.
