### ISSUE TITLE
Constraint pointA not properly being set when bodies are in motion

### ISSUE THREAD

**Issue by notbrian** [liabru/matter-js#902]
[Demo Here](http://notbriann.com/interactive-media-web/interactive-typologies/index.html)
[Code Here](https://github.com/notbrian/interactive-media-web/blob/master/interactive-typologies/script.js)

I'm attaching bodies together with constraints to form a chain like object and it works perfectly when the bodies aren't heavily in motion. But when they begin to move a lot the pointA of the constraint moves off center of where it should be locally on bodyA. I've confirmed this by turning on the anchor points for the constraint.

You can see this in the demo as the bones are all bunched up and disconnected instead of a seamless connection end to end. 

I've tried a bunch of different things but I'm not quite sure what it could be at this point other than the constraint being created and the engine updating new positions before it can finish. (not sure if this is even possible in matter.js)

Any help would be much appreciated :) 

```
Constraint.create({
      bodyA: ropeA.bodies[ropeA.bodies.length - 2],
      bodyB: ropeA.bodies[ropeA.bodies.length - 1],
      pointA: {
        x: 0,
        y: 20,
      },
      pointB: {
        x: 0,
        y: -20,
      },
      length: 1,
      render: { visible: false },
    })
```

**Comment by liabru** [comment]
Neat game. I think what you're looking for should work fine, did you manage to figure out the issue? Are you sure you're connecting them end to end?
