### ISSUE TITLE
get rectangle tops

### ISSUE THREAD

**Issue by Sanuich** [liabru/matter-js#904]
How to get coordinates of the rectangle tops?

**Comment by bouraqadi** [comment]
`rectangle.vertices` or `rectangle.bounds`: Those are not the same BTW
See [Body properties](https://brm.io/matter-js/docs/classes/Body.html#properties)

**Comment by liabru** [comment]
Yeah, one of those should be it.

I assume you mean the points `{ x: body.bounds.min.x, y: body.bounds.min.y }` and `{ x: body.bounds.max.x, y: body.bounds.min.y }`?
