### ISSUE TITLE
Mouse interaction with HTML buttons and bodies at the same time on mobile

### ISSUE THREAD

**Issue by FestiveAkp** [liabru/matter-js#905]
I've got a simple site with some HTML text and buttons on it, and underneath I'm adding a scene with some moving bodies (using `position: absolute` to cover the background and `z-index: -1` to make the canvas go underneath the text). I'm able to interact with the bodies and the buttons at the same time on desktop, but on mobile it seems I can only interact with the bodies and the buttons cannot be tapped on.

Is there any way to get the mouse inputs to go through on mobile while still retaining the ability to move the bodies?

Sandbox: https://codesandbox.io/s/fast-pond-z2tjg (The button is clickable on desktop, but not on mobile).

**Comment by liabru** [comment]
This isn't really in the scope of this project as it sounds more like a CSS problem, but it sounds like it should be possible and you may just have to investigate by debugging your mobile browser over USB.

**Comment by FestiveAkp** [comment]
I eventually figured it out, it was indeed a CSS problem. It's a matter of setting `z-index` and `pointer-events` correctly:

https://codesandbox.io/s/great-shockley-lyi5z?file=/style.css

**Comment by liabru** [comment]
Thanks for getting back with the fix, glad you figured it out (site looks slick too).
