### ISSUE TITLE
Soft Bodies

### ISSUE THREAD

**Issue by 1234shel** [liabru/matter-js#908]
Is there a way to control the soft bodies or add actuation? I want to design soft bodies that can have some sort of movement on their own.

**Comment by liabru** [comment]
There are a bunch of ways and it depends on your set up, but you can try some combination of the following:

- using constraints as pistons by modifying length
- setting position or rotation of certain parts as a motor
- applying forces
- applying velocity

The [body manipulation](http://localhost:8000/#manipulation) example is a good place to start.

Also check out this awesome paper where the engine was used for something similar so may be helpful: [Evolutionary Design of Mechanical Linkages](https://canvas.harvard.edu/files/2030972/download?download_frd=1&verifier=WLwW02l7ae7qin8hgxyOg0nzCP2xrfocXdv2oX7C)  by Amanda Ghassaei, Joy Ming
