### ISSUE TITLE
When softBody set restitution, this softBody will not stop

### ISSUE THREAD

**Issue by df257** [liabru/matter-js#910]
![image](https://user-images.githubusercontent.com/7835444/93066249-59d28c80-f6ac-11ea-9e91-c6bb9f05affe.png)

![2020091417](https://user-images.githubusercontent.com/7835444/93067083-54297680-f6ad-11ea-9f17-e29b1e991d35.gif)

**Comment by liabru** [comment]
Try reducing the stiffness on the constraints by passing this options object as the final argument: `{ stiffness: 0.5 }` and increase or decrease the value as needed.
