### ISSUE TITLE
Can disable an object?

### ISSUE THREAD

**Issue by df257** [liabru/matter-js#912]
This object will not affected by gravity and will not be collided

I'm use:
body.isStatic=true;
body.isSensor=true;

It seems not good

**Comment by liabru** [comment]
What exactly are you looking for? You could try removing the body from the world if that's what you mean?

**Comment by df257** [comment]
like this: checked is enable, unchecked is disable. Can set it in code?
![image](https://user-images.githubusercontent.com/7835444/93288294-290a6880-f80e-11ea-92d4-bbc3a30b51a1.png)

**Comment by df257** [comment]
> What exactly are you looking for? You could try removing the body from the world if that's what you mean?

like this: checked is enable, unchecked is disable. Can set it in code?
![image](https://user-images.githubusercontent.com/7835444/93288550-a635dd80-f80e-11ea-8aa1-7586a4af5ef4.png)

**Comment by liabru** [comment]
I'm not sure what program that is, so you may need to check with them on how that is implemented, as there is no built in flag for that in the engine. My suggestion for that would be to remove the body from the world and add it back as needed.
