### ISSUE TITLE
When adding body in world + body is colliding with 2 static bodies, body is stuck

### ISSUE THREAD

**Issue by felixmariotto** [liabru/matter-js#915]
Hi,

I'm new to matter.js and trying to wrap my head around the basics, so please bear with me.
I'm making a game in which a body can switch from a world to another, and in each world there is a different gravity and obstacles.

My problem is : when using `Matter.Composite.move( world1, bodyToMove, world2 )` to move the body as I said, and the body is added in a position that put it in collision with two static bodies, then it is stuck. Thereafter, while in the world in which it was added, the body won't be affected by gravity and `Matter.Body.applyForce`.

I'm sure it must be my mistake somehow, can somebody please tell me how I can keep this body from being stuck ?

**Comment by felixmariotto** [comment]
It was for a jam so I released [the game](https://felixmariotto.itch.io/dimensional-bug) with a workaround, but I'm still interested in a solution for latter projects.

Anyway great job on this lib, very easy to use, thank you.

**Comment by liabru** [comment]
I'm not sure from your description or looking at the game exactly what the issue is unfortunately, if you're still interested a more specific code example would help (sorry I didn't get back to you on this in time for the jam, nice looking game though).

**Comment by felixmariotto** [comment]
Ah it's been a little while already, I don't even remember my problem very well... I'm closing, thanks for this great lib 👍
