### ISSUE TITLE
I need help preloading textures.

### ISSUE THREAD

**Issue by Lann4daze** [liabru/matter-js#917]
So i have my game, And the character's textures, The texture changes so the character faces wherever he just moved. I need help preloading the textures, so that the character doesn't take 2s to load the next texture when the level starts. my code is this
```javascript
function left(){
  Matter.Body.applyForce( Sprite, {x: Sprite.position.x, y: Sprite.position.y}, {x: -0.2, y: 0});
  Sprite.render.sprite.texture = `./Assets/Char_assets/Left.png`;
};
function right(){
Matter.Body.applyForce( Sprite, {x: Sprite.position.x, y: Sprite.position.y}, {x: 0.2, y: 0});
Sprite.render.sprite.texture = `./Assets/Char_assets/Right.png`;
};
function jump(){
    Matter.Body.applyForce( Sprite, {x: Sprite.position.x, y: Sprite.position.y}, {x: 0, y: -0.3});
    Sprite.render.sprite.texture = `./Assets/Char_assets/Jump.png`;
};
```
Can anyone help?

**Comment by liabru** [comment]
This is out of scope of the engine, but I think you should be able to preload by loading the image in advance using hidden image elements on the page, if that works there are probably libraries around that can help you with that too.

**Comment by Lann4daze** [comment]
I didn’t even think about that! Thank you!

**Comment by Lann4daze** [comment]
@liabru Sorry for asking this, It’s kinda dumb’ but after that’ how do i link it to the texture? I cant use image.src, becase that’s the src of the image, not the preloaded image.

**Comment by liabru** [comment]
If you load `<img src="./Assets/Char_assets/Left.png" />` and then some time later use that same path as a texture, I think that would be it?
