### ISSUE TITLE
use in TypeScript

### ISSUE THREAD

**Issue by stmtk1** [liabru/matter-js#919]
This library doesn't use typeScript. So if we use this library with TypeScript, we can't guarantee type safe.

**Comment by photonstorm** [comment]
Or, you could use the typedefs available on Definitely Typed.

**Comment by stmtk1** [comment]
thanks.

**Comment by GapMAX** [comment]
> Or, you could use the typedefs available on Definitely Typed.

There are so many errors in @types/matter-js, such as Render.create() return Render options while type defination return Render type.

**Comment by stmtk1** [comment]
We also have many errors in typescript, but some maintainer says typescript does not support. So we have to change @types/matter-js.

**Comment by liabru** [comment]
I don't maintain the TypeScript bindings so I can't help much (they're a separate project) but if there's any TypeScript users willing to help them out, I think they take contributions.
