### ISSUE TITLE
Matter.Body.scale on circles does not rerender bodies

### ISSUE THREAD

**Issue by mizhgan** [liabru/matter-js#92]
Hello!
If you apply Matter.Body.scale on circle body generated by Bodies.circle it not rerender scaled circle in the world. Bounds seems to be ok, and in wireframes mode everything looks good, also rectangles works great. But circles, in wireframes=false mode stays the same visually.
Whats the example, based on one of codepens - http://codepen.io/anon/pen/ZGWypP
Thanks for great engine by the way!

**Comment by liabru** [comment]
The built in renderer uses a special body property called `body.circleRadius` to render circles.
For this to work with `Body.scale` I'd need another special case, which I'd rather avoid.

So for now you can add the code:

    allb[i].circleRadius *= 2;

**Comment by mizhgan** [comment]
Thanks, i got it.
