### ISSUE TITLE
Feature Request: Labels

### ISSUE THREAD

**Issue by SketchySketch** [liabru/matter-js#923]
It is sometimes necessary to label an object to show some differences. Is there any methods to add labels (or texts) to the canvas?
Thanks a lot.

**Comment by bouraqadi** [comment]
There's a [related stackoverflow thread](https://stackoverflow.com/questions/26043360/matter-js-placing-text-or-images-on-the-canvas), but it's quite old. I never tried it myself. But, I have the impression, the trick relies on making images out of text.
