### ISSUE TITLE
Gluing slippery rotating bodies on the ground

### ISSUE THREAD

**Issue by Seragonia** [liabru/matter-js#924]
Hello ! 

I am currently using MatterJS with Phaser 3 for a game project. It is basically the same concept as the "**draw climber**" game.

The idea is to move a character on a solid ground (generated from a SVG path) defined as follows: 
`
isStatic: true,
friction: 0.8
`

I then allow the player to draw the "legs" of the character, which are dynamically added to the character via a constraint:
```
this.constraintA = scene.matter.add.constraint(mainBody, legA.body, 0, 1, {
    pointA: { x: 0, y: YOffset }
});
```

These legs are based on a set of vertices. They rotate at a fixed speed and at an opposite angle, using the `Matter.Body.rotate` function:
```
Matter.Body.rotate(legA.body, Math.PI/60);
```

However, I cannot get these legs to "stick/glue" to the ground. With the rotation, they slide on it. More precisely, I would like the character to be able to move forward properly. Here is a visualization of the problem:

![issue](https://user-images.githubusercontent.com/30507286/96354961-bfb39900-10dc-11eb-99df-b5fd010d4d4e.gif)

When a collision between a leg and the ground is detected, I tried to calculate the normal vector from the current leg angle in order to force the body to move forward, but the character then makes strange and non-consistent jumps. Here is a handmade example of this normal vector according to the leg angle:

![img](https://user-images.githubusercontent.com/30507286/96355083-0fdf2b00-10de-11eb-88f3-9aff63ce5ba5.png)

I also tried to modify the parameters related to friction and mass, without any good result.

Finally, is there a way to make the leg "stick" to the ground and thus allow the player to move forward? Or maybe a much simpler solution proposed by MatterJS for this type of problem? Thanks!

**Comment by bouraqadi** [comment]
Regarding "sticking" the foot to the ground, did you change the friction of both the ground and the feet.

**Comment by Seragonia** [comment]
Hi! Thank you so much for your help!
I have indeed changed both frictions. I finally realized that the problem was due to the fact that the "legs" were slightly going through the solid ground (even though the density is very high), due to the rotation. The solution was to limit the velocity of the legs in the "beforeUpdate" function of the MatterJS engine.

Now, I can define a high leg friction (>1) and use the initial ground friction (0.7).

**Comment by liabru** [comment]
Did you get this working? I'd say to experiment with `body.frictionStatic` (this is roughly how 'sticky' the body is) as well as `body.friction` and then try tuning the `body.slop` (how much bodies can sink into each other for traction) of both the legs and the ground.

**Comment by lucasmaffazioli** [comment]
Hey @Seragonia could you please share more info? I have the exact same problem, it's being really difficult to nail the correct values, specially if the object is small
