### ISSUE TITLE
Is there a way to trace body path or trajectory in Matter.js

### ISSUE THREAD

**Issue by baljeetrathi** [liabru/matter-js#927]
I want to trace the path that two objects take after (and before) the collision. Basically, I just want to draw a line at its center wherever the object goes. Is there a way to do that in Matter.js?

Thanks.

**Comment by bouraqadi** [comment]
Doesn't the double pendulum example answer your question? https://brm.io/matter-js/demo/#doublePendulum

**Comment by baljeetrathi** [comment]
Thanks @bouraqadi :)

I should have taken a look at all the demos before asking the question.

**Comment by liabru** [comment]
Yeah thanks @bouraqadi, hopefully that example is what you're after so I'll close this.
