### ISSUE TITLE
Chrome complains about non-passive event listeners

### ISSUE THREAD

**Issue by konijn** [liabru/matter-js#930]
Greetings,

code works fine, but when run on Chrome 86.0.4240.111 with matter.js version "//cdnjs.cloudflare.com/ajax/libs/matter-js/0.14.2/matter.js" I get the following in the console;

matter.js:5647 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
matter.js:5650 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
matter.js:5651 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

I searched for duplicates of this ticket with the keyword and only found 1 ticket where you advised the use of a passive listener, so I am sure you can address this ;)

Is there good place to ask matter.js questions by the way? I could not find a good Reddit forum, and stackoverflow is well... stackoverflow.

**Comment by liabru** [comment]
That's strange, I'm not seeing that message on Chrome `87.0.4280.88` (Mac) on the live [demo](https://brm.io/matter-js/demo/). 

Do you see it on the demo or could you link me to somewhere that does?

**Comment by iolyd** [comment]
@liabru, yes, Chrome (`Version 98.0.4758.102 (Official Build) (64-bit)`) does throw the warning, once per added body.

**Comment by liabru** [comment]
@iolyd I can't reproduce this on the official demo [here](https://brm.io/matter-js/demo/#mixed), could you share more info like hardware / OS and reproduction steps to help track this down?

**Comment by Skagoo** [comment]
@liabru  This is still an issue and should be taken care of as it can cause stutters when scrolling a page. The fix is really trivial, I could open a PR if you are willing to merge and resolve this?

_sidenote; it can be seen in the console as a verbose log as stated in a previous comment, as well as being reported by lighthouse. https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/_

**Comment by Striffly** [comment]
Any update ?

**Comment by liabru** [comment]
`Matter.Mouse` uses `event.preventDefault` [e.g. here](https://github.com/liabru/matter-js/blob/master/src/core/Mouse.js#L100-L103) which you can't use with passive handlers. Though Chrome doesn't seem to detect this and still shows the warning, unless anyone knows how to avoid that?

The reason for `event.preventDefault` is to avoid the page scrolling around when interacting with the canvas, which I think is still something most users of `Matter.Mouse` will want by default.

I'm considering adding a property for `eventOptions` where you could set passive, but the page would then scroll during interaction (I think) so I don't think it would be the default.

If anyone has any ideas with above in mind let me know, or if the option would help?

**Comment by adiba** [comment]
@liabru could you please deploy this version to npm?

**Comment by murekong** [comment]
I'm currently having these issues while using the cdn
