### ISSUE TITLE
Removing any Object that is Sleeping

### ISSUE THREAD

**Issue by HenryHell0** [liabru/matter-js#933]
So I had this idea for a game: there are a few object on screen and if you leave them alone for too long, they disappear(removed from the world), and if there all gone, you lose. So basically if the objects are sleeping then remove them from the world. But I cant figure out how.
I'm trying to use Events.on to detect sleeping but cant figure it out. I'm a little new to your Physics engine, but like it alot so I bet there's like one thing that wrong but I cant see it. I was trying to use the event in the body documentation(Events.on(body, "sleepStart", callback) <-- that one), but couldn't get it to work.

plz help!
Code that I tried:
```javascript
Events.on(engine.world, "sleepStart", function(event) {
	let sourceObj = event.source;
	Composite.remove(engine.world, sourceObj);
});
```

**Comment by HenryHell0** [comment]
I also tried this:
```javascript
for(i = 0; i < stack.bodies.length; i++){
	let theBody = stack.bodies[i];
	if(theBody.isSleeping){
		Composite.remove(engine.world, theBody);
	}
}
```

**Comment by liabru** [comment]
The sleep events are fired on the sleeping body and not the world, that might be the issue here:

`Events.on(body, 'sleepStart', callback)` see docs for [Matter.Body events](https://brm.io/matter-js/docs/classes/Body.html#event_sleepStart).
