### ISSUE TITLE
So in the demos its bugged

### ISSUE THREAD

**Issue by HenryHell0** [liabru/matter-js#935]
https://github.com/liabru/matter-js/blob/master/examples/terraing.js

it doesent work you put a g in it(in the terrain demo)

**Comment by codylico** [comment]
_(outsider comment for clarification)_
It seems like you are referring to the source code link that shows up on the Demos web page. Correct me if I am wrong.

[https://brm.io/matter-js/demo/#terrain](https://brm.io/matter-js/demo/#terrain), at the button that says Source (the `{}` button).
My browser shows me that the Source button would take me to `.../terraing.js` (with a `g`).

**Comment by liabru** [comment]
Thanks for reporting, looks like this is no longer an issue now the demo has been updated.
