### ISSUE TITLE
how to make body move in specific path?

### ISSUE THREAD

**Issue by hatem-mazid** [liabru/matter-js#938]
how to make body move in specific path, and stay in it, something like a rail

**Comment by stfnnklc** [comment]
One way to do it is to make the body static using `isStatic: true`, and then change its position with `Matter.Body.setPosition(body, position)` on every frame.

**Comment by hatem-mazid** [comment]
i want non static body to interact with forces and gravity
and in the same time stay in the path

> One way to do it is to make the body static using `isStatic: true`, and then change its position with `Matter.Body.setPosition(body, position)` on every frame.

**Comment by stfnnklc** [comment]
Oh, OK... Maybe you can try `Matter.Body.applyForce(body, position, force)` to pull the object towards the new position on a path on every frame.

**Comment by AnonymousPS** [comment]
you can add invisble objects and change the collision Filter of body so that only it interacts with the invisble objects.

**Comment by hatem-mazid** [comment]
it's work but in circular path
i put constrain from the center circle to the target body
but i didn't see any official way to do it for complex paths

**Comment by hatem-mazid** [comment]
do you mean some thing like magnetic field?

> Oh, OK... Maybe you can try `Matter.Body.applyForce(body, position, force)` to pull the object towards the new position on a path on every frame.

**Comment by hatem-mazid** [comment]
> you can add invisble objects and change the collision Filter of body so that only it interacts with the invisble objects.

i can make it in closed paths
what if the path is open??

**Comment by stfnnklc** [comment]
> do you mean some thing like magnetic field?

Yes, kinda like a magnet that changes its position on every frame. It should work for any kind of path, but you'll have to play around with the force parameter until you get it right. It shouldn't be too weak nor too strong.

**Comment by liabru** [comment]
There are a number of ways to move bodies around as @stfnnklc mentioned, each with pros and cons. See the body [manipulation example](https://brm.io/matter-js/demo/#manipulation) and [code](https://github.com/liabru/matter-js/blob/master/examples/manipulation.js) for a demonstration of a few techniques and you could also try using some constraints too.
