### ISSUE TITLE
Bodies not sleeping on Firefox 83

### ISSUE THREAD

**Issue by jacksongoode** [liabru/matter-js#939]
Hi, I mentioned this at the end of #906 but I felt it would useful to make as a separate issue.

I've been logging the value of body.isSleeping and it appears that Firefox is not allowing bodies to sleep? I'm on Firefox 83 and I can also confirm that your [demo](https://brm.io/matter-js/demo/#sleeping) doesn't work either.

**Comment by bouraqadi** [comment]
I've run the demo on Firefox 82 and 83, and all objects went to sleep.

**Comment by jacksongoode** [comment]
That's very odd. I disabled all of my extensions - nothing. However, I am noticing that the walls in the demo are successfully falling asleep, just not the objects themselves.

**Comment by codylico** [comment]
Firefox on which OS?

**Comment by jacksongoode** [comment]
> Firefox on which OS?

macOS 10.15.7

**Comment by codylico** [comment]
does Safari have a similar issue? i wonder if it's a macOS thing with browsers.

**Comment by bouraqadi** [comment]
It works here on Firefox on Mac OS 10.15.7

**Comment by jacksongoode** [comment]
Yes, I just downloaded a dev channel for Firefox and it does seem to work. I'm wondering what's going on - maybe I flipped a flag somewhere.

**Comment by liabru** [comment]
I tried the sleeping demo on Firefox 84.0.1 for Mac and it appears to be working for me.

Could it be that you had an unstable FPS? I'm not sure if that could affect it though. Let me know if you figure it out.
