### ISSUE TITLE
How do I make an overlay on top of the Matter.js Renderer

### ISSUE THREAD

**Issue by AliaNeedsHelp** [liabru/matter-js#941]
My game needs an overlay and I have tried many ways, but always failed. Is it possible to do it using the debug renderer?

**Comment by mjduniverse** [comment]
What do you mean by "overlay"? Also, in which way did it fail?

**Comment by AliaNeedsHelp** [comment]
My game needs a GUI that users can interact with. I've seen people use the "afterRender" event, but nothing happens. I'm currently using my own renderer, but there are two issues I'm facing with this approach: mouseConstraint complications and sprite rendering issues. Here is my renderer as a reference: 
`var Camera = {
  X: 0,
  Y: 0,
  Z: 0.5, //Zoom, not Z-axis
  Render: function () {
    var bodies = Composite.allBodies(engine.world);
    var obj;
    for (var i = 0; i < bodies.length; i++) {
      //Pan and Zoom camera
      push();
      translate(this.X, this.Y);
      scale(this.Z);
      obj = bodies[i].render;
      if (!typeof obj.sprite.texture === undefined) {
        //Handle sprite bodies (BROKEN)
        rotate(degrees(bodies[i].angle));
        image(imageCache[obj.sprite.texture], obj.position.x, obj.position.y);
      } else {
        //Handle non-sprite bodies
        var verts = bodies[i].vertices;
        stroke(obj.fillStyle);
        fill(obj.fillStyle);
        beginShape();
        for (var v = 0; v < verts.length; v++) {
          vertex(verts[v].x, verts[v].y);
        }
        endShape(CLOSE);
      }
      pop();
    }
  }
};`
I already removed the module alias to Matter.Render.

**Comment by AliaNeedsHelp** [comment]
Or just use this: https://codesandbox.io/s/bathtub-simulator-b4cs6?file=/Game.js

**Comment by liabru** [comment]
I think drawing to the canvas using `Events.on(render, 'afterRender', callback)` should work as far as I know. Either way, it sounds to me like a better option would be to make a copy of the `Matter.Render` code and customise it as you need. Another option used in some games is to render the GUI using DOM elements placed on top of the main canvas.

**Comment by AliaNeedsHelp** [comment]
Would DOM elements in this case slow down my game?

**Comment by liabru** [comment]
Only if you try to update the DOM too often or make really large changes would there be an impact. If you stick to generating the DOM once and use best practices like CSS based animations, opacity and transforms it should be fine. But that will mean your game UI can only run in a browser environment, so best to consider that carefully.

**Comment by AliaNeedsHelp** [comment]
You mean it is possible for JavaScript to run on Node.js and use a display window?

**Comment by AliaNeedsHelp** [comment]
I'm working on a sandbox game, so I think DOM elements should be fine, but
I'm fairly new to DOM manipulation with JavaScript

**Comment by liabru** [comment]
Yeah it depends on your setup what works best so you may need to try out the options, hope that helps.
