### ISSUE TITLE
CCD problem

### ISSUE THREAD

**Issue by PyChaps** [liabru/matter-js#943]
Hi, I would like to ask if the CCD problem is solved, because I got this problem so many times and just didn't find a solution for it, thank you.

**Comment by michael-garofalo** [comment]
That's still an open issue...
https://github.com/liabru/matter-js/issues/5

**Comment by liabru** [comment]
I realise this is one of the most important requested features, but it also happens to be one of the most difficult to solve in a way that works well in general. It's still considered an area of research and is known to be a tough problem for real-time physics engines. 

That said I hope to post some further updates on this when I have them, but there are already known work-arounds that have been discussed in the main thread (I'll probably write a wiki page on these now that the thread is so long!).

For now please refer to that existing thread #5 instead though, as I'll be sure to post any updates there.
