### ISSUE TITLE
Question: Stick-built construction and propagating forces

### ISSUE THREAD

**Issue by goossaert** [liabru/matter-js#944]
I’m trying to implement some basic stick-built construction with matter.js, and I need help figuring out the best way to approach it. 

What I mean by “sticks” is an arrangement of rectangles or blocks that form connections with one another at their extremities and remain connected as long as the load is acceptable, and break when overloaded. Below is a screenshot from the game “Poly Bridge 2” so you can have a visual reference of what I’m trying to accomplish.

![Stick-built construction](https://user-images.githubusercontent.com/210749/101930260-35694c00-3bd8-11eb-806b-3245c2596c91.jpg)

Matter.js has a `Composite` type, and I can use that to create the structure I want. However, that doesn’t solve my problem entirely, I’m still looking for:
1. How to calculate the propagation of forces into all the bodies of a composite structure? i.e. if I have a stick structure and place a box on top of one of the sticks, all the sticks connected to that initial stick (distance N+1) will receive a fraction of the force/pressure, all the sticks connected to those (distance N+2) will receive an even smaller force, etc.
2. How to sum the forces of multiple objects? For example if I stack five boxes vertically, how to find what is the weight applied to the box at the bottom of the stack?

The behavior I expect is that if the force on a stick goes beyond a threshold, its connections with other sticks would break, which would the propagate in a domino effect to the rest of the structure. I looked at the examples, and combined the `bridge` example with boxes and cars to get a sense of how the engine works, but even after diving in the doc I couldn’t find anything.

Is there a way to achieve such stick constructions from the default API, or would I have to implement some added physics myself? If I have to do it myself, any recommendations on how to approach it?

**Comment by liabru** [comment]
Instead of thinking in terms of force, it's easier to think in terms of displacement (distance) for this sort of thing.

I assume here the 'sticks' are rectangle bodies, that are connected using small constraints (like pins)? If you make those constraints slightly soft and keep track of the length of those constraints, you can use that as a basis to decide if they have been broken or even to make a rough estimate of the weight.

**Comment by goossaert** [comment]
Thanks for your reply!
