### ISSUE TITLE
How to pause MouseConstraint on-demand

### ISSUE THREAD

**Issue by AliaNeedsHelp** [liabru/matter-js#948]
I'm making a sandbox game where the user is NOT allowed to move objects via MouseConstraint during "play" mode. Is this possible? If so, how?

**Comment by bouraqadi** [comment]
You can remove the mouse constraint during play mode and add it back in other modes

**Comment by AliaNeedsHelp** [comment]
I thought of that, but the only way to remove objects is by feeding the `World.remove()` function an exact replica of the MouseConstraint, which can be obtained two ways: subtracting the world object before adding the MouseConstraint from the world after the constraint is added, or feeding `Composite.get()` the `mouseConstraint` type (but MouseConstraints do NOT supply an id.) I have tried the first method, but the code is very messy and I doubt it's possible to subtract object properties using a similar copy of the object.

**Comment by liabru** [comment]
@AliaNeedsHelp you could do it like @bouraqadi mentioned but you will need to apply it to the `mouseConstraint.constraint` property instead I think. 

The other option would be to set up a [mouseConstraint.collisionFilter](https://brm.io/matter-js/docs/classes/MouseConstraint.html#property_collisionFilter) and toggle it as you need.

**Comment by AliaNeedsHelp** [comment]
Also, is rendering always triggered after it's `engine` has finished updating?

**Comment by AliaNeedsHelp** [comment]
I'm thinking of using a custom mousConstraint which allows drag-n-drop

**Comment by liabru** [comment]
@AliaNeedsHelp if you're using the built in runner / renderer, that's right it renders after update. A custom constraint sounds like a good idea to get exactly what you need. Looks like you're on track so I'll close this.
