### ISSUE TITLE
Poly-decomp not loading in

### ISSUE THREAD

**Issue by AliaNeedsHelp** [liabru/matter-js#949]
I think I did it correctly, but it's not finding Poly-decomp. Is this how?
`Matter.use("poly-decomp");`

Also, I'm using Google Chrome for my game.

**Comment by liabru** [comment]
If you're using it in a browser you need to include the [poly-decomp.js](https://github.com/schteppe/poly-decomp.js/) script before loading `matter.js`. If you're using Node.js then `npm install poly-decomp` in your project.

There was an issue in `0.15.0` with resolving this dependency in some cases, so please try the latest release `0.16.0` which hopefully fixes that problem.

**Comment by liabru** [comment]
See my latest post on [#559](https://github.com/liabru/matter-js/issues/559#issuecomment-777881867) for an update on this and feel free to use that thread for any further comments, thanks for reporting.
