### ISSUE TITLE
How can I stop clipping?

### ISSUE THREAD

**Issue by BrianComics** [liabru/matter-js#951]
How can I stop my bodies from squishing/clipping into each other like [here](https://user-images.githubusercontent.com/72044529/104140007-07b12780-537d-11eb-9395-c8d046e328e9.png)?

It occurs most often when an object is travelling at high speeds or a lot of objects are falling onto each other.

**Comment by bouraqadi** [comment]
It seems like this related to issue #5

**Comment by liabru** [comment]
To prevent the bodies overlapping you can try some or all of these approaches:

- increase `engine.positionIterations` and `engine.velocityIterations`
- use a fixed timestep for `Engine.update` (you can do this in `Matter.Runner` options too)
- use a smaller timestep and multiple iterations of `Engine.update` per-step
- keep mass values in a tighter range

As for issues with high speed collisions, as @bouraqadi mentioned please refer to discussion in #5 which presents some ways to avoid this until CCD is completed.
