### ISSUE TITLE
How can I make the simulation more precise in this case where a pool of particles collapses into itself?

### ISSUE THREAD

**Issue by jt0dd** [liabru/matter-js#953]
In a simulation where I have a pool of particles freely moving around (with upward and downward forces involved based on a heat gradient), when a certain number of particles get involved, suddenly they all collapse in on eachother, as if the simulation decides "I no longer care whether these particles overlap".

I've tinkered with the `broadphase` and `positionIterations` settings and it didnt seem to fix it, any suggestions?

Here's a video of it happening:

https://i.gyazo.com/fa2052ca1c7243b3353d3f37d1e0e28e.mp4

**Comment by liabru** [comment]
Can you check out my response in #951? 

It's worth trying each of those but in particular here it looks like you should switch to a fixed timestep, though the simulation may slow down due to the amount of collisions in your example.
