### ISSUE TITLE
Proper way to handle resizing.

### ISSUE THREAD

**Issue by DaveSeidman** [liabru/matter-js#955]
@liabru First off, thanks for this opensource library, it has excellent performance and very intuitive so it's easy to get going quick. 

That being said, it took me several hours to figure out the proper way to resize the renderer. Everything I tried before finding this solution would either stretch the final image or not expand the bounds of the world correctly (resulting in objects disappearing near edges). So for anyone else looking, this is what I've landed on:

```
const render = Matter.Render.create({ ... });

window.addEventListener('resize', () => { 
  render.bounds.max.x = window.innerWidth;
  render.bounds.max.y = window.innerHeight;
  render.options.width = window.innerWidth;
  render.options.height = window.innerHeight;
  render.canvas.width = window.innerWidth;
  render.canvas.height = window.innerHeight;
});
```

Substitute `window.innerWidth` and `innerHeight` with `element.getBoundingClientRect().width` and `.height` if not full screen.

Apologies if there's already a convenience method for this in docs or codebase somewhere, but I searched and couldn't find it :)

I'm also debouncing my resize method on a slight timeout to help with performance.

**Comment by liabru** [comment]
Yeah unfortunately this isn't currently a feature built in to the debug renderer, but your solution looks about right to me. 

Thanks for raising though, I've marked this as a feature request as I realise it's not the most straightforward thing to do.

**Comment by liabru** [comment]
Think this would also cover #595.

**Comment by dave-bvr** [comment]
I think your question should probably be more broad in that you're asking how to translate coordinates inside of a WebGL canvas to an HTML dom element's 2D pixel position. Start by searching for answers to a question like that, there are some intricacies but it mostly boils down to projecting the objects via your camera object into a value that will roughly map to -1 to 1 of the x and y axis, (for objects within the camera's frustum) which you would then multiply by the dimensions of the canvas (attainable many ways but start with canvas.getBoundingClientRect().width, .height). Hope this helps.
