### ISSUE TITLE
Error: Unable to resolve module `poly-decomp` from `node_modules\matter-js\build\matter.js`: poly-decomp could not be found within the project.

### ISSUE THREAD

**Issue by nnhunguet** [liabru/matter-js#956]
![image](https://user-images.githubusercontent.com/52577080/105154369-109fb700-5b3c-11eb-961a-69ab0619be5d.png)

Help me ! I don't run project FlappyBird

**Comment by codylico** [comment]
Possibly related to liabru/matter-js#559?

**Comment by liabru** [comment]
Can you give more information? 

- What have you tried so far? 
- Can you confirm you have installed it in the project e.g. `npm install poly-decomp --save`?
- Is the project online somewhere?
- What was the last working version of `matter-js` for this?

**Comment by entozoon** [comment]
Same thing here. Installing the dependency manually as you suggest @liabru is a good workaround. 
Issue occurs with a simple `import { Engine } from "matter-js"`, in webpack with matter v0.16.0

**Comment by liabru** [comment]
Thanks for confirming. That's not a workaround though, that's the intended approach.

I guess it should be made clearer in the docs! That said, I am hoping to be taking this out of the core project when I get around to it.

**Comment by entozoon** [comment]
Fair enough @liabru ! :)

**Comment by liabru** [comment]
@entozoon Actually, are you saying you get an error even when not using `Bodies.fromVertices`?

**Comment by nnhunguet** [comment]
Thank you, i will install npm install poly-decomp --save .
Last, i install matter-js !

**Comment by entozoon** [comment]
@liabru  No buddy; installing poly-decomp fixed everything. Just needs adding to the readme and/or the error output.
I probably wouldn't have closed the issue until then @nnhunguet as it'll keep happening for people

**Comment by liabru** [comment]
Thanks for confirming all, I will be looking at improving the docs and error outputs on this.

Just to check in case of a regression, @nnhunguet was this working before upgrading? 

If so, how was it working? Using a global `decomp`?
