### ISSUE TITLE
Bodies can enter the seams of a concave polygon

### ISSUE THREAD

**Issue by MattTreichelYeah** [liabru/matter-js#957]
For a game, I've created a static donut-like boundary polygon through an inner & outer set of circular points with `Matter.Bodies.fromVertices`. I have some players inside it represented here as simple `Matter.Bodies.circle`s. Random 360 degree movement is applied to them through what I think is a fairly weak `Matter.Body.applyForce`, and it all seems to interact correctly, but if the player applies force at the correct angle, it seems the body can enter seams of the donut and not be pushed out. 

![image](https://user-images.githubusercontent.com/6729569/105785835-db370700-5f49-11eb-880c-9c947c7d3aaa.png)

The random movement means I haven't really tried to see how easily this can occur by a consistently applied force, but it seems to happen surprisingly often enough this way. Is this enough information?

**Comment by MattTreichelYeah** [comment]
I tried layering on a second donut that was built with points offset from the first to "cover" the seams and it seems pretty effective. I'm still seeing behaviour like the bodies want to enter the seam and jitter, though.

**Comment by liabru** [comment]
This is a known issue I'd like to improve, but for now the usual way to avoid this is to make sure that all parts overlap by a small amount. There are a few ways to do that, one way could be just slightly increase the scale of each part after creation.

Another thought I've had is to set `slop: 0` as an option when creating the body - can you let me know if this helps? If so I think I might have a starting point for a better solution.

**Comment by MattTreichelYeah** [comment]
@liabru As in like this, yes?

```
    const donut = Matter.Bodies.fromVertices(..., { isStatic: true, slop: 0 });
```

Doesn't seem to have made a difference, unfortunately. Doesn't seem to make any difference what value I set to, tbh.

**Comment by liabru** [comment]
Yes thanks for trying that anyway, did you try the overlapping technique? 

That should work I think, though you may need to try construct the circle in other ways to get it robust (e.g. avoid edges that are on the circle radius, use edges that lie tangent instead).

**Comment by MattTreichelYeah** [comment]
I'd have to figure something out to do that I think but I could believe it works, I may just go ahead with using a second offset donut to cover the seams. Thanks.

**Comment by liabru** [comment]
Yeah that sounds like a good idea. I think in general it's just very difficult to fully automate robust geometry generation for physics engines, it's a complex problem in itself and can require manual work. There's definitely room to improve this utility though.

Hopefully you can get it working from that so I'll close this, feel free to report back here still if you find some success.
