### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by shafhad** [liabru/matter-js#959]
How to make collision between two objects

**Comment by liabru** [comment]
Can you explain further what you need?

**Comment by shafhad** [comment]
I am trying to make a shooter game but stuck at collision part , i wanted to make bullets collide with enemy but even i am not able to apply Force to bullets and i have no idea how do i detect the collision also i tried multiple reference available but no help

**Comment by bouraqadi** [comment]
One solution is to rely on sensors as in https://brm.io/matter-js/demo/#sensors

**Comment by liabru** [comment]
You might also want to try using ray casting instead for fast things like bullets, see the [example](https://brm.io/matter-js/demo/#raycasting) and [code](https://github.com/liabru/matter-js/blob/master/examples/raycasting.js). 

For more resources on getting started definitely check out the [tutorials wiki page](https://github.com/liabru/matter-js/wiki/Tutorials) too.

**Comment by Shubham814** [comment]
Can you please tell what to write in this condition easily
