### ISSUE TITLE
[IDE] No intellisense in VSCode when installed from npm.

### ISSUE THREAD

**Issue by ChristianTucker** [liabru/matter-js#961]
Hey there, I was setting up a test project using Matter to compare with Planck and noticed that for some reason that intellisense isn't being loaded in for matter-js. I'm using the current npm version `^0.16.0` and it's quite the hassle getting started with a library without the feature. 

Just wondering if you know how I can go about getting this enabled! Thanks.

**Comment by liabru** [comment]
I tested this in VSCode using `0.16.0` and the intellisense seems to be working for me:

<img width="816" alt="Screenshot 2021-01-27 at 23 32 58" src="https://user-images.githubusercontent.com/654420/106068202-1c6d1980-60f8-11eb-995e-65726718c65c.png">

All I did was install via npm and write `import Matter from 'matter-js'` and then I got the above.

Is that what you're after? Could it be a problem with your config or a VSCode bug?
