### ISSUE TITLE
Change location of gravity / black hole effect

### ISSUE THREAD

**Issue by jacksonkr** [liabru/matter-js#963]
Is it possible to make a specific point the center of gravitational pull?

eg. when I select/click a shape I want to make all the other shapes become attracted to that shape almost like it has become a black hole. The closest example I can think of is the bridge if it was possible to turn the bridge mechanic off and on manually.

**Comment by liabru** [comment]
Sure, you can just disable the built in gravity and then use `Body.applyForce` at the position you'd like.

But there's also a plugin for this! Check out [matter-attractors](https://github.com/liabru/matter-attractors).

**Comment by jacksonkr** [comment]
@liabru Look at you! You're doing great things my friend.

**Comment by arjuaman** [comment]
Hi @jacksonkr, were you able to implement this? How, and can you help me out with same? Immediate help would be appreciated, thanks!!

**Comment by jacksonkr** [comment]
@arjuaman I vaguely remember doing exactly what was mentioned, disabling global gravity then applying force to individual objects toward the black hole's position. Ultimately it's been too long and I have no idea where that prototype is. Best of luck!
