### ISSUE TITLE
Using a mouse constraint on a server side engine

### ISSUE THREAD

**Issue by jamesmackenzie1999** [liabru/matter-js#964]
Hi there,

I was hoping if you could help me with using a mouse constraint on a server side engine. I'm struggling as it needs an HTML element to be created.
In my case, I am sending the X & Y coordinates of the mouse to a node.js server, where the matter.js engine is running - I would love the objects in matter.js to then become effected by the mouses movement. I'd then return the position & angles of the body to the clients, for it to render it.

Thanks for your help,

James.

**Comment by liabru** [comment]
Check out the source for [Matter.MouseConstraint](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js) and you can see how it uses an internal `Matter.Constraint`. So on the server you can use a  `Matter.Constraint` instead exactly in place of it, then just move one of the constraint points around based on the mouse position you send from the client.
