### ISSUE TITLE
Broken Shape after Body.setParts()

### ISSUE THREAD

**Issue by dragonwhites** [liabru/matter-js#966]
I was trying to scale parts of a compound, and I found that the collision is wrong.
It turns out the compound needs to do autoHull after its' parts scaled.
So I manually call Body.setParts() to trigger the autoHull, but, the vertices of the parts will randomly break into the wrong shapes.

I found a possible reason for the broken vertices.
In Body.setParts() (line 406 to 410)
```
Body.setParts = function(body, parts, autoHull) {
.
.
.
if (autoHull) {
    var vertices = [];
    for (i = 0; i < parts.length; i++) {
         vertices = vertices.concat(parts[i].vertices);
    }
                        
    Vertices.clockwiseSort(vertices);
```
vertices are concated without being cloned.
and Vertices.clockwiseSort() modified the vertices which resulting broken shape.

My current workaround is to clone the vertices of all the parts before Body.setParts();
And then setVertices() again to fix the borken vertices.

```
const partAClonedVertices = partA.vertices.map(v => ({ x: v.x, y: v.y }));
const partBClonedVertices = partB.vertices.map(v => ({ x: v.x, y: v.y }));
Body.setParts( compound, [compound, partA, partB] );
Body.setVertices( partA, partAClonedVertices );
Body.setVertices( partB, partBClonedVertices );
```

**Comment by liabru** [comment]
>I was trying to scale parts of a compound, and I found that the collision is wrong.

Can you share the code for this? If it involves reusing parts and vertices then that is likely the issue, this function does not clone.
