### ISSUE TITLE
matterjs  sleep problem

### ISSUE THREAD

**Issue by a6965921** [liabru/matter-js#967]
The rigid body first sleeps, then moves to its position and then activates. But why does it disappear after activation instead of falling down??
this my code
https://codepen.io/a6965921/pen/MWbazwm

```
  setTimeout(function(){
         imageBody.position.x=231;
        imageBody.position.y=111;
    Matter.Sleeping.set(imageBody, 0)
    
  },1000)
```

**Comment by liabru** [comment]
I think you need to use [Body.setPosition](https://brm.io/matter-js/docs/classes/Body.html#method_setPosition) instead here rather than setting position directly (some properties require using setter functions, you can find them in the docs).
