### ISSUE TITLE
p5 Renderer

### ISSUE THREAD

**Issue by AliaNeedsHelp** [liabru/matter-js#968]
I've noticed that Matter.js uses a context-based renderer, but I'm more used to p5 rendering techniques than vanilla context. Could you add an optional p5 rendering module? Basically a replica of the render module, but p5 friendly.

**Comment by liabru** [comment]
If you're interested in using the engine with p5 there are some third-party integrations, examples and tutorials worth checking out:

https://github.com/CodingTrain/p5-matter
https://github.com/b-g/p5-matter-examples
https://github.com/pzp1997/p5-matter
https://github.com/liabru/matter-js/wiki/Tutorials

Integration is out of scope for this project though, but hope that helps you get started.

**Comment by AliaNeedsHelp** [comment]
I recommend adding p5 rendering support where instead of a 2dcontext, it's
a Canvas or Graphics Buffer.q
