### ISSUE TITLE
reseting a isStatic:true to isStatic:false

### ISSUE THREAD

**Issue by parthsharma365628** [liabru/matter-js#969]
i have a problem. 
how do i change the isStatic command to false

____________________________________________________________________________________________________________
var starImg, fairyImg, bgImg;
var fairy , fairyVoice;
var star, starBody;

const Engine = Matter.Engine;
const World = Matter.World;
const Bodies = Matter.Bodies;
const Body = Matter.Body;

function preload()
{
	starImg = loadImage("images/star.png");
	fairyImg = loadAnimation("images/fairyImage1.png","images/fairyImage2.png");
	bgImg = loadImage("images/starNight.png");
	fairyVoice = loadSound("sound/JoyMusic.mp3");

}

function setup() {
	createCanvas(800, 750);

	fairyVoice.play();

	fairy = createSprite(130, 520);
	fairy.addAnimation("fairyflying",fairyImg);  
	fairy.scale =0.25;

	star = createSprite(650,30);
	star.addImage(starImg);
	star.scale = 0.2;

	engine = Engine.create();
	world = engine.world;

	starBody = Bodies.circle(650 , 30 , 5 , {restitution:0.5, isStatic:true});
	World.add(world, starBody);
	
	Engine.run(engine);

}

function draw() {
  background(bgImg);
  
  star.x=starBody.position.x
  star.y=starBody.position.y
keyPressed()

  drawSprites();

}

function keyPressed(){
	if(keyDown(LEFT_ARROW)){
   fairy.x=fairy.x-5

	}
	if(keyDown(RIGHT_ARROW)){
   fairy.x=fairy.x+5
}
____________________________________________________________________________________________________________
**if(keyDown(DOWN_ARROW)){
//have to change isStatic command here pls help
	
}**
	 
	

 
}

**Comment by Sai-Smaran** [comment]
Use this:
`Matter.Body.setStatic(starBody.body, false);`

**Comment by SurbhiBhide** [comment]
> Use this:
> `Matter.Body.setStatic(starBody.body, false);`

I did that but its still not working🙁🙁
Plz help

**Comment by parthsharma365628** [comment]
i solved it like this
____________________________________________________________________________________________________________

if(keyDown(DOWN_ARROW)){
Matter.Body.setStatic(starBody,false)
}
