### ISSUE TITLE
Now that I can use Sprites with Pixi, get cross domain image loading errors.

### ISSUE THREAD

**Issue by salamanders** [liabru/matter-js#97]
Fixed the Pixi version library with #87, thank you!

Now that I can try using the WebGL renderer, I ran into a second issue.  When I'm not using WebGL, I can load images fine.  When I am trying to use WebGL, I get `Image from origin 'the source site' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'my web site' is therefore not allowed access.`

This means that WebGL is somehow more strict than whatever Matter.js uses normally?  If so, is there some way anyone has found to perhaps "proxy" the images by loading them with the method matter.js normally uses, then passing them to the WebGL renderer?

PS: this isn't a "running local vs running on a website issue", I've tried both with and without the one `/*controller: Matter.RenderPixi,*/` line as the only difference, with everything on web servers, and it breaks with it and works without it.

**Comment by liabru** [comment]
Are your images on a different domain, or using http vs https?
As this isn't allowed when using webgl unless they have the `Access-Control-Allow-Origin` header set.

If they're on the same server and protocol, could you provide a jsfiddle?

**Comment by salamanders** [comment]
Different domain.  And yes, after reading up on it, this issue isn't specific to matter-js.  Which is bizarre when upgrading to Pixi - it breaks, because WebGL has stronger cross-domain requirements (valid CORS headers) than plain matter-js.  And I can't get around it by rendering to a data URL via a canvas either because it is a "tainted" canvas.  Very unexpected overall.  Back to non-pixi rendering for me! :(

**Comment by liabru** [comment]
Thanks for confirming. Yeah, this is a well known browser restriction rather than anything in matter.js.
You should really just add the cors headers to your images if you own the server they live on.
Otherwise you'll just have to try put the images on the same domain.

**Comment by yreenchan** [comment]
@liabru I got this error on opera or firefox
It also catch error "No 'Access-Control-Allow-Origin' header is present on the requested resource."
