### ISSUE TITLE
failed with documentation code...

### ISSUE THREAD

**Issue by jyeann** [liabru/matter-js#972]
1st time testing here and tried testing out the demo code in getting start, but it kept showing 
matter-js: Render.create: options.element was undefined, render.canvas was created but not appended warn

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="./matter-js-0.16.1/build/matter.js"></script>
    <script>
      var Engine = Matter.Engine,
        Render = Matter.Render,
        World = Matter.World,
        Bodies = Matter.Bodies;

      // create an engine
      var engine = Engine.create();

      // create a renderer
      var render = Render.create({
        element: document.body,
        engine: engine,
      });

      // create two boxes and a ground
      var boxA = Bodies.rectangle(400, 200, 80, 80);
      var boxB = Bodies.rectangle(450, 50, 80, 80);
      var ground = Bodies.rectangle(400, 610, 810, 60, { isStatic: true });

      // add all of the bodies to the world
      World.add(engine.world, [boxA, boxB, ground]);

      // run the engine
      Engine.run(engine);

      // run the renderer
      Render.run(render);
    </script>
  </head>
  <body></body>
</html>
`

**Comment by michael-garofalo** [comment]
Where did you see this documentation?

It looks similar to this...
https://github.com/liabru/matter-js/wiki/Getting-started
...and that works for me.

I also used a slightly modified version to help troubleshoot an issue here...
https://github.com/liabru/matter-js/issues/256#issuecomment-752126652

Although, I think there are two issues...
![matterjs-comparison](https://user-images.githubusercontent.com/62625227/107893037-d33e0780-6ef6-11eb-906b-849842e771da.png)

It looks like there's a section missing and it looks like there's an extra comma.

**Comment by francoispeyret** [comment]
@michael-garofalo your remark seems to be the right one

**Comment by jyeann** [comment]
@liabru yes, is the exact getting started code. 

tried, but still empty when load browser

tried you #256 (comment) code. still blank browser

**Comment by michael-garofalo** [comment]
> tried you #256 (comment) code. still blank browser

Usually, when something like this happens, I open up the developer tools in the browser. Which browser are you using? Typically, there's a console log message that says what's wrong.

The HTML, in issue #256, is not enough. It needs the **matter.min.js** file too.

`<script src="matter.min.js"></script>`

**Comment by jyeann** [comment]
Thank you, i got it.

some how replaced the source files, the browser show the output.


Regards

'Jyeann
Hp +6012 370 7373
Connecting <https://www.linkedin.com/in/jye-ann-a4b4333a> Creativity
<https://www.linkedin.com/in/jye-ann-a4b4333a>

   Design  •  Trading  •  Technology

**Comment by bohemian916** [comment]
I also faced the same error.
It was because I loaded the script in the head section.
Instead, I load in the body section, and no error appeared.
