### ISSUE TITLE
Encountering an unknown bug in SAT.collide() (Update: I think I found the issue)

### ISSUE THREAD

**Issue by dragonwhites** [liabru/matter-js#973]
I am trying to keep the tab open as I am not sure this bug is recreatable.
I am using matter.js for the server later, so I am desperate to fix this issue.

The game was running smoothly and all of a sudden it broke.
The error is coming from SAT.collide().
Specifically this line.
```
axes = [axisBodyA.axes[previousCollision.axisNumber]];
```
In my case, **axisBodyA.axes** only has 5 axes, but **previousCollision.axisNumber** is 5;

However, after some checking, other same type bodies are having 6 axes.
All of them include the problematic body is a circle with 10 vertices.
So somehow this body has reduced its' number of axes.

Can anyone tell me what can cause this issue? Could it be because I did the Body.scale() to it?

![matterjsbug](https://user-images.githubusercontent.com/8843200/107371302-1c6d1080-6b1f-11eb-8e08-fd2724c4e7a7.png)
backup screenshot: https://stabfish.io/dwUploads/matterjsbug.png

**Comment by dragonwhites** [comment]
Additional Info:  I collected the vertices of the body, and applied Axes.fromVertices() on it. It is indeed returning 5 axes only

These are the vertices of the body
```
[{"x":-1461.955524679188,"y":591.6986380382463},{"x":-1476.937642556764,"y":599.7377971973967},{"x":-1490.8938146579017,"y":597.3182443837248},{"x":-1498.4937180601846,"y":585.3654018845264},{"x":-1496.8334846578293,"y":568.443949194706},{"x":-1486.5474020767451,"y":553.0166270312482},{"x":-1471.5652841991666,"y":544.9774678720988},{"x":-1457.6091120980282,"y":547.3970206857663},{"x":-1450.0092086957447,"y":559.3498631849703},{"x":-1451.669442098104,"y":576.2713158747882}]
```

**Comment by dragonwhites** [comment]
So after further investigate the source code, I now understand how does this happens.

1st, these bodies are created using Body.circle() with maxSides = 10;

When doing Body.scale() to these bodies, their axes are regenerated.

But the thing is, the axes that generated might be 5 or 6;

so a previous circle that had 6 axes might have only 5 axes now.

Can someone offer a solution for my problem?

**Comment by dragonwhites** [comment]
Perhaps, every time when a body is scaled or recreated fromVertices... we should delete the collision of all active pairs that contain said body? so when Detector.collisions(), the previousCollision would be null

**Comment by dragonwhites** [comment]
I tried to implement my workaround however it isn't easy as the bodies don't know which engine they are residing in. :(

**Comment by dragonwhites** [comment]
> Perhaps, every time when a body is scaled or recreated fromVertices... we should delete the collision of all active pairs that contain said body? so when Detector.collisions(), the previousCollision would be null
> 
> Or Body.scale() should set the world to modified?

Welp, setting collision to null is not working, the hack i did is to set the collision.collided to false instead so it wont be used by SAT

**Comment by liabru** [comment]
Thanks for reporting, interesting case I think I see what you mean - looks like collision reuse optimisations need to take this possibility into account.

In the meantime as a workaround, I'd say try create your own scaling function (based on `Body.scale`) that avoids changing the axes (should work in convex cases). 

You could also try patching `Matter.Detector.collisions` by copying the code but remove `previousCollision` from the line with `SAT.collides(partA, partB, previousCollision)`.

I've been meaning to improve collision reuse issues, so I'll see if this can be properly resolved.

**Comment by liabru** [comment]
The latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) should resolve issues relating to collision reuse, so would be great to hear if that resolves this issue too.

**Comment by hanzooo** [comment]
Seems that I have the same situation, my game object has a scaling animation and sometimes it breaks with the same error. If I disable the scale logic it doesn't break. After upgrading to version 0.18.0, it didn't happen again.

**Comment by liabru** [comment]
@hanzooo do you mean that upgrading solved the issue for you? Or something else?

**Comment by hanzooo** [comment]
> @hanzooo do you mean that upgrading solved the issue for you? Or something else?

 @liabru Yes, the upgrading solved the issue, it works good.

**Comment by liabru** [comment]
Thanks for confirming, closing this as hopefully that means it's solved.
