### ISSUE TITLE
[question] Copying bodies, predicting the trajectory of bodies

### ISSUE THREAD

**Issue by sstucker** [liabru/matter-js#975]
For my application, it is important I can display the path a body is likely to take as it orbits around planets that attract it. I want to use the engine to calculate the next n-steps of a body's physics with every other body held constant.

#584 got me started on the solution, but I'm having trouble cloning a non-static body in order to use it for the forward simulation, and even more trouble using update() to step a non-static body through time only to put it back.

What interface should I use for the copying and/or the prediction? 

I am using matter-js via Phaser3.

**Comment by liabru** [comment]
Can you explain the need to clone? I don't think you would need to and it sounds like that would cause problems.

You could try using `Body.setStatic` instead if you just want to 'pause' certain bodies? You could also try remove them from the world, do some updates, then add them all back in.

**Comment by sstucker** [comment]
I intended to create a clone of the body to advance through time to use to render the prediction while the original was left alone.

**Comment by liabru** [comment]
Okay in that case, make sure the 'clone' is actually a fully unique separate body, so call `Body.create(options)` twice and add both in the world. Any values passed in options passed should also be unique for each body.

I'd still say this approach sounds like it may not be the best way to achieve this. You should also consider a custom rendering approach instead to avoid having duplicate bodies.

**Comment by ErrorBot1122** [comment]
Well for predicting the trajectories you could try stopping the render, Sepping The Engin how many frames you want to predict, Getting all the data you need, and then go back to the original frame and start rendering it again.

**Comment by sstucker** [comment]
@ErrorBot1122 This is the approach I want to take-- The issue I am having is going back to the original frame.

**Comment by codylico** [comment]
Maybe you can clone the engine, or the entity state?

>

**Comment by ErrorBot1122** [comment]
I know that you can pause it by using: `engine.enabled = false` and you can try using `engine.timing.timestamp` for going forward it in time and you try using `Composite.allBodies(composite)` to get all the bodies, but for copying you could try this:


```javascript

function CopyBody(body) {
        return Bodies.fromVertices(body.position.x, body.position.y, body.vertices, {
             collisionFilter: body.collisionFilter,
             render: body.render,
             plugin: body.plugin,
             label: body.label,
             friction: body.friction.
             restitution: body.restitution,
             angle: body.angle,
             slop: body.slop,
             isStatic: body.isStatic,
             isSensor: body.isSensor
        });
}

```

**Comment by sstucker** [comment]
I will try this, thanks
