### ISSUE TITLE
Passive Event Listeners

### ISSUE THREAD

**Issue by AliaNeedsHelp** [liabru/matter-js#976]
Apparently, my game is throwing errors saying 
`[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`
I did some research and turns out this can be fix this by adding the `passive` flag to `document.addEventListener` for some browsers.

**Comment by francoispeyret** [comment]
do you have a sample code?

take care

**Comment by liabru** [comment]
@AliaNeedsHelp I can't reproduce this on any of the examples, can you share the code that shows the issue?

**Comment by ErrorBot1122** [comment]
ya @AliaNeedsHelp you need to show you code
