### ISSUE TITLE
Creating a "Fake" Mouse For MouseContrant

### ISSUE THREAD

**Issue by ErrorBot1122** [liabru/matter-js#978]
**DISCLAMER: I AM NEW TO MATTER.JS**

I'm currently trying to make a multiplayer game with Matter.js. I don't want any cheating so on going to only send inputs to the server and back to the clients. My game uses MouseContrains so one of the things I will send will be Mouse Data like:
```
mouse: {
   x: 100,
   y: 100,
   isDown: false
},
```
but how would I Convert X, Y, and other data to Element Mouse Data for `Matter.Mouse.create()` to use?

**Comment by francoispeyret** [comment]
I'm not sure but I don't think matter.js can handle fake mice natively... 
The class Mouse was creating events listeners on the client's web page.

What do you think about creating fake bodies (circle for example) and updating their data on your server and clients? 🤔

**Comment by ErrorBot1122** [comment]
But then how would i move the circle because I tried:
```
let testConst = Constraint.create({
   pointA: {
      x: mouse.x,
      y: mouse.y
   },
   bodyB: CircleBody
});
```
worked in a very weird way because whatever the circle's position was offset by the original position so what do I do?

_Also, I have Collision Filtering in the `MouseContrant` and I don't think you can have that in normal Constraints._

I also tried just setting the body's `x` and `y` to `mouse.x` and `mouse.y` like this:

```
CircleBody.position = mouse; // This will work because I don't think matter.js uses the "isDown" property or anything extra, only the x an y
```

**Comment by francoispeyret** [comment]
update a position's body with method "set"
[](https://brm.io/matter-js/docs/classes/Body.html#method_set)

**Comment by liabru** [comment]
The mouse constraint just uses a regular constraint underneath and sets up event listeners to move the constraint around, you should check out the code for [MouseConstraint](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js) to see how that works.

Then see [this section](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js#L107-L113) for where it moves the constraint based on mouse position, in your case that position would just be coming from a different source.

**Comment by ErrorBot1122** [comment]
@liabru What about Collision Filtering? Because in my code, I have Collision Filtering in the mouseConstraint

**Comment by liabru** [comment]
You can use [Detector.canCollide](https://brm.io/matter-js/docs/classes/Detector.html#method_canCollide) if you need to check whether two `body.collisionFilter` can collide.

**Comment by ErrorBot1122** [comment]
@

> The mouse constraint just uses a regular constraint underneath and sets up event listeners to move the constraint around, you should check out the code for [MouseConstraint](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js) to see how that works.
> 
> Then see [this section](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js#L107-L113) for where it moves the constraint based on mouse position, in your case that position would just be coming from a different source.

I tried that but it did this:

https://user-images.githubusercontent.com/65428515/109403435-8a347d00-7912-11eb-8d07-cd7486a134a6.mp4

I don't know why this is happening?!?!?!

if i remove this:

```javascript
constraint.pointA = position;
  constraint.bodyB = body;
  constraint.pointB = {
    x: position.x - body.position.x,
    y: position.y - body.position.y
  };
```
the constraint works: 

https://user-images.githubusercontent.com/65428515/109403675-a5ec5300-7913-11eb-8f7e-7ba2869de9a3.mp4

I don't know what is wrong!?!?!?

the code: https://editor.p5js.org/Errorbot_1122_School/sketches/q0sOqAkSX

**Comment by ErrorBot1122** [comment]
Future me, IDK what happened 🤷 

<small>*I understand why no one answered this lol*</small>
