### ISSUE TITLE
How can i get the ray reflection?

### ISSUE THREAD

**Issue by Wexelus** [liabru/matter-js#980]
**I want to get the correct reflection of the ray from the body surface with a shape of any complexity**

Visualization:
![picture](https://user-images.githubusercontent.com/47812547/110130080-b2702000-7dd9-11eb-8d94-8bcc4b58390e.PNG)

**Thanks for any help!**

**Comment by liabru** [comment]
The built in ray casting is a little limited and doesn't currently give complete information for performance reasons at the moment. 

You can use it for a fast initial check, then once a collision is found you'll need to implement and perform an additional ray cast to get the exact edge face normal and the point of intersection, from there you can use the [law of reflection](https://www.physicsclassroom.com/class/refln/Lesson-1/The-Law-of-Reflection).

Check out the [phaser-raycaster](https://github.com/wiserim/phaser-raycaster) project by @wiserim which implements a more detailed raycast approach.
