### ISSUE TITLE
Module not found: Can't resolve 'poly-decomp'

### ISSUE THREAD

**Issue by steveja42** [liabru/matter-js#981]
I am seeing this message in the debug output when using matter-js:

> ./node_modules/.pnpm/matter-js@0.16.1/node_modules/matter-js/build/matter.js
> Module not found: Can't resolve 'poly-decomp' in 'C:\dev\webpranks\node_modules\.pnpm\matter-js@0.16.1\node_modules\matter-js\build'

This is the minimal code to reproduce:
```
import { Engine, Render, Bodies, World } from "matter-js";
const engine = Engine.create();
```

**Comment by liabru** [comment]
Thanks for reporting, can you give more information on the environment you're running this in?

Any build tools, node version, npm version, browser etc. and what program specifically is the error message coming from?

**Comment by steveja42** [comment]
I think the error message is from typescript. It is a .ts file. I am using create-react-app build and node ver 14.15.1. and I'm using pnpm ver 5.18.3 instead of npm. When I do yarn start and then change the .ts file it says:

> Compiled with warnings.
> 
> ./node_modules/.pnpm/matter-js@0.16.1/node_modules/matter-js/build/matter.js
> Module not found: Can't resolve 'poly-decomp' in 'C:\dev\webpranks\node_modules\.pnpm\matter-js@0.16.1\node_modules\matter-js\build'

It seems like matter.js is still functioning anyway.

**Comment by treardon17** [comment]
I am also getting this error message

**Comment by liabru** [comment]
@treardon17 could you please also provide the above requested info? Thanks!

**Comment by treardon17** [comment]
@liabru sure thing! sorry I didn't include more details to begin with...

node: v12.15.0
yarn: 1.23.0-20200928.1349

Minimum code to reproduce: 
```
import Matter from 'matter-js';
```

Causes this warning during my build process:
```
WARNING in /project/node_modules/matter-js/build/matter.js
Module not found: Error: Can't resolve 'poly-decomp' in '/project/node_modules/matter-js/build'
```

Doing `yarn add poly-decomp` fixes the issue, but if `poly-decomp` is a required dependency shouldn't it be in the `package.json` dependencies?

**Comment by liabru** [comment]
@treardon17 thanks what build tools are you using here?

**Comment by liabru** [comment]
@treardon17 can you tell which program the error message is originating from specifically? I'm using Webpack and it seems to be fine, my guess is rollup?

**Comment by treardon17** [comment]
@liabru the error is coming from the webpack build, but I'm wondering if the issue is in the output of the rollup build...

**Comment by liabru** [comment]
To be clear for anyone still seeing this issue you can avoid the warning for the moment by just installing the module via `npm install poly-decomp` (even though it's technically optional).

The problem seems to be external - build tools don't appear to handle conditional `require` calls as expected, which I'm not sure there's a fix for (unless anybody has any ideas).

So unfortunately there may need to be a breaking change coming (which I've been trying to avoid): removing this `require` all together and asking users to pass the `decomp` module as an argument (or set the global).  I'm sure that will create just as much confusion as this error though.

**Comment by treardon17** [comment]
@liabru it seems like having users pass the dependency would be a good direction. It would make the `poly-decomp` module feel more like a plugin.

**Comment by liabru** [comment]
As of release `0.17.0` the approach is now to use the new function [Common.setDecomp](https://brm.io/matter-js/docs/classes/Common.html#method_setDecomp), which you can see in use on the [concave example](https://github.com/liabru/matter-js/blob/master/examples/concave.js).

The `window.decomp` global is also still supported, but it is still advised to specifically use `Common.setDecomp` where possible.

There is no longer any `require` usage meaning bundlers should work fine, so considering the issue now resolved but feel free to comment still if needed. Thanks again for reporting.

**Comment by fccm2** [comment]
Could you explain how to set the poly-decomp dependency, `Common.setDecomp(require('poly-decomp'))` doesn't work, I get an error with `require` in my web-browser.

**Comment by michalgrzyska** [comment]
bump, how to load poly-decomp? I can even see that there is a fork named `poly-decomp-es`, but I still cant load it. it does nothing in my case...
