### ISSUE TITLE
Troubles with setting sprites

### ISSUE THREAD

**Issue by Rafii2198** [liabru/matter-js#982]
So I tried using Matter.js for now I am really happy with it but whenever I am trying to apply sprite to a body I get tons of `Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state` errors and I have no idea what is wrong. I am looking at Sprites example and I am trying to do it similarly
```js
World.add(world, Bodies.rectangle(500, 80, 65, 65, {
  render: {
    sprite: { texture: './Test.png' },
  },
}));
```
When I add that whole render part that error starts appearing. Test.png is a 65x65 file same as rectangle size.

**Comment by liabru** [comment]
First check the file is not corrupt, can you open and view the file directly in the browser?

Then are there any errors in the dev tools network tab for the file?

How are you serving the image file? Does your server provide the correct MIME type?

**Comment by Rafii2198** [comment]
Ok, so sorry for a but late replay but I have set up my environment again and removed ./ and left just Test.png and it worked. No idea why, it seems it was an issue on my end. Sorry for false alarm! :)

**Comment by ak3311g** [comment]
I am getting same error and i am using location as block/img.png
