### ISSUE TITLE
How to put a object behind another object?

### ISSUE THREAD

**Issue by MiAccess** [liabru/matter-js#983]
Thanks for this great engine.
I am developing a game called A Midnight Journey made with Matter.js.
I am trying to put the car behind water(in picture). But I can't. I was success to put the ball and other object behind water. But it doesn't work at the car.
Here is the code-

[Matter.js  A Midnight Journey.zip](https://github.com/liabru/matter-js/files/6136049/Matter.js.A.Midnight.Journey.zip)

![Capture](https://user-images.githubusercontent.com/72332364/111056363-740ade80-8433-11eb-8508-b5d3c4d5f94a.PNG)

**Comment by liabru** [comment]
The built in renderer doesn't support this kind of 'z-index' feature at the moment, but see issue #243 where someone shared an example of how to implement this in your own renderer.

I'd highly recommend doing so if you're building a game like this, you can also fork `Matter.Render` to get started and adapt it as you need.

**Comment by bouraqadi** [comment]
The order of adding bodies seems to be related for rendering. Ones added last are drawn on top of the others. 
But, bodies inside composites are rendered after rendering the others.

**Comment by liabru** [comment]
@bouraqadi yeah the resulting render order is related to that though I wouldn't recommend relying on it as it is unspecified.
