### ISSUE TITLE
Composite.removeBody problem when using custom update loop

### ISSUE THREAD

**Issue by samredfern** [liabru/matter-js#99]
https://jsfiddle.net/psychicsoftware/76rb8s08/1/

Composite.removeBody doesn't work when called from inside the collisionStart event. Only happens if you're using a custom update loop

**Comment by liabru** [comment]
This is because in 0.8.0 the collision events were called by the runner, since you're using a custom runner the collision events are not getting fired at all.

This has actually been resolved since that release, so if you switch to using the latest master build then your example should work.

**Comment by samredfern** [comment]
That does seem to be true in my jsfiddle, yes. It's definitely not true in my game though, which uses 0.8.0-edge.  I'm using a custom loop and do lots of other stuff in the collision events, and they definitely do happen. Also removeBody works fine too when triggered in collision events as long as I do it via a setTimeout rather than immediately.  In any case, *shrug* the latest release works fine and that's what matters.  Thanks :-)

**Comment by liabru** [comment]
It may help to buffer the bodies to be removed into an array inside the the `collisionStart` event handler, then actually remove them in the `afterUpdate` event handler.

If this doesn't help, there may be an actual issue with the bodies being maintained in the pair manager even after they are no longer in the world which could manifest in weird ways.

**Comment by samredfern** [comment]
I'm not sure if this is the best place to reply, but I was lead to finding this by your final comment above, "If this doesn't help, there may be an actual issue with the bodies being maintained in the pair manager even after they are no longer in the world which could manifest in weird ways."

I'm making a game that involves quite a lot of physics bodies being created and removed, and was finding that pairs.list.length keeps growing all the time, contributing to an increasing CPU load the longer you play. This seems like something that should be fixed? I fixed it myself by editing Pairs.removeOld to delete any pair involving a body that has been removed from the world
