### ISSUE TITLE
how to make a multiplayer game in matter.js

### ISSUE THREAD

**Issue by adwait2007** [liabru/matter-js#991]
Hi , I want to know that how to make a multiplayer game in matter.js

**Comment by liabru** [comment]
Check out [Phaser](https://github.com/photonstorm/phaser) which is a game engine that includes the Matter.js physics engine and a whole lot more.

You can also search issues here to find some [previous discussions](https://github.com/liabru/matter-js/issues?q=is%3Aissue+multiplayer+is%3Aclosed) on this topic, while you can certainly build something like this yourself, Matter.js itself does not include anything for this built in.
