### ISSUE TITLE
Printable documentation

### ISSUE THREAD

**Issue by anonimo82** [liabru/matter-js#998]
Hello everyone.
I'd like to print the whole class reference for this, is it there any PDF or single page document?

Something like this:
![docs](https://user-images.githubusercontent.com/38261009/114521653-ee9d6880-9c42-11eb-980b-1ce127d7178f.png)

Thanks in advance for any help.

**Comment by liabru** [comment]
Unfortunately at the moment there's no 'cheat sheet' format like this for the docs, but it's a neat idea and I will keep it in mind when improving the docs in future.

Maybe there are some tools that can help you generate this though?

**Comment by anonimo82** [comment]
I don't know, but maybe?

**Comment by anonimo82** [comment]
Any update on this?

**Comment by liabru** [comment]
This isn't something I'm working on at the moment but the docs have been improved to make it easier to see an overview of all module members at once e.g. on [Matter.Engine](https://brm.io/matter-js/docs/classes/Engine.html).

**Comment by anonimo82** [comment]
Ok, thanks so much.
Looking forward this =)

**Comment by liabru** [comment]
@anonimo82 not sure what you mean by idl?

**Comment by anonimo82** [comment]
Nothing, I messed up with terms from other projects, but an IDL is something you would use (in eg) with emscripten

**Comment by anonimo82** [comment]
I did one myself, it's quite big, but maybe someone will summarise it (?)
I just pasted each documentation page in turn inside a PDF document, nothing special.

[Here it is (for 30 days)](https://easyupload.io/wqd9we)

**Comment by anonimo82** [comment]
@liabru please, check back here

**Comment by anonimo82** [comment]
I'm back asking for printable documentation, but I'm not looking for cheatsheets this time.
Please, can you provide the whole documentation as a pdf or as a single, printer friendly page?

**Comment by photonstorm** [comment]
Why not just do this yourself? It feels like a complete waste of the developers time to request here. There are far more important things to be done with the library.

**Comment by anonimo82** [comment]
Because I have no idea how to.
Is it there a way I can "procedurally"?
Edit: Ok, `npm run doc`.
But gives this error:
```
> matter-js@0.20.0 doc
> yuidoc --config yuidoc.json --project-version $npm_package_version

sh: riga 1: yuidoc: comando non trovato
```

Edit: Nevermind, installed the yuidoc package and now it works.

**Comment by anonimo82** [comment]
Nevermind, I generated the documentation in HTML, then converted each HTML file in PDF with pandoc
`for i in *.html; do pandoc -f html -t pdf -o $i.pdf $i; done`
then joined the PDFs with another package called pdfarranger.

All with Linux, IDK how would I've been done with Windows.... Of course a solution would exist, but IDK it.
If is anyone interested, I can send the final PDF.

Thanks everyone anyhow.

**Comment by giampoborm** [comment]
hey! would you share that pdf please?

**Comment by anonimo82** [comment]
Sure! Here you are: 

[14 - MatterJS.pdf](https://github.com/user-attachments/files/18518457/14.-.MatterJS.pdf)

**Comment by giampoborm** [comment]
grazie mille!!

**Comment by anonimo82** [comment]
Di niente. 
You're welcome
